### ISSUE TITLE
[NBug] Can not add a section that already exists: -remote

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10152]
### Environment

- Git Extensions 33.33.33
- Build 0c137d548962df3c8252fec5cc80c4d7b67222c4 based on 464a2064d8e607a423bf2bf806b062e4f47fbb0b
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.8
- DPI 96dpi (no scaling)

### Issue description

```
System.ArgumentException: Can not add a section that already exists: -remote
   at GitCommands.Config.ConfigFile.AddConfigSection(IConfigSection configSection)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass9_0.<AddConfigSection>b__0()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.LockedAction(Action action)
   at GitCommands.Settings.ConfigFileSettingsCache.AddConfigSection(IConfigSection configSection)
   at GitCommands.Settings.ConfigFileSettings.AddConfigSection(IConfigSection configSection)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.ToggleRemoteState(String remoteName, Boolean disabled)
   at GitUI.BranchTreePanel.RemoteRepoNode.Disable()
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c.<RegisterContextActions>b__16_14(RemoteRepoNode remote)
   at GitUI.BranchTreePanel.Node.OnNode[T](TreeNode treeNode, Action`1 action)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass15_0`1.<RegisterClick>b__0(Object o, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

- configure at least two remote repos (hosting diverged forks)
- deactivate one of the remote repos (as a workaround for an annoying incompatibility of LFS)
--> BugReporter + lost configuration of repo to be deactivated

### Did this work in previous version of GitExtensions?

yes

**Comment by mstv** [comment]
Updating Git was blocked either - until I closed VS Code. (I had closed all GE instances before).
Since the Git update, the de/activation of remotes works again.

Though this error must not be reported as a GE bug but as an `ExternalOperationException`.
