### ISSUE TITLE
GPG info Regression

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#10242]
### Environment

- Git Extensions 33.33.33
- Build 077046ca17bf43a6fe0fd958b53d2493a780db52
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

### Issue description

Looks like a regression between v3.5.4 and master.  Somehow it is failing to get any output from 
https://github.com/gitextensions/gitextensions/blob/3d4ed902fcd13dba41d66dd1e6b918ba78eac3f5/GitCommands/Git/GitGpgController.cs#L231-L246

---
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.9093.0
- DPI 96dpi (no scaling)
![image](https://user-images.githubusercontent.com/3629489/194782238-0df11204-cbb0-44b0-bb9d-a926789dab49.png)

---
- Git Extensions 33.33.33
- Build 077046ca17bf43a6fe0fd958b53d2493a780db52
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

AND

- Git Extensions 33.33.33
- Build 8b80e54f15e8923a85f5801cca033f932ced821f
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

![image](https://user-images.githubusercontent.com/3629489/194782273-7f84e529-31c1-470e-aceb-a3d17a2d77f5.png)

### Steps to reproduce

View a commit with a signed tag and view gpg tab.

### Did this work in previous version of GitExtensions?

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.9093.0
- DPI 96dpi (no scaling)

### Diagnostics

![image](https://user-images.githubusercontent.com/3629489/194782817-e95be451-b704-469c-9c56-ae331d701434.png)

**Comment by BinHavin0323** [comment]
- [ ] []()

**Comment by vbjay** [comment]
I'm running a bisect. but things got in the way.  I'll  finish it tonight.  
```
git bisect start
# status: waiting for both good and bad commits
# good: [c4e1f8150d26dcf772366247f909c18f8f38f3e5] C#9 new()
git bisect good c4e1f8150d26dcf772366247f909c18f8f38f3e5
# status: waiting for bad commit, 1 good commit known
# bad: [077046ca17bf43a6fe0fd958b53d2493a780db52] Include stash@{0} also for current/filtered branch (#10228)
git bisect bad 077046ca17bf43a6fe0fd958b53d2493a780db52
# bad: [46b3ad420faec3b4db303d9378101d2b8e5ebc77] Rebase & Apply Patch: add mnemonics, fix tab order, add a shortcut (#9621)
git bisect bad 46b3ad420faec3b4db303d9378101d2b8e5ebc77
# good: [3bd6aec7b55fedb1c09027d7ff272fab5bbce819] Merge pull request #9371 from gitextensions/listview_cleanup
git bisect good 3bd6aec7b55fedb1c09027d7ff272fab5bbce819
# skip: [a0298745df0db224c8c02baa080a52ad0f359bd1] fix: Show current branch resets when switch repos
git bisect skip a0298745df0db224c8c02baa080a52ad0f359bd1
# skip: [19ec25398a6b6a5d855c9415f7c1d971334a2e27] RevFileTree: Blame instead of View
git bisect skip 19ec25398a6b6a5d855c9415f7c1d971334a2e27
# bad: [6f9bf27ca8e82719d0e71b5a7048bd7247371ede] Show toolbar grips (#9586)
git bisect bad 6f9bf27ca8e82719d0e71b5a7048bd7247371ede
# skip: [d8ddc1f6e6c72ceef18fc4b17abfefcefa46adf6] Reset revision filter when switching repos (#9477)
git bisect skip d8ddc1f6e6c72ceef18fc4b17abfefcefa46adf6
# skip: [1d608481ddb56dd24c3fc5aa15fd93bce5c75980] Restore splitter persistence (#9106)
git bisect skip 1d608481ddb56dd24c3fc5aa15fd93bce5c75980
# skip: [d27b07897808e223fad5b5be1b685d0ebb8afc18] GitHub PR template - merge strategies (#9453)
git bisect skip d27b07897808e223fad5b5be1b685d0ebb8afc18
# skip: [e6b51dfc1fb27c6ed5a63c0de2bd59f81904e1cf] Fixed Commit info varying indents. Fixes #9164 (#9444)
git bisect skip e6b51dfc1fb27c6ed5a63c0de2bd59f81904e1cf
# skip: [0dfcd09394546559ec5f08b9d11999a2467645fc] Don't show delete dialog on CTRL+ALT+DEL (#9460)
git bisect skip 0dfcd09394546559ec5f08b9d11999a2467645fc
# skip: [c43bf0ce863bce407e4b0beecbc4d07788d26ea5] Browse: Remove unused _artificialStatus
git bisect skip c43bf0ce863bce407e4b0beecbc4d07788d26ea5
# skip: [df412624e74ac1464eea96716e3afcce72d72111] Recent repo search (#9380)
git bisect skip df412624e74ac1464eea96716e3afcce72d72111
```

**Comment by vbjay** [comment]
I made a Bisect test script that I will make a pull request for but here  it is for now.

```ps
# Param([switch] $Force)

$path = Split-Path $MyInvocation.MyCommand.Path -Parent

$result = 0
# if (-not $Force) {
#     $result = $Host.UI.PromptForChoice('Running git clean -xdf', 'Are you sure you want to proceed? This will delete all files that are new and not committed or staged.', @('&Yes'; '&No'), 1)
# }


function Build() {
    $buildScript=Join-Path -Path $path -ChildPath build.ps1
    git clean -x -d -f --exclude="scripts/Bisect-Test.ps1"
    git submodule update --init --recursive
    git submodule foreach --recursive git clean -x -d -f
    if (Test-Path -Path $buildScript) {
        & $buildScript -rebuild -bn -b -restore
    }
    else {
        dotnet build
    }
}

function Test() {
   
    $artifacts = Join-Path -Path $path -ChildPath ..\artifacts
    $artifacts
    $ge = Get-ChildItem -Path $artifacts -Name gitextensions.exe -Recurse | Select-Object -First 1
    $geFull = Join-Path -Path $artifacts -ChildPath $ge
    $geFull = Resolve-Path -Path $geFull
    Write-Output "Starting $geFull"
    Start-Process -Wait -FilePath $geFull -ArgumentList browse
              
    $testResult = $Host.UI.PromptForChoice('Did it perform as expected?', 'Did Git Extensions behave as expected?', @('&Yes'; '&No', '&Unsure'), 0)
    
    if ($testResult -eq 0) {
        exit 0
    }
    elseif ($testResult -eq 1) {
        exit 1 
    }
    elseif ($testResult -eq 3) {
        exit 125; # See https://git-scm.com/docs/git-bisect/#_bisect_run
    }
}


if ($result -eq 0) {

   
   
   
    $continue = $true
    try {
        Build  
        Write-Output "Built"
    }
    catch {
         
        $continue = $false         
        write-output "Error  $LASTEXITCODE"
        exit 125; # See https://git-scm.com/docs/git-bisect/#_bisect_run
    }   
    Write-Output "Continue? $continue"
    Test
}

```

You run it by  like this

```ps
# I recommend doing some thing like git bisect start master v3.5.4 to start with it worked in last release but now it is broken
git bisect start
git bisect run powershell -Command .\scripts\Biesect-Test.ps1
```
Then it will do the building and running of GE and then you can do the needed actions in program and then close program.  Answer the question and then it  will automatically mark the commit as good/bad/skip



```

**Comment by vbjay** [comment]
```
54982642e4857153f837d6662bc322d26e4c2732 is the first bad commit
commit 54982642e4857153f837d6662bc322d26e4c2732
Author: Gerhard Olsson <gerhardol@users.noreply.github.com>
Date:   Thu Apr 29 22:49:20 2021 +0200

    TryGetParents: Ignore git errors

    Reproduce - example: submodule commit does not exist when opening
    * Use worktree with submodules
    * In one instance make a new commit in a submodule
    * Commit in superproject
    * Create a new branch in the second worktree instance
      on same commit as the first instance
    * Double click on the submodule in side panel

    (cherry picked from commit c3c84541e46bee22aadd898833c0b03c7736a659)

 GitCommands/Git/ExecutableExtensions.cs                | 10 +++++++---
 GitUI/UserControls/RevisionGrid/RevisionGridControl.cs |  6 +-----
 2 files changed, 8 insertions(+), 8 deletions(-)
```
```
# bad: [077046ca17bf43a6fe0fd958b53d2493a780db52] Include stash@{0} also for current/filtered branch (#10228)
# good: [65f01f39982ccb121c4df7d4b00b506939553958] Move the init logic from OnLoad to InternalInitialize (#9591)
git bisect start 'master' 'v3.5.4'
# good: [c7500166e9800a05f3f9834cd93cdc74fd4349b6] Ignore VS service logs
git bisect good c7500166e9800a05f3f9834cd93cdc74fd4349b6
# good: [a727559297482e157c19e13fa8357ddf8ea89df6] Merge pull request #9286 from mstv/fix/9108_partial_graph_rendering
git bisect good a727559297482e157c19e13fa8357ddf8ea89df6
# bad: [d6be9ba68c6e6f72493178b98ea96c68a0195d7d] Adjust Debug.Assert for tests (#9745)
git bisect bad d6be9ba68c6e6f72493178b98ea96c68a0195d7d
# bad: [9e3700ee72c44b3a88991e6bca581d8703ac533c] Merge pull request #8957 from RussKie/formremotedelete
git bisect bad 9e3700ee72c44b3a88991e6bca581d8703ac533c
# good: [efe84d57f40226e1290e8857a85e620399e4c169] Update contributors.txt (#9384)
git bisect good efe84d57f40226e1290e8857a85e620399e4c169
# bad: [eeb8f67ddbf87ccc88741fe31c31ac444948a266] Fix build warnings
git bisect bad eeb8f67ddbf87ccc88741fe31c31ac444948a266
# bad: [cea231da50e60df4c642ad6412f4207bbff462bd] Merge pull request #9056 from mstv/fix/6527_git_errors
git bisect bad cea231da50e60df4c642ad6412f4207bbff462bd
# good: [6d385dac91331fdf09738a00ec69746e234a5f86] Enable use of the designer (#9387)
git bisect good 6d385dac91331fdf09738a00ec69746e234a5f86
# good: [b4c6305684f53932844ac84daf1c1e934a776321] Do not blame folders (#9392)
git bisect good b4c6305684f53932844ac84daf1c1e934a776321
# good: [ab9b18bb5c257d8a2aeca19ffc1b6363f63ee81f] Merge pull request #8956 from RussKie/formdelete
git bisect good ab9b18bb5c257d8a2aeca19ffc1b6363f63ee81f
# bad: [54982642e4857153f837d6662bc322d26e4c2732] TryGetParents: Ignore git errors
git bisect bad 54982642e4857153f837d6662bc322d26e4c2732
# good: [25060c3b0683c710cd5b47cdfc550b7f8a3b4940] Throw on non-0 exit code and on stderror output
git bisect good 25060c3b0683c710cd5b47cdfc550b7f8a3b4940
# first bad commit: [54982642e4857153f837d6662bc322d26e4c2732] TryGetParents: Ignore git errors
# good: [ab9b18bb5c257d8a2aeca19ffc1b6363f63ee81f] Merge pull request #8956 from RussKie/formdelete
git bisect good ab9b18bb5c257d8a2aeca19ffc1b6363f63ee81f
# first bad commit: [54982642e4857153f837d6662bc322d26e4c2732] TryGetParents: Ignore git errors

```

**Comment by vbjay** [comment]
- Git Extensions 33.33.33
- Build 54982642e4857153f837d6662bc322d26e4c2732
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.17
- DPI 96dpi (no scaling)

```
2022-10-14T17:05:29.8306645-04:00	98	19448	UI	exc	git	verify-tag test-defaultKey	C:\git\gitextensions\
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorOutput)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorOutput)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput)
   at GitCommands.ExecutableExtensions.<>c__DisplayClass2_0.<GetOutput>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput)
   at GitCommands.Gpg.GitGpgController.GetTagVerificationMessage(IGitRef tagRef, Boolean raw)
   at GitCommands.Gpg.GitGpgController.EvaluateTagVerifyMessage(IReadOnlyList`1 usefulTagRefs)
   at GitCommands.Gpg.GitGpgController.GetTagVerifyMessage(GitRevision revision)
   at GitUI.CommandsDialogs.FormBrowseController.LoadGpgInfoAsync(GitRevision revision)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetResult()
   at System.Threading.Tasks.Task.WhenAllPromise.Invoke(Task completedTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at GitCommands.Gpg.GitGpgController.GetRevisionCommitSignatureStatusAsync(GitRevision revision)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.<>c.<.cctor>b__20_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, ObjectId selectedId, ObjectId firstId)
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

GitExtUtils.ExternalOperationException: gpg: Signature made 10/9/2022 2:52:32 PM Eastern Daylight Time
gpg:                using RSA key 39DE882CE3097A4E7E6C2D80223DF2DDA3ECCBBF
gpg: Good signature from "Jay Asbury <vbjay.net@gmail.com>" [ultimate]
 ---> System.Exception: gpg: Signature made 10/9/2022 2:52:32 PM Eastern Daylight Time
gpg:                using RSA key 39DE882CE3097A4E7E6C2D80223DF2DDA3ECCBBF
gpg: Good signature from "Jay Asbury <vbjay.net@gmail.com>" [ultimate]
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput) in C:\git\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 130
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput) in C:\git\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 49
   at GitCommands.Gpg.GitGpgController.GetTagVerificationMessage(IGitRef tagRef, Boolean raw) in C:\git\gitextensions\GitCommands\Git\GitGpgController.cs:line 245
   at GitCommands.Gpg.GitGpgController.EvaluateTagVerifyMessage(IReadOnlyList`1 usefulTagRefs) in C:\git\gitextensions\GitCommands\Git\GitGpgController.cs:line 267
   at GitCommands.Gpg.GitGpgController.GetTagVerifyMessage(GitRevision revision) in C:\git\gitextensions\GitCommands\Git\GitGpgController.cs:line 228
   at GitUI.CommandsDialogs.FormBrowseController.LoadGpgInfoAsync(GitRevision revision) in C:\git\gitextensions\GitUI\CommandsDialogs\FormBrowseController.cs:line 82
   at GitUI.CommandsDialogs.FormBrowse.FillGpgInfoAsync(GitRevision revision) in C:\git\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1430
2022-10-14T17:06:09.3231529-04:00	303	28244	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	C:\git\gitextensions\
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorOutput)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorOutput)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorOutput)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass43_0.<<Update>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass43_0.<Update>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(Func`1 asyncMethod)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass26_0.<.ctor>b__0(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, ObjectId selectedId, ObjectId firstId)
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

```

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/195950525-c2b6369a-0bd6-4742-8cc1-685cad1e65d2.png)

solves the problem.

**Comment by gerhardol** [comment]
Why is Git returning other than 0?
Is there inappropriate parameters to the command?
`throwOnErrorOutput` was added to not hide Git errors, which often caused issues later in the processing.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/195952095-3571f7bb-b2ac-40b7-acfd-7ce4804c82ef.png)
- Git Extensions 33.33.33
- Build e703d0c65e71ee1ac49bec57f0aa4a08cc5058b4 (Dirty)
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)
![image](https://user-images.githubusercontent.com/3629489/195955172-615f2b4f-2e7d-4806-ab79-a3b66f5eff4a.png)

**Comment by gerhardol** [comment]
what do you get from the command line?

**Comment by vbjay** [comment]
I get a good result.  Do ou see the problem now?

After change
![image](https://user-images.githubusercontent.com/3629489/195955690-231e2977-1611-4cdd-b3ed-8d101ac68cc7.png)
![image](https://user-images.githubusercontent.com/3629489/195955800-7013e41d-0491-4a87-9cd4-abc7c76494d8.png)

Do you see how the standard output is empty while the standard error has the result?  

---

![image](https://user-images.githubusercontent.com/3629489/195956520-2bb51950-294c-4115-b045-b37d69e42fdb.png)

![image](https://user-images.githubusercontent.com/3629489/195956610-874778b9-20e9-42b2-855b-0f4316c0f2d8.png)

**Comment by mstv** [comment]
It is surprising that git prints this information on StandardError, isn't it?
As a workaround for this git issue, `throwOnErrorOutput: false` is correct. But add a comment why this is necessary, please.
And the exit code should still be checked and e.g. printed unless being zero.

Anyway, this raises the question where the ExternalOperationException was caught without further notice. 👎

**Comment by gerhardol** [comment]
Opened a PR for this. Some info mostly written before the PR below, not cleaning up all of it.
@vbjay Please review this (maybe add unit tests too, I do not think so, @RussKie disagrees).
--
Return in stderr is not an error. That is even what the git-verify-tag should do with `--raw`
https://git-scm.com/docs/git-verify-tag
The handling of git-verify-log should only parse stderr.

Also, an unchecked Git error should raise ExternalOperationException, so there is no error exit. `throwOnErrorExit` has fixed and improved some incorrect handling in GE, even if most error suppressions were OK.

The man page does not say anything about the exit code for git-verify-tag though. 
I believe the exit code variable in cmd is `ErrorLevel `, do not know what LASTEXITCODE contains. In bash it is `$?`.
The log on https://github.com/gitextensions/gitextensions/issues/10242#issuecomment-1279560202 says that the error code is 0.

If the throw is suppressed, the exit code should normally still be checked.
The reasons for a non zero code should be investigated.
As there is nothing in the man page, search for other explanations or check the Git code.

The first two occurrences on https://github.com/gitextensions/gitextensions/issues/10242#issuecomment-1279514408
are for git-log, `throwOnErrorExit` must not be suppressed.

**Comment by vbjay** [comment]
@gerhardol  @RussKie  @mstv 
By the way, I am working on a feature where everywhere we use a gpg key we use a dropdown that gets the key ids.  Also in settings it will provide the config to set up git signing.  
![image](https://user-images.githubusercontent.com/3629489/195988795-993e795b-64e6-452e-ade6-df7c6d7db096.png)

It is how I found the issue to begin with.
