### ISSUE TITLE
[NBug] Object reference not set to an instance of an object. (Settings other than "effective")

### ISSUE THREAD

**Issue by mik0001** [gitextensions/gitextensions#10323]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUIPluginInterfaces.NumberSetting`1.NumericUpDownBinding.LoadSetting(ISettingsSource settings, NumericUpDown control)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetCurrentSettings(RepoDistSettings settings)
   at GitUI.CommandsDialogs.SettingsDialog.RepoDistSettingsPage.SetGlobalSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageHeader.GlobalRB_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Calling Plugin "Delete obsolete branches", then choose another option than "Effective"

### Steps to reproduce

Calling "Delete obsolete branches", then choose another option than "Effective".

**Comment by gerhardol** [comment]
Seem to be new

> then choose another option than "Effective".

Screenshot?

**Comment by GraySerg** [comment]
![image](https://user-images.githubusercontent.com/12149591/200547788-bb6d48e3-579c-4e52-bea8-940e2da9394c.png)

**Comment by trojanobelix** [comment]
Same here. Easy to reproduce as described and different to #10364.
