### ISSUE TITLE
[NBug] An error occurred trying to start process 'C:\Program Files...

### ISSUE THREAD

**Issue by anton-platzoeder** [gitextensions/gitextensions#10321]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.10
- DPI 120dpi (125% scaling)

### Issue description

Command: C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe

```
GitExtUtils.ExternalOperationException: An error occurred trying to start process 'C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe' with working directory 'C:\Program Files (x86)\GitExtensions'. The system cannot find the file specified.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe' with working directory 'C:\Program Files (x86)\GitExtensions'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   --- End of inner exception stack trace ---
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitUI.CommandsDialogs.FormBrowse.StartAuthenticationAgentToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Using the PuTTY option in the Tools menu throws an error

### Steps to reproduce

In the File menu, select 'Tools -> PuTTY -> Start Authentication agent'

**Comment by gerhardol** [comment]
PuTTY binaries were removed from GE in 3.4, you need to install PuTTY separately. (GE has other release cycles than PuTTY and cannot keep up at security issues etc.)
So please change your settings.

The error message could be better though. Probably add a check in Executable.Start() if the file does not exist.

**Comment by RussKie** [comment]
> In the File menu, select 'Tools -> PuTTY -> Start Authentication agent'

This opens the error dialog:
![image](https://user-images.githubusercontent.com/4403806/199875938-2ff34da7-1bbd-4723-9d5b-0a3310450fe5.png)

The actual path pageant.exe comes from the user config: C:\Users\\<user\>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings

![image](https://user-images.githubusercontent.com/4403806/199876969-f097137d-86c6-47e7-90ad-22caf0eca20b.png)

As a fix, I think, this property must check if path exists, and return `null`, if ti doesn't:
https://github.com/gitextensions/gitextensions/blob/173099c12d048d4f1c25613cedf0f42abf6e3a5d/GitCommands/Settings/AppSettings.cs#L1381

Ditto for other "file path" properties - `Plink`, `Puttygen`, etc.
