### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by DennisPitallano** [gitextensions/gitextensions#10324]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get gitflow.branch.master
Working directory: C:\GitHub\pst-withdrawal-backoffice-web\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

[Window Title]
Error

[Content]
Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get gitflow.branch.master
Working directory: C:\my directory

If you think this was caused by Git Extensions, you can report a bug for the team to investigate.

[Ignore] [Report bug!]

### Steps to reproduce

Plugins>GitFlow

### Did this work in previous version of GitExtensions?

Yes

**Comment by RussKie** [comment]
This is the error from executing `git --get gitflow.branch.master`. This is not the application issue, this is something you need to look into.
