### ISSUE TITLE
Git Flow plugin crashes on first use

### ISSUE THREAD

**Issue by mbikovitsky** [gitextensions/gitextensions#10334]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get gitflow.branch.master
Working directory: [REDACTED]

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Open the Git Flow plugin inside a repository that doesn't have Git Flow initialized.

### Did this work in previous version of GitExtensions?

[v3.5.4](https://github.com/gitextensions/gitextensions/releases/tag/v3.5.4)

### Diagnostics

The issue is that `git config --get gitflow.branch.master` exits with status 1 because the setting isn't set. Running `git flow init -d` manually beforehand solves the issue.

**Comment by vbjay** [comment]
Related to 25060c3b0683c710cd5b47cdfc550b7f8a3b4940

See work done in relation to https://github.com/gitextensions/gitextensions/issues/10242. Need to tighten git config fetching to handle values not existing.

**Comment by gerhardol** [comment]
#9056
Exit code is OK here.

```c#
        private bool IsGitFlowInitialised
        {
            get
            {
                GitArgumentBuilder args = new("config")
                {
                    "--get",
                    "gitflow.branch.master"
                };
                ExecutionResult exec = _gitUiCommands.GitModule.GitExecutable.Execute(args, throwOnErrorExit: false);
                return exec.ExitedSuccessfully && !string.IsNullOrWhiteSpace(exec.StandardOutput);
            }
        }
```

What is the usage of the GitFlow plugin if this has not been seen until now?
This plugin should probably be removed from GE core and be maintained by users.

**Comment by vbjay** [comment]
Disagree. Just because you changed git executable handling of output and didn't verify plugin handling doesn't mean you should anandan a very useful plugin. 

Git flow plugin supports git flow. https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by vbjay** [comment]
Actually the better fix is to use the module's git config functionality to retrieve the setting. @mbikovitsky did you want to attempt that change?

**Comment by gerhardol** [comment]
Short term change is to apply the change I posted.
Longer term there is no maintainer working with this plugin, so it cannot be well maintained within GE and may benefit from a separate release cycle.

**Comment by vbjay** [comment]
@mbikovitsky one thing that would help. Press f12 before launching gitflow dialog. Capture log output. Any error message?

**Comment by mbikovitsky** [comment]
@vbjay, here you go:

<details>
<summary>Log output</summary>

```plain
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   config --get gitflow.branch.master
Working dir: [REDACTED]
Process ID:  19080
Started at:  2022-11-05T18:43:00.5811365+02:00
UI Thread?:  True
Duration:    30.581 ms
Exit code:   GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
Call stack:  
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.ExecutableExtensions.<>c__DisplayClass2_0.<GetOutput>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```
</details>

But I'll leave the fix to someone else :) I don't have enough free time on my hands at this moment.

**Comment by vbjay** [comment]
Ok. @gerhardol I see what you changed. That would work too. Did you want to put it   in?

**Comment by gerhardol** [comment]
> Ok. @gerhardol I see what you changed. That would work too. Did you want to put it in?

Anyone is welcome to create a PR with that.
(I try to look at issues between other things to do and plan to submit PRs after that.)

**Comment by pmiossec** [comment]
Until a fix is released, maybe initializing GitFlow manually is the solution by running the command `git flow init -d` (for default branch naming convention) or `git flow init` (but I'm not sure the plugin support another branch name than `master`...)

**Comment by vbjay** [comment]
No. When the config is in it reads the branch name from config. It's just
yelling because of the exit code. It should accept that and not throw on
that exit code.

**Comment by pmiossec** [comment]
> When the config is in it reads the branch name from config.

For me `master`is hardcoded: https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitFlow/GitFlowForm.cs#L50
If I'm not wrong, there is no git config that store the name of the main branch of the repository.
I will be really pleased if someone prove me wrong...

**Comment by vbjay** [comment]
Yep. That is basically what is the name of the branch release and hotfix branches go to when completed.

**Comment by pmiossec** [comment]
> Yep. That is basically what is the name of the branch release and hotfix branches go to when completed. @pmiossec might want to read https://nvie.com/posts/a-successful-git-branching-model/

Yes, Yes, I know a little how it works. That's the link **I** put in the plugin UI as a documentation when I developed the plugin 😜 

That's just I didn't remember the config key name and this name was especially misleading since Git introduced support for another name for default branch...

But still, the initialization of git flow with the default values as it is done today will not support another default branch than `master`...

**Comment by vbjay** [comment]
So git flow init won't read from what git understands is the main/master/trunk
..whatever we call the default branch?

**Comment by pmiossec** [comment]
> So git flow init won't read from what git understands is the main/master/trunk
> ..whatever we call the default branch?  

It's a good question. 
I don't know if git flow try to do something clever I don't know how but I don't think so.
It's something that needs to be tested...

**Comment by vbjay** [comment]
Just did.  I renamed my branch master which is not defaukt branch name in my config.  
![image](https://user-images.githubusercontent.com/3629489/202534121-de83963f-14a9-431f-84d3-b0fc9f85d667.png)

it still was smart enough and once I ran the init, plugin behaves well.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/202535983-3a19ab95-2b89-4897-b363-cb6bcd718bbe.png)

So it actually looks at current branches to determine suggestions

**Comment by pmiossec** [comment]
I did some quick test also and when running `git flow init -d` (what is run by the plugin), there is a special handling for `master`(normal because it is the historic default) and `main`.
I tried other names `trunk` or another random one but with only 1 branch in the repository and the command failed.

So as long as `master` or `main` are used, it should be ok...

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/202537736-894716f1-8f2d-45e0-a64b-c3ed80948acd.png)
Confirmed and init.defaultbranch does not play a part

![image](https://user-images.githubusercontent.com/3629489/202539074-9cafbcb8-c90c-4c3d-ab3e-6412930266fd.png)
