### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by Timwi** [gitextensions/gitextensions#10348]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsTreeViewUserControl.textBoxFind_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.TextBox.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

I simply installed the application, opened a repo, attempted a push which failed due to SSH keys not being set up, then I opened the Settings dialog. The error occurred immediately when the dialog opened.

**Comment by RussKie** [comment]
Duplicate of #10377
