### ISSUE TITLE
[NBug] no commits visible, fetch all throws error

### ISSUE THREAD

**Issue by thomasbiel** [gitextensions/gitextensions#10349]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: D:\source\4.2\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at GitUI.CommandsDialogs.FormBrowse.fetchAllToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

tried a "Fetch all" from a non-empty repo since no commits are visible at all

### Steps to reproduce

click "fetch all"

### Did this work in previous version of GitExtensions?

yes

**Comment by gerhardol** [comment]
A variant of #10329
The PR in #10344 need to be adapted

**Comment by gerhardol** [comment]
@thomasbiel Did you pull to the repo D:\source\4.2\?
What is the output and exit code of `git remote` in this directory?

**Comment by thomasbiel** [comment]
Can‘t say, reverted to 3.5 - but it claimed that the owner was different and to execute a command which fixed the problem…

**Comment by RussKie** [comment]
> but it claimed that the owner was different and to execute a command which fixed the problem…

Something like this?
![image](https://user-images.githubusercontent.com/4403806/200512764-cea80757-25bf-4d4f-a2fc-1f6dd8c08860.png)

**Comment by thomasbiel** [comment]
the "dubious" part was identical, but the command (from v3.5) was different

**Comment by RussKie** [comment]
This error comes from git, and not an application error. You would have observed the same error on a command line too.
In v4 we improved (over v3.x) how errors that can be fixed a user are shown.
