### ISSUE TITLE
[NBug] An error occurred trying to start process 'C:\Program Files...

### ISSUE THREAD

**Issue by ira-bar** [gitextensions/gitextensions#10352]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Команда: C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe
Рабочий каталог: C:\_WORK\_PROJECTS\rrkopt.ru\

```
GitExtUtils.ExternalOperationException: An error occurred trying to start process 'C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe' with working directory 'C:\_WORK\_PROJECTS\rrkopt.ru\'. Не удается найти указанный файл.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files (x86)\GitExtensions\PuTTY\pageant.exe' with working directory 'C:\_WORK\_PROJECTS\rrkopt.ru\'. Не удается найти указанный файл.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   --- End of inner exception stack trace ---
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitUI.CommandsDialogs.FormBrowse.StartAuthenticationAgentToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

launch putty auth agent from previous install

### Steps to reproduce

launch putty auth agent from previous installation

**Comment by RussKie** [comment]
PuTTY binaries were removed from GE in 4.0, you need to install PuTTY separately. (GE has other release cycles than PuTTY and cannot keep up at security issues etc.)
So please change your settings.

**Comment by RussKie** [comment]
Duplicate of #10321

**Comment by ira-bar** [comment]
> PuTTY binaries were removed from GE in 4.0, you need to install PuTTY separately. (GE has other release cycles than PuTTY and cannot keep up at security issues etc.) So please change your settings.

 Thank's a lot!
