### ISSUE TITLE
Delete obsolete branches throws this error

### ISSUE THREAD

**Issue by blagoev** [gitextensions/gitextensions#10364]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.33.0.windows.2 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 168dpi (175% scaling)

### Issue description

```
System.ArgumentOutOfRangeException: Value of '999999999' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'. (Parameter 'value')
Actual value was 999999999.
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Delete obsolete branches throws this exception

### Steps to reproduce

Invoke "Delete obsolete branches" from the UI

### Did this work in previous version of GitExtensions?

not sure

**Comment by gerhardol** [comment]
Related to #10347 but a different issue

**Comment by mstv** [comment]
BTW: The maximum value is 100,000 (almost 274 years). Unfortunately, the exception message does print the configured values. This would be a request to WinForms.

**Comment by blagoev** [comment]
@mstv Why not keep this issue open until it is fixed. 
> So please stick to 5 nines.
Not sure if this is an answer directed to me, but I have not configured any number of nines anywhere. I just updated this to latest. I guess this value `999999999` is the default one in the config. If this value is not a correct one then the problem is the config of this plugin accepts invalid values or perhaps it defaults to invalid values.

I am totally fine for changing the issue tittle to something else like "Delete obsolete branches config accepts invalid values" but right now there is an issue which is closed as not planned.

cheers

**Comment by vbjay** [comment]
Number up down has a hard set limit

![image](https://user-images.githubusercontent.com/3629489/202522092-ea4de9ed-5d65-4a5e-a888-d393838d48e3.png)

and change focus

![image](https://user-images.githubusercontent.com/3629489/202522230-58afab89-a91a-405d-99d5-95ee6de4e8ef.png)


So we just have to confirm limit on command side vs ui.

**Comment by mstv** [comment]
Please check your settings:

![grafik](https://user-images.githubusercontent.com/36601201/202539901-a9405495-de32-49ce-ac76-fc069ab753d1.png)

I admit, this dialog allows to enter higher numbers...
