### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by AlexisPambourg** [gitextensions/gitextensions#10367]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 120dpi (125% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Le fichier spécifié est introuvable.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext()
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsFormBase.InitializeComplete()
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands)
   at GitUI.GitUICommands.<>c__DisplayClass142_0.<StartPushDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow)
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

When I push I new branch that doesnt exist on repo

### Steps to reproduce

Create a new branch that doesnt exist on repo.
Push it and bam Error

### Did this work in previous version of GitExtensions?

Yes

**Comment by pmiossec** [comment]
Can you answer the same question than here: https://github.com/gitextensions/gitextensions/issues/10363#issuecomment-1308944293

**Comment by AlexisPambourg** [comment]
J'ai redémarré et maintenant, je ne peux pas reproduire le bug. Je suis vraiment désolé pour le dérangement.
