### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by ms-coder** [gitextensions/gitextensions#10368]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext()
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsFormBase.InitializeComplete()
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands)
   at GitUI.GitUICommands.<>c__DisplayClass142_0.<StartPushDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow)
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

i can't push

### Steps to reproduce

try to push

**Comment by pmiossec** [comment]
Can you answer the same question than here: https://github.com/gitextensions/gitextensions/issues/10363#issuecomment-1308944293

**Comment by mstv** [comment]
It happened to me, too, when I tried to open FormPush.
Other GE instances running in parallel are able to push!

- Git Extensions 33.33.33
- Build 0bd62f609cb1df6348acfc6098f0a7ac6b57dcf4
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext()
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsFormBase.InitializeComplete()
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands)
   at GitUI.GitUICommands.<>c__DisplayClass142_0.<StartPushDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow)
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by vbjay** [comment]
Output of 

```cmd
dotnet --list-sdks

dotnet --list-runtimes
```

**Comment by mstv** [comment]
@vbjay, my point is:

> Other GE instances, which have been running in parallel for more than one day, are able to push!
Restarting the affected instance has helped.

**Comment by vbjay** [comment]
During that time did you alter dotnet runtimes?  Curious if that might have caused issues.

**Comment by RussKie** [comment]
Do you know if that happened straight away or after some specific action?
E.g., opening settings or using a plugin?
Do you have some 3rd party plugins installed?

It looks like we completely overlooked versioning
gitextensions.extensibility package and the Package Manager. Both of which
still target net5.0.

**Comment by mstv** [comment]
The this week's Windows update (from local WSUS) was waiting for reboot since about an hour before.

I have even disabled plug-in loading on that machine.

**Comment by mstv** [comment]
#10376 might have the same cause although a different DLL was affected.

**Comment by RussKie** [comment]
So, resolved?

**Comment by mstv** [comment]
> So, resolved?

Still unclear.
Windows update should know that .NET is in use...
Anti-Virus temporarily blocking a file?
But why does it need a restart of the application then?

**Comment by vbjay** [comment]
Because it loaded different dlls when app was running for days vs your run after the update. Windows does seem to fail here where Linux supports inode replacement and no reboot patching to a point.

**Comment by vbjay** [comment]
I'd leave it to weird state from update. Possibly report to windows and dotnet teams to support some kind of state move feature like installer creating symbolic links or whatnot so there isn't some kind of weird mid update state.

**Comment by mstv** [comment]
> Because it loaded different dlls when app was running for days vs your run after the update.

N/A because:

>> Other GE instances, which **have been running in parallel** for more than one day, are able to push!

All instances were started at the same time. I think I had pushed from all instances before the updates.

> I'd leave it to weird state from update.

I agree.

Does it work for you after restart (and installation of .NET desktop runtime >= 6.0.9), too, @ms-coder?
