### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Net.Mail, Version=6...

### ISSUE THREAD

**Issue by espr14** [gitextensions/gitextensions#10363]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches()
   at GitUI.PatchGrid.Initialize()
   at GitUI.PatchGrid.OnRuntimeLoad()
   at ResourceManager.GitExtensionsControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I wanted to rebase on the selected commit.

### Steps to reproduce

Rebase on commit.

### Did this work in previous version of GitExtensions?

It worked in 3.4.x

**Comment by pmiossec** [comment]
My 1st though would be that it is an install problem...

Is it possible that you installed the v4 in a not empty folder of a previous version?
If yes, could you try an install in an emptied directory or in another folder?

In the program folder, do you have this 'System.Net.Mail.dll' file? If yes, could you move it outside of the folder and try again?

It could be a lot of things similar but the idea is that the application found a bad version of 'System.Net.Mail.dll' somewhere and try to load it instead of the good one installed with the .net 6 desktop runtime...

**Comment by CRidge** [comment]
I for one cannot find System.Net.Mail.dll anywhere in any folder relating to GitExtensions on my machine. I do, however, find a total of 138 copies of that file across my disks :)
