### ISSUE TITLE
[NBug] Out of memory.

### ISSUE THREAD

**Issue by Klaus-fischer** [gitextensions/gitextensions#10372]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Added (German.gif / German.xfl / German.Plugins.xlf) files from https://github.com/gitextensions/gitextensions/tree/master/GitUI/Translation 

to Translation directory

### Steps to reproduce

1. Add German translation from https://github.com/gitextensions/gitextensions/tree/master/GitUI/Translation to Translation directory
2. select choose language in the basic setting overview

**Comment by Klaus-fischer** [comment]
Issue fixed, 

die Gif image was not correct copied or downloaded (could not be displayed in explorer as well)
