### ISSUE TITLE
[NBug] Value must not be null. (Open Settings)

### ISSUE THREAD

**Issue by zmaten** [gitextensions/gitextensions#10377]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsTreeViewUserControl.textBoxFind_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.TextBox.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Open GE
Alt+T
Arrow UP
Enter (at settings)

### Steps to reproduce

Open GE
Alt+T
Arrow UP
Enter (at Settings)

### Did this work in previous version of GitExtensions?

Yes

**Comment by mstv** [comment]
Thank you for describing the repro, @zmaten!

**Comment by mstv** [comment]
Is there a way to tell the duplicates-detector-bot to ignore an analyzed ticket, (which is not a duplicate)?

**Comment by RussKie** [comment]
> Is there a way to tell the duplicates-detector-bot to ignore an analyzed ticket, (which is not a duplicate)?

The code is here: https://github.com/RussKie/potential-duplicates-bot
