### ISSUE TITLE
[NBug] An error occurred trying to start process 'https://github.c...

### ISSUE THREAD

**Issue by gatepoet** [gitextensions/gitextensions#10429]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.10
- DPI 144dpi (150% scaling)

### Issue description

Tries to open web URL as file on disk
```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://github.com/acaudwell/Gource/' with working directory 'C:\Program Files (x86)\GitExtensions'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at GitExtensions.Plugins.Gource.GourceStart.linkLabel1_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Click toolbar: Plugins -> Gource
Click link: Gource project

**Comment by vbjay** [comment]
Looks like url is now a 404.  Should point to https://github.com/acaudwell/Gource/wiki/Controls now.

Change here. 
https://github.com/gitextensions/gitextensions/blob/master/Plugins/Gource/GourceStart.cs#L156


Might also use open in default browser functionality.  https://github.com/gitextensions/gitextensions/blob/master/GitUI/OsShellUtil.cs#L45

**Comment by SaumyaBhushan** [comment]
Hi @vbjay Can you please check the pull request?
