### ISSUE TITLE
[NBug] error: pathspec 'Scenarios/...

### ISSUE THREAD

**Issue by nirhp** [gitextensions/gitextensions#10468]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout dd71d42fee822db96497ae2290112536b3686d06 -- "Scenarios../..SiteSimulator500@SiteSimulator.xml"
Working directory: C:\wor..

```
GitExtUtils.ExternalOperationException: error: pathspec 'Scenarios/...SiteSimulator500@SiteSimulator.xml' did not match any file(s) known to git
 ---> System.Exception: error: pathspec 'Scenarios/.../..SiteSimulator500@SiteSimulator.xml' did not match any file(s) known to git
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunBatchCommand(IExecutable executable, ICollection`1 batchArguments, Action`1 action, Byte[] input, Boolean createWindow)
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at GitUI.CommandsDialogs.RevisionDiffControl.resetFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I tried to reset change to a file which was renamed.

The reset was done in a non head commit by right clicking it.

### Steps to reproduce

1. Select a non-head commit which contains a file rename.
2. Open the commit "diff" tab, 
3. Right click the renamed file
4. Select "reset file to" -> "first"

Reult:
GitExtentions will crash

**Comment by mstv** [comment]
Similar to #10423 and #10470.
This is not a crash. GE has just tried a command which could not be applied in the current state of this file. This can be improved.
Instead of nothing happening, you got a popup.

As a workaround, you could delete the working copy file and restore the desired revision then.

**Comment by RussKie** [comment]
@mstv was #10556 targeting this as well?

@nirhp  can you please try one of the latest 4.0 build and see if your issue is fixed? E.g., this one https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45820457/artifacts.

**Comment by gerhardol** [comment]
@nirhp Please try the correction in #10853
