### ISSUE TITLE
[NBug] git checkout-index: backend/src/S...

### ISSUE THREAD

**Issue by AndreyRavkov** [gitextensions/gitextensions#10470]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "backend/src/Services/Quote/Validation/Rules/Common/Inactive/ListPriceExceededInRenewalRule.cs" "backend/tests/Services.Tests/Quote/Validation/Rules/Common/ListPriceExceededInRenewalRuleTests.cs"
Working directory: D:\_projects\mf\

```
GitExtUtils.ExternalOperationException: git checkout-index: backend/src/Services/Quote/Validation/Rules/Common/Inactive/ListPriceExceededInRenewalRule.cs is not in the cache
 ---> System.Exception: git checkout-index: backend/src/Services/Quote/Validation/Rules/Common/Inactive/ListPriceExceededInRenewalRule.cs is not in the cache
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

git cherry-pick
merge wih remove file
revert changes

### Steps to reproduce

git cherry-pick
choose to merge with removed file
revert changes

**Comment by RussKie** [comment]
@mstv was #10556 targeting this as well?

@AndreyRavkov  can you please try one of the latest 4.0 build and see if your issue is fixed? E.g., this one https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45820457/artifacts.

**Comment by gerhardol** [comment]
> @mstv was #10556 targeting this as well?

No

**Comment by gerhardol** [comment]
Stage/unstage to reset for now.
Upcoming 4.1 handles reset in some more situations but not conflicts when files are removed or added.

To handle this some internal datastructures need to be changed (so worktree and index status know each other).
This is not planned, the focus is to get 4.1 released right now.

**Comment by RussKie** [comment]
@gerhardol do you have any plans for this?

**Comment by gerhardol** [comment]
> do you have any plans for this?

Not right now.

The likely most common situations of a generic "reset" are handled.
The direct use of the Reset form (Reset current branch to here) should follow Git and not be too smart.
There are some other generic reset cases that could be handled, but they could lead to more situations like #11216 so the behavior is not obvious.
The output at Git errors are improved in next version.
Let us implement what is seen as problems, or present the scenario to the users somehow.

**Comment by RussKie** [comment]
> > do you have any plans for this?
> 
> Not right now.

I'm punting it out of v4.2 then.

**Comment by SAPHemlock** [comment]
Some of this has aged out and some of it has not, so here is where it stands on master.

### The reported stack trace can no longer happen

`FormCommit.ResetSoftClick` does not go near `checkout-index` any more — it is a plain soft reset now (`FormCommit.cs:1962-1982`):

```csharp
ArgumentString cmd = Commands.Reset(ResetMode.Soft, _resetSoftRevision);
Module.GitExecutable.RunCommand(cmd);
```

and `GitModule.ResetFiles` from the trace was renamed to `CheckoutIndexFiles`. So this exact report cannot reproduce.

### The mechanism @gerhardol described is still there

`CheckoutIndexFiles` (`GitModule.cs:1327-1341`) is still reached from `GitModule.ResetChanges` (`:1446`), which is live behind "reset selected files" — `FileStatusList.ContextMenu.cs:998` and `GitUICommands.cs:882`. And it still cannot report a failure:

```csharp
return GitExecutable.GetBatchOutput(new GitArgumentBuilder("checkout-index") { "--index", "--force", "--" }
    .BuildBatchArgumentsForFiles(files));
```

`GetBatchOutput` (`ExecutableExtensions.cs:62-77`) has no `throwOnErrorExit` parameter at all — it loops over `GetOutput`, and that path hard-codes `throwOnErrorExit: true` (`:110`). So any non-zero exit from `checkout-index`, including the "is not in the cache" case @gerhardol identified as legitimate for some file statuses, leaves as an exception. Neither caller catches it.

Worth noting the sibling method already solves this: `RunBatchCommand` (`:181-187`) does take `throwOnErrorExit`, and roughly forty call sites elsewhere in `GitModule.cs` pass `false` and inspect the `ExecutionResult`. `CheckoutIndexFiles` is one of the few that does not, and it is one where git failing is expected rather than exceptional.

The smallest change that turns the crash into a message would be to switch it over:

```csharp
return GitExecutable.RunBatchCommand(new GitArgumentBuilder("checkout-index") { "--index", "--force", "--" }
        .BuildBatchArgumentsForFiles(files),
    throwOnErrorExit: false)?.StandardOutput ?? string.Empty;
```

and let `ResetChanges` surface the stderr through the message it already builds for `filesInUse`/`filesCannotCheckout`, rather than as an NBug report. `git log -S"checkout-index"` shows nothing that deliberately made this throw — the pattern since has been narrow pre-filters (#10854, #11035, #11393) rather than changing the contract.

### Why I have not just sent it

@gerhardol was explicit here that the real fix needs the worktree and index status to know about each other, that it was not planned, and #10854 says in as many words that it does not cover the added/removed case. Converting the crash to a message is a symptom fix, and it would make a genuine failure quieter — reasonable for an operation that is expected to fail on some files, but that is a maintainer's call, not mine.

I also could not verify that the original repro (cherry-pick producing a removed file, then revert) still reaches `CheckoutIndexFiles` today, given the filters added since 2023.

If you want the patch above I will send it with a test — `GitModuleTests` has no `CheckoutIndexFiles` coverage at all, and a test staging a non-zero exit would genuinely fail on master today. Otherwise this issue is arguably closeable, since the trace in it is from code that no longer exists.

*Analysed with [Claude Code](https://claude.com/claude-code).*

**Comment by RussKie** [comment]
> If you want the patch above I will send it with a test — GitModuleTests has no CheckoutIndexFiles coverage at all, and a test staging a non-zero exit would genuinely fail on master today. Otherwise this issue is arguably closeable, since the trace in it is from code that no longer exists.

This would be great, thank you
