### ISSUE TITLE
[NBug] error: the following file has staged content different from...

### ISSUE THREAD

**Issue by jebisseySidel** [gitextensions/gitextensions#10494]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: rm --cached "PC.Lib.AsyncTcpServer.net6"
Working directory: C:\Users\BisseyJE\Documents\Sidel\Dev\Test\PlcSimu\

```
GitExtUtils.ExternalOperationException: error: the following file has staged content different from both the
file and the HEAD:
    PC.Lib.AsyncTcpServer.net6
(use -f to force removal)
 ---> System.Exception: error: the following file has staged content different from both the
file and the HEAD:
    PC.Lib.AsyncTcpServer.net6
(use -f to force removal)
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at GitCommands.GitModule.UnstageFile(String file)
   at GitUI.CommandsDialogs.FormSubmodules.RemoveSubmoduleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Try to remove a previously added submodule

### Steps to reproduce

Remove a submodule

### Did this work in previous version of GitExtensions?

yes

**Comment by mstv** [comment]
Similar to #10423, could be set as a duplicate.
git-checkout-index cannot be used for files with certain statuses.
Before 4.0 the Git error was just hidden, the popup is added in 4.0. Just ignore it for now.
