### ISSUE TITLE
[NBug] Unable to pull after updating Git and Git Extensions

### ISSUE THREAD

**Issue by silashn** [gitextensions/gitextensions#10497]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: C:\Data\Repositories\aspiri\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPullClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Updated to latest version of Git and Git Extensions, afterwards I tried to pull from a branch on a repository that previously worked flawlessly.

**Comment by pmiossec** [comment]
It seems more due to the git update. Seems duplicate of #9954.
See discussion in this issue...
