### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by sloschiavo** [gitextensions/gitextensions#10504]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at GitUI.Blame.BlameControl.contextMenu_Opened(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Right click on the 2nd pane, in the File Tree Tab with a file selected. The pane shows nothing in it, similar to the 3rd pane (file preview?), which is also empty

### Steps to reproduce

Select a commit. In the bottom of the window, select the "File Tree" tab. In the Tree, select any random file.  Nothing shows in the 2nd and 3rd panes. 
Right click on the 2nd pane. Error occurs.

### Did this work in previous version of GitExtensions?

Has worked in previous versions, as I rely a lot on the info in the File Tree to file contents of previous commits. Not sure what version I was using prior to this, I had to uninstall it in order to install 4.0.0

**Comment by gerhardol** [comment]
Any errors in Git Command Log?
What path is the repo stored in, special characters or spaces?

Blame is default in 4.0, you can select View in context menu or with `B`.

This works for me.
filename or blameid is not set here.

**Comment by sloschiavo** [comment]
Ah,  "B" fixed it. Seems to alternate between two different views. I don't know what the non-working view is supposed to be.

This is what is logged when clicking on the file in File Tree...

File name:   C:\Program Files\Git\bin\git.exe
Arguments:   blame --porcelain -M -w -l "ccdc781e35a23957029b62512b7fe2b7f1cd1453" -- "VERSION"
Working dir: C:\git\brandm8\
Process ID:  14052
Started at:  2022-12-08T13:03:19.1382778+11:00
UI Thread?:  False
Duration:    83.543 ms
Exit code:   GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.Blame(String fileName, String from, Encoding encoding, String lines, CancellationToken cancellationToken)
   at GitUI.Blame.BlameControl.<>c__DisplayClass31_0.<LoadBlameAsync>b__0(CancellationToken cancellationToken)
   at GitCommands.AsyncLoader.<>c__DisplayClass10_0.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.LoadAsync[T](Func`2 loadContent, Action`1 onLoaded)
Call stack:  
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.ExecutableExtensions.<>c__DisplayClass8_0.<Execute>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.Blame(String fileName, String from, Encoding encoding, String lines, CancellationToken cancellationToken)
   at GitUI.Blame.BlameControl.<>c__DisplayClass31_0.<LoadBlameAsync>b__0(CancellationToken cancellationToken)
   at GitCommands.AsyncLoader.<>c__DisplayClass10_0.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.LoadAsync[T](Func`2 loadContent, Action`1 onLoaded)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by gerhardol** [comment]
> I don't know what the non-working view is supposed to be.

Blame is default in 4.0 (maybe changed to View in #10453).
See context menu.
