### ISSUE TITLE
[NBug] An error occurred trying to start process 'https://gerrit.e...

### ISSUE THREAD

**Issue by BBzzz** [gitextensions/gitextensions#10508]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://gerrit.ext.net.nokia.com/gerrit/c/CSF-CMT/+/4969386' with working directory 'C:\Users\bborbely\work\CSF-CMT'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at GitExtensions.GerritPlugin.FormGerritChangeSubmitted.<>c__DisplayClass1_0.<ShowSubmitted>b__0(Object s, EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Just trying to create a new gerrit review

### Steps to reproduce

Try to publish a new gerrit review

**Comment by pmiossec** [comment]
Have you updated the plug-in to the last version 2.0.1 in the plug-in manager?

**Comment by BBzzz** [comment]
Yes, I already did (a week ago), right now I have GitExtensions.GerritPlugin.2.0.1.128
