### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by petrkoula** [gitextensions/gitextensions#10528]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 120dpi (125% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Systém nemůže nalézt uvedený soubor.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext()
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items)
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromFields(String category, Object obj, ITranslation translation)
   at ResourceManager.TranslationUtils.TranslateItemsFromFields(String category, Object obj, ITranslation translation)
   at ResourceManager.GitExtensionsFormBase.TranslateItems(ITranslation translation)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsControlInitialiser.InitializeComplete()
   at ResourceManager.GitExtensionsFormBase.InitializeComplete()
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands)
   at GitUI.GitUICommands.<>c__DisplayClass142_0.<StartPushDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow)
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

- I created two commits into a branch
- I clicked at Push icon
- An error window appeared..

**Comment by petrkoula** [comment]
It works normally after app restart.
