### ISSUE TITLE
[NBug] fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMa...

### ISSUE THREAD

**Issue by NikolayGrigoryev** [gitextensions/gitextensions#10542]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.33.0.windows.2 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: rm -- "GGClient/Assets/AdditiveHands-ForRegularMan.anim" "GGClient/Assets/AdditiveHands-ForRegularMan.anim.meta"
Working directory: D:\WORK\REPOS\GG\

```
GitExtUtils.ExternalOperationException: fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMan.anim' did not match any files
 ---> System.Exception: fatal: pathspec 'GGClient/Assets/AdditiveHands-ForRegularMan.anim' did not match any files
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.RemoveFiles(IReadOnlyList`1 files, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedFilesWithConfirmation()
   at GitUI.CommandsDialogs.RevisionDiffControl.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsControl.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.RevisionDiffControl.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### Steps to reproduce

Hi guys, thanks for your work <3
I tried to reset working copy files. It had added files and chenged. I sellected both.

### Did this work in previous version of GitExtensions?

yes, it is a new crash

**Comment by NikolayGrigoryev** [comment]
May be it helps: After sellecting files in diff tab I used Hotkey R to invoke the reset.

**Comment by NikolayGrigoryev** [comment]
Another tip - I found that it reproduces even if I select only added files. Probably they did not exist in my local copy, but Diff tab had elder information.

**Comment by mstv** [comment]
Newly added files need to be _deleted_ instead.
The previous version just did nothing visible in this case.
Perhaps GE should automatically run different git commands in dependency on the file status.

**Comment by NikolayGrigoryev** [comment]
I can imagine the best user-friendly variant - deleting for new and resetting for diffs, yes.

**Comment by gerhardol** [comment]
It is easier to explain to users to only allow reset if only tracked files are shown, that is how most commands are implemented. 
This is the intention here already, supposedly need to be tweaked.

For FormCommit, similar handling need to be tweaked for update-index, there are some issues for 4.0.

**Comment by mstv** [comment]
But the hotkey `R` bypasses the enabled state of the regarding context menu item.

**Comment by gerhardol** [comment]
> But the hotkey `R` bypasses the enabled state of the regarding context menu item.
> 
> And I am happy that I get told at least that it didn't work.

Better if there is a popup with info that reset cannot be done prior to execution?

**Comment by mstv** [comment]
> Better if there is a popup with info that reset cannot be done prior to execution?

I don't think so but:

> GE should automatically run different git commands in dependency on the file status.
