### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by AlexNek** [gitextensions/gitextensions#10550]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 192dpi (200% scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get gitflow.branch.master
Working directory: Y:\user_alex_new\dot_net2022\AddOns\DocumentationAssistant\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.get_IsGitFlowInitialised()
   at GitExtensions.Plugins.GitFlow.GitFlowForm.Init()
   at GitExtensions.Plugins.GitFlow.GitFlowForm..ctor(GitUIEventArgs gitUiCommands)
   at GitExtensions.Plugins.GitFlow.GitFlowPlugin.Execute(GitUIEventArgs args)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Start gitflow on clone https://github.com/jinyafeng/DocumentationAssistant.git

### Steps to reproduce

clone https://github.com/jinyafeng/DocumentationAssistant.git
Start gitflow

**Comment by RussKie** [comment]
What do you get if you run it from a command line?

**Comment by AlexNek** [comment]
How can I run it on command line? I can see menu only.

**Comment by mstv** [comment]
start cmd.exe and enter
```
cd Y:\user_alex_new\dot_net2022\AddOns\DocumentationAssistant\
"C:\Program Files\Git\bin\git.exe" config --get gitflow.branch.master
```

**Comment by AlexNek** [comment]
it is return nothing. It doesn't work with nay repo. Something broken as in previous time it is work fine

**Comment by mstv** [comment]
The plugin should ignore the ExitCode 1, which is returned by git in case no regarding configuration exists, in this case "gitflow.branch.master".
As a workaround, you could configure it manually`:
```
"C:\Program Files\Git\bin\git.exe" config --get gitflow.branch.master master
```
Not sure, which value is expected.

**Comment by mstv** [comment]
... without `--get`, of course

**Comment by AlexNek** [comment]
I can do the same work with: git flow init. Previous command doesn't work everywhere or I was looking into wrong repo and confirm for working

**Comment by gerhardol** [comment]
Fixed in #10341, included in 4.0.1

**Comment by AlexNek** [comment]
- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 192dpi (200% scaling)
- Microsoft.WindowsDesktop.App Versions

No changes. The same error

**Comment by mstv** [comment]
Sorry, this patch was missing in the release branch. I have added it right now.
