### ISSUE TITLE
[NBug] There is an error in XML document (9, 2).

### ISSUE THREAD

**Issue by Ludwig151** [gitextensions/gitextensions#10553]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 106dpi (110% scaling)

### Issue description

```
System.InvalidOperationException: There is an error in XML document (9, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderTranslationFile.Read6_xliff()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at ResourceManager.Xliff.TranslationSerializer.Deserialize(String path)
   at ResourceManager.Translator.GetTranslation(String translationName)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsControlInitialiser.InitializeComplete()
   at ResourceManager.GitExtensionsControl.InitializeComplete()
   at GitUI.BranchTreePanel.RepoObjectsTree..ctor()
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent()
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, BrowseArguments args)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

downloaded french translation on https://github.com/gitextensions/gitextensions/tree/master/GitUI/Translation
and apply to Git Extensions v4.0.1.15887 then crash

### Steps to reproduce

downloaded french translation on https://github.com/gitextensions/gitextensions/tree/master/GitUI/Translation
3 files : French.gif, French.xlf and French.Plugins.xlf
copy to C:\Program Files (x86)\GitExtensions\Translation\
Then Menu Tools - Settings - Appearance - Language - Choose French
Restart then Crash

### Did this work in previous version of GitExtensions?

first version I try

**Comment by mstv** [comment]
Works for me with the [most recent files](https://github.com/gitextensions/gitextensions/tree/c948b3539670c462ad7d82b3c4020d00625c3260/GitUI/Translation):

![image](https://user-images.githubusercontent.com/36601201/208396032-7bf796af-d73d-44b9-99ec-0c8a021aeda2.png)

**Comment by Ludwig151** [comment]
Retry with the 3 files French.gif, French.xlf and French.Plugins.xlf from : 
https://github.com/gitextensions/gitextensions/tree/c948b3539670c462ad7d82b3c4020d00625c3260/GitUI/Translation
exactly the same result

**Comment by gerhardol** [comment]
> <html xmlns=''>

The file was saved with html, not as raw, so there is a lot of garbage in it...
