### ISSUE TITLE
[NBug] error: open("data/user/creator_inf4all/.ipython/profile_def...     on handling linux symlinks

### ISSUE THREAD

**Issue by abauske** [gitextensions/gitextensions#10600]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies -U1000000 -- "data/user/creator_inf4all/.ipython/profile_default/startup/get_cell_info.py"
Working directory: C:\Users\adria\Documents\Uni\AI8\

```
GitExtUtils.ExternalOperationException: error: open("data/user/creator_inf4all/.ipython/profile_default/startup/get_cell_info.py"): Invalid argument
fatal: cannot hash data/user/creator_inf4all/.ipython/profile_default/startup/get_cell_info.py
 ---> System.Exception: error: open("data/user/creator_inf4all/.ipython/profile_default/startup/get_cell_info.py"): Invalid argument
fatal: cannot hash data/user/creator_inf4all/.ipython/profile_default/startup/get_cell_info.py
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.GetCurrentChangesAsync(String fileName, String oldFileName, Boolean staged, String extraDiffArguments, Encoding encoding, Boolean noLocks)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetChangedFileTextAsync(GitModule module, GitItemStatus file)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(CancellationToken cancellationToken)
   at GitUI.SpellChecker.EditNetSpell.<InitializeAutoCompleteWordsTask>b__109_0()
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitUI.SpellChecker.EditNetSpell.UpdateOrShowAutoComplete(Boolean calledByUser)
   at GitUI.SpellChecker.EditNetSpell.AutoCompleteTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

This happens all the time when having linux symlink (e.g. created from inside a docker container). The commit process was done in a docker container as GitExtensions always throws this error.

### Steps to reproduce

- Run a docker container and mount a windows volume inside (that windows volume is managed by GitExtension as a git project)
- now create symlinks from within the docker container so the symlink-file is inside that windows volume
- now try to commit this symlink from GitExtensions -> Errors when typing the commit message (after about the 10th letter)
- now mount the entire git repo into the docker container and commit the symlink from there using command line -> everything fine
- windows GitExtensions still shows changed files and when trying to commit other unrelated files this error appears

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks

**Comment by knight37x** [comment]
@vbjay thanks for your suggestion
I tried both `git config core.symlinks false` and `git config core.symlinks true` but errors are popping up on both settings. Maybe I am doing something wrong?

**Comment by vbjay** [comment]
Reinstall git and validate symlink support

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows

May help.

**Comment by gerhardol** [comment]
This error could be ignored, auto completion is not essential functionality. (In 3.x such errors were always ignored.)
However, similar issues should occur in the diff window.

In mixed win/*nix environments like this, disable filemode in windows, you normally want it enabled in *nix though.
With a path like C:\Users\adria\Documents\Uni\AI8\ GE will use the Windows Git (WSL mode is not involved here.)

**Comment by gerhardol** [comment]
Probably the same as #10499, should be handled by #10934
