### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by joepuresdk** [gitextensions/gitextensions#10605]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.DisplayInformation.get_BitsPerPixel()
   at System.Windows.Forms.DisplayInformation.get_LowResolution()
   at System.Windows.Forms.ToolStripProfessionalRenderer.get_RendererOverride()
   at System.Windows.Forms.ToolStripProfessionalRenderer.OnRenderToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
   at System.Windows.Forms.ToolStripRenderer.DrawToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
   at System.Windows.Forms.ToolStripPanel.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

GitExtensions was just running in the background.
When I tried to bring it to front I got this error.

it is possible that I changed system font size while GitExtensions was in the background.

### Steps to reproduce

I was not able to reproduce this.

**Comment by gerhardol** [comment]
Duplicate of #8921 and #7433
No known way to reproduce
