### ISSUE TITLE
Unsupported file: GitExtUtils.ExternalOperationException: fatal: git cat-file ...: bad file

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#10643]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The error raises in the GitExt Browser on that repository commit:
https://github.com/andry81-tests/gil-test1-A/commit/f5f753fed28282a7297428e2eb158f948f719711

I am not sure is that a bug, but the github itself parses it correctly as `Submodule gil-test1-B added at aaeb0e`.

### Steps to reproduce

>git clone https://github.com/andry81-tests/gil-test1-A X

If open the GitExt browse on the cloned repository and select the commit from the list, then the diff pane would has:

```
Unsupported file: 

GitExtUtils.ExternalOperationException: fatal: git cat-file aaeb0e3c6454758ad849b61bd0cab4a1f86b955c: bad file
 ---> System.Exception: fatal: git cat-file aaeb0e3c6454758ad849b61bd0cab4a1f86b955c: bad file
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.GetFileText(ObjectId id, Encoding encoding)
   at GitUI.Editor.FileViewer.<>c__DisplayClass126_0.<ViewGitItemAsync>g__GetFileTextIfBlobExists|1()
   at GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.LoadAsync[T](Func`2 loadContent, Action`1 onLoaded)
```

**Comment by mstv** [comment]
Refer to https://github.com/gitextensions/gitextensions/discussions/10644.
