### ISSUE TITLE
[NBug] One or more errors occurred. (Exception of type 'GitCommand...

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#10691]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

```
System.AggregateException: One or more errors occurred. (Exception of type 'GitCommands.Config.GitConfigurationException' was thrown.)
 ---> GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown.
 ---> System.Exception: Key <<<<<<< HEAD in config file C:\temp\...\.gitmodules is not in a section.
   at GitCommands.Config.ConfigFile.ConfigFileParser.NewKey()
   at GitCommands.Config.ConfigFile.ConfigFileParser.ReadKey(Char c)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.GitModule.<.ctor>g__InitialiseSubmoduleProperties|21_6()
   at GitCommands.GitModule..ctor(String workingDir)
   at GitCommands.Git.SubmoduleHelpers.ParseSubmoduleStatus(String text, GitModule module, String fileName)
   at GitCommands.Git.SubmoduleHelpers.ParseSubmodulePatchStatus(Patch patch, GitModule module, String fileName)
   at GitCommands.Git.SubmoduleHelpers.GetCurrentSubmoduleChangesAsync(GitModule module, String fileName, String oldFileName, Boolean staged, Boolean noLocks)
   at GitCommands.GitModule.<>c__DisplayClass195_0.<<GetCurrentSubmoduleStatus>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at GitUI.FileStatusList.<>c__DisplayClass128_0.<<UpdateFileStatusListView>b__5>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GitUI.FileStatusList.AppendItemSubmoduleStatus(String text, GitItemStatus item)
   at GitUI.FileStatusList.FormatListViewItem(ListViewItem item, PathFormatter formatter, Int32 itemWidth)
   at GitUI.FileStatusList.<>c__DisplayClass129_0.<UpdateColumnWidth>b__2(ListViewItem item)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.DefaultIfEmptyIterator`1.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at GitUI.FileStatusList.<UpdateColumnWidth>g__GetWidth|129_0()
   at GitUI.FileStatusList.UpdateColumnWidth()
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Open the commit form while there is a conflict on .gitmodules file:

```
<<<<<<< HEAD
[submodule "XXX"]
	path = XXX
	url = https://XXX.git
	branch = "XXX"
=======
[submodule "YYY"]
	path = YYY
	url = https://YYY.git
	branch = "YYY"
>>>>>>> b8b771d (...)

```

The form looks to load for ever. Then I tried to resize the form and I get this error.

I can't reproduce the exception but the form is always in loading mode.

**Comment by gerhardol** [comment]
This is intentional. You have a bad Git config issue that GE cannot handle. Some scenarios could be fine ignoring the issue, others not. (Before 4.0 GE mostly silently ignored such errors, which had other cosequences.)
The error itself could be presented differently, but there are a few levels of errors already.
Suggest this is closed.

**Comment by mstv** [comment]
(I cannot reproduce it by manually editing the `.gitmodules` file.)
Do you get the conflict banner in the RevisionGrid (before opening FormCommit)?

![image](https://user-images.githubusercontent.com/36601201/215598223-2b276ac5-00fc-48d0-9a38-ba39db8c7768.png)

**Comment by RussKie** [comment]
I'm inclined to close this. The app alerted to the fact there's a broken config, and you know how to fix it. The app can't fix it for you. 
Special-casing the error doesn't feel like a priority to me either.

**Comment by bansan85** [comment]
To reproduce the bug, I have done :

  * Create a new repository with a default branch
  * Create a first commit with a random file
  * Add a submodule and commit it with the .gitsubmodule file
  * Create a new branch on the initial commit
  * Add a submodule (not the same than the first submodule) and commit it with the .gitsubmodule file
  * Rebase the second branch on the first branch

You will have a conflict. Close the rebase form and click on commit. You will have a loading form.

Unfortunately, I still can't reproduce the exception :(

![image](https://user-images.githubusercontent.com/9248729/216270324-947d958b-604c-4341-b018-8eb05d5c107f.png)

**Comment by bansan85** [comment]
If I click on the refresh button (at the top on the left), it refreshes the form with a better (but not best) result.

I think that this form should appear at start.

![image](https://user-images.githubusercontent.com/9248729/216272896-bf8f55b5-65d5-46e3-a343-65676a967ee9.png)

**Comment by RussKie** [comment]
This is a low priority bug. Pull requests are welcome.
