### ISSUE TITLE
[NBug] Unable to sort because the IComparer.Compare() method retur...

### ISSUE THREAD

**Issue by PeterSchuebel** [gitextensions/gitextensions#10706]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 216dpi (225% scaling)

### Issue description

```
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[GitUI.UserControls.RevisionGrid.Graph.RevisionGraphRevision]'.
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedNodesCache(Int32 currentRowIndex)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.GetNodeForRow(Int32 row)
   at GitUI.RevisionGridToolTipProvider.OnCellMouseMove(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseMove(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I pulled from my repo, which seemed OK, but when I then clicked OK on the final dialog the error came up. Probably related to GitExtensions refreshing the UI for the new content.

I would recommend writing unit tests for the affected comparator code, to ensure strict weak ordering is preserved.

### Steps to reproduce

* open existing working copy of my repo. it shows all remote branches, 3 of which also exist locally for active work.
* press "pull and rebase button" to get the currently checked out and active branch up-to-date with the remote origin. I have no local changes at this point, so nothing actually needs rebasing
* the process runs through and fetches all branches, and pulls changes from my active branch and updates to the branch head
* the dialog stays open, so I need to confirm by clicking OK
* I click OK.
* The exception appears.

This could not be replicated again by following the same steps. Most likely because the second time there was nothing to fetch/pull.

### Did this work in previous version of GitExtensions?

It worked OK in the same version before and after. So the error only occurrs sometimes.

**Comment by mstv** [comment]
Indeed, the existing unit tests fail in very rare occasions - seems to be a race condition in parallel execution.
I have not seen this error popup but noticed varying sorting of branches on refresh (`F5`) - but I only use my private build with an extended branch sorting strategy. I thought it was not mature.
Since this happens in real use now, we need to analyze...
