### ISSUE TITLE
[NBug] Index was outside the bounds of the array: Error in the `BackgroundFetchPlugin`

### ISSUE THREAD

**Issue by simonmckenzie** [gitextensions/gitextensions#10700]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

I am experiencing an out of range exception when I have the periodic background fetch plugin active:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitExtensions.Plugins.BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass11_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
```

### Steps to reproduce

Turn on periodic background fetch, set a fetch period, wait! I have the fetch set to 300 seconds.
This happens on the first trigger of the background fetch (for me, after five minutes).

Note that I do _not_ have any git command set for this operation - there wasn't one there by default (I only just installed the app), so I don't know if that's the problem:

![screenshot of the background fetch plugin settings](https://user-images.githubusercontent.com/17579442/216885395-79277239-16c2-4f88-9cc6-7b1ce4d9e50a.png)

### Did this work in previous version of GitExtensions?

Yes, the final v3 version.

**Comment by gerhardol** [comment]
Git error log (F12) with the last command s

**Comment by simonmckenzie** [comment]
Hi @gerhardol,

The app is in a crashed state by then - I can't open the error log. I can confirm, however, that the error is caused by having empty "arguments" configured for the plugin.

**Comment by gerhardol** [comment]
Just do not enable the plugin if command is not set.
Did a crude PR to use the default value "fetch --all" if empty.
