### ISSUE TITLE
[NBug] An error occurred trying to start process 'https://github.c...

### ISSUE THREAD

**Issue by neuxioz** [gitextensions/gitextensions#10726]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://github.com/nvie/gitflow' with working directory 'C:\Program Files (x86)\GitExtensions'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at GitExtensions.Plugins.GitFlow.GitFlowForm.lnkGitFlow_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Hi,
I've tried to open link About GitFolw from dialog of GitFlow plugin.

### Steps to reproduce

* Open the app
* Select a repository
* Open menu Plugins -> GitFlow
* Click About GitFlow link

**Comment by mstv** [comment]
Similar to #10429. But the URL seems to be correct. Is your default browser able to open the URL?

**Comment by pmiossec** [comment]
> Similar to #10429. But the URL seems to be correct. Is your default browser able to open the URL?

I think that's because the way we launch it is no more compatible with the .net core way to open links
 https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitFlow/GitFlowForm.cs#L396

https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/
