### ISSUE TITLE
[NBug] The host key is not cached for this server:  gerrit.ext.n...

### ISSUE THREAD

**Issue by BBzzz** [gitextensions/gitextensions#10729]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T -P 29418 "bborbely@gerrit.ext.net.nokia.com:CSF-CLCM""

```
GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  gerrit.ext.net.nokia.com (port 29418)
You have no guarantee that the server is the computer
you think it is.
The server's rsa2 key fingerprint is:
  ssh-rsa 1024 SHA256:JL7soi70bRRq805BuKRCOlfzYwyh8wH3Q/a8bVrqIfQ
If you trust this host, enter "y" to add the key to
PuTTY's cache and carry on connecting.
If you want to carry on connecting just once, without
adding the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
 ---> System.Exception: The host key is not cached for this server:
  gerrit.ext.net.nokia.com (port 29418)
You have no guarantee that the server is the computer
you think it is.
The server's rsa2 key fingerprint is:
  ssh-rsa 1024 SHA256:JL7soi70bRRq805BuKRCOlfzYwyh8wH3Q/a8bVrqIfQ
If you trust this host, enter "y" to add the key to
PuTTY's cache and carry on connecting.
If you want to carry on connecting just once, without
adding the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host)
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e)
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e)
   at GitUI.UserControls.ConsoleOutputControl.FireDataReceived(TextEventArgs args)
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output)
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

git clone not working!

### Steps to reproduce

Wanted to clone a repository and it fails with a key error

**Comment by RussKie** [comment]
Did you read the message? Did you press `^C` instead of accepting or rejecting the rsa2 key fingerprint?

**Comment by HEX-C3550** [comment]
I have the same problem, I cannot input y and press enter, I can input ctrl+c , but i cannot input y or n

**Comment by RussKie** [comment]
Run the command from command line
