### ISSUE TITLE
[NBug] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by nils-a** [gitextensions/gitextensions#10779]
### Environment

- Git Extensions 4.0.2.15932
- Build bee2ee3874e21e0c3679bb3200cd1306cb257cb5 (Dirty)
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitExtensions.Plugins.BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass11_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
```

Don't really know, actually.
I went away from the computer and when I came back this happend.
I did, however, enable auto-fetch before. Maybe it has to do something with that plugin.

### Steps to reproduce

Don't know, sorry.

**Comment by nils-a** [comment]
Closing, as duplicate of https://github.com/gitextensions/gitextensions/issues/10563
