### ISSUE TITLE
[NBug] The following paths are ignored by one of your .gitignore f...

### ISSUE THREAD

**Issue by MaxEden** [gitextensions/gitextensions#10806]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.14
- DPI 120dpi (125% scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: add -- "Assets/StreamingAssets/Audio/GeneratedSoundBanks/Windows/SoundbanksInfo.xml"
Working directory: C:\GitWork\demolition-vr\

```
GitExtUtils.ExternalOperationException: The following paths are ignored by one of your .gitignore files:
Assets/StreamingAssets/Audio
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
 ---> System.Exception: The following paths are ignored by one of your .gitignore files:
Assets/StreamingAssets/Audio
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.HandleConflictSelectSide(String fileName, String side)
   at GitUI.CommandsDialogs.FormResolveConflicts.ChooseRemoteOnConflict(String fileName)
   at GitUI.CommandsDialogs.FormResolveConflicts.ContextChooseRemote_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

conflict while rebasing -i autosquash
The following paths are ignored by one of your .gitignore files:
Assets/StreamingAssets/Audio
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"

### Steps to reproduce

Resolve merge conflicts
choose local
error "The following paths are ignored by one of your .gitignore files:"
View details

**Comment by RussKie** [comment]
The error seems pretty self explanatory, that's something you should be
able to action, no?

**Comment by gerhardol** [comment]
GE is primarily an UI on top of Git. There is no way to prevent the core problem, that occur at the merge. In this case it could be possible to wrap the problem in another popup, but I do not see any advantage in that.
