### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [gitextensions/gitextensions#10816]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.15
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException:  ---> System.Exception: 

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled)
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled)
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass95_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.StartPullDialog(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.GitUICommands.Pull(IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

### Steps to reproduce

Run "Pull" from the context menu in Windows Explorer.

### Did this work in previous version of GitExtensions?

Yes.
If you tell me how to find out a version number of software that I needed to uninstall before installing the new version, I'll be happy to help you out with that version number. IMHO, it's gone. I recall it was a major number change.

### Diagnostics

Not sure if that is related: if I open the repository ("GitExt open repository") it asks me whether I want to trust the repository.

**Comment by thomasw-mitutoyo-ctl** [comment]
It **is** related to the trust relationship. It's just that the `git config --global --add safe.directory ...` command does not work when invoked from the GitExt GUI.

**Comment by RussKie** [comment]
the app is failing to show you the git security error because of the owner of the git repo you're trying to open is different.

See https://github.com/git-for-windows/git/releases/tag/v2.35.2.windows.1 and https://github.com/gitextensions/gitextensions/pull/10436.

**Comment by RussKie** [comment]
@pmiossec I think this is another instance of the same issue as in https://github.com/gitextensions/gitextensions/issues/11039 (https://github.com/gitextensions/gitextensions/issues/11039#issuecomment-1589414481).
