### ISSUE TITLE
[NBug] The host key is not cached for this server:  github.com (...

### ISSUE THREAD

**Issue by giancarlozero** [gitextensions/gitextensions#10865]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.15
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@github.com:StudioKraken/ultimobloco-renpy.git""

```
GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
 ---> System.Exception: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host)
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e)
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output)
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I can't use my SSH keys with Putty in Git Extensions. It can not save the key fingerprint in cache.

### Steps to reproduce

1 - Create public and private keys using PuttyGen on Windows 10;
2 - Save public key in GitHub account;
3 - In the "Repository > Remote repository" menu window, set the SSH repository URL;
4 - In the same window, set the private key, click "load SSH key" and save the SSH password;
5 - Click "Test Connection".

After click "Test Connection", it opens a cmd window, but nothing happens. After close the cmd, appears the error message "You have no guarantee that the server is the computer you think it is" etc.

### Did this work in previous version of GitExtensions?

I'm first-time user of Git Extensions.

**Comment by vbjay** [comment]
They updated their key.

**Comment by RussKie** [comment]
An animation would help better understand the nature of the issue. From the error message it looks like you may have not accepted the key: `Store key in cache? (y/n, Return cancels connection, i for more info) ^C`.

There have also been few updates in ssh-handling related scenarios in the upcoming v4.1, feel free to grab it from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46838436/artifacts and test.
