### ISSUE TITLE
[NBug] fatal: C:/msys64_v4/home/MarkusKohler/Projects/interface-ap...

### ISSUE THREAD

**Issue by MarkusRJK** [gitextensions/gitextensions#10862]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 120dpi (125% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies -U1000000 -- "include/SerialPort.h"
Working directory: C:\msys64_v4\home\MarkusKohler\Projects\interface-app\develop\

```
GitExtUtils.ExternalOperationException: fatal: C:/msys64_v4/home/MarkusKohler/Projects/interface-app/master/.git/worktrees/develop/index: index file open failed: Permission denied
 ---> System.Exception: fatal: C:/msys64_v4/home/MarkusKohler/Projects/interface-app/master/.git/worktrees/develop/index: index file open failed: Permission denied
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.GetCurrentChangesAsync(String fileName, String oldFileName, Boolean staged, String extraDiffArguments, Encoding encoding, Boolean noLocks)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetChangedFileTextAsync(GitModule module, GitItemStatus file)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(CancellationToken cancellationToken)
   at GitUI.SpellChecker.EditNetSpell.<InitializeAutoCompleteWordsTask>b__109_0()
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitUI.SpellChecker.EditNetSpell.UpdateOrShowAutoComplete(Boolean calledByUser)
   at GitUI.SpellChecker.EditNetSpell.AutoCompleteTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Just prepared a commit and staged files when suddenly this message popped up.

### Steps to reproduce

No idea, as it has never happened before. Middle in the preparation of a commit when staging files.

**Comment by RussKie** [comment]
Please re-read the error message. Did you have the repo opened in another
git client?

**Comment by vbjay** [comment]
This is normal. A git process had index locked at the moment. You don't have to report every git error. We did expose the git errors that occur in 4.0 version.

**Comment by pmiossec** [comment]
Could also be permissions on files broken because a tool (IDE like Visual
Studio) has been opened as administrator and has written some repository
files with admin rights.

Repo files permissions has to be fixed.
And never again open this software as administrator....

**Comment by gerhardol** [comment]
Duplicate of #10499
