### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by jmvdkolk98** [gitextensions/gitextensions#10875]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15
- DPI 144dpi (150% scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext()
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items)
   at ResourceManager.GitExtensionsFormBase.TranslateItems(ITranslation translation)
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName)
   at ResourceManager.GitExtensionsFormBase.InitializeComplete()
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands)
   at GitUI.GitUICommands.<>c__DisplayClass142_0.<StartPushDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted)
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow)
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I have just updated to the latest Microsoft Windows updates. I have rebooted my laptop. I am pushing a branch to the remote and get this error.

### Steps to reproduce

Use Windows 11 with the latest updates (update round of 4/11/2023. Push a branch to the remote.

### Did this work in previous version of GitExtensions?

It worked always. I don't think my GitExtensions was updated since the last time that this worked.

**Comment by jmvdkolk98** [comment]
After another reboot, the issue went away. I have no clue why this happened.

**Comment by pmiossec** [comment]
> After another reboot, the issue went away. I have no clue why this happened.

Windows update has updated the .net runtime and so GitExtensions failed to load some dlls because they have changed.
It's a temporary issue until reboot (or maybe restart of application).
Closing as it is not really a GitExtensions issue...
