### ISSUE TITLE
[NBug] Сбой при выполнении запрошенной операции с буфером обмена.

### ISSUE THREAD

**Issue by dmitry-kolesov** [gitextensions/gitextensions#10873]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.15
- DPI 96dpi (no scaling)

### Issue description

```
System.Runtime.InteropServices.ExternalException (0x800401D0): Сбой при выполнении запрошенной операции с буфером обмена.
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at System.Windows.Forms.Clipboard.ContainsText()
   at GitUI.SpellChecker.EditNetSpell.PasteMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

ывфа

### Steps to reproduce

copy and paste from chrome part of url field copied

**Comment by mstv** [comment]
This is rather an issue of Chrome or another tool blocking the clipboard for more than one second.

Is this reproducible? Do you notice the delay of one second? Do you use a clipboard manager or the clipboard sync of Windows?

**Comment by RussKie** [comment]
The clipboard is controlled by Windows, and it can be finicky at times. Additionally, the Windows Forms clipboard's wrapper is known to have some [non-trivial deficiencies](https://github.com/dotnet/winforms/issues/6269) that can at times exacerbate the issue. 
There's much we can do.
