### ISSUE TITLE
[NBug] Method not found: '!!0 GitUIPluginInterfaces.ISettingsSourc...

### ISSUE THREAD

**Issue by YannBrulhart** [gitextensions/gitextensions#10916]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 144dpi (150% scaling)

### Issue description

```
System.MissingMethodException: Method not found: '!!0 GitUIPluginInterfaces.ISettingsSource.GetValue(System.String, !!0, System.Func`2<System.String,!!0>)'.
   at GitExtensions.SolutionRunner.PluginSettings.get_IsTopLevelSearchedOnly()
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.OnDropDownOpening(Object sender, EventArgs e) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 40
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

Clicking on solution runner

### Steps to reproduce

CLick on Solution Runner

**Comment by RussKie** [comment]
Please raise the issue in the GitExtensions.SolutionRunner repo.
