### ISSUE TITLE
[NBug] Value must not be null.

### ISSUE THREAD

**Issue by GeneShiau** [gitextensions/gitextensions#10912]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.15
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Value must not be null.
   at Microsoft.Validates.Fail(String message)
   at Microsoft.Validates.NotNull[T](T value)
   at GitUIPluginInterfaces.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value)
   at GitUIPluginInterfaces.CredentialsSetting.SaveValue(ISettingsSource settings, String userName, String password)
   at GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   at GitUIPluginInterfaces.SettingControlBinding`2.SaveSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

On the Jira Commit Hint settings page I filled in the URL, the credential's username and API token, and left the query at default values. When I clicked the Apply button, I got this exception.

**Comment by GeneShiau** [comment]
Settings were saved in the respective repository as long as the repository was opened at the time of the change, as stated in https://github.com/gitextensions/gitextensions/issues/8396#issuecomment-856792563. This bug report is therefore withdrawn.
