### ISSUE TITLE
[NBug] error: unable to create file Customizations/Boschultes Prid...

### ISSUE THREAD

**Issue by dmurty** [gitextensions/gitextensions#10951]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "Customizations/Boschultes Pride II /HHA Visit AM.sql" "Customizations/Boschultes Pride II /HHA Visit PM.sql" "Customizations/Boschultes Pride II /HHA Visit Waiver.sql"
Working directory: C:\Repositories\documentforms\

```
GitExtUtils.ExternalOperationException: error: unable to create file Customizations/Boschultes Pride II /HHA Visit AM.sql: Invalid argument
error: unable to create file Customizations/Boschultes Pride II /HHA Visit PM.sql: Invalid argument
error: unable to create file Customizations/Boschultes Pride II /HHA Visit Waiver.sql: Invalid argument
 ---> System.Exception: error: unable to create file Customizations/Boschultes Pride II /HHA Visit AM.sql: Invalid argument
error: unable to create file Customizations/Boschultes Pride II /HHA Visit PM.sql: Invalid argument
error: unable to create file Customizations/Boschultes Pride II /HHA Visit Waiver.sql: Invalid argument
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Someone checked in a folder name that ended in a space from a MAC machine

### Steps to reproduce

have a user clone the repo on a MAC machine. Have them add a file to a new folder that ends in a space. commit and push. When pulled on a windows machine you get this error. User changed the folder name but the issue continues on the windows machine.

**Comment by mstv** [comment]
This is not a bug of Git Extensions. GE just displays the error reported by the called Git executable.
It you are able to create a folder having a trailing space on your drive, you could create an issue for Git. I doubt you will.
You could try to fixup the folder name using `git mv` manually.
