### ISSUE TITLE
[NBug] git checkout-index: lib is not in the cache

### ISSUE THREAD

**Issue by davidnyquist** [gitextensions/gitextensions#10950]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

```
GitExtUtils.ExternalOperationException: git checkout-index: lib is not in the cache ---> System.Exception: git checkout-index: lib is not in the cache

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFile(String file)
   at GitUI.GitUICommands.StartResetChangesDialog(String fileName)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

Trying to reset the file changes.

### Steps to reproduce

Trying to reset the file changes back to original

### Did this work in previous version of GitExtensions?

Don't know.  First time trying it.

**Comment by gerhardol** [comment]
A variant of https://github.com/gitextensions/gitextensions/issues/10470
stage/unstage the file to remove conflict before reset

Before 4.0, Git errors were silently ignored. Reset of files need special handling per type, not all cases were handled.
4.1 handles some common scenarios, some situations that require data structure changes for conflicted files with added/removed files are not handled still.

Will likely require a change, proably not covered by changes  in upcoming 4.1 for reset in Commit and Diff tab
renamed file changed in https://github.com/gitextensions/gitextensions/pull/10853
conflicts in the contents changed in https://github.com/gitextensions/gitextensions/issues/10423
