### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by grzegorz-marciniak-cc** [gitextensions/gitextensions#10969]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.Menus.CopyPathsToolStripMenuItem.CopyFullPathsNativeToolStripMenuItem_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\Menus\CopyPathsToolStripMenuItem.cs:line 45
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

### Steps to reproduce

- select one of the previous commits
- compare with the current branch
- select all files
- press on the keyboard CTRL + C

### Did this work in previous version of GitExtensions?

Yes

**Comment by grzegorz-marciniak-cc** [comment]
![Animation](https://github.com/gitextensions/gitextensions/assets/92423691/0c56a53f-214b-4ecc-a021-4a43501e8370)
- Before this error appears, I am pressing CTRL + C
- I have checked it at 4 repos

**Comment by RussKie** [comment]
Thank you, so the problem is observed in the diff dialog no in the main app's form.
