### ISSUE TITLE
Single test execution impossible

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10986]
### Environment

- MSVC 17.6.1
- Git Extensions 33.33.33
- Build a504b15fee0f955cec9fc327877960cc7e1d2d35
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

```
 SplitterPositionsShouldBeRestored(False)
   Source: SplitterPersistenceTests.cs line 52
   Duration: 316 ms

  Message: 
Microsoft.VisualStudio.Composition.CompositionFailedException : Expected 1 export(s) with contract name "ResourceManager.ILinkFactory" but found 0 after applying applicable constraints.

  Stack Trace: 
ExportProvider.GetExports(ImportDefinition importDefinition)
ExportProvider.GetExports(String contractName, ImportCardinality cardinality, Type type, Type metadataViewType, IMetadataViewProvider& metadataViewProvider)
ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
ExportProvider.GetExport[T,TMetadataView](String contractName)
ExportProvider.GetExport[T](String contractName)
ExportProvider.GetExport[T]()
ManagedExtensibility.GetExport[T]() line 126
CommitInfo.ctor() line 106
FormBrowse.InitializeComponent() line 70
FormBrowse.ctor(GitUICommands commands, BrowseArguments args) line 254
GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args) line 1155
SplitterPersistenceTests.<RunFormTest>b__8_0() line 107
UITest.RunForm[T](Action showForm, Func`2 runTestAsync, Boolean debug) line 83
SplitterPersistenceTests.RunFormTest(Func`2 testDriverAsync) line 106
SplitterPersistenceTests.RunFormTest(Action`1 testDriver) line 96
SplitterPersistenceTests.SplitterPositionsShouldBeRestored(Boolean leftPanelVisible) line 63

```

### Steps to reproduce

try to run just the ` SplitterPositionsShouldBeRestored` tests

**Comment by mstv** [comment]
Fixed by 6bba73353fbfe436eb75b13edcac007c95430bf9
But the test result on AV is different from the local execution.

---

I get project loading errors occasionally:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/41d1a898-d6dd-4abd-abb7-062e3671c786)

```
=====================
23.05.2023 01:10:22
LimitedFunctionality
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AdoptDepedentItemsAfterAddingNewItems(IProjectTree folder, IImmutableDictionary`2 projectData, ImmutableDictionary`2 newItemsInFolder)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, ConfiguredProjectExports originConfiguredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
===================
```

---

Why does "Run all tests" not run the `GitUI.Tests`?!?

---

Popup from "Run all tests" (after it finally had detected all tests):

```
************** Exception Text **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RevisionDataGridView'.
   at void System.Windows.Forms.Control.CreateHandle()
   at void System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(int value)
   at void GitUI.UserControls.RevisionGrid.RevisionDataGridView.EnsureRowVisible(int row) in D:/Build/gitextensions3_dev/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs:line 388
   at async void GitUI.UserControls.RevisionGrid.RevisionDataGridView.LoadingCompleted()+(?) => { } in D:/Build/gitextensions3_dev/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs:line 472
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in D:/Build/gitextensions3_dev/GitExtUtils/GitUI/TaskManager.cs:line 29
```

---

Test discovery failed:

"Unexpected (what else!) error detected. Check the Tests Output Pane for details."

![image](https://github.com/gitextensions/gitextensions/assets/36601201/6a590988-3390-42ce-8c17-8beb0dc489b1)

```
Log level is set to Informational (Default).
Multiple source code repositories are available, using D:\Build\gitextensions3_dev as the repository root.
Connected to test environment '< Local Windows Environment >'
Test data store opened in 1,921 sec.
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
========== Test discovery aborted: 0 Tests found in 373 ms ==========
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
========== Test discovery aborted: 0 Tests found in 7,3 ms ==========
Test project CommonTestUtils does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
Test project CommonTestUtils does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
```

---

The build and test execution such ... unstable. Sad!

**Comment by RussKie** [comment]
> I get project loading errors occasionally:

What VS version are you using? In situations like this it'd be great if you could log an issue via VS Feedback. `Microsoft.VisualStudio.ProjectSystem.*` stuff is kind of @drewnoakes's realm ;)




> Test discovery failed:
> 
> "Unexpected (what else!) error detected. Check the Tests Output Pane for details."

FWIW, I too get these entries in the output window, but the tests get discovered and executed nonetheless...

**Comment by drewnoakes** [comment]
+1 for a feedback ticket. Please attach a recording of the project failing to load as well, so that it's easier to diagnose. If you link it here I can make sure it's routed to the correct team.

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.AdoptDepedentItemsAfterAddingNewItems(IProjectTree folder, IImmutableDictionary`2 projectData, ImmutableDictionary`2 newItemsInFolder)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.HandleAddedItems(IProjectTree tree, IImmutableDictionary`2 projectData, IProjectChangeDescription change, IEnumerable`1 addedItems, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.OnProjectSubscriptionChanged(IProjectTree originalTree, ConfiguredProjectExports configuredProjectExports, ConfiguredProjectExports originConfiguredProjectExports, PhysicalProjectTreeInputData updateInput, CancellationToken cancellationToken)
```

This is CPS, which is an internal component. Possibly a project item has an invalid path in its `DependentUpon` metadata, which is causing that exception. That's juts a guess.

**Comment by mstv** [comment]
https://developercommunity.visualstudio.com/t/Test-discovery-fails-with-MicrosoftVis/10372682?port=1025&fsid=708954cf-6ea4-4ac6-8735-dbf396aaba02&ref=native&refTime=1684952393560&refUserId=2a9334e3-6c08-64a6-9b8f-60d221b1cbab

---

https://developercommunity.visualstudio.com/t/Provide-the-path-that-caused-the-excepti/10253001?port=1025&fsid=708954cf-6ea4-4ac6-8735-dbf396aaba02&ref=native&refTime=1684952393565&refUserId=2a9334e3-6c08-64a6-9b8f-60d221b1cbab

> This is CPS, which is an internal component. Possibly a project item has an invalid path in its `DependentUpon` metadata, which is causing that exception. That's just a guess.

I guess it might be a race condition, because it works when pressing the "Reload failted project(s)" button.

**Comment by vbjay** [comment]
May be related. 

https://developercommunity.visualstudio.com/t/Provide-the-path-that-caused-the-excepti/10253001?scope=follow

**Comment by drewnoakes** [comment]
Thank you for filing those.

There's no recording of the failure attached to those tickets, which will make it harder to investigate them. It's possible to add such a recording after the fact.

I've routed them both to the relevant teams.

**Comment by drewnoakes** [comment]
I suspect this is the root of the problem: https://github.com/gitextensions/gitextensions/blob/a504b15fee0f955cec9fc327877960cc7e1d2d35/UnitTests/GitCommands.Tests/GitCommands.Tests.csproj#L59-L65

**Comment by drewnoakes** [comment]
Also this line in the above output looks relevant. Maybe a package reference is missing:

```
========== Test discovery aborted: 0 Tests found in 7,3 ms ==========
Test project CommonTestUtils does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
```

**Comment by mstv** [comment]
> Maybe a package reference is missing: 
>
> Test project CommonTestUtils does not reference any .NET NuGet adapter.

Thank you for pointing this out, @drewnoakes. Anyway, deprecated features (refer to https://learn.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.8#testadapterextension) should either work or not. This should not randomly depend on how many concurrent threads are executed by the CPU.

Though `UnitTests\CommonTestUtils\CommonTestUtils.csproj` contains:
```
  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
    <PackageReference Include="NUnit" />
  </ItemGroup>
```
So the error message seems to be wrong at first glance. What is missing?

Using `packages.config` files as in b91c48f137f1681b0264962e9b218e78ee6ba334 raises lots of errors like "The project dependency ... contains no lower limit." for all the dependencies in the project files.
1. Should we add the dependencies to the project files instead (of to `packages.config`)?
2. How should we make `<DependentUpon>` reliably work for approval tests, @RussKie? (first introduced in `UnitTests\BugReporter.Tests\BugReporter.Tests.csproj`)

**Comment by drewnoakes** [comment]
> This should not randomly depend on how many concurrent threads are executed by the CPU.

Totally agree. I don't have any insight there and will leave it to the unit testing team.

> So the error message seems to be wrong at first glance. What is missing?

The `NUnit` package is not a test runner. I believe you also need the [`NUnit.Console`](https://www.nuget.org/packages/NUnit.Console) package.

> Using packages.config files as in https://github.com/gitextensions/gitextensions/commit/b91c48f137f1681b0264962e9b218e78ee6ba334 raises lots of errors like "The project dependency ... contains no lower limit." for all the dependencies in the project files.

`package.config` is an ancient way of specifying NuGet packages. For this solution, use `PackageReference` items in the project directly, such as:

```xml
<ItemGroup>
  <PackageReference Include="NUnit" Version="..." />
  <PackageReference Include="NUnit.Console" Version="..." />
```

> How should we make `<DependentUpon>` reliably work for approval tests

If you remove the explicit `DependentUpon` metadata you can configure the "dynamic file nesting" feature of VS to apply the sort of nesting that the MSBuild expression is trying to achieve.

https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022

**Comment by drewnoakes** [comment]
FWIW it may be possible to add those packages to all unit test projects in one place via a `Directory.Build.props` file, by including a `Condition` that filters to only the test projects (perhaps matching that the project name ends with "Test").

**Comment by RussKie** [comment]
> `package.config` is an ancient way of specifying NuGet packages

We're not using package.config, and use `PackageReference` instead. We define package versions in [Packages.props](https://github.com/gitextensions/gitextensions/blob/master/Packages.props) in a similar fashion to the [Central Package Management](https://learn.microsoft.com/nuget/consume-packages/Central-Package-Management), though our implementation predates the CPM.

**Comment by RussKie** [comment]
Our test-related packages are defined here:
https://github.com/gitextensions/gitextensions/blob/a504b15fee0f955cec9fc327877960cc7e1d2d35/Packages.props#L39-L50

**Comment by RussKie** [comment]
> I suspect this is the root of the problem:
> 
> https://github.com/gitextensions/gitextensions/blob/a504b15fee0f955cec9fc327877960cc7e1d2d35/UnitTests/GitCommands.Tests/GitCommands.Tests.csproj#L59-L65

What makes you think so? These are part of the `ApprovalTests` infra to create dependencies in the VS's Solution Explorer.

Related, though not terribly important, we should migrate off ApprovalTests (which are kind of unsupported) and to [VerifyTests](https://github.com/VerifyTests/Verify) (which are actively developed and supported). Essentially, the same thing, just newer.
