### ISSUE TITLE
[NBug] The following paths are ignored by one of your .gitignore f...

### ISSUE THREAD

**Issue by kusur** [gitextensions/gitextensions#11000]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: add -- "public/images/svg/dynamic/view_raw_2.svg"
Working directory: C:\xampp\htdocs\fkc-nectar\

```
GitExtUtils.ExternalOperationException: The following paths are ignored by one of your .gitignore files:
public/images
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
 ---> System.Exception: The following paths are ignored by one of your .gitignore files:
public/images
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 146
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 42
   at GitCommands.GitModule.HandleConflictSelectSide(String fileName, String side) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 556
   at GitUI.CommandsDialogs.FormResolveConflicts.ChooseBaseOnConflict(String fileName) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 850
   at GitUI.CommandsDialogs.FormResolveConflicts.<>c__DisplayClass122_0.<CheckForLocalRevision>b__0(ConflictResolutionPreference solveMergeConflictDialogResult) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1105
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenSolveMergeConflictDialogAndExecuteSelectedMergeAction(Action`1 selectedMergeAction, String dialogText, String dialogInstructionText, String dialogCaption, String dialogFooterCheckboxText, String keepLocalButtonText, String keepRemoteButtonText, String keepBaseButtonText) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 973
   at GitUI.CommandsDialogs.FormResolveConflicts.CheckForLocalRevision(ConflictData item) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1086
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 510
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1234
   at GitUI.CommandsDialogs.FormResolveConflicts.merge_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1494
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Files from path added to .gitignore are not ignored

### Steps to reproduce

Changed files in .gitignore path. 
Started interactive rebase.
Picked all commits.
Got conflicts.
Picked local changes

**Comment by RussKie** [comment]
Please read the message which comes from git and act accordingly.
