### ISSUE TITLE
[NBug] fatal: .git/index: index file open failed: Permission denied

### ISSUE THREAD

**Issue by niikoo** [gitextensions/gitextensions#11029]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 -- "Faktum.Ics.Server.Sources.Dynamics365/ODataClient/D365CustomODataClientBase.cs"
Working directory: C:\Dev\iizy\InvoiceCollectionSystem\

```
GitExtUtils.ExternalOperationException: fatal: .git/index: index file open failed: Permission denied
 ---> System.Exception: fatal: .git/index: index file open failed: Permission denied
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 128
   at GitCommands.GitModule.GetCurrentChangesAsync(String fileName, String oldFileName, Boolean staged, String extraDiffArguments, Encoding encoding, Boolean noLocks) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2817
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetChangedFileTextAsync(GitModule module, GitItemStatus file) in C:\projects\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 161
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(CancellationToken cancellationToken) in C:\projects\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 57
   at GitUI.SpellChecker.EditNetSpell.<InitializeAutoCompleteWordsTask>b__109_0() in C:\projects\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 888
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitUI.SpellChecker.EditNetSpell.UpdateOrShowAutoComplete(Boolean calledByUser)
   at GitUI.SpellChecker.EditNetSpell.AutoCompleteTimer_Tick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 1076
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tried to stage some files in the commit window.

### Steps to reproduce

I could not reproduce it. It sometimes happens when I open the commit window and try to stage some files.
Impossible to ignore the error, it happened again and again and I had to force close the app.

### Did this work in previous version of GitExtensions?

I think I have seen this in previous versions.

**Comment by gerhardol** [comment]
Duplicate #10499 

Check what other Git clients that run, something else is locking the index. If the popup occurs repeatedly, the index could also be inaccessible for the user.

You can also deactivate auto completion.
The contents in Git Command Log could explain what occurs in more detail.

![image](https://github.com/gitextensions/gitextensions/assets/6248932/2e02737e-fad2-4719-a954-7242dfe5e2ab)

GE itself should not lock the index in background operations (by using `--no-optional-locks` for background access).
It is required in interactive commands and is used in some situations due to performance (next invocation will be faster).
This command could be run without locks, but with other Git clients you may see similar popups (but likely not repeatedly).
