### ISSUE TITLE
[NBug] Could not load type 'ICSharpCode.TextEditor.Document.EolMar...

### ISSUE THREAD

**Issue by AlexLekar** [gitextensions/gitextensions#11023]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)

### Issue description

```
System.TypeLoadException: Could not load type 'ICSharpCode.TextEditor.Document.EolMarkerStyle' from assembly 'ICSharpCode.TextEditor, Version=4.0.2.6466, Culture=neutral, PublicKeyToken=null'.
   at GitUI.Editor.FileViewer.InitializeComponent()
   at GitUI.Editor.FileViewer..ctor() in C:\projects\gitextensions\GitUI\Editor\FileViewer.cs:line 91
   at GitUI.CommandsDialogs.RevisionFileTreeControl.InitializeComponent() in C:\projects\gitextensions\GitUI\CommandsDialogs\RevisionFileTreeControl.Designer.cs:line 51
   at GitUI.CommandsDialogs.RevisionFileTreeControl..ctor() in C:\projects\gitextensions\GitUI\CommandsDialogs\RevisionFileTreeControl.cs:line 57
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.Designer.cs:line 72
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, BrowseArguments args) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 254
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1155
   at GitExtensions.Program.RunApplication() in C:\projects\gitextensions\GitExtensions\Program.cs:line 195
   at GitExtensions.Program.Main() in C:\projects\gitextensions\GitExtensions\Program.cs:line 105
```

Cannot start Git Extentions GUI (probably not all params were set in General Settings)

### Steps to reproduce

1) Install Git
2) Setup params in General Settings (not all)
setup WinMegre as diff and merge, but one of params should be red
3) Close General settings and close Git Extentions
4) Start Git Extentions for the first time

**Comment by RussKie** [comment]
> System.TypeLoadException: Could not load type 'ICSharpCode.TextEditor.Document.EolMarkerStyle' from assembly 'ICSharpCode.TextEditor, Version=4.0.2.6466, Culture=neutral, PublicKeyToken=null'.

I checked the assembly which is shipped in v4.1, and the type is there. Try repairing the installation maybe?

**Comment by AlexLekar** [comment]
Repairing the installation solved the issue

**Comment by RussKie** [comment]
Great to hear
