### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Net.Mail, Version=6...

### ISSUE THREAD

**Issue by ordnko** [gitextensions/gitextensions#11047]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 90
   at GitUI.PatchGrid.Initialize() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 119
   at GitUI.PatchGrid.OnRuntimeLoad() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 71
   at ResourceManager.GitExtensionsControl.OnLoad(EventArgs e) in C:\projects\gitextensions\ResourceManager\GitExtensionsControl.cs:line 38
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

The error occurred when I tried to rebase one branch on another in interactive mode. If I choose `Ignore` on error dialog window displayed, rebase dialog appears but I cannot choose target branch of rebase there (branch dropdown list is empty).

### Steps to reproduce

Try to rebase one branch onto another by clicking right mouse button on a target branch in main window and then choosing `Rebase current branch on->Selected commit interactively...` from context menu. Error dialog saying that some .NET assembly is missing appears.

### Did this work in previous version of GitExtensions?

Yes, it worked. I don't remember what the version was, though.

**Comment by ordnko** [comment]
After application restart, the rebase operation succeeded.

**Comment by pmiossec** [comment]
> After application restart, the rebase operation succeeded.

This type of issue is due to windows update most of the times.
Closing as we are aware of it and there is no easy workaround for that...
