### ISSUE TITLE
[NBug] fatal: 'BI-3373_Für_Kachel_\Anstehende_Zahlungen\_sollen_di...

### ISSUE THREAD

**Issue by tih2010** [gitextensions/gitextensions#11061]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.18
- DPI 144dpi (150% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: check-ref-format --branch "BI-3373_Für_Kachel_\\"Anstehende_Zahlungen\\"_sollen_die_Logik_leicht_verändert_werden"
Working directory: D:\Rhein-Spree\Code\BFS\BfsSoftware\

```
GitExtUtils.ExternalOperationException: fatal: 'BI-3373_Für_Kachel_\Anstehende_Zahlungen\_sollen_die_Logik_leicht_verändert_werden' is not a valid branch name
 ---> System.Exception: fatal: 'BI-3373_Für_Kachel_\Anstehende_Zahlungen\_sollen_die_Logik_leicht_verändert_werden' is not a valid branch name
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 229
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 168
   at GitCommands.GitModule.CheckBranchFormat(String branchName) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 3867
   at GitUI.CommandsDialogs.FormCreateBranch.OkClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCreateBranch.cs:line 121
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I was tried to create a new Branch named

BI-3373 Für Kachel "Anstehende Zahlungen" sollen die Logik leicht verändert werden

Seems the replacement for the funny German letter doesn't work here.

### Steps to reproduce

Try to create a new Branch named:

Für Kachel "Anstehende Zahlungen" sollen die Logik leicht verändert werden]

Seems there is a problem with der German letters ü or ä or with the " or with a combination of those. Shouldn't be too much of a problem though.

**Comment by RussKie** [comment]
A branch name can only contain legal symbols, i.e., those permitted by the operating system. `'` and `"` aren't legal.

The app has the option to sanitise branch names, is it on?
![image](https://github.com/gitextensions/gitextensions/assets/4403806/009bc5f8-5175-4ef1-8769-7809ccedf228)

**Comment by 0x000N3X4N** [comment]
@RussKie 
Faced with the same issue after update to 4.2.1 version.
Looks like problem **with double quotes** in branch name. 
Before update In 4.2 version double quotes automatically normalized on Create branch.
![image](https://github.com/gitextensions/gitextensions/assets/38838465/d8e13434-4977-49b9-ac6b-d5124bad1acf)
![image](https://github.com/gitextensions/gitextensions/assets/38838465/a6574625-371d-4852-83fa-04a4c9628e13)

**Comment by RussKie** [comment]
Thank you for more context.

> Before update In 4.2 version double quotes automatically normalized on Create branch.

I find it peculiar because the [normaliser](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitBranchNameNormaliser.cs) hasn't changed in years. And I don't think it ever changed `'` or `"`.

In either case, don't use `'` or `"` in file or folder names. :)
If you are particularly affected by the bug - please feel free to send a fix in.

**Comment by SAPHemlock** [comment]
This one is already fixed, and the culprit is not the encoding.

### The crash

`FormCreateBranch.OkClick` calls `Module.CheckBranchFormat` *before* its own `try`/`catch`, and that method used to end in `_gitExecutable.RunCommand(args)`, which defaults to `throwOnErrorExit: true`. So any branch name `git check-ref-format` rejected threw an unhandled `ExternalOperationException` straight into NBug, instead of the "… is not valid branch name." message box.

`dc0bf19a4` ("fix: RunCommand() should not throw when exit is checked", #11871, merged 2024-09-04) rewrote it:

```csharp
GitArgumentBuilder args = new("check-ref-format") { "--branch", branchName.QuoteNE() };
return GitExecutable.Execute(args, throwOnErrorExit: false).ExitedSuccessfully;
```

It cannot throw now — a rejected name returns `false` and you get the message box. That PR even names "checking the characters in a branch name" as a motivating case. So this report cannot reproduce on current master.

### Why git rejected that name, since the reason is not obvious

The umlauts were never the problem. Checked against git 2.55.0.windows.5:

```
git check-ref-format --branch 'foo"bar'   -> exit 0    (a quote is legal to git)
git check-ref-format --branch 'foo\bar'   -> exit 128  fatal: 'foo\bar' is not a valid branch name
```

Look at the name in the report — `…Kachel_\Anstehende_Zahlungen\_sollen…` — the quotes the user typed are *gone* and lone backslashes stand where they were. That is the fingerprint of the old code escaping the same quote twice: `branchName.Replace("\"", "\\\"")` and then `.QuoteNE()`, which escapes it again. The result goes into `ProcessStartInfo.Arguments` as a raw string, and under the usual Win32 argv rules an even number of backslashes before a quote makes that quote a mode toggle rather than a character — so `\\"` reaches git as one literal backslash and no quote. The backslash is what `check-ref-format` correctly refused. `dc0bf19a4` removed the double escaping too.

### One thing that is still open, and I have sent a PR for it

While confirming the above I found that `PathUtil.IsValidPathChar` — which decides what "automatically normalise branch name" replaces — has silently stopped filtering `"`, `<` and `>`. It defers to `Path.GetInvalidPathChars()`, which returned those under .NET Framework, where the code was written in `687c98ebe`, but not since .NET Core. Measured on the runtime this targets:

```
.NET 10.0.12
GetInvalidPathChars     (printable): '|'
GetInvalidFileNameChars (printable): '"' '<' '>' '|' ':' '*' '?' '\' '/'
```

@RussKie, that matches what you wrote here about `'` and `"` not being legal — the intent is still in the code, the framework moved underneath it. It matters because a ref is a file under `.git/refs/`, and Windows will not name a file `"`, `<` or `>`.

That is #13324, with tests that fail on master. It is a separate defect from this report, so I would suggest closing this one as fixed by `dc0bf19a4` rather than keeping it open for that.

*Analysed with [Claude Code](https://claude.com/claude-code).*
