### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#11064]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.GetRemoteNames()
   at GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Cloning repository results this error.

### Steps to reproduce

1) Start Git Extensions v4.0.0
2) Click Cloning repository
3) Results error

**Comment by RussKie** [comment]
I _think_ the app is failing due to a git security error - e.g., because of the owner of the git repo you're trying to open is different. 
See https://github.com/git-for-windows/git/releases/tag/v2.35.2.windows.1 and https://github.com/gitextensions/gitextensions/pull/10436.

Are you able to attach a debugger and see what's going on?

**Comment by klorinczi** [comment]
Unfortunately I didn't use debugger, yet.

If I get steps, what to do, I will do it for you.

**Comment by pmiossec** [comment]
> I _think_ the app is failing due to a git security error - e.g., because of the owner of the git repo you're trying to open is different. See https://github.com/git-for-windows/git/releases/tag/v2.35.2.windows.1 and #10436.

If I can't exclude the probability (for example if it is cloned in an existing folder where he is not the owner), I think that it is not the security issue the reason here because when you clone, it creates a new folder where you are the owner. So you should not have this problem of ownership. It's how see it but I might be wrong...

@klorinczi Did you try to clone in an existing empty directory (created before)?

**Comment by klorinczi** [comment]
> @klorinczi Did you try to clone in an existing empty directory (created before)? 

@pmiossec: No, I just entered the target directory name into Git Extensions. Directory was NOT created by me.

**Comment by pmiossec** [comment]
@klorinczi Thanks for the information. So from what I understand it seems to be a new kind of problem.
To be really sure, it will be really appreciated if you could test the portable version available [here](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/47345568/artifacts) to see if you have a different behavior.

If not, as @RussKie asked, you will have to investigate more on your side because it seems to be a new issue and maybe specific to your environment...
