### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by SebiCiuca** [gitextensions/gitextensions#11066]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext() in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 82
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items) in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 206
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromFields(String category, Object obj, ITranslation translation) in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 322
   at ResourceManager.TranslationUtils.TranslateItemsFromFields(String category, Object obj, ITranslation translation) in C:\projects\gitextensions\ResourceManager\TranslationUtils.cs:line 42
   at ResourceManager.GitExtensionsFormBase.TranslateItems(ITranslation translation) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 142
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName) in C:\projects\gitextensions\ResourceManager\Translator.cs:line 89
   at ResourceManager.GitExtensionsControlInitialiser.InitializeComplete() in C:\projects\gitextensions\ResourceManager\GitExtensionsControlInitialiser.cs:line 73
   at ResourceManager.GitExtensionsFormBase.InitializeComplete() in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 118
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 111
   at GitUI.GitUICommands.<>c__DisplayClass143_0.<StartPushDialog>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1212
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 318
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1230
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1239
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1288
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1558
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\ToolStripEx.cs:line 97
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I tried to commit a code and got this error.
Nothing special was done before.

### Steps to reproduce

 - Open GITExtension
 - Open a repository
 - Change some files ( no files added/deleted, just changed)
 - Open Commit form 
 - Don't stage any file 
 - Add commit message 
 - Click on "Commit & Push"

### Did this work in previous version of GitExtensions?

This work in current version also, feels like a transient error.

**Comment by pmiossec** [comment]
> This work in current version also, feels like a transient error.

Yes, windows update issue most of the time.  We are aware of that so closing...
