### ISSUE TITLE
[NBug] Cannot access a disposed object.Object name: 'FormBrowse'.

### ISSUE THREAD

**Issue by Oberon00** [gitextensions/gitextensions#11063]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.18
- DPI 96dpi (no scaling)

### Issue description

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FormBrowse'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ContainerControl.FocusActiveControlInternal()
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1163
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1606
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1460
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1433
   at GitExtensions.Program.RunApplication() in C:\projects\gitextensions\GitExtensions\Program.cs:line 204
   at GitExtensions.Program.Main() in C:\projects\gitextensions\GitExtensions\Program.cs:line 105
```

Closed window right after starting.

### Steps to reproduce

Start gitextensions inside a folder with a git repository. Close it right away, while the UI still seems to be loading by middle clicking (press mouse wheel) on the window preview from the Windows taskbar. Seems to be 100% reliably reproducible for me that way.

Note that this does not seem to work by clicking the X button, as there is seems to block that until the UI is fully loaded.

### Did this work in previous version of GitExtensions?

I never observed this with earlier versions, but I might also not have run into the case.

**Comment by Oberon00** [comment]
Might indeed be the same as #8272 (closed), but here you have steps to reproduce 😃

#6901 looks different at first glance.

**Comment by RussKie** [comment]
Thank you for providing the repro steps. I can't seem able to replicate but I may not be fast enough... For me the preview on the taskbar becomes available after the app has already loaded.
As a workaround - don't try to close it that fast :) A PR with a fix is welcome too.

**Comment by Oberon00** [comment]
I had a second instance open before launching the one I closed (that was the reason I closed it actually). Maybe that makes the taskbar hover preview appear sooner. OS is Windows 11.

Yeah "don't try to close it that fast" is a good workaround. 🙂

(The root cause would be solved by a feature request: If starting gitex and the repo is already opened in another instance, focus that instance instead of starting a new one)

**Comment by SAPHemlock** [comment]
Still reproducible at HEAD in principle — the code path is unchanged. @RussKie, I think this explains why you couldn't reproduce it, and why @Oberon00 could.

### The crash window is exactly as long as `FormBrowse.OnLoad` takes

`Form.SetVisibleCore(true)` creates the handle, raises `OnLoad`, and only *then* calls `FocusActiveControlInternal()`. All three frames are in the reported stack, in that order.

`FormBrowse.OnLoad` does a great deal of work between those two points — `CreateToolbarsMenus`, `RefreshSplitViewLayout`, `LayoutRevisionInfo` (which itself forces handle creation: `_ = CommitInfoTabControl.Handle;`), `SetSplitterPositions`, and the repository load below that. Anything in there that pumps messages — and this codebase runs git synchronously through `JoinableTaskFactory.Run` in plenty of places — lets a `WM_CLOSE` be processed. The form is disposed, `SetVisibleCore` then continues to `FocusActiveControlInternal()`, touches `.Handle`, and WinForms tries to *recreate* the window of a disposed form. Hence `ObjectDisposedException` from `CreateHandle` rather than a null reference.

So this isn't really "closed it too fast" — it's "closed it during the load", and the window is however long the load takes. That fits both reports:

- @Oberon00 had **a second instance already open**, so the taskbar button and its live preview existed immediately, making the close gesture available from the first moment of the load.
- On your machine the preview only appeared once loading had finished, i.e. after the vulnerable window had already closed.

### Mechanism, and what it is *not*

Worth recording, because two plausible-looking explanations don't apply:

- **Not the Rx/`InvalidOperationException` family** guarded by `5bda3c908` and `9380ae11f`. Different exception type, different site, different trigger — no Rx subscription and no `Invoke` anywhere on this path.
- **Not the async-continuation-after-dispose family** either. There is no thread hop here at all: the whole stack from `Application.Run` down is one synchronous, reentrant call chain. `SwitchToMainThreadAsync(CancellationToken)`, which ties a resumption to the control's `Disposed` event, has nothing to attach to.

### What I'd suggest, and what I'd avoid

**Avoid** wrapping `Application.Run(form)` in a `catch (ObjectDisposedException)`. That was my first instinct and it's wrong: `Application.Run` doesn't return until the form closes, so the catch would swallow that exception for the entire lifetime of the message loop, not just the startup race.

A tighter candidate, scoped to exactly the frame in the stack:

```csharp
protected override void SetVisibleCore(bool value)
{
    try
    {
        base.SetVisibleCore(value);
    }
    catch (ObjectDisposedException) when (IsDisposed)
    {
        // The window can be closed while it is shown for the first time, because loading the
        // repository pumps messages. WinForms then focuses the active control of the form it
        // has just disposed.
    }
}
```

One form, one call, and only when the form really is disposed — so it can't mask an unrelated failure.

I'd rather ask than push it, for two reasons. It suppresses a symptom rather than shortening the window, and the better-but-larger answer is to stop doing message-pumping work inside `OnLoad` — which is its own project and overlaps what @mstv is doing in #11205. Say the word and I'll send the narrow version; if you'd prefer it left alone as a rare timing window with a known workaround, that's a fair call too.

One thing I could not verify: I have no way to reproduce the taskbar-preview gesture here, so the "messages get pumped during `OnLoad`" step is read from the code rather than observed. If anyone with a repro can confirm the form is already disposed by the time `FocusActiveControlInternal` runs, that nails it.

*Analysed with [Claude Code](https://claude.com/claude-code).*

**Comment by RussKie** [comment]
> A tighter candidate, scoped to exactly the frame in the stack:
> 
> protected override void SetVisibleCore(bool value)
> {
>     try
>     {
>         base.SetVisibleCore(value);
>     }
>     catch (ObjectDisposedException) when (IsDisposed)
>     {
>         // The window can be closed while it is shown for the first time, because loading the
>         // repository pumps messages. WinForms then focuses the active control of the form it
>         // has just disposed.
>     }
> }
> One form, one call, and only when the form really is disposed — so it can't mask an unrelated failure.

this looks good

**Comment by mstv** [comment]
Rather let's finish #11205.
