### ISSUE TITLE
[NBug] Failed to set Win32 parent window of the Control.

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [gitextensions/gitextensions#11075]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.36.0.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.18
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.ComponentModel.Win32Exception (5023): Failed to set Win32 parent window of the Control.
   at System.Windows.Forms.Control.SetParentHandle(IntPtr value)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at GitUI.CommandsDialogs.FormBrowse.HideDashboard() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 731
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1673
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\Dashboard.cs:line 187
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.OnModuleChanged(GitModuleEventArgs args) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 366
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.TryOpenRepository(Repository repository) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 944
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 646
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\NativeListView.cs:line 93
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

1. I've opened ConEemu tool (from GitExtensions directory)
2. I've opened new GitExtensions window
3. I've attached GitExtensions window to ConEmu: Using "Attach to.." option from the popup menu
4. After initial attachment I've tried to open some repository within git extensions and then I saw the exception
![image](https://github.com/gitextensions/gitextensions/assets/34109031/7eba5c76-4dd8-45e6-b1d2-d76d3aacadb9)

![image](https://github.com/gitextensions/gitextensions/assets/34109031/66467aa1-a628-4827-8593-33c5db738d1b)

**Comment by pmiossec** [comment]
Can you explain what you try to achieve?
Do you know what the "Attach to" feature of ConEmu is doing?
I don't get what you try to achieve.
"Attach to..." is for attaching a console instance and GitExtensions is not a console application.
