### ISSUE TITLE
[NBug] 

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [gitextensions/gitextensions#11086]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.19
- DPI 96dpi (no scaling)

### Issue description

GitExtensions crash

```
GitExtUtils.ExternalOperationException:  ---> System.Exception: 

   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 323
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 259
   at GitCommands.GitModule.GetRemoteNames() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2220
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0() in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 409
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 416
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 206
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPull.cs:line 222
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPull.cs:line 147
   at GitUI.GitUICommands.<>c__DisplayClass96_0.<StartPullDialogInternal>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 603
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 318
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 616
   at GitUI.GitUICommands.StartPullDialog(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 594
   at GitUI.GitUICommands.Pull(IReadOnlyDictionary`2 arguments) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1889
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1501
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1433
   at GitExtensions.Program.RunApplication() in C:\projects\gitextensions\GitExtensions\Program.cs:line 204
   at GitExtensions.Program.Main() in C:\projects\gitextensions\GitExtensions\Program.cs:line 105
```

### Steps to reproduce

Run git pull with Git Extensions from Explorer context menu.

Possibly related: the git command line reported "dubious permissions" and I recalled that Git Extensions would allow me to fix that. Well, not this time...

### Diagnostics

```
git count-objects -vH
fatal: detected dubious ownership in repository at [...]
```

**Comment by pmiossec** [comment]
> Possibly related: the git command line reported "dubious permissions" and I recalled that Git Extensions would allow me to fix that. Well, not this time...

Indeed, not this time in this current version of GitExtensions. You will have to rely on the command line to fix it.
But #11062 fixes it for next version. So closing....

**Comment by RussKie** [comment]
In some situations the git security exception won't trigger the "user
friendly " dialog. We recently fixed this issue in the dev version.
