### ISSUE TITLE
[NBug] fatal: ref HEAD is not a symbolic ref

### ISSUE THREAD

**Issue by jebisseySidel** [gitextensions/gitextensions#11087]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.18
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: symbolic-ref HEAD
Working directory: C:\Users\BisseyJE\OneDrive - Sidel\Documents\Sidel\Dev\PC.Soft.MachineDesigner\PC.Lib.ProgramBase\

```
GitExtUtils.ExternalOperationException: fatal: ref HEAD is not a symbolic ref
 ---> System.Exception: fatal: ref HEAD is not a symbolic ref
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 146
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 42
   at GitExtensions.Plugins.GitFlow.GitFlowForm.DisplayHead() in C:\projects\gitextensions\Plugins\GitFlow\GitFlowForm.cs:line 401
   at GitExtensions.Plugins.GitFlow.GitFlowForm.RunCommand(ArgumentString commandText) in C:\projects\gitextensions\Plugins\GitFlow\GitFlowForm.cs:line 331
   at GitExtensions.Plugins.GitFlow.GitFlowForm.btnInit_Click(Object sender, EventArgs e) in C:\projects\gitextensions\Plugins\GitFlow\GitFlowForm.cs:line 219
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Happends during init git flow

### Steps to reproduce

Add new sub module.
Init git flow

### Did this work in previous version of GitExtensions?

Yes, last one.

**Comment by vbjay** [comment]
Is the submodule an empty repo without any commits?

**Comment by gerhardol** [comment]
Check out a branch before init GitFlow
Before 4.1, errors were by default silently ignored.

Please test https://github.com/gitextensions/gitextensions/pull/11089 (portable)
That basically ignores if no branch is checked out.

**Comment by jebisseySidel** [comment]
@vbjay , no the submodule wasn't an empty repo.
Actually, I don't know exactly what appened. I was building a new solution. I probably did something wrong.
So, I cleared and rebluilded without any problem.

@gerhardol , normally when I add a submodule I always select de develop Branch. Perhaps I didn't it this time.

**Comment by gerhardol** [comment]
@jebisseySidel Please try the updated build for a spin regardless, to make sure it works for you in normal situations too.

**Comment by jebisseySidel** [comment]
Sorry I couldn't reproduce the problem with my current version. Like I said, I don't know exactly what I did when the crash happened. Next time I will be very attentive during each action taken to create a new application.
