### ISSUE TITLE
GE shown wrong timeline commit log

### ISSUE THREAD

**Issue by sxp200422** [gitextensions/gitextensions#11129]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

### Issue description

GE shown wrong timeline commit log as below.
![image](https://github.com/gitextensions/gitextensions/assets/12292750/eca5ac18-693d-407b-9282-ea186caa74ab)
Sourcetree  can shown the right timeline in same repo.
![image](https://github.com/gitextensions/gitextensions/assets/12292750/7aeed396-8eb7-477c-8f84-dbef1c257315)
※GE works well in other repo.

### Steps to reproduce

Nothing special. Just clone a new git repo, and open it by GE.

### Diagnostics

2023-08-07T15:46:01.5296569+08:00	50	29036	UI	1	git	config --get ą	
**2023-08-07T15:46:01.5984720+08:00	2		UI	exc	git		
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)**
2023-08-07T15:46:01.6044571+08:00	40	29068	UI	1	git		
2023-08-07T15:46:03.1980060+08:00	43	22176	UI	0	git	--version	
2023-08-07T15:46:03.2658241+08:00	55	12220		128	git	--no-optional-locks for-each-ref --format="%(objectname) %(refname)" refs/heads/	
2023-08-07T15:46:03.2678186+08:00	64	16696		128	git	--no-optional-locks for-each-ref --format="%(if)%(authordate)%(then)%(objectname) %(refname)%(else)%(*objectname) %(*refname)%(end)" refs/heads/ refs/remotes/ refs/tags/	
2023-08-07T15:46:03.2698146+08:00	72	9840		128	git	--no-optional-locks for-each-ref --format="%(if)%(authordate)%(then)%(objectname) %(refname)%(else)%(*objectname) %(*refname)%(end)" refs/tags/	
2023-08-07T15:46:03.3037222+08:00	72	3456	UI	128	git	rev-parse --git-common-dir	
2023-08-07T15:46:03.3276592+08:00	63	23548		128	git	for-each-ref --color=never --format="%(push:track,nobracket)::%(upstream:track,nobracket)::%(push)::%(upstream)::%(refname:short)" refs/heads/	
2023-08-07T15:46:03.3406237+08:00	55	25396		128	git	remote -v	
2023-08-07T15:46:03.3974741+08:00	53	23728		128	git	symbolic-ref HEAD	
2023-08-07T15:46:03.4004657+08:00	55	18060		128	git	--no-optional-locks for-each-ref --format="%(if)%(authordate)%(then)%(objectname) %(refname)%(else)%(*objectname) %(*refname)%(end)" refs/heads/ refs/remotes/ refs/tags/	
2023-08-07T15:46:03.4593052+08:00	74	25532		128	git	remote

**Comment by pmiossec** [comment]
I think that's because you display 'Author date'. Switch to 'Commit Date'
from the view menu and it should be OK...

**Comment by gerhardol** [comment]
As well as sorting:

![image](https://github.com/gitextensions/gitextensions/assets/6248932/36d1da92-fc16-4a46-ae2b-105af9f8017e)
