### ISSUE TITLE
[NBug] Entry point was not found.

### ISSUE THREAD

**Issue by Mike-E-angelo** [gitextensions/gitextensions#11133]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.3
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.EntryPointNotFoundException: Entry point was not found.
   at System.IObserver`1.OnError(Exception error)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 424
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.TailRecursiveSink`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 128
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 34
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Linq.ObservableImpl.Catch`2._.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs:line 104
   at System.Reactive.Linq.ObservableImpl.Catch`2.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Catch.cs:line 87
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 148
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 51
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Producer`2.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 97
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 37
   at GitUI.FileStatusList.SetupUnifiedDiffListSorting() in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 228
   at GitUI.FileStatusList..ctor() in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 72
   at GitUI.CommandsDialogs.FormCommit.InitializeComponent() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.Designer.cs:line 81
   at GitUI.CommandsDialogs.FormCommit..ctor(GitUICommands commands, CommitKind commitKind, GitRevision editedCommit, String commitMessage) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 224
   at GitUI.GitUICommands.<>c__DisplayClass91_0.<StartCommitDialog>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 542
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 318
   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, String commitMessage, Boolean showOnlyWhenChanges) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 563
   at GitUI.CommandsDialogs.FormBrowse.CommitToolStripMenuItemClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1283
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\ToolStripEx.cs:line 97
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I pressed the Commit button :)

### Steps to reproduce

I pressed the Commit button to start a commit and was surprised to find this exception.  Everything else has been working quite well.  Note that opening a new instance and trying again worked as expected.

### Did this work in previous version of GitExtensions?

It's been working well in this version until this instance.

**Comment by gerhardol** [comment]
Error is internal to .NET
This could be related to #10368 and similar, related to Windows and/or .NET updates and seem to be resolved by app or possible PC restarts.
Updated message in https://github.com/gitextensions/gitextensions/pull/11074

**Comment by RussKie** [comment]
Thanks for reporting this. Are you able to repro this issue consistently?

**Comment by Mike-E-angelo** [comment]
Hi @RussKie this only occurred one time and I have not seen it since. 🤔

**Comment by RussKie** [comment]
Please let us know, if it comes back.
