### ISSUE TITLE
[NBug] The host key is not cached for this server:  ssh.dev.azur...

### ISSUE THREAD

**Issue by martys** [gitextensions/gitextensions#11132]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.39.1.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@ssh.dev.azure.com:v3/chevron/ITC-ITFDTN-ChevronAtlas/Atlas-Platform""

```
GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  ssh.dev.azure.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's rsa2 key fingerprint is:
  ssh-rsa 2048 SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Connection abandoned.
 ---> System.Exception: The host key is not cached for this server:
  ssh.dev.azure.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's rsa2 key fingerprint is:
  ssh-rsa 2048 SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Connection abandoned.
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 81
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 71
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormRemoteProcess.cs:line 169
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormProcess.cs:line 217
   at GitUI.UserControls.ConsoleOutputControl.FireDataReceived(TextEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleOutputControl.cs:line 50
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 210
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 175
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

unable to setup ssh connection for my repo

### Steps to reproduce

I have an existing repo - that I've been using over https. Now I'm trying to switch to SSH. 
I've generated a public key using putty, registered it on the Azure DevOps. 
Trying to change the repo URL in the repository settings - from https to ssh. 
when saving -it suggest to register the fingerprint - and open an empty console window. after closing the console - it fails to register the servers fingerprint

**Comment by RussKie** [comment]
As a workaround you can run the command manually:
```
"C:\Program Files\PuTTY\plink.exe" -T "git@ssh.dev.azure.com:v3/chevron/ITC-ITFDTN-ChevronAtlas/Atlas-Platform"
```

**Comment by gerhardol** [comment]
Duplicate of #10826 Not GitHub but the link describes the action.
Manual action is needed, but the console should request the user to respond here.
