### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Runtime.Serializati...

### ISSUE THREAD

**Issue by xlisec** [gitextensions/gitextensions#11153]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.20
- DPI 115dpi (120% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Serialization.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitCommands.Utils.JsonSerializer.Serialize[T](T myObject)
   at GitCommands.CommitTemplateItem.SerializeCommitTemplates(CommitTemplateItem[] items) in C:\projects\gitextensions\GitCommands\CommitTemplateItem.cs:line 59
   at GitCommands.CommitTemplateItem.SaveToSettings(CommitTemplateItem[] items) in C:\projects\gitextensions\GitCommands\CommitTemplateItem.cs:line 41
   at GitUI.CommandsDialogs.CommitDialog.FormCommitTemplateSettings.SaveSettings() in C:\projects\gitextensions\GitUI\CommandsDialogs\CommitDialog\FormCommitTemplateSettings.cs:line 77
   at GitUI.CommandsDialogs.CommitDialog.FormCommitTemplateSettings.buttonOk_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\CommitDialog\FormCommitTemplateSettings.cs:line 83
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

exception. I had a templete, but now I can;t see it.

### Steps to reproduce

.

### Did this work in previous version of GitExtensions?

.

### Diagnostics

.

**Comment by RussKie** [comment]
Presumably the issue is related to the Windows update, the app should work after a restart. #11074 should help.
