### ISSUE TITLE
[NBug] Invoke or BeginInvoke cannot be called on a control until t...

### ISSUE THREAD

**Issue by mlhDevelopment** [gitextensions/gitextensions#11154]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.21
- DPI 96dpi (no scaling)

### Issue description

```
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at Microsoft.VisualStudio.Threading.JoinableTask.Post(SendOrPostCallback d, Object state, Boolean mainThreadAffinitized)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

Don't know but I did have the commit window open and from one of the staged changes I hit H to open the file's history window. That came up, then I closed it; I typed in a commit message and was about to hit commit & push (maybe I did) and this crash came up

### Steps to reproduce

I don't know exactly this occured prior:

- I had the commit window open and all changes staged,
- From one of the staged changes I hit 'H' to open the file's history window.
- That came up, I clicked around in the history then closed that window
- I typed in a commit message and hit commit & push
- The crash report window came up over the "this is a new branch for the remote" confirm box

### Did this work in previous version of GitExtensions?

Commit & Push has always worked, I've used it multiple times, but I don't know if I've followed these steps before (stage, history, commit & push)

**Comment by RussKie** [comment]
Thanks for reporting, but the stack trace isn't actionable. 
Are you able to repro the issue consistently?

**Comment by mlhDevelopment** [comment]
No, I have not seen it since. I tried explicitly to reproduce but it did not occur.
