### ISSUE TITLE
[NBug] fatal: 'Azure DevOps Git' is not a valid remote name

### ISSUE THREAD

**Issue by the-amazing-nikhil** [gitextensions/gitextensions#11285]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.23
- DPI 288dpi (300% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote add "Azure DevOps Git" "https://tegasyssolutionsuk@dev.azure.com/tegasyssolutionsuk/Candi%20Portal%20B/_git/Candi%20Portal%20B"
Working directory: E:\Work\CandiPortalB\

```
GitExtUtils.ExternalOperationException: fatal: 'Azure DevOps Git' is not a valid remote name
 ---> System.Exception: fatal: 'Azure DevOps Git' is not a valid remote name
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 128
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 42
   at GitCommands.GitModule.AddRemote(String name, String path) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2209
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.SaveRemote(ConfigFileRemote remote, String remoteName, String remoteUrl, String remotePushUrl, String remotePuttySshKey) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 293
   at GitUI.CommandsDialogs.FormRemotes.SaveClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormRemotes.cs:line 412
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Not a Valid remote name (whats a valid name?)

### Steps to reproduce

Add a new remote name & add URL. Click Save to get this error.

**Comment by mstv** [comment]
Git Extensions just presents you the **Git** error output: "fatal: 'Azure DevOps Git' is not a valid remote name".
What was so unclear in this message?
Spaces in identifiers use to cause issues in many tools.
