### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Net.Mail, Version=6...

### ISSUE THREAD

**Issue by NahomiB** [gitextensions/gitextensions#11298]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.21
- DPI 192dpi (200% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 90
   at GitUI.PatchGrid.Initialize() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 119
   at GitUI.PatchGrid.OnRuntimeLoad() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 71
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

I just made a pull - rebase on main. Then changed to another branch and tried to rebase that branch on main.

**Comment by gerhardol** [comment]
A side effect of a windows update. Restart the application.
A more user friendly handling in next version : https://github.com/gitextensions/gitextensions/pull/11074
Included in 4.2 rc1
