### ISSUE TITLE
Opening a repository created by Google's Repo tool in WSL v2 on Windows causes exception

### ISSUE THREAD

**Issue by kalibyrn** [gitextensions/gitextensions#11303]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IO.IOException: The name of the file cannot be resolved by the system. : '\\wsl$\Ubuntu\home\rduff\code\tools\tool_magnet_verify_artifact\.git'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadLines(String path)
   at System.IO.Abstractions.FileWrapper.ReadLines(String path)
   at GitCommands.Git.GitDirectoryResolver.Resolve(String repositoryPath) in C:\projects\gitextensions\GitCommands\Git\GitDirectoryResolver.cs:line 83
   at GitCommands.GitModule..ctor(String workingDir) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 71
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.OpenGitRepository(String path, ILocalRepositoryManager localRepositoryManager) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 158
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.LoadClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 88
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at GitUI.CommandsDialogs.BrowseDialog.FormOpenDirectory.folderBrowserButton_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\FormOpenDirectory.cs:line 112
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I got this exception when trying to access a WSL (v2) path. The browse button (when navigating to a repository to open) was able to take me to the correct location, but after selecting it, I got this exception. I've been able to open WSL paths before, however this repository was created using Google's repo tool, which creates a symlink of the .git directory to point to another location on disk. The link uses a relative path:  ../../.repo/projects/tools/tool_magnet_verify_artifact.git The combination of WSLv2 plus Google Repo likely caused this situation.

### Steps to reproduce

Create a WSL v2 installation, then clone a repo using Google's Repo tool within that installation. Try to open that repository using the `\\wsl$` path. It should cause this exception. The cause is likely that Google's Repo tool creates a symlink of the `.git` folder. You can likely skip the Google Repo step if you manually move the `.git` folder and create a symlink to the new location.

### Did this work in previous version of GitExtensions?

Not that I'm aware of.

**Comment by gerhardol** [comment]
File.Exists() should report false for symbolic links in WSL what I see. But File.Exists() should be true also for dirs so I do not see how the normal case works.

```c#
            if (_fileSystem.File.Exists(gitPath))
            {
                const string gitdir = "gitdir:";
                string line = _fileSystem.File.ReadLines(gitPath).FirstOrDefault(l => l.StartsWith(gitdir));
```

**Comment by RussKie** [comment]
Could [this](https://stackoverflow.com/a/74024819/2338036) help? https://learn.microsoft.com/dotnet/api/system.io.filesysteminfo.linktarget

**Comment by gerhardol** [comment]
> Could [this](https://stackoverflow.com/a/74024819/2338036) help? https://learn.microsoft.com/dotnet/api/system.io.filesysteminfo.linktarget

The handling of symbolic links in WSL for .NET is not documented, I found some hints for File.Exists() that it was not supported though.
In this case ReadLines() seem to need try-catch, some similar for the directory handling below. Then the special handling for WSL can begin...

**Comment by gerhardol** [comment]
Windows and .NET do not support symbolic links in WSL.
I submitted a PR that allows opening these repos, but there is only partial functionality in these repos. Finding and fixing all quirks could be a lot of follow ups.

It may be that GE should not support symbolic links in repos at all

**Comment by gerhardol** [comment]
Please try the updated PR.

As WSL links are not supported from Windows, there are some limitations, I listed those I could think of.
Full support of these repos will be quite hard unless the WSL implementation of the file server is updated (I doubt that will happen).
