### ISSUE TITLE
[NBug] fatal: 'FF4 bootloader ST' is not a valid remote name

### ISSUE THREAD

**Issue by repentagliaiv** [gitextensions/gitextensions#11300]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Users\Lavoro\AppData\Local\Programs\Git\bin\git.exe
Arguments: remote add "FF4 bootloader ST" "git@bitbucket.org:chronos-tech/bootloader_st.git"
Working directory: D:\ing\Firmware\Chronos\FF4\NRG-FF4.FW_Bootloader_ST\

```
GitExtUtils.ExternalOperationException: fatal: 'FF4 bootloader ST' is not a valid remote name
 ---> System.Exception: fatal: 'FF4 bootloader ST' is not a valid remote name
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 128
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 42
   at GitCommands.GitModule.AddRemote(String name, String path) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2209
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.SaveRemote(ConfigFileRemote remote, String remoteName, String remoteUrl, String remotePushUrl, String remotePuttySshKey) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 293
   at GitUI.CommandsDialogs.FormRemotes.SaveClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormRemotes.cs:line 412
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Adding a remote whose name had blank spaces

### Steps to reproduce

Adding a remote origin with blank spaces in name

### Did this work in previous version of GitExtensions?

Don't know

**Comment by gerhardol** [comment]
Git do not allow remotes with spaces, not an error in GE
All user errors are not formatted or blocked, it is eventually Git that is using the info
The error is presented slightly different in upcoming 4.2

**Comment by repentagliaiv** [comment]
Ok, thank you. Honestly the issue report opened automatically after I input
the wrong data. The only real problem was that, after the bad input, GE
crashed.
Best Regards,
Andrea

Il giorno mer 25 ott 2023 alle ore 10:59 Gerhard Olsson <
***@***.***> ha scritto:

**Comment by mstv** [comment]
> Honestly the issue report opened automatically after I input the wrong data. The only real problem was that, after the bad input, GE crashed.

Didn't you get a popup like the following before?

![image](https://github.com/gitextensions/gitextensions/assets/36601201/1dc24505-122e-4dce-9d54-aedca1ef927e)

**Comment by repentagliaiv** [comment]
Hello Michael,
I'm sorry, I really don't remember, it all happened very quickly and I
didn't pay attention. I remember that after some click the web page of
issue notification opened automatically and then I realized that GE windows
was not open anymore.

Il giorno mer 25 ott 2023 alle ore 20:58 Michael Seibt <
***@***.***> ha scritto:
