### ISSUE TITLE
[NBug] Could not load type 'GitUI.OsShellUtil' from assembly 'GitU...

### ISSUE THREAD

**Issue by John-Riley-TSI** [gitextensions/gitextensions#11319]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.TypeLoadException: Could not load type 'GitUI.OsShellUtil' from assembly 'GitUI, Version=4.1.0.16698, Culture=neutral, PublicKeyToken=null'.
   at GitExtensions.GerritPlugin.FormGitReview.lnkGitReviewPatterns_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Installed Gerrit plugin. Attempted to click on the ".gitreview file format" link from both the plugin manager and the "Edit .gitreview" main menu item. Both displayed the Error popup.

### Steps to reproduce

1. Install Gerrit Plugin
2. Plugin > Gerrit Code Review
3. From "Gerrit Plugin" popup, click on ".gitreview file format" link

### Did this work in previous version of GitExtensions?

I don't know, this was my first attempt to use Gerrit.

**Comment by mstv** [comment]
This class was moved to a different namespace `GitCommands` in #10727 (which does not match the folder structure `GitCommands/Git/OsShellUtil.cs`).
An update of the plugin using the Plugin Manager might help.

**Comment by John-Riley-TSI** [comment]
I just installed it for the first time today. I checked in the Updates tab and there are no updates available, not even preview updates.

**Comment by mstv** [comment]
Thank you for checking. I have requested an update.
