### ISSUE TITLE
[NBug] Method not found: 'GitUIPluginInterfaces.IProcess GitUIPlug...

### ISSUE THREAD

**Issue by MTimoshinin** [gitextensions/gitextensions#11354]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.24
- DPI 144dpi (150% scaling)
- Portable: False
- GitExtensions.SolutionRunner v6.0.2

### Issue description

```
System.MissingMethodException: Method not found: 'GitUIPluginInterfaces.IProcess GitUIPluginInterfaces.IExecutable.Start(GitExtUtils.ArgumentString, Boolean, Boolean, Boolean, System.Text.Encoding, Boolean, Boolean)'.
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.GetListAsync(Boolean isTopLevelSearchOnly, Boolean includeWorkspaces)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.GetListAsync(Boolean isTopLevelSearchOnly, Boolean includeWorkspaces)
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.<>c__DisplayClass4_0.<<CreateBundleItemsAsync>b__0>d.MoveNext() in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 65
--- End of stack trace from previous location ---
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.CreateBundleItemsAsync(Boolean isTopLevelSearchedOnly, Boolean includeWorkspaces, HashSet`1 solutions) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 61
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.OnDropDownOpening(Object sender, EventArgs e) in D:\Development\Maraf\GitExtensions.SolutionRunner\src\GitExtensions.SolutionRunner\UI\SolutionListMenuItem.cs:line 37
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

Updated to 4.2 from 4.1

### Steps to reproduce

Update GitEx from 4.1 to 4.2.
Open "Solution Runner" menu

### Did this work in previous version of GitExtensions?

4.1

**Comment by MTimoshinin** [comment]
Sorry, found duplicate #9417
