### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by ZackButcherDutchi** [gitextensions/gitextensions#11355]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext() in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 82
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items) in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 206
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName) in C:\projects\gitextensions\ResourceManager\Translator.cs:line 89
   at ResourceManager.GitExtensionsFormBase.InitializeComplete() in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 118
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 111
   at GitUI.GitUICommands.<>c__DisplayClass143_0.<StartPushDialog>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1212
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 318
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1230
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1239
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2060
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 52
   at GitUI.CommandsDialogs.FormBrowse.ProcessHotkey(Keys keyData) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1996
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 68
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

Trying to open push dialog (Ctl+UpArrow)

### Steps to reproduce

I created a new Bitbucket repo, default branch "develop". No commits
Cloned repo and opened. No brached checked out
Added dotnet ignore file using the dotnet cli
Commited this to the repo locally, master branch
Create new branch "develop"
Tried to open push dialog (CTL+Up) and got this message

**Comment by ZackButcherDutchi** [comment]
Duplicate. Update to 4.2 fixed this.
