### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Data.Common, Versio...

### ISSUE THREAD

**Issue by ArmorBearer** [gitextensions/gitextensions#11361]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at System.Reflection.RtFieldInfo.InitializeInvocationFlags()
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResourceManager.Xliff.TranslationUtil.GetObjFields(Object obj, String objName)+MoveNext() in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 82
   at ResourceManager.Xliff.TranslationUtil.TranslateItemsFromList(String category, ITranslation translation, IEnumerable`1 items) in C:\projects\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:line 206
   at ResourceManager.GitExtensionsFormBase.TranslateItems(ITranslation translation) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 142
   at ResourceManager.Translator.Translate(ITranslate obj, String translationName) in C:\projects\gitextensions\ResourceManager\Translator.cs:line 89
   at ResourceManager.GitExtensionsFormBase.InitializeComplete() in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 118
   at GitUI.CommandsDialogs.FormPush..ctor(GitUICommands commands) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 111
   at GitUI.GitUICommands.<>c__DisplayClass144_0.<StartPushDialog>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1187
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow, Boolean forceWithLease, Boolean& pushCompleted) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1205
   at GitUI.GitUICommands.StartPushDialog(IWin32Window owner, Boolean pushOnShow) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 1214
   at GitUI.CommandsDialogs.FormBrowse.PushToolStripMenuItemClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1297
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPushClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1561
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\ToolStripEx.cs:line 97
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Tried to push my changes.  Never had this happen before even though I've been using this app for several years...

### Steps to reproduce

I committed a minor change to one file.  Then I clicked Push.

### Did this work in previous version of GitExtensions?

Worked just fine previously in this version of GE and many prior versions.

**Comment by pmiossec** [comment]
@ArmorBearer Did you saw the (newly addedin v4.2) pop-up described in #11074  ?

I hope it is the case. If it is the case, please explain if you reproduced it after a restart and why you reported it?

**Comment by ArmorBearer** [comment]
The error message in GE said (in so many words), "Restarting the program should solve the problem. If not, please report the error."

This means that the devs don't want to know that this problem occurs unless it can't be solved by a restart! So, you don't care to know how often it occurs, and you don't want to think about what changes might prevent this from happening in the first place?

From the dev perspective, the problem has been fixed "silently", and they aren't required to learn anything or change anything. Nice for them, but not nice for the users.  So, of course I reported the error, even though restarting allowed me to work around the problem.

As a software developer, I am expected to place a high priority on user experience.  I expect my tools to do the same.  Just like a builder of high-end homes who does not use cheap tools.

**Comment by pmiossec** [comment]
@ArmorBearer 

Once again a friendly message putting the blame on the ones that provide a service **on our free time**...

>The error message in GE said (**in so many words**),

Try to explain things to users, they will reproach you... 2 sentences are too much for you?

>you don't want to think about what changes might prevent this from happening in the first place?

Have you read the 2nd line of text in the error popup or 1st line of link I provided to you? You will find the known reason (which is the only one known at the moment!).

>As a software developer, I am expected to place a high priority on user experience.

Yes, please, spend time to help Microsoft fix the dotnet fwk Windows Update issue: https://github.com/dotnet/runtime/issues/60144
I would say we try to do our best also that's why we put in place this friendly popup instead of an application crash to catch **only** this issue because we already know that we can't fix it on our side.

As a consequence, if you don't want to have the issue and put the user experience above everything else, I'm sure you will take action by turning off Windows Update... 🤣

**Comment by ArmorBearer** [comment]
> 2 sentences are too much for you?

When I used the phrase "in so many words" it was not intended to criticize the length or wording of your message.  In English, this phrase is often used to mean "I am not giving an exact quote, but rather a summary or paraphrase".  Sorry for the miscommunication.

> Have you read the 2nd line of text in the error popup or 1st line of link I provided to you? You will find the known reason (which is the only one known at the moment!).

The second line of text in the error popup states:  "... likely caused by Windows Update."  This is important information, but not the complete picture.

I'm a software developer, and our team uses .NET to produce software which is used by thousands of users every day all over the world.  Why hasn't our software failed with the same problem?

For that matter, why haven't I experienced this problem with any other software besides GitExtensions?  This is not a criticism; it is an interesting question.  There must be something different about the way GE works that makes it more vulnerable to this problem.  Could it be made to work differently?

Telling the user not to report the error sends the message that you don't want to consider questions like this.

> Yes, please, spend time to help Microsoft fix the dotnet fwk Windows Update issue: https://github.com/dotnet/runtime/issues/60144

I have looked at the runtime issue.  I'm still unsure how this is the cause of the problem I experienced, because when Windows Update happened on my machine, it restarted the computer.  After restart, (if I remember correctly) GE was not open.  I had to start it.  At that point, I would expect it to find the updated DLLs (or fail immediately).  Instead, the failure came the next day.  So I think there's still a mystery here...

In spite of this, I will add a comment to the .NET issue to encourage MS to fix the problem, since I trust your judgment that this is the cause of the GE problem.  If you had mentioned this known .NET problem to me yesterday, I would have already done that.

I believe it would put more pressure on Microsoft to fix this problem if you could say "So far this issue has caused work disruption for N of our customers."  But since you don't get those problem reports, you don't know what number to put for N, so you can't say that - missed opportunity... 😞
