### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by ChaerilM** [gitextensions/gitextensions#11387]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: True

### Issue description

Exit code: 128
Command: wsl
Arguments: -d Ubuntu git remote
Working directory: \\wsl$\Ubuntu\home\ubuntu\work\kamalio\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 332
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 264
   at GitCommands.GitModule.GetRemoteNames() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2317
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.<>c__DisplayClass37_0.<<GetHostedRemotesForModule>g__Remotes|0>d.MoveNext() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 235
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.GetHostedRemotesForModule() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 229
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 215
   at GitUI.PluginRegistry.<>c.<TryGetGitHosterForModule>b__11_0(IRepositoryHostPlugin gitHoster) in C:\projects\gitextensions\GitUI\Plugin\PluginRegistry.cs:line 59
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.PluginRegistry.TryGetGitHosterForModule(GitModule module) in C:\projects\gitextensions\GitUI\Plugin\PluginRegistry.cs:line 59
   at GitUI.CommandsDialogs.RevisionDiffControl.RegisterGitHostingPluginInBlameControl() in C:\projects\gitextensions\GitUI\CommandsDialogs\RevisionDiffControl.cs:line 1458
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1715
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\Dashboard.cs:line 187
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.OnModuleChanged(GitModuleEventArgs args) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 365
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.TryOpenRepository(Repository repository) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 933
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 645
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\NativeListView.cs:line 93
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

WSL2 mode, open git extension. it usually works but now it wont

### Steps to reproduce

open git extension, open WSL2 repo

### Did this work in previous version of GitExtensions?

yes, it even works yesterday.

### Diagnostics

File name:   wsl -d Ubuntu git
Arguments:   remote
Working dir: \\wsl$\Ubuntu\home\ubuntu\work\kamalio\
Process ID:  16376
Started at:  2023-11-24T09:17:11.1629001+07:00
UI Thread?:  True
Duration:    154,004 ms
Exit code:   GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.

File name:   wsl -d Ubuntu git
Arguments:   --no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files
Working dir: \\wsl$\Ubuntu\home\ubuntu\work\kamalio\
Process ID:  33692
Started at:  2023-11-24T09:17:11.4583148+07:00
UI Thread?:  False
Duration:    146,031 ms
Exit code:   GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Threading.ThreadingTools.WithCancellationSlow[T](Task`1 task, CancellationToken cancellationToken)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 332
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass46_0.<<Update>b__0>d.MoveNext() in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\GitStatusMonitor.cs:line 479
Call stack:  not captured

**Comment by ChaerilM** [comment]
i use my git inside wsl2, the gitextension work until yesterday, i think after i added systemctl to wsl2 via some hacky way. then realized i could just add it via wsl.conf.
git from vscode is working so its not the git itself nor the faulty repo
![image](https://github.com/gitextensions/gitextensions/assets/1352081/cdb12c16-af01-4c14-b2d6-57f6a32846b5)
name and email is there also.

**Comment by ChaerilM** [comment]
![image](https://github.com/gitextensions/gitextensions/assets/1352081/39073b3e-a747-457c-a452-44a20a060ee0)

![image](https://github.com/gitextensions/gitextensions/assets/1352081/e91ec6c0-8f59-4858-b793-2befbc781914)

**Comment by gerhardol** [comment]
Do that in the repo where you saw the problem.

**Comment by gerhardol** [comment]
wsl -d Ubuntu git remote

**Comment by ChaerilM** [comment]
![image](https://github.com/gitextensions/gitextensions/assets/1352081/3b841130-c607-43fc-8970-e60556c54d15)

![image](https://github.com/gitextensions/gitextensions/assets/1352081/cf65e1b1-a170-448b-949c-fc9080620f71)

**Comment by gerhardol** [comment]
and in Windows

It is Git that raises the error, I cannot see that GE invokes the command incorrectly

If only error exit in WSL and this is a worktree, Git sets up paths incorrectly.
https://git-extensions-documentation.readthedocs.io/en/main/settings.html#wsl-git-notes
https://git-extensions-documentation.readthedocs.io/en/main/worktrees.html#note-for-wsl

**Comment by ChaerilM** [comment]
Ok. seems like that was the culprit, i found the revert [there](https://raw.githubusercontent.com/DamionGans/ubuntu-wsl2-systemd-script/dee9b7f604d7a4f4f0294a8dbb9b942fe0aedda9/uninst_00.sh). 
and then use the wsl2 internal systemd via wsl.conf.

thanks
