### ISSUE TITLE
[NBug] ListView in ListViewGroupAccessibleObject..ctor(ListViewGroup owningGroup, Boolean owningGroupIsDefault)

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11385]
### Environment

- Git Extensions 33.33.33
- Build 4d6b2fb3d73a03ccdb5b970637d6b7b6e71e8764
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.0
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: ListView
   at System.Windows.Forms.ListViewGroup.ListViewGroupAccessibleObject..ctor(ListViewGroup owningGroup, Boolean owningGroupIsDefault)
   at System.Windows.Forms.ListViewGroup.get_AccessibilityObject()
   at System.Windows.Forms.ListView.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m) in D:\Build\gitextensions3\GitUI\UserControls\NativeListView.cs:line 31
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

Click the FileStatusList in the Diff tab - perhaps with a modifier key

### Did this work in previous version of GitExtensions?

Yes, I guess before .NET 8

**Comment by RussKie** [comment]
This could possible be a bug in Windows Forms

**Comment by mstv** [comment]
`Alt+Tab` to GE:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/61f3f943-f29b-4396-91d0-7f1349b58c64)

**Comment by RussKie** [comment]
I tried but I wasn't unable to replicate. I guess I'm missing some step.

**Comment by RussKie** [comment]
I think this is where it fails, but I can't imagine what leads to this:
https://github.com/dotnet/winforms/blob/32ceec875f936778d598af959bca81b415834b7a/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs#L23-L27

**Comment by mstv** [comment]
re-occurred, this time when refreshing FormCommit after commiting

**Comment by RussKie** [comment]
This is a Windows Forms bug.
