### ISSUE TITLE
[NBug] serialised

### ISSUE THREAD

**Issue by tommycologne** [gitextensions/gitextensions#11383]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.25
- DPI 144dpi (150% scaling)
- Portable: False

### Issue description

```
System.ArgumentException: serialised
   at GitCommands.UserRepositoryHistory.Legacy.RepositoryCategoryXmlSerialiser.Deserialize(String serialised) in C:\projects\gitextensions\GitCommands\UserRepositoryHistory\Legacy\RepositoryCategoryXmlSerialiser.cs:line 23
   at GitCommands.UserRepositoryHistory.Legacy.RepositoryStorage.Load() in C:\projects\gitextensions\GitCommands\UserRepositoryHistory\Legacy\RepositoryStorage.cs:line 55
   at GitCommands.UserRepositoryHistory.Legacy.RepositoryHistoryMigrator.MigrateAsync(IEnumerable`1 currentHistory) in C:\projects\gitextensions\GitCommands\UserRepositoryHistory\Legacy\RepositoryHistoryMigrator.cs:line 61
   at GitCommands.UserRepositoryHistory.LocalRepositoryManager.LoadFavouriteHistoryAsync() in C:\projects\gitextensions\GitCommands\UserRepositoryHistory\LocalRepositoryManager.cs:line 183
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesListController.PreRenderRepositories(Graphics g, String pattern) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesListController.cs:line 88
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.ShowRecentRepositories(Boolean reloadData) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 279
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.RefreshContent() in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\Dashboard.cs:line 61
   at GitUI.CommandsDialogs.FormBrowse.ShowDashboard() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 732
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1710
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 486
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 571
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Starting th Program

### Steps to reproduce

Every time starting the program

**Comment by gerhardol** [comment]
Open your settings file: C:\Users\ejgo\AppData\Roaming\GitExtensions\GitExtensions\GitExtensios.settings
`repositories` seem to exist but is empty, so migration of old settings fail
Remove the section

```
<item>
    <key>
      <string>repositories</string>
    </key>
    <value>
      <string></string>
    </value>
  </item>
```

--
In GitCommands\UserRepositoryHistory\Legacy\RepositoryStorage.cs:47
change
if (legacySetting is null)
to
if (string.IsEmptyOrNull(legacySetting))
