### ISSUE TITLE
[NBug] Method not found: 'System.String GitUIPluginInterfaces.IGit...

### ISSUE THREAD

**Issue by avi-intel** [gitextensions/gitextensions#11400]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.25997.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.MissingMethodException: Method not found: 'System.String GitUIPluginInterfaces.IGitModule.GetSelectedBranch()'.
   at GitExtensions.GerritPlugin.FormGerritPublish.GetBranchName(String targetBranch)
   at GitExtensions.GerritPlugin.FormGerritPublish.FormGerritPublishLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\GitExtensionsForm.cs:line 67
   at GitExtensions.GerritPlugin.FormGerritBase.OnLoad(EventArgs e)
   at GitExtensions.GerritPlugin.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Getting this message on push to gerrit.

### Steps to reproduce

Push to gerrit using the gerrit plugin.

**Comment by pmiossec** [comment]
A new version of gerrit plugin has been released to fix this breaking change issue. Please update the plugin.

**Comment by avi-intel** [comment]
[0001-Updated-version-to-1.30.0.4.patch](https://github.com/gitextensions/gitextensions/files/13477417/0001-Updated-version-to-1.30.0.4.patch)

**Comment by pmiossec** [comment]
> This is the commit that caused the exception:
> 
> [0001-Updated-version-to-1.30.0.4.patch](https://github.com/gitextensions/gitextensions/files/13477417/0001-Updated-version-to-1.30.0.4.patch)

It won't help us here. Update the gerrit plugin since you installed a new version of GitExtensions that is no more compatible.

![image](https://github.com/gitextensions/gitextensions/assets/460196/f1633054-cb0d-47b5-91dd-ebfaac35dd1c)
