### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by Deimos21-EFI** [gitextensions/gitextensions#11418]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 1
Command: wsl
Arguments: -d Ubuntu git remote
Working directory: \\wsl$\Ubuntu\root\archibus\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 368
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 264
   at GitCommands.GitModule.GetRemoteNames() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2323
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.<>c__DisplayClass37_0.<<GetHostedRemotesForModule>g__Remotes|0>d.MoveNext() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 235
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.GetHostedRemotesForModule() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 229
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.ConfigureContextMenu(ContextMenuStrip contextMenu) in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 261
   at GitUI.Blame.BlameControl.ConfigureRepositoryHostPlugin(IRepositoryHostPlugin gitHoster) in C:\projects\gitextensions\GitUI\UserControls\BlameControl.cs:line 83
   at GitUI.CommandsDialogs.RevisionFileTreeControl.RegisterGitHostingPluginInBlameControl() in C:\projects\gitextensions\GitUI\CommandsDialogs\RevisionFileTreeControl.cs:line 971
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1732
   at GitUI.RepositoryHistoryUIService.ChangeWorkingDir(String path) in C:\projects\gitextensions\GitUI\RepositoryHistoryUIService.cs:line 62
   at GitUI.RepositoryHistoryUIService.OpenRepo(String repoPath) in C:\projects\gitextensions\GitUI\RepositoryHistoryUIService.cs:line 73
   at GitUI.RepositoryHistoryUIService.<>c__DisplayClass9_0.<AddRecentRepositories>b__0(Object obj, EventArgs args) in C:\projects\gitextensions\GitUI\RepositoryHistoryUIService.cs:line 41
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Commit from wsl Ubuntu on Windows 11

### Steps to reproduce

When opening gitExtension and select the \\wsl$\Ubintu\... project

**Comment by gerhardol** [comment]
Duplicate of #11387 

From Windows, eg. in GE console:
wsl -d Ubuntu git remote
git remote

From Ubuntu:
git remote

**Comment by gerhardol** [comment]
Windows command "wsl.exe" that invokes Git in wsl occasionally fails. We should probably add an additional popup for wsl, similar to permission handling to avoid sporadic reports - failures will happen occasionally.
