### ISSUE TITLE
[NBUG] System.OperationCanceledException: The operation was canceled. (System.Threading)

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11453]
### Environment

- Git Extensions 33.33.33
- Build 667a8101b891fca60aaf44bff27202f8630a3158
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.0
- DPI 96dpi (no scaling)

### Issue description

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GitUI.RevisionGridControl.<>c__DisplayClass145_0.<PerformRefreshRevisions>g__OnRevisionRead|6(GitRevision revision) in F:\Build\gitextensions3\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 1239
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Steps to reproduce

Hit `F5` several times with #11205 included.

**Comment by gerhardol** [comment]
I cannot recreate (not a clean test though).
However, occasionally the graph is not reloaded (with and without the PR), #9223

![image](https://github.com/gitextensions/gitextensions/assets/6248932/c27f96b6-d33e-40bc-b7d5-b2c6b10ad5ce)
