### ISSUE TITLE
[NBug] Method not found: 'System.Collections.Generic.IReadOnlyList...

### ISSUE THREAD

**Issue by BBzzz** [gitextensions/gitextensions#11455]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.25
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<GitUIPluginInterfaces.IGitRef> GitUIPluginInterfaces.IGitModule.GetRefs(Boolean, Boolean)'.
   at GitExtensions.GerritPlugin.FormGerritPublish.FormGerritPublishLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\GitExtensionsForm.cs:line 67
   at GitExtensions.GerritPlugin.FormGerritBase.OnLoad(EventArgs e)
   at GitExtensions.GerritPlugin.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I can't publish my gitreview!

### Steps to reproduce

When I try to publish my Gerrit change it drops the above-mentioned error!

### Did this work in previous version of GitExtensions?

The last version which worked for me was 3.5, and since then every time I tried to update to newest version of GE it failed when tried to publish my commit to Gerrit

**Comment by pmiossec** [comment]
Please update the gerrit plugin from the plugin manager.
