### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by ivan-garcia-subero** [gitextensions/gitextensions#11459]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: -1
Command: wsl
Arguments: -d Ubuntu-20.04 git --version
Working directory: \\wsl$\Ubuntu-20.04\var\www\spsitios\library\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 129
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 43
   at GitCommands.GitVersion.CurrentVersion(IExecutable gitExec, String gitIdentifiable) in C:\projects\gitextensions\GitCommands\Git\GitVersion.cs:line 48
   at GitCommands.GitModule.get_GitVersion() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 167
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 950
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions(Func`2 getRefs) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 654
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 625
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1719
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\Dashboard.cs:line 187
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.OnModuleChanged(GitModuleEventArgs args) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 365
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.TryOpenRepository(Repository repository) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 933
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\BrowseDialog\DashboardControl\UserRepositoriesList.cs:line 645
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\NativeListView.cs:line 93
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Error opening a repo using Git Extensions for Windows, repo is stored in Ubuntu for Windows

### Steps to reproduce

Try to open a repo stored in Ubuntu for Windows from Git Extensions installed on Windows

**Comment by pmiossec** [comment]
Seems similar to #11387. Please have a look.
