### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by ChrisL** [gitextensions/gitextensions#11490]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 1
Command: D:\programs\Git\bin\git.exe
Arguments: config --get http.proxy
Working directory: D:\sources\EnMAP\masterprocessor\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 129
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 43
   at GitExtensions.Plugins.ProxySwitcher.ProxySwitcherForm.RefreshProxy() in C:\projects\gitextensions\Plugins\ProxySwitcher\ProxySwitcherForm.cs:line 66
   at GitExtensions.Plugins.ProxySwitcher.ProxySwitcherForm.ProxySwitcherForm_Load(Object sender, EventArgs e) in C:\projects\gitextensions\Plugins\ProxySwitcher\ProxySwitcherForm.cs:line 55
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Upgraded to new version of GitExtensions, which also required installing a new version of Git.
Thereafter using the ProxySwitcher fails.

### Steps to reproduce

Upgrade to new major version of GitExtensions (new version see above), which also required a new version of Git.
Thereafter using the ProxySwitcher (after opening an existing repo) fails.

After providing the proxy in the Plugin Settings dialog, I was able to set the proxy by ignoring the error, but I can't un-set the proxy using the ProxySwitcher dialog, I have to remove it from the Proxy Settings dialog (Effective).

Note: I only provide the `HTTP Proxy` and the `HTTP Proxy Port`, no `Username` and `Password` is required for our proxy.

### Did this work in previous version of GitExtensions?

Git: 2.23.0
GitExtensions: 3.2.1.6628

probably I also

**Comment by gerhardol** [comment]
http.proxy is not set which Git reports as an error. Since GE 4.0, all such Git errors that are not suppressed are reported in a popup.
Just ignore the popup for now.
You may also set http.proxy globally and in each repo.

Please try the update in #11491 to not raise the popup.
