### ISSUE TITLE
[NBug] SplitterDistance must be between Panel1MinSize and Width - ...

### ISSUE THREAD

**Issue by hasary** [gitextensions/gitextensions#11522]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at GitUI.CommandsDialogs.FormBrowse.SetSplitterPositions() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2222
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 473
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 565
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

.

### Steps to reproduce

Open GitExt

**Comment by RussKie** [comment]
Please update to the latest.

**Comment by pmiossec** [comment]
Duplicate of #11085
