### ISSUE TITLE
[NBug] error: unable to unlink old 'logs/application.log': Invalid...

### ISSUE THREAD

**Issue by Vinzent82** [gitextensions/gitextensions#11532]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: reset --hard --
Working directory: C:\Users\Victor Klüber\Git_Repos\moisture-manager-front\

```
GitExtUtils.ExternalOperationException: error: unable to unlink old 'logs/application.log': Invalid argument
fatal: Could not reset index file to revision 'HEAD'.
 ---> System.Exception: error: unable to unlink old 'logs/application.log': Invalid argument
fatal: Could not reset index file to revision 'HEAD'.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 234
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 169
   at GitCommands.GitModule.Reset(ResetMode mode, String file) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 1284
   at GitCommands.GitModule.ResetAllChanges(Boolean clean, Boolean onlyWorkTree) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 1271
   at GitUI.GitUICommands.<>c__DisplayClass107_0.<StartResetChangesDialog>g__Action|2() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 732
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartResetChangesDialog(IWin32Window owner, IReadOnlyCollection`1 workTreeFiles, Boolean onlyWorkTree) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 728
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass194_0.<ResetChanges>b__0() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 2646
   at GitUI.CommandsDialogs.FormCommit.BypassFormActivatedEventHandler(Action action) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 2662
   at GitUI.CommandsDialogs.FormCommit.ResetChanges(Boolean onlyWorkTree) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 2646
   at GitUI.CommandsDialogs.FormCommit.btnResetAllChanges_Click(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 2636
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

tried to reset all changes

### Steps to reproduce

click on `commit` -> `reset all changes` 

for unknown reaon the file `applocation.log` can not be resetted.

**Comment by mstv** [comment]
🤔 Is your application still running and writing to the log file?
Definitely nothing, GE or git could help you with.

**Comment by Vinzent82** [comment]
thanks @mstv your assumption was correct the application was still running but I forgot...
