### ISSUE TITLE
[NBug] Method not found: 'GitUIPluginInterfaces.ISettingsSource Re...

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#11541]
### Environment

- Git Extensions 33.33.33
- Build 99aa0686048a9abb15fbd76ccfffa7709148613c
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.1
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.MissingMethodException: Method not found: 'GitUIPluginInterfaces.ISettingsSource ResourceManager.GitPluginBase.get_Settings()'.
   at GitExtensions.PluginManager.Plugin.Register(IGitUICommands commands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p) in C:\Users\Pavel\Projects\GitExtensions\GitUI\Plugin\PluginRegistry.cs:line 89
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in C:\Users\Pavel\Projects\GitExtensions\GitExtUtils\Linq\LinqExtensions.cs:line 88
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands) in C:\Users\Pavel\Projects\GitExtensions\GitUI\Plugin\PluginRegistry.cs:line 89
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins() in C:\Users\Pavel\Projects\GitExtensions\GitUI\CommandsDialogs\FormBrowse.cs:line 805
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\Users\Pavel\Projects\GitExtensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1721
   at GitUI.RepositoryHistoryUIService.ChangeWorkingDir(String path) in C:\Users\Pavel\Projects\GitExtensions\GitUI\RepositoryHistoryUIService.cs:line 61
   at GitUI.RepositoryHistoryUIService.OpenRepo(String repoPath) in C:\Users\Pavel\Projects\GitExtensions\GitUI\RepositoryHistoryUIService.cs:line 72
   at GitUI.RepositoryHistoryUIService.<>c__DisplayClass9_0.<AddRecentRepositories>b__0(Object obj, EventArgs args) in C:\Users\Pavel\Projects\GitExtensions\GitUI\RepositoryHistoryUIService.cs:line 40
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

It occurs every time I switch repositories.

### Did this work in previous version of GitExtensions?

Certainly, this started occuring in the last couple of weeks.

**Comment by pmiossec** [comment]
>Certainly, this started occuring in the last couple of weeks.

It seems you are building a custom version so you means that it starts to crash since you built an earlier version of master?

Do you have external plugins installed from plugin manager?

**Comment by crypto-rsa** [comment]
> It seems you are building a custom version so you means that it starts to crash since you built an earlier version of master?

Yes, that's right.

> Do you have external plugins installed from plugin manager?

No, I've never used the plugin manager. Although now I've run it and it shows an update for itself (from v1.1.0.109 to v2.0.1.195). I guess it could help?

**Comment by RussKie** [comment]
The Plugin Manager is a part of the application bundle, and it has to
version alongside the main app.

**Comment by crypto-rsa** [comment]
> and it has to version alongside the main app.

What does it mean? That I need to regularly update it? But when I tried it through the GE UI I got an error message that the update package cannot be found.
In the end I manually downloaded the update package and replaced the contents of `C:\Users\<username>\AppData\Local\GitExtensions\UserPlugins` with the package contents. I can now run the `PackageManagerUI` application separately but I get an exception when GE starts (_Could not load type 'GitUIPluginInterfaces.BoolSetting' from assembly 'GitUIPluginInterfaces'_). And obviously the Plugin Manager is not available in GE.

I am wondering what's the correct way to handle the GE Plugin Manager?

**Comment by mstv** [comment]
> I am wondering what's the correct way to handle the GE Plugin Manager?

Currently, we are refactoring the `GitUIPluginInterfaces` in addition to the switch to .NET 8 - without keeping downward compatibility.
One might need to manually build the (adapted) Plugin Manager.
Since you do not use plugins, it might work to remove all plugins including the Plugin Manager - or else use something like 9f1f6cdc35eb7d01c683958c3d951c384685d4c4 in your private build.

> That I need to regularly update it? But when I tried it through the GE UI I got an error message that the update package cannot be found.

Yes. We need to make this work when releasing vNext.

**Comment by crypto-rsa** [comment]
Thanks for the clarification.
