### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by celeron533** [gitextensions/gitextensions#11617]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.27
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: config --get http.proxy
Working directory: C:\Users\celeron533\Documents\Git\DicomGrep\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 147
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 43
   at GitExtensions.Plugins.ProxySwitcher.ProxySwitcherForm.RefreshProxy() in C:\projects\gitextensions\Plugins\ProxySwitcher\ProxySwitcherForm.cs:line 66
   at GitExtensions.Plugins.ProxySwitcher.ProxySwitcherForm.UnsetProxy_Button_Click(Object sender, EventArgs e) in C:\projects\gitextensions\Plugins\ProxySwitcher\ProxySwitcherForm.cs:line 135
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

This error occurs when using the plugin "ProxySwitcher" to unset Git http proxy.
1. Define a http proxy server endpoint in the plugin settings.
2. In the "ProxySwitcher" plugin, set then unset the proxy.
3. When unset the proxy, this error popup.

PS1. Although it reported an error, the proxy is removed.
PS2. In source code `GitModule.cs`, method `public string? GetGitSetting(...)` already defined the following
```
           // Handle no value set, is error code 1: https://git-scm.com/docs/git-config#_description
            const int ConfigKeyInvalidOrNotSet = 1;
```
but somehow this doesn't work.

### Steps to reproduce

This error occurs when using the plugin "ProxySwitcher" to unset Git http proxy.
1. Define a http proxy server endpoint in the plugin settings.
2. In the "ProxySwitcher" plugin, set then unset the proxy.
3. When unset the proxy, this error popup.

**Comment by gerhardol** [comment]
Duplicate of #11490
Fixed in #11491

Try latest master build as standalone. Just set the global proxy for now

**Comment by celeron533** [comment]
Thank you @gerhardol !
