### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by iseliweb** [gitextensions/gitextensions#11613]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET 6.0.27
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout -- "**.Apps.***.Data/DataContext.cs"
Working directory: C:\Workspace\**\**.Apps.***\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 368
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunBatchCommand(IExecutable executable, ICollection`1 batchArguments, Action`1 action, Action`1 writeInput) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 196
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 1483
   at GitCommands.GitModule.Reset

### Steps to reproduce

* Create a file in a new branch
* Commit and push
* Checkout another branch where the file not yet exists 



### Did this work in previous version of GitExtensions?

no, may be git related

### Diagnostics

_No response_

**Comment by iseliweb** [comment]
rm -f ./git/index.lock helped
Maybe this is more a topic for git itself instead of git extensions
