### ISSUE TITLE
[NBug] The type initializer for 'System.Data.Common.DataStorage' t...

### ISSUE THREAD

**Issue by werwolfby** [gitextensions/gitextensions#11639]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.27
- DPI 144dpi (150% scaling)
- Portable: False

### Issue description

```
System.TypeInitializationException: The type initializer for 'System.Data.Common.DataStorage' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Numerics, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.Numerics, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Data.Common.DataStorage..cctor()
   --- End of inner exception stack trace ---
   at System.Data.Common.DataStorage.GetStorageType(Type dataType)
   at System.Data.DataColumn..ctor(String columnName, Type dataType, String expr, MappingType type)
   at System.Data.DataColumnCollection.Add(String columnName, Type type)
   at GitUI.CommandsDialogs.FormPush.UpdateMultiBranchView() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 935
   at GitUI.CommandsDialogs.FormPush.TabControlTagBranch_Selected(Object sender, TabControlEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPush.cs:line 1126
   at System.Windows.Forms.TabControl.OnSelected(TabControlEventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Push multiple branches tab doesn't fails with this exception

### Steps to reproduce

Press push button, switch to `Push multiple branches` tab.

### Did this work in previous version of GitExtensions?

Do not use this tab very often. But it definitely worked some time ago.

**Comment by pmiossec** [comment]
> Do not use this tab very often. But it definitely worked some time ago.

Could you try again after restarting gitextensions?
Because it seems a typical issue caused by windows update and where gitextensions has no real possible way to handle it gracefully...

**Comment by werwolfby** [comment]
Damn it! It really helped :)
