### ISSUE TITLE
[NBug] Ctrl+C pressed or console closed

### ISSUE THREAD

**Issue by scottburns-ati** [gitextensions/gitextensions#11669]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.28
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.OperationCanceledException: Ctrl+C pressed or console closed
 ---> GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Using username "git".
 ---> System.Exception: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Using username "git".
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 81
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 71
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormRemoteProcess.cs:line 169
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormProcess.cs:line 217
   at GitUI.UserControls.ConsoleOutputControl.FireDataReceived(TextEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleOutputControl.cs:line 50
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 210
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 175
   at ConEmu.WinForms.AnsiLog.PumpStream()
   at ConEmu.WinForms.ConEmuSession.<>c__DisplayClass38_0.<Init_AnsiLog>b__1(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Created a ssh key on win10 using putty via git extenstions. Added key to github and authorized. Cloned fresh copy of an authorized repo. Loaded ppk, before cloning began I got a message that the certificate needed to be accepted. A command line window opened. Pressed Y, enter. Prompted to press return to begin session and did so. Git extensions hung and would not move on.

### Steps to reproduce

Created a ssh key on win10 using putty via git extenstions. Added key to github and authorized. Cloned fresh copy of an authorized repo. Loaded ppk, before cloning began I got a message that the certificate needed to be accepted. A command line window opened. Pressed Y, enter. Prompted to press return to begin session and did so. Git extensions hung and would not move on. Closed the command line window to see if that was needed and hit the bug.

### Did this work in previous version of GitExtensions?

unknown, did use ssh previously

**Comment by TheObliterator** [comment]
I have the same problem on a new Window 11 setup.
