### ISSUE TITLE
[NBug] Cannot access a disposed object.Object name: 'NativeListV...

### ISSUE THREAD

**Issue by ExterminatorX99** [gitextensions/gitextensions#11668]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'NativeListView'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ListView.CreateHandle()
   at GitUI.UserControls.NativeListView.CreateHandle() in C:\projects\gitextensions\GitUI\UserControls\NativeListView.cs:line 21
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphics()
   at GitUI.FileStatusList.<UpdateColumnWidth>g__GetWidth|130_0() in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 1276
   at GitUI.FileStatusList.UpdateColumnWidth() in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 1278
   at GitUI.FileStatusList.UpdateFileStatusListView(Boolean updateCausedByFilter) in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 1110
   at GitUI.FileStatusList.FilterFiles(String value) in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 1753
   at GitUI.FileStatusList.<InitialiseFiltering>b__154_0(String filterText) in C:\projects\gitextensions\GitUI\UserControls\FileStatusList.cs:line 1795
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 117
```

Compare previous commit with current branch. Close the compare window.

### Steps to reproduce

- Compare previous commit to current branch
- Close compare window

**Comment by RussKie** [comment]
This looks like a fluke... Without a stable repro there's nothing we can do.
