### ISSUE TITLE
[NBug] Crash when using putty.exe as a ssh agent

### ISSUE THREAD

**Issue by andreicimpean** [gitextensions/gitextensions#11663]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.28
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.OperationCanceledException: Ctrl+C pressed or console closed
 ---> GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Connection abandoned.
 ---> System.Exception: The host key is not cached for this server:
  github.com (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) Connection abandoned.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 81
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 71
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormRemoteProcess.cs:line 169
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormProcess.cs:line 217
   at GitUI.UserControls.ConsoleOutputControl.FireDataReceived(TextEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleOutputControl.cs:line 50
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 210
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 175
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Use putty.exe as ssh agent with github

### Steps to reproduce

use putty.exe as a ssh agent with a github repo

**Comment by RussKie** [comment]
Thanks for the report but it feels like you trimmed some of the information off the report as there are no command/exit code/arguments information provided...

Looks like a dup of https://github.com/gitextensions/gitextensions/issues/11132

**Comment by mstv** [comment]
no response from author
