### ISSUE TITLE
[NBug] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by cforbin1** [gitextensions/gitextensions#11678]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.28
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   at GitUI.CommandsDialogs.FormCommit.Message_TextChanged(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCommit.cs:line 2785
   at GitUI.SpellChecker.EditNetSpell.TextBoxTextChanged(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 640
   at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
   at System.Windows.Forms.RichTextBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Pressed standard Commit button instead of "Complete" merge, following successful conflict resolution of a merge from a commit that's "mid stream" on one branch, to the head of another branch.

### Steps to reproduce

1. Merge from a commit that's mid-stream on one branch, to the head of another branch.
2. Ensure this merge will get at least one conflict to resolve.
3. (For me, this was a big merge involving MANY files but few conflicts.  No idea if this contributes to the error or not.)
4. Resolve the conflicts.
5. Shut down and re-start Git Extensions.
6. Press the standard "Commit" button, NOT the "Continue" (merge) button.
7. (Possible contributing factor: specified 30 previous commits to be added into the comment.  It's a LONG comment that needs editing.)
8. Get the Index out of Range exception.

**Comment by mstv** [comment]
very similar to #7614 (and #8607)
cannot reproduce
