### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Net.Mail, Version=6...

### ISSUE THREAD

**Issue by dariusiko** [gitextensions/gitextensions#11681]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.28
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 90
   at GitUI.PatchGrid.Initialize() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 119
   at GitUI.PatchGrid.OnRuntimeLoad() in C:\projects\gitextensions\GitUI\UserControls\PatchGrid.cs:line 71
   at ResourceManager.GitExtensionsControl.OnLoad(EventArgs e) in C:\projects\gitextensions\ResourceManager\GitExtensionsControl.cs:line 38
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

a

### Steps to reproduce

Rebase one branch with another branch

**Comment by pmiossec** [comment]
@valekseev-fls It's due to the update of dotnet framework that just been released provided through Windows update.
THe workaround is indeed to restart GitExtensions.
