### ISSUE TITLE
[NBug] Ctrl+C pressed or console closed

### ISSUE THREAD

**Issue by PromidataAchim** [gitextensions/gitextensions#11699]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.27
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.OperationCanceledException: Ctrl+C pressed or console closed
 ---> GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  bitbucket.org (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:ybgmFkzwOSotHTHLJgHO0QN8L0xErw6vd0VhFA9m3SM
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info)
 ---> System.Exception: The host key is not cached for this server:
  bitbucket.org (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:ybgmFkzwOSotHTHLJgHO0QN8L0xErw6vd0VhFA9m3SM
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 81
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 71
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormRemoteProcess.cs:line 169
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormProcess.cs:line 217
   at GitUI.UserControls.ConsoleOutputControl.FireDataReceived(TextEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleOutputControl.cs:line 50
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 210
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 175
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

first checkout from bitbucket on new PC

### Steps to reproduce

New PC, first checkouts from Github were fine. 
Do a checkout from BitBucket and conrifm to add fingerprint

**Comment by mstv** [comment]
What have you done on the prompt "Store key in cache? (y/n, Return cancels connection, i for more info)"?
1. entered 'y' or 'n' and pressed `Return`
2. closed the console window using the `X` button or `Alt+F4`

**Comment by PromidataAchim** [comment]
In the console nothing was Prompted, it just hand. 
The exception comes when I then close the console window after some minutes.
The problem is not the exception after the close of the console windows, it is that in the window nothing is in and nothing happens.

**Comment by mstv** [comment]
Do you get that prompt and can enter your input if you use ConEmu?

![image](https://github.com/gitextensions/gitextensions/assets/36601201/21edbc36-f265-4a0b-b3c3-69330d688395)

**Comment by PromidataAchim** [comment]
I do only get an empty console without any text.
I could not check if it works when deactivating this setting, because I had to work and already add the bitbucket key manual
