### ISSUE TITLE
Display of MC on moved file

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11755]
### Environment

- Git Extensions 33.33.33
- Build 2bbffb108db4ac8f160327345e77d4f7561c78ec
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.4
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Weird display of MC: The same file appears as deleted in both `working dir` and  `commit index`.
Might be caused by the file being moved both in `master` commit and in the feature commit.

working dir:
![image](https://github.com/gitextensions/gitextensions/assets/36601201/fdcfe645-7e07-41e3-ae61-5bbae51bd9a7)

commit index:
![image](https://github.com/gitextensions/gitextensions/assets/36601201/334cff59-7b52-49ba-9503-05cf77f0b015)

git rebase output:
```
CONFLICT (rename/rename): Plugins/GitUIPluginInterfaces/ServiceProviderExtensions.cs renamed to src/plugins/GitUIPluginInterfaces/ServiceProviderExtensions.cs in HEAD and to src/app/GitExtUtils/ServiceProviderExtensions.cs in 8ee6592d5 (feat: Add SubscribableTraceListener).
CONFLICT (file location): GitExtUtils/ServiceContainerRegistry.cs added in 8ee6592d5 (feat: Add SubscribableTraceListener) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to src/app/GitExtUtils/ServiceContainerRegistry.cs.
CONFLICT (file location): Plugins/GitUIPluginInterfaces/ServiceProviderExtensions.cs renamed to GitExtUtils/ServiceProviderExtensions.cs in 8ee6592d5 (feat: Add SubscribableTraceListener), inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to src/app/GitExtUtils/ServiceProviderExtensions.cs.
CONFLICT (file location): GitExtUtils/SubscribableTraceListener.cs added in 8ee6592d5 (feat: Add SubscribableTraceListener) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to src/app/GitExtUtils/SubscribableTraceListener.cs.
```

Resolving by chosing "ours" failed with:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/478e3f97-6aa7-4eb8-a345-ce6f0f977269)

### Steps to reproduce

Try to rebase the following patch on current `master`
![image](https://github.com/gitextensions/gitextensions/assets/36601201/64003ffb-79ba-491b-8a6d-92f151a19c23)

### Did this work in previous version of GitExtensions?

do not know

### Diagnostics

Stack trace
```
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in D:\Build\gitextensions3\GitCommands\Git\ExecutableExtensions.cs:line 131
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.GitModule.HandleConflictSelectSide(String fileName, String side) in D:\Build\gitextensions3\GitCommands\Git\GitModule.cs:line 564
   at GitUI.CommandsDialogs.FormResolveConflicts.ChooseRemoteOnConflict(String fileName) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 913
   at GitUI.CommandsDialogs.FormResolveConflicts.<>c__DisplayClass131_0.<CheckForLocalRevision>b__0(ConflictResolutionPreference solveMergeConflictDialogResult) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1106
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenSolveMergeConflictDialogAndExecuteSelectedMergeAction(Action`1 selectedMergeAction, String dialogText, String dialogInstructionText, String dialogCaption, String dialogFooterCheckboxText, String keepLocalButtonText, String keepRemoteButtonText, String keepBaseButtonText) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 978
   at GitUI.CommandsDialogs.FormResolveConflicts.CheckForLocalRevision(ConflictData item) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1091
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 530
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 520
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool() in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1254
   at GitUI.CommandsDialogs.FormResolveConflicts.merge_Click(Object sender, EventArgs e) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 1499
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by gerhardol** [comment]
This is how git-status reports merge conflicts, in both index and worktree. 
One reason they are hard to reset
