### ISSUE TITLE
Error when clicked "View details" in error dialog

### ISSUE THREAD

**Issue by tomas-laubr-smart-software** [gitextensions/gitextensions#11869]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.29
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: check-ref-format --branch "DPP-2133-V_logu_je_spousta_warningu_\\"HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\\""
Working directory: C:\develop\soliteapay-portal\

```
GitExtUtils.ExternalOperationException: fatal: 'DPP-2133-V_logu_je_spousta_warningu_\HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\' is not a valid branch name
 ---> System.Exception: fatal: 'DPP-2133-V_logu_je_spousta_warningu_\HHH90003004__firstResult/maxResults_specified_with_collection_fetch;_applying_in_memory\' is not a valid branch name
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 234
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 169
   at GitCommands.GitModule.CheckBranchFormat(String branchName) in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 3974
   at GitUI.CommandsDialogs.FormCreateBranch.OkClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormCreateBranch.cs:line 121
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

trying to create a branch of name 'V logu je spousta warningu "HHH90003004: firstResult/maxResults specified with collection fetch; applying in memory"'.

Error dialog appeared with "Ignore" and "View details" buttons. I clicked "View details"

### Steps to reproduce

Try to create branch with name `V logu je spousta warningu "HHH90003004: firstResult/maxResults specified with collection fetch; applying in memory"`

**Comment by RussKie** [comment]
You're receiving a git error because this is not valid branch name.
