### ISSUE TITLE
[NBug] fatal: Failed to resolve 'HEAD~1' as a valid revision.

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11894]
### Environment

- Git Extensions 33.33.33
- Build 4d90769cc05b4cd59e51fcbb8a58dd5682f4dcc9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: reset --soft "HEAD~1" --
Working directory: D:\Build\gitextensions3_dev\

```
GitExtensions.Extensibility.ExternalOperationException: fatal: Failed to resolve 'HEAD~1' as a valid revision.
 ---> System.Exception: fatal: Failed to resolve 'HEAD~1' as a valid revision.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow, Boolean throwOnErrorExit) in D:\Build\gitextensions3\src\app\GitCommands\Git\ExecutableExtensions.cs:line 236
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow, Boolean throwOnErrorExit) in D:\Build\gitextensions3\src\app\GitCommands\Git\ExecutableExtensions.cs:line 164
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e) in D:\Build\gitextensions3\src\app\GitUI\CommandsDialogs\FormCommit.cs:line 2178
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

- create an orphan commit (BTW: The dialog forces to select a pointless base commit.)
- open FormCommit
- amend
- reset soft
--> exception
--> The soft reset is not performed.

**Comment by gerhardol** [comment]
The soft reset would do nothing...
So ignore the error for reset?

**Comment by mstv** [comment]
No, amend must be unticked, too.
Rather disable the button.
