### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'input')

### ISSUE THREAD

**Issue by pvanschendel** [gitextensions/gitextensions#11892]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.ParseUserInputs(String scriptName, String arguments, IGitUICommands uiCommands, IWin32Window owner, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 46
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScriptInternal(ScriptInfo script, IWin32Window owner, IGitUICommands uiCommands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 133
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScript(ScriptInfo script, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 32
   at GitUI.ScriptsEngine.ScriptsManager.RunScript(ScriptInfo scriptInfo, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.cs:line 71
   at GitUI.GitModuleForm.<ExecuteCommand>g__ExecuteScriptCommand|24_0(<>c__DisplayClass24_0&) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 119
   at GitUI.GitModuleForm.ExecuteCommand(Int32 command) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 107
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 2062
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass76_1.<InternalInitialize>b__3(Object s, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 1083
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\src\app\GitUI\UserControls\ToolStripEx.cs:line 89
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

The script configuration was (in GUI):

Name: OpenVSCode
Enabled: True
Command: "{WorkingDir}tools/user_open_vscode_with_msvc.bat"
Arguments: <empty>
Execute on Event: ShowInUserMenuBar
Icon: VisualStudioTemServices
Icon or associated file path: <empty>

I fixed the problem by entering a value in "Arguments". This happened before figuring that the problem was probably caused by the content of the old GitExtensions.settings file, and I have no backup of that file.

This is not how it occurred, but this seems to produce the same result:
- take GitExtensions.settings file, 
- locate the ScriptInfo, 
- remove the line `    &lt;Arguments /&gt;`.

### Did this work in previous version of GitExtensions?

Version 4.x (probably latest)

**Comment by drag-d** [comment]
Has same issue when just click "Pull and rebase" in the active repo
[pull_crash_log.txt](https://github.com/user-attachments/files/16928339/pull_crash_log.txt)
