### ISSUE TITLE
[NBug] No service for type 'ResourceManager.IHotkeySettingsLoader'...

### ISSUE THREAD

**Issue by Cabrill** [gitextensions/gitextensions#11908]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: No service for type 'ResourceManager.IHotkeySettingsLoader' has been registered.
   at GitUIPluginInterfaces.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider) in C:\projects\gitextensions\src\plugins\GitUIPluginInterfaces\ServiceProviderExtensions.cs:line 50
   at GitUI.GitModuleForm.set_UICommands(IGitUICommands value) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 61
   at GitUI.GitModuleForm..ctor(IGitUICommands commands, Boolean enablePositionRestore) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 94
   at GitUI.GitExtensionsDialog..ctor(IGitUICommands commands, Boolean enablePositionRestore) in C:\projects\gitextensions\src\app\GitUI\GitExtensionsDialog.cs:line 20
   at GitUI.HelperDialogs.FormStatus..ctor(IGitUICommands commands, ConsoleOutputControl consoleOutput, Boolean useDialogSettings) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormStatus.cs:line 18
   at GitUI.HelperDialogs.FormProcess..ctor(IGitUICommands commands, ConsoleOutputControl outputControl, ArgumentString arguments, String workingDirectory, String input, Boolean useDialogSettings, String process) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormProcess.cs:line 24
   at GitUI.HelperDialogs.FormProcess..ctor(IGitUICommands commands, ArgumentString arguments, String workingDirectory, String input, Boolean useDialogSettings, String process) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormProcess.cs:line 56
   at GitUI.HelperDialogs.FormRemoteProcess..ctor(IGitUICommands commands, ArgumentString arguments) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormRemoteProcess.cs:line 33
   at GitUI.CommandsDialogs.RepoHosting.ForkAndCloneForm.Clone(IHostedRepository repo) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RepoHosting\ForkAndCloneForm.cs:line 377
   at GitUI.CommandsDialogs.RepoHosting.ForkAndCloneForm._cloneBtn_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RepoHosting\ForkAndCloneForm.cs:line 308
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Trying to clone a Github repo to local

### Steps to reproduce

Use Github API key, and attempt to clone a repository.

### Did this work in previous version of GitExtensions?

Yes.

**Comment by Cabrill** [comment]
Closing as duplicate of: https://github.com/gitextensions/gitextensions/issues/11906
