### ISSUE TITLE
[NBug] No service for type 'ResourceManager.IHotkeySettingsLoader'...

### ISSUE THREAD

**Issue by SanteR1** [gitextensions/gitextensions#11906]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: No service for type 'ResourceManager.IHotkeySettingsLoader' has been registered.
   at GitUIPluginInterfaces.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider) in C:\projects\gitextensions\src\plugins\GitUIPluginInterfaces\ServiceProviderExtensions.cs:line 50
   at GitUI.GitModuleForm.set_UICommands(IGitUICommands value) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 61
   at GitUI.GitModuleForm..ctor(IGitUICommands commands, Boolean enablePositionRestore) in C:\projects\gitextensions\src\app\GitUI\GitModuleForm.cs:line 94
   at GitUI.GitExtensionsDialog..ctor(IGitUICommands commands, Boolean enablePositionRestore) in C:\projects\gitextensions\src\app\GitUI\GitExtensionsDialog.cs:line 20
   at GitUI.HelperDialogs.FormStatus..ctor(IGitUICommands commands, ConsoleOutputControl consoleOutput, Boolean useDialogSettings) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormStatus.cs:line 18
   at GitUI.HelperDialogs.FormProcess..ctor(IGitUICommands commands, ConsoleOutputControl outputControl, ArgumentString arguments, String workingDirectory, String input, Boolean useDialogSettings, String process) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormProcess.cs:line 24
   at GitUI.HelperDialogs.FormProcess..ctor(IGitUICommands commands, ArgumentString arguments, String workingDirectory, String input, Boolean useDialogSettings, String process) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormProcess.cs:line 56
   at GitUI.HelperDialogs.FormRemoteProcess..ctor(IGitUICommands commands, ArgumentString arguments) in C:\projects\gitextensions\src\app\GitUI\HelperDialogs\FormRemoteProcess.cs:line 33
   at GitUI.CommandsDialogs.RepoHosting.ForkAndCloneForm.Clone(IHostedRepository repo) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RepoHosting\ForkAndCloneForm.cs:line 377
   at GitUI.CommandsDialogs.RepoHosting.ForkAndCloneForm._cloneBtn_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\RepoHosting\ForkAndCloneForm.cs:line 308
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Clone new git repository from Github

### Steps to reproduce

Clone repository from GitHub

**Comment by SanteR1** [comment]
Restarting Win or git extensions does not help

**Comment by mstv** [comment]
Line 61 fails on
```
_hotkeySettingsLoader = _uiCommands.GetRequiredService<IHotkeySettingsLoader>();
```
This service is provided once on application startup.

How do you open the Clone dialog?

**Comment by mstv** [comment]
How do you open the Clone dialog?
Which protocol do you use?
How do you enter credentials?
@SanteR1, @Cabrill

**Comment by SanteR1** [comment]
@mstv 

![image](https://github.com/user-attachments/assets/dd7481c8-933c-47ea-8af9-80a868538738)
![image](https://github.com/user-attachments/assets/17e3b0f2-2d57-4545-b49e-668c0da344e5)

**Comment by mstv** [comment]
Thank you for the details.
(I guess the GitHub plugin's settings are not used when cloning.)
I can clone GH repos in all ways.

You could try to open an existing repo (or create a local temporary one) and clone then using the main menu entry.

![image](https://github.com/user-attachments/assets/764e9046-b6ec-4496-af89-47230678aea3)

**Comment by RussKie** [comment]
It looks like it's happening when one tries to clone a repo using this dialog:
![image](https://github.com/user-attachments/assets/3cb1e20b-da62-49ec-bdb8-2c78abcda4b3)

**Comment by intelliflo-snimalan** [comment]
Same here.
![image](https://github.com/user-attachments/assets/b913f406-bd85-45d6-b1c9-1caf55527337)

This is the version I am running:
![image](https://github.com/user-attachments/assets/41148213-8ffd-4173-98fa-cab58317f7e9)

**Comment by vbjay** [comment]
Do you see the copy button in that about dialog? Click it and paste in a comment. That icon is the standard copy icon.

**Comment by pmiossec** [comment]
> Same here. 

@intelliflo-snimalan PR  #11927 should fix the issue but has still not been merged. You could test the fix.

**Comment by Vic152** [comment]
same here

**Comment by emilnechifor** [comment]
same issue here

**Comment by arkoak** [comment]
can be bypassed by using start > clone repository > type in the url of the repo 

(instead of selecting from the list fetched from github)
