### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'input')

### ISSUE THREAD

**Issue by BalazsNagyNET** [gitextensions/gitextensions#11902]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.ParseUserInputs(String scriptName, String arguments, IGitUICommands uiCommands, IWin32Window owner, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 46
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScriptInternal(ScriptInfo script, IWin32Window owner, IGitUICommands uiCommands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 133
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScript(ScriptInfo script, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 32
   at GitUI.ScriptsEngine.ScriptsManager.RunScript(ScriptInfo scriptInfo, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.cs:line 71
   at GitUI.GitModuleControl.<ExecuteCommand>g__ExecuteScriptCommand|20_0(<>c__DisplayClass20_0&) in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 144
   at GitUI.GitModuleControl.ExecuteCommand(Int32 command) in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 132
   at GitUI.RevisionGridControl.ExecuteCommand(Int32 cmd) in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 3228
   at ResourceManager.GitExtensionsControl.ProcessHotkey(Keys keyData) in C:\projects\gitextensions\src\app\ResourceManager\GitExtensionsControl.cs:line 59
   at GitUI.RevisionGridControl.ProcessHotkey(Keys keyData) in C:\projects\gitextensions\src\app\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 838
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData) in C:\projects\gitextensions\src\app\ResourceManager\GitExtensionsControl.cs:line 94
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& message)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

Cause: Pressing ctrl+shift+down shortcut set for script Fetch prune

### Steps to reproduce

Setup ctrl+shift+down for Fetch prune script and try to use it.

**Comment by pmiossec** [comment]
(Seems) duplicate of #11892. Fixed by #11893

You could test the portable version to confirm if issue is fixed: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50564009/artifacts

Ask for reopen if it's not the case.
