### ISSUE TITLE
[NBug] Only TrueType fonts are supported. This is not a TrueType f...

### ISSUE THREAD

**Issue by chrisfindlayST** [gitextensions/gitextensions#11919]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentException: Only TrueType fonts are supported. This is not a TrueType font.
   at System.Drawing.Font.FromLogFont(LOGFONT& logFont, IntPtr hdc)
   at System.Windows.Forms.FontDialog.UpdateFont(LOGFONT& lf)
   at System.Windows.Forms.FontDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.AppearanceFontsSettingsPage.diffFontChangeButton_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Pages\AppearanceFontsSettingsPage.cs:line 52
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

This font always used to work in previous versions of GitExtensions!

$ file GufDina*
GufDinaTranslated.ttf:     TrueType Font data, 13 tables, 1st "FFTM", 14 names, Macintosh
GufDinaTranslatedBold.ttf: TrueType Font data, digitally signed, 14 tables, 1st "DSIG", 14 names, Macintosh, Generated by fontforge, http://fontforge.sourceforge.netGufDinaTranslatedBoldFontForge : GufDina
[fonts.zip](https://github.com/user-attachments/files/17007651/fonts.zip)

### Steps to reproduce

Configuring fonts as per my other machine - same font, different error.

### Did this work in previous version of GitExtensions?

Yes

**Comment by RussKie** [comment]
This is the Windows Forms/Windows error, so there's nothing the app can do about  this.

**Comment by chrisfindlayST** [comment]
The previous version worked fine with this font, and on my other machine, configured to use this font, when it upgraded it still worked!

**Comment by chrisfindlayST** [comment]
Do I just have to hack the config or something..?

**Comment by chrisfindlayST** [comment]
...copied config from old machine and it still works with this font, so this is a bug as that font is fine.

**Comment by RussKie** [comment]
If you provide a diff of your configs, this could shed some light on this
issue.

**Comment by chrisfindlayST** [comment]
There is no diff now - I was trying to select the font I used in v4 and it didn't let me - font attached above.  Yet my other machine had it configured, then upgraded to 5 and kept the setting.  Everything works fine with the font except for being unable to select it in v5, but if I copy over the config from the one that upgraded to this machine it's working fine with my font there too.
