### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by fcabrerab2** [gitextensions/gitextensions#11928]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsControls() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 20
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.Init(IGitPlugin gitPlugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 36
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsPageFromPlugin(ISettingsPageHost pageHost, IGitPlugin gitPlugin, IServiceProvider serviceProvider) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 42
   at GitUI.CommandsDialogs.FormSettings.<OnRuntimeLoad>b__18_1(IGitPlugin plugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 174
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at GitUI.CommandsDialogs.FormSettings.OnRuntimeLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 177
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\GitExtensionsForm.cs:line 71
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

changed to high contrast dark theme, restarted the app, then this happened.

### Steps to reproduce

Set high contrast dark theme and restart.

### Did this work in previous version of GitExtensions?

idk

**Comment by gerhardol** [comment]
Just beware: To use this theme, you need to set dark high contrast mode in Windows too

**Comment by gerhardol** [comment]
A plugin failed to load the settingspage, I cannot see how that is related to the theme.

**Comment by RussKie** [comment]
Do you have custom plugins installed (i.e., those not shipped with the app)? If so, are those up to date and compatible with v5.x?

**Comment by fcabrerab2** [comment]
No custom plugins installed.

**Comment by mstv** [comment]
We hope to have fixed this in v7.0.0.
