### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by maryokk** [gitextensions/gitextensions#11935]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsControls() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 20
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.Init(IGitPlugin gitPlugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 36
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsPageFromPlugin(ISettingsPageHost pageHost, IGitPlugin gitPlugin, IServiceProvider serviceProvider) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 42
   at GitUI.CommandsDialogs.FormSettings.<OnRuntimeLoad>b__18_1(IGitPlugin plugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 174
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at GitUI.CommandsDialogs.FormSettings.OnRuntimeLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 177
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\GitExtensionsForm.cs:line 71
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

I was simply going to: Tools/Settings

### Steps to reproduce

1- Start the app
2- goto Tools/Settings

**Comment by gerhardol** [comment]
Duplicate of #11928 
A plugin fails to load its settings page

**Comment by pmiossec** [comment]
Has the v5 of GitExtensions installed on a previous version? i.e. is there remaining old v4 plugins inside application folder?

Or do you have installed a custom plugin (through the plugin manager) that could be not compatible?

Because, if I understand well the code, the loading from the file settings will be done later and the code is failing while GE is creating the setting page based on plugin settings declaration (even if it is not clear which part is failing... stacktrace is not really helpful where is the NRE exactly!). So I expect the behavior be deterministic (as the settings value are still not used) and no crash should be expected if loading only the plugins bundled with GE...

**Comment by maryokk** [comment]
Yes the GitExtensions version V5 was installed on a preinstalled version V4. This Nbug happend only the first gitExtensions start after installation of version 5.

After the upgrade to v5, the installer asked to install/update my .NET framework. Which I did and thereafter started the appllication and when to Tools/settings... and then I got this bug. After restarting the application, I did the same and I went well.

**Comment by RussKie** [comment]
Do you have custom plugins installed (i.e., those not shipped with the app)? If so, are those up to date and compatible with v5.x?

**Comment by mstv** [comment]
We hope to have fixed this in v7.0.0.
