### ISSUE TITLE
[NBug] Git setting 'pull.rebase': failed to convert value 'merges' into type 'System.Boolean'

### ISSUE THREAD

**Issue by Ririshi** [gitextensions/gitextensions#11939]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
GitExtensions.Extensibility.Settings.GitConfigFormatException: Git setting 'pull.rebase': failed to convert value 'merges' into type 'System.Boolean'
   at GitCommands.Settings.ConfigFileSettings.ConvertValue[T](String value, String setting) in C:\projects\gitextensions\src\app\GitCommands\Settings\ConfigFileSettings.cs:line 103
   at GitCommands.Settings.ConfigFileSettings.GetValue[T](String setting) in C:\projects\gitextensions\src\app\GitCommands\Settings\ConfigFileSettings.cs:line 86
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigAdvancedSettingsPage.SettingsToPage() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Pages\GitConfigAdvancedSettingsPage.cs:line 44
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 103
   at GitUI.CommandsDialogs.FormSettings.LoadSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 69
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 275
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

I have pull.rebase set to 'merges', but when I opened the settings interface, I got this exception.

### Steps to reproduce

Manually set pull.rebase=merges in git config file.
Open repository where this config file is in effect in Git Extensions.
Open Tools -> Settings.

### Did this work in previous version of GitExtensions?

I don't know, I just changed the setting in my gitconfig file a day or two ago.

**Comment by NatRavenhill** [comment]
I have reproduced this locally. The setting that corresponds to pull.rebase is a tickbox and parses the input on an assumption that the only possible values are true and false:
![image](https://github.com/user-attachments/assets/68ebf726-158e-47f4-b4af-cc940d0976bd)



According to the docs, 'interactive' is an acceptable setting, in addition to 'merges'. So currently both of these config values are not supported, and will cause an exception:
![image](https://github.com/user-attachments/assets/45f63a1d-f273-4bb2-bed7-70ec392fef82)

**Comment by mstv** [comment]
Should we replace the CheckBox with a ComboBox? Or would it suffice to map all non-boolean values to `CheckState.Indeterminate`?

"setting not set" is not visible on this settings page.

**Comment by gerhardol** [comment]
CheckState.Indeterminate should be enough, set merges/interactive from commandline
Same for other settings, even if only pull is special
