### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by iseliweb** [gitextensions/gitextensions#11936]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 255
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout -- "Deployment/Scripts/Decommissioning/leftCountries.txt" "Deployment/Scripts/Decommissioning/unpublishCountries.txt"
Working directory: C:\Workspace\Sika\Management\

```
GitExtensions.Extensibility.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\src\app\GitCommands\Git\ExecutableExtensions.cs:line 338
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\src\app\GitCommands\Git\ExecutableExtensions.cs:line 268
   at GitCommands.ExecutableExtensions.RunBatchCommand(IExecutable executable, ICollection`1 batchArguments, Action`1 action, Action`1 writeInput) in C:\projects\gitextensions\src\app\GitCommands\Git\ExecutableExtensions.cs:line 200
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force) in C:\projects\gitextensions\src\app\GitCommands\Git\GitModule.cs:line 1497
   at GitCommands.GitModule.ResetChanges(ObjectId resetId, IReadOnlyList`1 selectedItems, Boolean resetAndDelete, IFullPathResolver fullPathResolver, StringBuilder& output, Action`1 progressAction) in C:\projects\gitextensions\src\app\GitCommands\Git\GitModule.cs:line 1429
   at GitUI.CommandsDialogs.FormCommit.ResetFilesClick(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormCommit.cs:line 2135
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

Wanted to reset file changes. Git already updated from 2.64 to 2.64.2 but with no success.

### Steps to reproduce

1. Make a change to an already tracked txt file.
2. Open commit window
3. Mark txt file, right click, revert file changes

### Did this work in previous version of GitExtensions?

Yes, v4.2.1

**Comment by mstv** [comment]
Has your editor locked the file?

What is the output if you manually run the command (to be copied from Git Command Log `F12`).

**Comment by iseliweb** [comment]
Crazy, I've closed all editors, tried the command via git bash and it didn't work. Today it worked again. I guess there was indeed a lock somewhere that was only released after reboot. I'm going to close the ticket. Thanks anyway!
