### ISSUE TITLE
[NBug] SplitterDistance must be between Panel1MinSize and Width - ...

### ISSUE THREAD

**Issue by gergelyurbancsik** [gitextensions/gitextensions#11933]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.32.0.windows.1 (recommended: 2.42.0 or later)
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.33
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at GitUI.CommandsDialogs.FormBrowse.SetSplitterPositions() in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2242
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 479
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 106
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 571
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

The git extension tool crash after start

### Steps to reproduce

just start the git extension tool

**Comment by mstv** [comment]
This should have been handled in v5.0.0.
