### ISSUE TITLE
[NBug] Value cannot be null. (Parameter 'input') - Running custom script

### ISSUE THREAD

**Issue by michael-wolfenden** [gitextensions/gitextensions#11968]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.ParseUserInputs(String scriptName, String arguments, IGitUICommands uiCommands, IWin32Window owner, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 46
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScriptInternal(ScriptInfo script, IWin32Window owner, IGitUICommands uiCommands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 133
   at GitUI.ScriptsEngine.ScriptsManager.ScriptRunner.RunScript(ScriptInfo script, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.ScriptRunner.cs:line 32
   at GitUI.ScriptsEngine.ScriptsManager.RunScript(ScriptInfo scriptInfo, IWin32Window owner, IGitUICommands commands, IScriptOptionsProvider scriptOptionsProvider) in C:\projects\gitextensions\src\app\GitUI\ScriptsEngine\ScriptsManager.cs:line 71
   at GitUI.GitModuleControl.<ExecuteCommand>g__ExecuteScriptCommand|20_0(<>c__DisplayClass20_0&) in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 144
   at GitUI.GitModuleControl.ExecuteCommand(Int32 command) in C:\projects\gitextensions\src\app\GitUI\GitModuleControl.cs:line 132
   at GitUI.LeftPanel.RepoObjectsTree.ExecuteCommand(Int32 cmd) in C:\projects\gitextensions\src\app\GitUI\LeftPanel\RepoObjectsTree.cs:line 592
   at System.Windows.Forms.BindableComponent.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

I have a script called Cleanup the runs the following command:
`npx  -y git-removed-branches@latest --prune --force`

![Image](https://github.com/user-attachments/assets/e0f3dbf8-dc99-4182-a122-c6e90322aa2f)

Right clicking on a branch -> Run script -> Cleanup causes this issue.

![Image](https://github.com/user-attachments/assets/d1e9277c-8605-4853-8584-78ebd8cd8ce0)

This was working in previous version however I'm unsure of which one as I update regularly

### Steps to reproduce

As above

### Did this work in previous version of GitExtensions?

As above

### Diagnostics

As above

**Comment by RussKie** [comment]
The arguments aren't supplied.
This was fixed in #11893
