### ISSUE TITLE
[NBug] error: the following file has staged content different from...

### ISSUE THREAD

**Issue by oliver-winter-plockcontrol** [gitextensions/gitextensions#11973]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: rm --cached "Model"
Working directory: D:\source\PlockVerse\

```
GitExtensions.Extensibility.ExternalOperationException: error: the following file has staged content different from both the
file and the HEAD:
    Model
(use -f to force removal)
 ---> System.Exception: error: the following file has staged content different from both the
file and the HEAD:
    Model
(use -f to force removal)
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.RunCommandAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\src\app\GitCommands\Git\ExecutableExtensions.cs:line 238
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow) in C:\projects\gitextensions\src\app\GitCommands\Git\ExecutableExtensions.cs:line 171
   at GitCommands.GitModule.UnstageFile(String file) in C:\projects\gitextensions\src\app\GitCommands\Git\GitModule.cs:line 2845
   at GitUI.CommandsDialogs.FormSubmodules.RemoveSubmoduleClick(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSubmodules.cs:line 156
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Steps to reproduce

1. Copy the submodule folder. 
2. Make changes there. (commit/pull)
3. Try to remove the "old" submodule.

**Comment by RussKie** [comment]
You were trying to do something rather unusual, and that upset git. The app runs git commands and informs you, if there were any errors. 

```
> C:\Program Files\Git\bin\git.exe rm --cached "Model"

error: the following file has staged content different from both the
file and the HEAD:
    Model
(use -f to force removal)
```

In the older versions (before v4.0, I think) not all errors were shown to the user, and now the app hides significantly less, thus, allowing the user to react and resolve issues manually.
