### ISSUE TITLE
[NBug] error: the branch 'ToBeDeleted' is not fully merged.If you...

### ISSUE THREAD

**Issue by Dirksche** [gitextensions/gitextensions#11975]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.30
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: branch -d ToBeDeleted
Working directory: D:\git\PE-S3000-WaWi-Sourcen\

```
GitExtUtils.ExternalOperationException: error: the branch 'ToBeDeleted' is not fully merged.
If you are sure you want to delete it, run 'git branch -D ToBeDeleted'
 ---> System.Exception: error: the branch 'ToBeDeleted' is not fully merged.
If you are sure you want to delete it, run 'git branch -D ToBeDeleted'
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 147
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitExtensions.Plugins.DeleteUnusedBranches.DeleteUnusedBranchesForm.<>c__DisplayClass27_0.<<Delete_Click>b__2>d.MoveNext() in C:\projects\gitextensions\Plugins\DeleteUnusedBranches\DeleteUnusedBranchesForm.cs:line 212
```

I was using the "Delete obsolete branches" plugin, git an error that the branch has not been fully merged und pressed on "View details".

### Steps to reproduce

Cannot remember.

**Comment by pmiossec** [comment]
Fixed by  #11937
