### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kensanata** [gitextensions/gitextensions#11990]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 144dpi (150% scaling)
- Portable: False

Possibly related to #11928 and #11935, both of which involve the Settings dialogue.

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.SettingsDialog.Pages.FormBrowseRepoSettingsPage.PageToSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Pages\FormBrowseRepoSettingsPage.cs:line 32
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\SettingsPageBase.cs:line 110
   at GitUI.CommandsDialogs.FormSettings.Save() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 233
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 324
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

I was looking at Settings / Advanced and checked "Push force with lease when …" and pressed Cancel. Then I opened Settings / Advanced again, checked the checkbox again and pressed Apply.

### Steps to reproduce

1. Open Git Extensions
2. Open a recent repository
3. Click on the cog wheel icon to go to settings
4. Click OK

**Comment by kensanata** [comment]
I'm not sure exactly what that fix involves. I guessed that perhaps some value is undefined and so I started GitExtensions, clicked the cog wheel, clicked Advanced, and toggled every checkbox twice (resulting in no visible changes but maybe setting any null values). When I clicked OK, the problem was still there. If there is any thing else I can do to narrow it down, let me know. Clicking on all the checkboxes in all the setting panes would be a lot of clicking, however. 😄

**Comment by mstv** [comment]
It looks like no shells are found on your machine, or else none of them is selected.

**Comment by RussKie** [comment]
Does the issue repro consistently? If so, could you share your app configs?

**Comment by kensanata** [comment]
Thanks! I tried that and still missed it. 🙈 

In any case, you are correct: currently there is no shell set (see below).

**Setting that to "bash" fixed my problem!**

 Thanks.

![Image](https://github.com/user-attachments/assets/ef1eba5c-f910-49d3-a530-65956dce5cf5)

**Comment by RussKie** [comment]
Is the issue resolved?

**Comment by kensanata** [comment]
Setting the default shell fixed the immediate error I was getting.

I still think that the crash is a bug if the shell is not set.

I also don’t know how it was possible to get into a situation with no shell. Since bash comes with Git Extensions, it should not be possible to have an empty value for this setting.
