### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Reflection.Emit.Lig...

### ISSUE THREAD

**Issue by rinkmi1** [gitextensions/gitextensions#12039]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Emit.Lightweight, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'System.Reflection.Emit.Lightweight, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode(String pattern, RegexTree regexTree, RegexOptions options, Boolean hasTimeout)
   at System.Text.RegularExpressions.Regex.Compile(String pattern, RegexTree regexTree, RegexOptions options, Boolean hasTimeout)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.ParseRegexes()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetRegexForExtension(String extension)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(CancellationToken cancellationToken)
   at GitUI.SpellChecker.EditNetSpell.<>c__DisplayClass109_0.<<InitializeAutoCompleteWordsTask>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ThreadingTools.WithCancellationSlow[T](Task`1 task, CancellationToken cancellationToken)
   at GitUI.SpellChecker.EditNetSpell.<>c__DisplayClass73_0.<<ToggleAutoCompletion>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at GitUI.TaskManager.HandleExceptionsAsync(Func`1 asyncAction, Func`2 handleExceptionAsync)
```

tried to commit on a new created feature branch

### Steps to reproduce

- git flow feature start *mybranchname*
- make a change
- make a commit 

### Did this work in previous version of GitExtensions?

Yes

**Comment by mstv** [comment]
It's Windows Update Day.
