### ISSUE TITLE
[NBug] Field not found: 'GitExtensions.Extensibility.Delimiters.Sp...

### ISSUE THREAD

**Issue by Sc0tTyXL** [gitextensions/gitextensions#12047]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.44.0.windows.1 (recommended: 2.46.0 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.MissingFieldException: Field not found: 'GitExtensions.Extensibility.Delimiters.Space'.
   at GitExtensions.Plugins.BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass12_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 732
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 680
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs:line 94
```

### Steps to reproduce

I don't know, wasn't doing anything

**Comment by pmiossec** [comment]
It's related to background fetch feature that you should have enabled. Have a look at the configuration if it happen again...

**Comment by mstv** [comment]
`GitExtensions.Extensibility.Delimiters` was changed between v5.0 and v5.1. Though the BackgroundFetchPlugin is delivered with the main app. I.e. it can hardly become incompatible.
Might the update have failed to update all DLLs?

**Comment by Sc0tTyXL** [comment]
Found the issue!

I use portable mode on my OneDrive as there is no option to used a shared config (or import/export settings for that matter).
Seems there was a conflict on this machine and it had the .dll's of the old version.

Removing those fixed the issue.
