### ISSUE TITLE
InvalidOperationException on "Trust all repositories"

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#12053]
### Environment

- GitExtensions version: v5.1.1

### Issue description

```
System.InvalidOperationException
  HResult=0x80131509
  Message=No service for type 'ResourceManager.IHotkeySettingsLoader' has been registered.
  Source=GitExtUtils
  StackTrace:
   at GitExtUtils.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider) in D:\Build\gitextensions3_dev\src\app\GitExtUtils\ServiceProviderExtensions.cs:line 50
   at GitUI.GitModuleForm.set_UICommands(IGitUICommands value) in D:\Build\gitextensions3_dev\src\app\GitUI\GitModuleForm.cs:line 61
   at GitUI.GitModuleForm..ctor(IGitUICommands commands, Boolean enablePositionRestore) in D:\Build\gitextensions3_dev\src\app\GitUI\GitModuleForm.cs:line 94
   at GitUI.GitModuleForm..ctor(IGitUICommands commands) in D:\Build\gitextensions3_dev\src\app\GitUI\GitModuleForm.cs:line 101
   at GitUI.CommandsDialogs.FormEditor..ctor(IGitUICommands commands, String fileName, Boolean showWarning, Boolean readOnly, Nullable`1 lineNumber) in D:\Build\gitextensions3_dev\src\app\GitUI\CommandsDialogs\FormEditor.cs:line 21
   at GitUI.NBugReports.BugReportInvoker.<>c.<ReportDubiousOwnership>b__9_7(Object _, EventArgs _) in D:\Build\gitextensions3_dev\src\app\GitUI\NBugReports\BugReportInvoker.cs:line 343
   at System.Windows.Forms.TaskDialog.HandleTaskDialogCallback(HWND hWnd, TASKDIALOG_NOTIFICATIONS notification, IntPtr wParam, IntPtr lParam)
```

![Image](https://github.com/user-attachments/assets/4f870275-86ed-45b3-a38a-a5a3e39bb86f)

### Steps to reproduce

- try to open an unsafe repo
- click "Trust all repos"

### Did this work in previous version of GitExtensions?

I hope so. I have never used this editor-based variant of this button (because that generic config has never worked for me and it would be dangerous).

**Comment by RussKie** [comment]
We're passing `EmptyServiceProvider` here, and this leads to the issue.
At the time I changed the code, I couldn't see any obvious needs for a real instance of a service provider, but as this issue shows, there's one.

**Comment by mstv** [comment]
I am not sure whether we should support "Trust all" at all.
I do not like the implementation. A TaskDialog with the warning and a non-default button for copying the command to the clipboard would have needed less and less problematic code.
But I suggest to remove that button.

**Comment by RussKie** [comment]
The suggestion works for me.
