### ISSUE TITLE
[NBug] warning: safe.directory ''*'' not absolute

### ISSUE THREAD

**Issue by bahman59** [gitextensions/gitextensions#12051]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Command: D:\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z -1 --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" 58fa4bc05eb83496ca2f3dee16904ee4a2299b2d

```
GitExtensions.Extensibility.ExternalOperationException: warning: safe.directory ''*'' not absolute

 ---> System.Exception: warning: safe.directory ''*'' not absolute

   --- End of inner exception stack trace ---
   at GitCommands.RevisionReader.GetRevision(String commitHash, Boolean hasNotes, Boolean throwOnError, CancellationToken cancellationToken) in C:\projects\gitextensions\src\app\GitCommands\RevisionReader.cs:line 190
   at GitCommands.GitModule.GetRevision(ObjectId objectId, Boolean shortFormat, Boolean loadRefs) in C:\projects\gitextensions\src\app\GitCommands\Git\GitModule.cs:line 980
   at GitUI.CommandsDialogs.FormCreateBranch.commitPickerSmallControl1_SelectedObjectIdChanged(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormCreateBranch.cs:line 165
   at GitUI.UserControls.CommitPickerSmallControl.SetSelectedCommitHash(String commitHash) in C:\projects\gitextensions\src\app\GitUI\UserControls\CommitPickerSmallControl.cs:line 40
   at GitUI.CommandsDialogs.FormCreateBranch..ctor(IGitUICommands commands, ObjectId objectId, String newBranchNamePrefix) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormCreateBranch.cs:line 45
   at GitUI.GitUICommands.<>c__DisplayClass84_0.<StartCreateBranchDialog>g__Action|0() in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 453
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartCreateBranchDialog(IWin32Window owner, ObjectId objectId, String newBranchNamePrefix) in C:\projects\gitextensions\src\app\GitUI\GitUICommands.cs:line 457
   at GitUI.CommandsDialogs.FormBrowse.CreateBranchToolStripMenuItemClick(Object sender, EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormBrowse.cs:line 1745
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

commnads -> create branch

### Steps to reproduce

try to create branch from commands menu

**Comment by mstv** [comment]
I guess git complains about your `safe.directory` configuration.

What is the output from
`git config --show-origin --get-all safe.directory`
?

Git v2.46.0 works well with just `*`, i.e. without single or double quotes.
I would not fiddle around with "trust all" but trust each repo on first open instead - after thinking twice - using
![Image](https://github.com/user-attachments/assets/53b3d92a-752d-4865-a413-ed118179722d)

**Comment by Aswinkk123** [comment]
Is this a problem for project ❔

**Comment by gerhardol** [comment]
This is Git configuration error, not GE. 
GE presents the error message, the user must set owner or override the Git check.
https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git
