### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ohlidalp** [gitextensions/gitextensions#12079]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsControls() in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 20
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.Init(IGitPlugin gitPlugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 36
   at GitUI.CommandsDialogs.SettingsDialog.Plugins.PluginSettingsPage.CreateSettingsPageFromPlugin(ISettingsPageHost pageHost, IGitPlugin gitPlugin, IServiceProvider serviceProvider) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\SettingsDialog\Plugins\PluginSettingsPage.cs:line 42
   at GitUI.CommandsDialogs.FormSettings.<OnRuntimeLoad>b__18_1(IGitPlugin plugin) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 174
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at GitUI.CommandsDialogs.FormSettings.OnRuntimeLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\FormSettings.cs:line 177
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\src\app\GitUI\GitExtensionsForm.cs:line 71
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

I'm not sure this can be easily reproduced, unfortunately...
The exception happened when I clicked "settings" from the top menu "Tools".
I've had gitexensions open for a while, last action was an attempt to rebase branch on top of another... upon conflict I opened winmerge 2 times, always discarding changes, ultimately giving up and aborting the rebase. Then I went to install KDiff3 because I grew unhappy with Winmerge I was evaluating at the momemnt. after that, I wanted to reconfigure gitext to use kdiff3... boom.

### Steps to reproduce

[2024-11-30_GitExtSettingsException_commandLog.txt](https://github.com/user-attachments/files/17966692/2024-11-30_GitExtSettingsException_commandLog.txt)
I tried to reproduce but I couldn't. This is what I tried:
1. have winmerge configured as difftool/mergetool
2. try rebasing a branch on top of another, run into conflict
3. on the Merge dialog press >Solve conflicts<, 
4. on the ResolveConflicts dialog press Merge
5. in the "no base revision - fallback to 2way merge" click Yes
7. close winmerge; gitextensions pops up "is the conflict resolved?", press No
8. on the Resolveconflicts dialog press Merge again, this time saying No to the fallbackTo2waymerge popup.
9. close winmerge again, press No on the IsTheConflictResolved dialog.
10. in the Resolveconflicts dialog press Reset and confirm the 2 popups.
11. In the Merge dialog press Abort
12. Run KDiff3 installer Kdiff3-64bit-0.9.98-2.exe, selecting "run kdiff3 now", then closing the Merge dialog and the Kdiff3 window immediatelly.
13. switch back to GitExt window, in top menu select Tools/Settings --> boom.

### Did this work in previous version of GitExtensions?

Yes, never got a crash trying to open settings.

**Comment by ohlidalp** [comment]
[2024-11-30_GitExtSettingsException_commandLog.txt.txt](https://github.com/user-attachments/files/17966694/2024-11-30_GitExtSettingsException_commandLog.txt.txt)

Here is my Git Command Log - I captured it after I tried to reproduce the issue and also after I invoked the rebase multiple times simply because I wasn't able to remember correctly the dialog/button names when writing the "steps to reproduce".

**Comment by mstv** [comment]
It is most likely related to outdated plugins.
Does it occur with v5.1.1, too?
