### ISSUE TITLE
[NBug] External program returned non-zero exit code.

### ISSUE THREAD

**Issue by TiborJarosi** [gitextensions/gitextensions#12082]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.36
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote
Working directory: C:\Pixel_projects\TS3\Client.TrainStation3\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 332
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken) in C:\projects\gitextensions\GitCommands\Git\ExecutableExtensions.cs:line 264
   at GitCommands.GitModule.GetRemoteNames() in C:\projects\gitextensions\GitCommands\Git\GitModule.cs:line 2323
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.<>c__DisplayClass15_0.<PopulateRemotes>b__0() in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 409
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.PopulateRemotes(List`1 allRemotes, Boolean enabled) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 416
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.LoadRemotes(Boolean loadDisabled) in C:\projects\gitextensions\GitCommands\Remotes\ConfigFileRemoteSettingsManager.cs:line 206
   at GitUI.CommandsDialogs.FormPull.BindRemotesDropDown(String selectedRemoteName) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPull.cs:line 222
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormPull.cs:line 147
   at GitUI.GitUICommands.<>c__DisplayClass98_0.<StartPullDialogInternal>g__Action|0() in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 610
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 322
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 623
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(Boolean& pullCompleted, IWin32Window owner, String remoteBranch, String remote, PullAction pullAction) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 596
   at GitUI.GitUICommands.StartPullDialogAndPullImmediately(IWin32Window owner, String remoteBranch, String remote, PullAction pullAction) in C:\projects\gitextensions\GitUI\GitUICommands.cs:line 589
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2336
   at GitUI.CommandsDialogs.FormBrowse.ToolStripButtonPullClick(Object sender, EventArgs e) in C:\projects\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2298
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in C:\projects\gitextensions\GitUI\UserControls\ToolStripEx.cs:line 97
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

bwindows lue screen

### Steps to reproduce

windows blue screen

**Comment by mstv** [comment]
Perhaps something got lost in your `.git/config` when your system crashed.

You could run "git remote" on the command line and see what git is complaining about.
