### ISSUE TITLE
[NBug] Form ShowDialog tried to set an ineligible form as its owne...

### ISSUE THREAD

**Issue by b-f-** [gitextensions/gitextensions#12083]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.11
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.ArgumentException: Form ShowDialog tried to set an ineligible form as its owner. Forms cannot own themselves or their owners. (Parameter 'owner')
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at GitUI.CommandsDialogs.Menus.WorkingDirectoryToolStripSplitButton.<OnDropDownShow>b__13_2(Object hs, EventArgs he) in C:\projects\gitextensions\src\app\GitUI\CommandsDialogs\Menus\WorkingDirectoryToolStripSplitButton.cs:line 113
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

from repository dropdown select "Configure this menu"

### Steps to reproduce

From repository dropdown select "Configure this menu..."

### Did this work in previous version of GitExtensions?

unsure, but likely: 3.4.3.9999

**Comment by mstv** [comment]
works on (my) Win10 PCs

**Comment by RussKie** [comment]
I can't replicate the issue either...
