### ISSUE TITLE
[NBug] Ctrl+C pressed or console closed | failed to push to new Gitea Repo

### ISSUE THREAD

**Issue by PSchileffski** [gitextensions/gitextensions#12114]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.33
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

```
System.OperationCanceledException: Ctrl+C pressed or console closed
 ---> GitExtUtils.ExternalOperationException: The host key is not cached for this server:
  gitserver.fritz.box (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
SHA256:67jOYNu...................
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
 ---> System.Exception: The host key is not cached for this server:
  gitserver.fritz.box (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
  ssh-ed25519 255 SHA256:67j0YNuNjacMh0mk/OoTI5lsXHYvfum367kokmgcnqM
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info) ^C
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.Plink.ConnectAsync(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 81
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitUI.Infrastructure.Plink.Connect(String host) in C:\projects\gitextensions\GitUI\Infrastructure\Plink.cs:line 71
   at GitUI.HelperDialogs.FormRemoteProcess.DataReceived(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormRemoteProcess.cs:line 169
   at GitUI.HelperDialogs.FormProcess.DataReceivedCore(Object sender, TextEventArgs e) in C:\projects\gitextensions\GitUI\HelperDialogs\FormProcess.cs:line 218
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.SendAsLines(String output) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 210
   at GitUI.UserControls.ConsoleCommandLineOutputProcessor.AnsiStreamChunkReceived(Object sender, AnsiStreamChunkEventArgs args) in C:\projects\gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs:line 175
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

The host key is not cached for this server:
gitserver.fritz.box (port 22)
You have no guarantee that the server is the computer you
think it is.
The server's ssh-ed25519 key fingerprint is:
ssh-ed25519 255
SHA256:67jOYNu...................
If you trust this host, enter "y" to add the key to Plink's
cache and carry on connecting.
If you want to carry on connecting just once, without adding
the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n, Return cancels connection, i for more info)

### Steps to reproduce

push to a new Gitea repo

**Comment by mstv** [comment]
Most likely, you have closed the console window.
Plink was asking you whether to store the server's SSH key fingerprint. I.e. you should have entered "y".
Did you see the copied output in the process window?
If not, you could try the development build from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/51229751/artifacts.
