### ISSUE TITLE
An error occurred trying to start process ' 'text://gotocommit/bd5d43601cdff807c90c22ec28908c5c186a2578' with working directory 'C:\Windows\system32'. Unknown error (0x80041002)

### ISSUE THREAD

**Issue by i486** [gitextensions/gitextensions#12110]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.2.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET 8.0.11
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.31 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Clicking on any clickable link results in errors like following

`An error occurred trying to start process 'text://gotocommit/bd5d43601cdff807c90c22ec28908c5c186a2578' with working directory 'C:\Windows\system32'. Unknown error (0x80041002)`

![Image](https://github.com/user-attachments/assets/8fd2ed81-6c14-476b-b9b3-19f37cb628a2)

Call Stack

```
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   ls-files -z --unmerged
Working dir: *\lobe-chat\
Process ID:  5380
Started at:  2024-12-23T04:15:03.0007414+08:00
UI Thread?:  True
Duration:    19.563 ms
Exit code:   0
Call stack:  
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, String extraCacheKey, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, String extraCacheKey, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.ExecutableExtensions.<>c__DisplayClass9_0.<Execute>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.InTheMiddleOfConflictedMerge(Boolean throwOnErrorExit)
   at GitUI.UserControls.InteractiveGitActionControl.RefreshGitAction(Boolean checkForConflicts)
   at GitUI.CommandsDialogs.FormBrowse.OnActivate()
   at GitUI.TaskManager.<>c__DisplayClass14_0.<AsyncAction>b__0()
   at GitUI.TaskManager.<>c__DisplayClass19_0.<<InvokeAndForget>b__1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitUI.TaskManager.<>c__DisplayClass19_0.<InvokeAndForget>b__1()
   at GitUI.TaskManager.HandleExceptionsAsync(Func`1 asyncAction, Func`2 handleExceptionAsync)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitUI.TaskManager.HandleExceptionsAsync(Func`1 asyncAction, Func`2 handleExceptionAsync)
   at GitUI.TaskManager.<>c__DisplayClass19_0.<InvokeAndForget>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions, Delegate entrypointOverride)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(Func`1 asyncMethod)
   at GitUI.TaskManager.InvokeAndForget(Control control, Func`1 asyncAction, CancellationToken cancellationToken)
   at GitUI.ThreadHelper.InvokeAndForget(Control control, Func`1 asyncAction, TaskManager taskManager, CancellationToken cancellationToken)
   at GitUI.ThreadHelper.InvokeAndForget(Control control, Action action, TaskManager taskManager, CancellationToken cancellationToken)
   at GitUI.CommandsDialogs.FormBrowse.OnActivated(EventArgs e)
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.NativeWindow.WndProc(Message& m)
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolbarProxyWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at Windows.Win32.PInvoke.<GetMessage>g__LocalExternFunction|10877_0(MSG* lpMsg, HWND hWnd, UInt32 wMsgFilterMin, UInt32 wMsgFilterMax)
   at Windows.Win32.PInvoke.<GetMessage>g__LocalExternFunction|10877_0(MSG* lpMsg, HWND hWnd, UInt32 wMsgFilterMin, UInt32 wMsgFilterMax)
   at Windows.Win32.PInvoke.GetMessage(MSG* lpMsg, HWND hWnd, UInt32 wMsgFilterMin, UInt32 wMsgFilterMax)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

### Steps to reproduce

1. Install Git Extensions on Windows 7
2. Open any repo with Git Extensions.
3. Click around links

### Did this work in previous version of GitExtensions?

Not sure. First time trying GitExtensions.

**Comment by mstv** [comment]
The error message in the title (and the issue description) is different from the one in the screenshot.
The call stack is missing in both cases.

`"//gotocommit"` links should be handled internally by Git Extensions.
The link in the screenshot is truncated: It should have been `"mailto:i@lobehub.com"`.

Perhaps, the RichTextBox control of Win7 does not work well with .NET 8.
Could you test the repo on a recent Windows? Or share the repo?

**Comment by i486** [comment]
> The error message in the title (and the issue description) is different from the one in the screenshot. The call stack is missing in both cases.

I’ve edited issue. The error occurs when clicking on any clickable commit hash links from any repository.  
I enabled the call stack and clicked on the Author, Child, and Parent links, pressing OK on the error dialog after each one.  I’ve attached only a single call stack as they are identical across these actions.

---

> `"//gotocommit"` links should be handled internally by Git Extensions. The link in the screenshot is truncated: It should have been `"mailto:i@lobehub.com"`.

The screenshot is accurate. It reflects exactly what is displayed on my system and matches the behavior shown in the GIF above.

---

> Perhaps, the RichTextBox control of Win7 does not work well with .NET 8. Could you test the repo on a recent Windows? Or share the repo?

That could be the case. I tested the app on Windows 10, and it worked without any issues.
However, I’d really like to use this app on Windows 7, especially since the documentation mentions states:

    Runtime environment | MS Windows 7SP1+ // .NET 8.0 SDK

I’ve also noticed that other .NET 8.x applications run smoothly on my Windows 7 system.

Here’s the repo:
https://github.com/lobehub/lobe-chat

Thank you

**Comment by mstv** [comment]
> I tested the app on Windows 10, and it worked without any issues.
> However, I’d really like to use this app on Windows 7

So, we cannot do much because the error is caused by an incompatibility between libraries of the .NET platform and the Windows UI.
Maybe older releases based on older .NET versions still work.

> the documentation mentions states:

```
Runtime environment | MS Windows 7SP1+ // .NET 8.0 SDK
```

Thank you for reporting. We will update this info.
