### ISSUE TITLE
Git extensions crashed (mono) - GDIPlus.CheckStatus

### ISSUE THREAD

**Issue by timabell** [gitextensions/gitextensions#1213]
Git extensions 2.40 crashed, (I think it was when I hit commit ready to type a message) leaving the following output in the console:

	SendMessage (73400451, 0x431, (nil), (nil))
	X11 Error encountered: 
	  Error: BadAlloc (insufficient resources for operation)
	  Request:     53 (0)
	  Resource ID: 0x4603416
	  Serial:      103705
	  Hwnd:        Hwnd, Mapped:True ClientWindow:0x4603416, WholeWindow:0x4603415, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x460339F, WholeWindow:0x460339E, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x460339D, WholeWindow:0x460339C, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x4603387, WholeWindow:0x4603386, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x4603385, WholeWindow:0x4603384, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x4603383, WholeWindow:0x4603382, Zombie=False, Parent:[Hwnd, Mapped:True ClientWindow:0x4603381, WholeWindow:0x4603380, Zombie=False, Parent:[<null>]]]]]]]
	  Control:     GitUI.ToolStripEx, Name: fileviewerToolbar, Items: 10   at System.Environment.get_StackTrace()
	   at System.Windows.Forms.XplatUIX11.HandleError(IntPtr display, XErrorEvent ByRef error_event)
	   at System.Drawing.GDIPlus.GdipCreateFromXDrawable_linux(IntPtr , IntPtr , IntPtr ByRef )
	   at System.Drawing.Graphics.FromXDrawable(IntPtr drawable, IntPtr display)
	   at System.Drawing.Graphics.FromHwnd(IntPtr hwnd)
	   at System.Windows.Forms.XplatUIX11.GetOffscreenGraphics(System.Object offscreen_drawable)
	   at System.Windows.Forms.XplatUI.GetOffscreenGraphics(System.Object offscreen_drawable)
	   at System.Windows.Forms.Control+DoubleBuffer.Start(System.Windows.Forms.PaintEventArgs pe)
	   at System.Windows.Forms.Control.WmPaint(Message ByRef m)
	   at System.Windows.Forms.Control.WndProc(Message ByRef m)
	   at System.Windows.Forms.ScrollableControl.WndProc(Message ByRef m)
	   at System.Windows.Forms.ToolStrip.WndProc(Message ByRef m)
	   at GitUI.ToolStripEx.WndProc(Message ByRef m)
	   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage(Message ByRef m)
	   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message ByRef m)
	   at System.Windows.Forms.NativeWindow.WndProc(IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam)
	   at System.Windows.Forms.XplatUIX11.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.XplatUI.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context)
	   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
	   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, Boolean showWhenNoChanges)
	   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner)
	   at GitUI.FormBrowse.CommitToolStripMenuItemClick(System.Object sender, System.EventArgs e)
	   at GitUI.FormBrowse.StatusClick(System.Object sender, System.EventArgs e)
	   at System.Windows.Forms.ToolStripItem.OnClick(System.EventArgs e)
	   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs e)
	   at System.Windows.Forms.ToolStripMenuItem.HandleClick(Int32 mouse_clicks, System.EventArgs e)
	   at System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs e, ToolStripItemEventType met)
	   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs mea)
	   at System.Windows.Forms.Control.WmLButtonUp(Message ByRef m)
	   at System.Windows.Forms.Control.WndProc(Message ByRef m)
	   at System.Windows.Forms.ScrollableControl.WndProc(Message ByRef m)
	   at System.Windows.Forms.ToolStrip.WndProc(Message ByRef m)
	   at GitUI.ToolStripEx.WndProc(Message ByRef m)
	   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage(Message ByRef m)
	   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message ByRef m)
	   at System.Windows.Forms.NativeWindow.WndProc(IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam)
	   at System.Windows.Forms.XplatUIX11.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.XplatUI.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context)
	   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
	   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, System.String filter)
	   at GitUI.GitUICommands.StartBrowseDialog(System.String filter)
	   at GitUI.GitUICommands.StartBrowseDialog()
	   at GitExtensions.Program.Main()

	X11 Error encountered: 
	  Error: BadDrawable (invalid Pixmap or Window parameter)
	  Request:     14 (0)
	  Resource ID: 0x46036A6
	  Serial:      103706
	  Hwnd:        <null>
	  Control:     <null>   at System.Environment.get_StackTrace()
	   at System.Windows.Forms.XplatUIX11.HandleError(IntPtr display, XErrorEvent ByRef error_event)
	   at System.Drawing.GDIPlus.GdipCreateFromXDrawable_linux(IntPtr , IntPtr , IntPtr ByRef )
	   at System.Drawing.Graphics.FromXDrawable(IntPtr drawable, IntPtr display)
	   at System.Drawing.Graphics.FromHwnd(IntPtr hwnd)
	   at System.Windows.Forms.XplatUIX11.GetOffscreenGraphics(System.Object offscreen_drawable)
	   at System.Windows.Forms.XplatUI.GetOffscreenGraphics(System.Object offscreen_drawable)
	   at System.Windows.Forms.Control+DoubleBuffer.Start(System.Windows.Forms.PaintEventArgs pe)
	   at System.Windows.Forms.Control.WmPaint(Message ByRef m)
	   at System.Windows.Forms.Control.WndProc(Message ByRef m)
	   at System.Windows.Forms.ScrollableControl.WndProc(Message ByRef m)
	   at System.Windows.Forms.ToolStrip.WndProc(Message ByRef m)
	   at GitUI.ToolStripEx.WndProc(Message ByRef m)
	   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage(Message ByRef m)
	   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message ByRef m)
	   at System.Windows.Forms.NativeWindow.WndProc(IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam)
	   at System.Windows.Forms.XplatUIX11.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.XplatUI.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context)
	   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
	   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, Boolean showWhenNoChanges)
	   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner)
	   at GitUI.FormBrowse.CommitToolStripMenuItemClick(System.Object sender, System.EventArgs e)
	   at GitUI.FormBrowse.StatusClick(System.Object sender, System.EventArgs e)
	   at System.Windows.Forms.ToolStripItem.OnClick(System.EventArgs e)
	   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs e)
	   at System.Windows.Forms.ToolStripMenuItem.HandleClick(Int32 mouse_clicks, System.EventArgs e)
	   at System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs e, ToolStripItemEventType met)
	   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs mea)
	   at System.Windows.Forms.Control.WmLButtonUp(Message ByRef m)
	   at System.Windows.Forms.Control.WndProc(Message ByRef m)
	   at System.Windows.Forms.ScrollableControl.WndProc(Message ByRef m)
	   at System.Windows.Forms.ToolStrip.WndProc(Message ByRef m)
	   at GitUI.ToolStripEx.WndProc(Message ByRef m)
	   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage(Message ByRef m)
	   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message ByRef m)
	   at System.Windows.Forms.NativeWindow.WndProc(IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam)
	   at System.Windows.Forms.XplatUIX11.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.XplatUI.DispatchMessage(MSG ByRef msg)
	   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context)
	   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
	   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, System.String filter)
	   at GitUI.GitUICommands.StartBrowseDialog(System.String filter)
	   at GitUI.GitUICommands.StartBrowseDialog()
	   at GitExtensions.Program.Main()

	System.Exception: Generic Error [GDI+ status: GenericError]
	  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0 
	  at System.Drawing.Graphics.FillRectangle (System.Drawing.Brush brush, Int32 x, Int32 y, Int32 width, Int32 height) [0x00000] in <filename unknown>:0 
	  at System.Drawing.Graphics.FillRectangle (System.Drawing.Brush brush, Rectangle rect) [0x00000] in <filename unknown>:0 
	  at (wrapper remoting-invoke-with-check) System.Drawing.Graphics:FillRectangle (System.Drawing.Brush,System.Drawing.Rectangle)
	  at System.Windows.Forms.Control.PaintControlBackground (System.Windows.Forms.PaintEventArgs pevent) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.OnPaintBackground (System.Windows.Forms.PaintEventArgs pevent) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ScrollableControl.OnPaintBackground (System.Windows.Forms.PaintEventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStrip.OnPaintBackground (System.Windows.Forms.PaintEventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at GitUI.ToolStripEx.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) [0x00000] in <filename unknown>:0 
	System.ObjectDisposedException: The object was used after being disposed.
	  at System.Windows.Forms.Control.CreateHandle () [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Form.CreateHandle () [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.get_Handle () [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.MessageBox+MessageBoxForm..ctor (IWin32Window owner, System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon, Boolean displayHelpButton) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.MessageBox+MessageBoxForm..ctor (IWin32Window owner, System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon) [0x00000] in <filename unknown>:0 
	  at (wrapper remoting-invoke-with-check) System.Windows.Forms.MessageBox/MessageBoxForm:.ctor (System.Windows.Forms.IWin32Window,string,string,System.Windows.Forms.MessageBoxButtons,System.Windows.Forms.MessageBoxIcon)
	  at System.Windows.Forms.MessageBox.Show (IWin32Window owner, System.String text, System.String caption, MessageBoxButtons buttons, MessageBoxIcon icon) [0x00000] in <filename unknown>:0 
	  at GitUI.FormBrowse.Initialize () [0x00000] in <filename unknown>:0 
	  at GitUI.FormBrowse.CommitToolStripMenuItemClick (System.Object sender, System.EventArgs e) [0x00000] in <filename unknown>:0 
	  at GitUI.FormBrowse.StatusClick (System.Object sender, System.EventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStripMenuItem.OnClick (System.EventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStripMenuItem.HandleClick (Int32 mouse_clicks, System.EventArgs e) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, ToolStripItemEventType met) [0x00000] in <filename unknown>:0 
	  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem:FireEvent (System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
	  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at GitUI.ToolStripEx.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x00000] in <filename unknown>:0 
	  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) [0x00000] in <filename unknown>:0

**Comment by wolak** [comment]
Any solutions to this issue on 14.04?

**Comment by KindDragon** [comment]
Cannot reproduce on 16.04 with mono 4.6.1

**Comment by RussKie** [comment]
@githubuser I believe this is a Mono issue - https://github.com/mono/mono/issues/8922 and nothing to do with GE.
