### ISSUE TITLE
Apply patch is crashing

### ISSUE THREAD

**Issue by regnarock** [gitextensions/gitextensions#1962]
I just tried to apply a trivial patch on my local repository through the GitExtensions interface. (version 2.46)

Here is the patch : https://drupal.org/files/views-fix-destination-link-for-ajax-1036962-29.patch (quite trivial as you can see).

I selected the patch then the folder to apply it. Clicked on the "apply" button and... crash.

Now I have the "You are in the middle of a patch apply" popping in red on the bottom-right corner (as usual in those cases). But when I click on it, GE crash again. The same goes for the Commands->Apply Patch menu.

**Comment by astra07** [comment]
The same issue in Git Extensions 2.44, it definitely relates to certain patch!
Please let us know what is the work around of the problem in Git Extensions?
And in what version will be fixed?
Thanks in advance!

Stack trace 
at System.Text.RegularExpressions.Regex.Match(String input)
   at GitCommands.GitModule.AppendQuotedString(String str1, String str2)
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.Initialize()
   at GitUI.FormApplyPatch.EnableButtons()
   at GitUI.GitUICommands.<>c__DisplayClass19.<StartApplyPatchDialog>b__18()
   at GitUI.GitUICommands.DoAction(IWin32Window owner, Boolean requiresValidWorkingDir, GitUIEventHandler preEvent, GitUIPostActionEventHandler postEvent, Func`1 action)
   at GitUI.GitUICommands.StartApplyPatchDialog(IWin32Window owner, String patchFile)
   at GitUI.FormBrowse.RebaseClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.StatusStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
![gitextensions_crash](https://cloud.githubusercontent.com/assets/12020818/7220287/40afcfa8-e6ca-11e4-9d70-96d707c809fa.png)

**Comment by RussKie** [comment]
Is this still an issue with the current version?

**Comment by RussKie** [comment]
Closing due to age.
