### ISSUE TITLE
Error in XML document -- GitExtensions.settings

### ISSUE THREAD

**Issue by ATECoder** [gitextensions/gitextensions#2450]
I reported the following error through the error reporting message box (see details below). The error, which crashes Git Extensions, is caused by a bad value in the settings file under the roaming user folder. 

<b>Workaround:</b> replace the settings file by the settings.backup file.

<b>Thoughts:</b> My thinking is that this failure could be avoided by loading the backup file. Also, it would help if the exception would notify of the offending XML file. Finally, it seems that the cause of the error is in the program using a font-aware edit box for comments, which added some bogus characters to the value due to font changes in the text that was copied from my note taking tool.

I hope the information below will help improve what is already a great program.

Thank you

David

<b>The details are:</b>

This was caused by the following element:
<code>
    <key>
      <string>lastCommitMessage</string>
    </key>
    <value>
      <string>Add the property MultipleSyncContextsExpected to the the property changed event handler.
&#xC;</string>
    </value>
</code>

Changing the value to 
<code>
      <string>Add the property MultipleSyncContextsExpected to the the property changed event handler.</string>
</code>

fixes this problem allowing Git Extensions to open.

This comment, which was pasted into the comment section from my note taking application (Tree Pad), looks like this:

```
Add the property MultipleSyncContextsExpected to the the property changed event handler.
```

I noticed the the comment section in Git Extension is font-aware -- possibly, the offending text is appended to the value in the course of converting the formatted text to non-formatted text.

```
There is an error in XML document (336, 4).
Target SIte:
System.Object Deserialize(System.Xml.XmlReader, System.String, System.Xml.Serialization.XmlDeserializationEvents) @ System.Xml.Serialization.XmlSerializer
Inner
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
   at GitCommands.XmlSerializableDictionary`2.ReadXml(XmlReader reader)
   at GitCommands.Settings.GitExtSettingsCache.ReadSettings(String fileName)
   at GitCommands.Settings.FileSettingsCache.LoadImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass1.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.<>c__DisplayClass1.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.<>c__DisplayClass15`1.<TryGetValue>b__14()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitUI.Lemmings.GetPictureBoxImage(DateTime currentDate)
   at GitUI.FormSplash..ctor()
   at GitExtensions.Program.Main()

HResult
-2146233079
```

**Comment by OomEttie** [comment]
My GitExtensions also didn't want to open at all. 
Error as stated above.
Just had to remove the settings file in my user folder and everything came right.

**Comment by jbialobr** [comment]
What version do you use?

**Comment by uga-buga** [comment]
Had a problem with the settings XML of GitExtensioins. It is located in %appdata%\GitExtensions\GitExtensions\GitExtensions.settings. The settings XML file seemed corrupted to me, and the settings.backup too. So I deleted both and started GitExtensions. Then some settings needed to be reconfigured but I got everything up and running in minutes.
