### ISSUE TITLE
Path name too long max 256 characters

### ISSUE THREAD

**Issue by rasmuseeg** [gitextensions/gitextensions#2650]
```
website/node_modules/grunt-contrib-less/node_modules/less/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/test/integration/test-delayed-stream-auto-pause.js"): Filename too long
fatal: Unable to process path website/node_modules/grunt-contrib-less/node_modules/less/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream/test/integration/test-delayed-stream-auto-pause.js


   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.<>c__DisplayClass2.<GetAutoCompleteWords>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Unable to delete or remove file git just crashes

**Comment by ghanique** [comment]
That looks like a Windows problem. Doesn't look like it has anything to do
with Git or Git Extensions.

**Comment by KindDragon** [comment]
Windows support paths longer that 260 symbols, but you should handle it in special way

**Comment by ghanique** [comment]
True, in a way. But you cannot use the normal file operations to do that.
Git uses the normal operations and fails with long file paths.

**Comment by KindDragon** [comment]
Msysgit works on supporting long paths as far as i know

**Comment by ghanique** [comment]
You are correct:

https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path

Bottom line: it can be enabled at your own risk.

So, then, is this issue resolved if this setting is enabled?

**Comment by rasmuseeg** [comment]
@ghanique @KindDragon Sorry for the delay. Okay, so know we know this issue is related to a config option. 
But this shouldn't cause the GitExtension client to crash?

**Comment by ghanique** [comment]
Hmm... You're probably right... Then perhaps the >256 chars option in Git
WAS enabled, but Git Extensions itself cannot handle long filenames like
that?

On Wed, Apr 29, 2015 at 8:40 AM, Rasmus Eeg Møller <notifications@github.com

**Comment by swtch3k** [comment]
is there any solution or workaround after two years??

**Comment by KindDragon** [comment]
A workaround is to use short path. You can create hardlink to folder if you want

**Comment by vbjay** [comment]
https://blogs.msdn.microsoft.com/jeremykuhne/2016/06/02/long-paths-in-net/

**Comment by vbjay** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/

**Comment by jporkka** [comment]
So, even if git / gitextensions cannot deal with the long path, gitextensions should not terminate with an exception in this case.

**Comment by RussKie** [comment]
Closing due to age.
Enable long paths support in git and the problem goes away
