### ISSUE TITLE
System.ArgumentNullException when applying commit filter

### ISSUE THREAD

**Issue by lggomez** [gitextensions/gitextensions#2653]
When I try to filter commits (by Commit only) I get a System.ArgumentNullException:

Value cannot be null.
Parameter name: key
Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

Happens in v2.48.03, and could reproduce it in multiple repos

**Comment by gpn39f** [comment]
same error here.. this is new in 2.48.3.. 
it's happens on using filter in menu bar, and in detail filter to.. 
mostly on same time you clicking enter,  sometimes the result is shown, but the error window is open to, without closing the main prog. you can work until the next search..

**Comment by lggomez** [comment]
Debugging 2.49a1 gives the following exception:

System.ObjectDisposedException was unhandled by user code
  HResult=-2146232798
  Message=Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
  Source=System.Net.Http
  ObjectName=System.Net.Http.HttpClient
  StackTrace:
       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
       at TeamCityIntegration.TeamCityAdapter.GetStreamAsync(String restServicePath, CancellationToken cancellationToken) in c:\DEV\gitextensions\Plugins\BuildServerIntegration\TeamCityIntegration\TeamCityAdapter.cs:line 310
       at TeamCityIntegration.TeamCityAdapter.GetStreamFromHttpResponseAsync(Task`1 task, String restServicePath, CancellationToken cancellationToken) in c:\DEV\gitextensions\Plugins\BuildServerIntegration\TeamCityIntegration\TeamCityAdapter.cs:line 346
       at TeamCityIntegration.TeamCityAdapter.<>c__DisplayClass29.<GetStreamAsync>b__28(Task`1 task) in c:\DEV\gitextensions\Plugins\BuildServerIntegration\TeamCityIntegration\TeamCityAdapter.cs:line 312
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
  InnerException:

**Comment by lggomez** [comment]
Update: It seems to be a bug in HttpWebRequest task management, see http://stackoverflow.com/a/15483405 for more details

**Comment by drauch** [comment]
Can confirm this for:

    Value cannot be null.
    Parameter name: key

    Target Site: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d
    Application: GitExtensions.exe [2.48.03]
    CLR: 4.0.30319.34209

Please fix.

**Comment by sadastronaut** [comment]
It appears that whenever I do a search in the filter that will get 0 results, that's when I get the System.ArgumentNullException. If I do a search returning results, GE behaves correctly.

**Comment by KindDragon** [comment]
This should be fixed in 2.48.04
