### ISSUE TITLE
System.IO.DirectoryNotFoundException when opening repository

### ISSUE THREAD

**Issue by Telanor** [gitextensions/gitextensions#2778]
I just reinstalled Git Extensions after restoring windows from a backup and now whenever I open a repository in Git Extensions, I get the following error:

![capture](https://cloud.githubusercontent.com/assets/416698/7103402/58b0b980-e073-11e4-8b6d-252964f6b6e1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/416698/7103403/58b0c768-e073-11e4-92f8-8f146bef7c33.PNG)

The stack trace says:

   at Microsoft.WindowsAPICodePack.Taskbar.ICustomDestinationList.SetAppID(String pszAppID)
   at Microsoft.WindowsAPICodePack.Taskbar.JumpList.Refresh()
   at GitUI.CommandsDialogs.FormBrowse.UpdateJumplist(Boolean validWorkingDir)
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)

I don't know if this is an issue with Git Extensions or something caused by me restoring from a backup.  I tried to find a list of install requirements for Git Extensions but couldn't find any, so I'm not sure what, if anything, I should try reinstalling.  Sorry if this is the wrong place to post this, really not sure where else to post it.

**Comment by Telanor** [comment]
Solved the issue by going into taskbar properties -> start menu -> checking "Store and display recently opened items in the start menu and the taskbar", applying it, then unchecking and applying again.
