### ISSUE TITLE
Clicking on the branch dropdown before selecting a repository triggers a NPE

### ISSUE THREAD

**Issue by tavakolia** [gitextensions/gitextensions#2786]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

When starting GitExtensions, clicking on the branch dropdown before selecting a repository triggers a NPE.

**Comment by valpa** [comment]
The NPE will happen when type something in the Branches text bar. Happens in both 2.48.04 and 2.48


System.NullReferenceException
   at GitUI.FilterBranchHelper.<>c__DisplayClass17.<UpdateBranchFilterItems>b__16(String branch)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GitUI.FilterBranchHelper.UpdateBranchFilterItems()
   at System.Windows.Forms.ToolStripComboBox.OnDropDown(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
n
