### ISSUE TITLE
Jenkins integration on localhost exception

### ISSUE THREAD

**Issue by VSRonin** [gitextensions/gitextensions#2875]
Exception thrown when adding integration with Jenkins. This will prevent the repository to open ever again in GitExtensions.

Step to reproduce:
Settings-> Build server integration -> select Local for current repository -> check both "enable build server integration" and "Show build status summary in revision log" -> select Jenkins from the combobox -> use localhost:8080 as server url and enter a project name (mine has spaces if it matters)

<ul>
<li>Exception: System.UriFormatException</li>
<li>Message: Invalid URI: Invalid port specified.</li>
<li>Target Site: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d</li>
<li>Source: GitUI</li>
<li>Stack Trace:    at GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()</li>
<li>Data["StackTrace0"]:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at JenkinsIntegration.JenkinsAdapter.Initialize(IBuildServerWatcher buildServerWatcher, ISettingsSource config)
   at GitUI.BuildServerIntegration.BuildServerWatcher.GetBuildServerAdapter()
   at GitUI.BuildServerIntegration.BuildServerWatcher.LaunchBuildServerInfoFetchOperation()
   at GitUI.GitUIExtensions.<>c__DisplayClass18.<InvokeSync>b__17(Object s)</li>
<li>HResult: -2146233033</li>
</ul>

**Comment by VSRonin** [comment]
Deleting GitExtensions.settings in the repository makes it possible to open it again
