### ISSUE TITLE
Gitextensions crashes constantly...

### ISSUE THREAD

**Issue by Stoffe** [gitextensions/gitextensions#2975]
For some reason, you have a bug in git extensions, not allowing it to show all lines in a merge.

I have merge conflicts, wich I cannot resolve, because when I press the solve merge conflicts.
Git extensions crashes with the error:

```
Exception: System.InvalidOperationException
Message: No room is available to display rows.
Taget Site: Void set_FirstDisplayedScrollingRowIndex(Int32) @ System.Windows.Forms.DataGridView
Source: System.Windows.Forms
Stack Trace:
  at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
   at GitUI.CommandsDialogs.FormResolveConflicts.Initialize()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
HResult:-2146233079
```

Please try to fix ASAP, since I seriously need this! :)

--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by ghanique** [comment]
Did you somehow resize that window the last time it did work? Perhaps the
dimensions of that window are stored somewhere and the problem goes away if
you can change it?

**Comment by ghanique** [comment]
Can you click the cross of the error window instead of one of the buttons
and resize the merge conflicts window?

**Comment by Stoffe** [comment]
Hmm, thank you for that reply, that actually did the work this time..
But I do think you need to do some errorhandling on this window, since it should not crash because of the window beeing to small (ie the list to small), I think.

**Comment by Stoffe** [comment]
Actually, Ill reopen this issue, since I think you need to add error handling to the window :)

**Comment by ghanique** [comment]
Who is "you"? :-)
