### ISSUE TITLE
ObjectDisposedException thrown after opening FormCommit in VS2013

### ISSUE THREAD

**Issue by idealist1508** [gitextensions/gitextensions#2999]
![ode](https://cloud.githubusercontent.com/assets/4608274/10783569/071ea2a2-7d59-11e5-8d19-538cc9e04076.PNG)
Occurs it to you too?

**Comment by EbenZhang** [comment]
Apparently, the exception occurs when the `AutoCompleteTimer` ticks in after the form was closed/disposed.

Not sure which version you're using. It should work fine for 2.48 and the current master version as someone added code to stop the timers when FormCommit is being closed (see the `CancelAutoComplete` function in d44d70026ee1012cd2b78035f71d749e4a169d17 and 13906615c37ba8d3a40f15d290a622b6f5c0bb68). And it wouldn't be a multiple threading issue because the timers are all UI thread timers which are not running in background.

If it still bothers, you can try stop the timers in the `Dispose` function in class `EditNetSpell`.

```csharp
protected override void Dispose(bool disposing)
{
    if (disposing)
    {
        // add the below three lines to stop the timers.
        AutoCompleteTimer.Stop();
        AutoCompleteToolTipTimer.Stop();
        SpellCheckTimer.Stop();
        _autoCompleteCancellationTokenSource.Dispose();
        _customUnderlines.Dispose();
        if (components != null)
            components.Dispose();
    }
    base.Dispose(disposing);
}
```

**Comment by idealist1508** [comment]
I am on Master e6260298ed35d76836047425c92eedda5c98e359.
I tried your fix and it is better now. I got `UICommands is null` when i try to open FormCommit.
Here is a call stack:
```
at GitUI.GitModuleForm.get_UICommands() in z:\github\sp\gitextensions\GitUI\GitModuleForm.cs:line 20
at GitUI.GitModuleControl.get_UICommands() in z:\github\sp\gitextensions\GitUI\GitModuleControl.cs:line 53
at GitUI.GitModuleControl.get_Module() in z:\github\sp\gitextensions\GitUI\GitModuleControl.cs:line 71
at GitUI.SpellChecker.EditNetSpell.get_Settings() in z:\github\sp\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 224
at GitUI.SpellChecker.EditNetSpell.LoadDictionary() in z:\github\sp\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 271
at GitUI.SpellChecker.EditNetSpell.EditNetSpellLoad(Object sender, EventArgs e) in z:\github\sp\gitextensions\GitUI\SpellChecker\EditNetSpell.cs:line 266
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
at ResourceManager.GitExtensionsControl.OnLoad(EventArgs e) in z:\github\sp\gitextensions\ResourceManager\GitExtensionsUserControl.cs:line 49
at System.Windows.Forms.UserControl.OnCreateControl()
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl()
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.Form.ControlCollection.Add(Control value)
at System.Windows.Forms.Design.ControlDesigner.DesignerControlCollection.Add(Control c)  
 ```
I fix it for me in [EditNetSpell.LoadDictionary()](https://github.com/gitextensions/gitextensions/blob/master/GitUI/SpellChecker/EditNetSpell.cs#L269):

```c#        
private void LoadDictionary()
{
    // Don`t load dictionary in Design-time
    if (Site != null && Site.DesignMode) return;
    ...
}
```
Thanks.

**Comment by EbenZhang** [comment]
Well, I didn't realise you're experiencing problem in **Designer** mode, now it sounds explainable: 

The Designer somehow disposes the `EditNetSpell` without closing the `FormCommit`, hence the `CancelAutoComplete` is not called, then the program crashes when the timer ticks as I analyzed previously.

Do you mind submit a pull request for the fix?

**Comment by idealist1508** [comment]
I've done PR  #3018. I found, that change in `LoadDictionary` was enough to fix this. Should I include changes in `Dispose()` too?

**Comment by EbenZhang** [comment]
I think so, the timer error is just the result/side effect of the loaddictionary error, adding the code in the dispose will be helpful in terms of troubleshioting in the future the editspell throws some other errors that cause the IDE to dispose the control.

Have a try to see if you can call the cancelautocomplete function in the dispose so dont have to duplicate the code.

**Comment by idealist1508** [comment]
Done
