### ISSUE TITLE
ICSharpCode.TextEditor Asserts on Inconsistent Line Endings

### ISSUE THREAD

**Issue by hypersw** [gitextensions/gitextensions#3147]
There would be assertions like this:
```
Found lone \r, data consistency problems?
```
on files with inconsistent line endings, shown as abort-retry-ignore message boxes in an infinite sequence.

This happens if a file either has inconsistent line endings, or a binary file is treated for text diff (e.g by repo settings).

**Comment by hypersw** [comment]
Full message box contents:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Found lone \r, data consistency problems?



   at ICSharpCode.TextEditor.Document.LineManager.NextDelimiter(String text, Int32 offset)

   at ICSharpCode.TextEditor.Document.LineManager.InsertInternal(Int32 offset, String text)

   at ICSharpCode.TextEditor.Document.LineManager.Replace(Int32 offset, Int32 length, String text)

   at ICSharpCode.TextEditor.Document.LineManager.SetContent(String text)

   at ICSharpCode.TextEditor.Document.DefaultDocument.set_TextContent(String value)

   at ICSharpCode.TextEditor.TextEditorControlBase.set_Text(String value)

   at GitUI.Editor.FileViewerInternal.SetText(String text) in w:\ThirdParty\GitExtensions\GitUI\Editor\FileViewerInternal.cs:line 130

   at GitUI.Editor.FileViewer.ViewPatch(String text) in w:\ThirdParty\GitExtensions\GitUI\Editor\FileViewer.cs:line 405

   at GitCommands.AsyncLoader.<>c__DisplayClass11`1.<Load>b__f(Task`1 task) in w:\ThirdParty\GitExtensions\GitCommands\AsyncLoader.cs:line 136

   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

   at System.Delegate.DynamicInvokeImpl(Object[] args)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)

   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)

   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter) in w:\ThirdParty\GitExtensions\GitUI\GitUICommands.cs:line 1497

   at GitUI.GitUICommands.StartBrowseDialog(String filter) in w:\ThirdParty\GitExtensions\GitUI\GitUICommands.cs:line 1506

   at GitUI.GitUICommands.StartBrowseDialog() in w:\ThirdParty\GitExtensions\GitUI\GitUICommands.cs:line 291

   at GitExtensions.Program.Main() in w:\ThirdParty\GitExtensions\GitExtensions\Program.cs:line 118


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by hypersw** [comment]
Where is the `ICSharpCode.TextEditor.dll` file coming from? Seems to be sitting in `Bin` folder in the repo. Were compiled for `Debug` configuration, it appears. I'd recompile for Release, for the starter. And maybe take the newest one.

**Comment by hypersw** [comment]
Found https://github.com/KindDragon/ICSharpCode.TextEditor.
