### ISSUE TITLE
Exception when opening Settings page

### ISSUE THREAD

**Issue by matthewtylerwood** [gitextensions/gitextensions#3200]
When I open Git Extensions on my co-worker's machine and go to the Settings page, it immediately throws the following error. Uninstalling & reinstalling does not fix the issue, and I tried deleting the settings file in AppData, but I still get the error. I am able to load his settings file using Git Extensions on my computer just fine.

GitExtensions.exe [2.48.05]
```
Illegal characters in path.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitUI.CommandsDialogs.SettingsDialog.CheckSettingsLogic.<>c__DisplayClass16.<CheckIfFileIsInPath>b__15(String dir)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at GitUI.CommandsDialogs.SettingsDialog.CheckSettingsLogic.SolveLinuxToolsDir(String possibleNewPath)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.TextBoxBase.set_Text(String value)
   at System.Windows.Forms.TextBox.set_Text(String value)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**Comment by KindDragon** [comment]
I think something wrong with his PATH environment variable https://github.com/gitextensions/gitextensions/blob/v2.48.05/GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs#L179-L185

**Comment by KindDragon** [comment]
It's probably contain illegal characters

**Comment by matthewtylerwood** [comment]
Thanks for the feedback @KindDragon.  I checked his PATH variable and found one path was wrapped in quotation marks (").  After removing these, the settings page opened without issue.

Thanks again for your help!

**Comment by KindDragon** [comment]
@KindDragon We should unquote paths and don't crash in CheckIfFileIsInPath if `PATH` contain invalid path chars

**Comment by jbialobr** [comment]
Duplicates #2924
