### ISSUE TITLE
Crashes when trying to update settings

### ISSUE THREAD

**Issue by benfranklin79** [gitextensions/gitextensions#3228]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

Tools -> Settings -> Try to make some change or no change at all to settings

Then click on OK

Error details:

Exception: System.IO.IOException
Message: This application does not support the current operation on symbolic links.
Target Site: Void WinIOError(Int32, System.String) @ System.IO.__Error
Source: mscorlib
Stack Trace:

 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalReplace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass1.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
HResult: -2147023432

**Comment by vbjay** [comment]
Looks like you have a symbolic link in the path for the settings file.

**Comment by benfranklin79** [comment]
Yep you're right, I've replaced it with a normal file and it's fine now.
