### ISSUE TITLE
Git Extensions crashes as soon as I open my repo

### ISSUE THREAD

**Issue by TimLovellSmith** [gitextensions/gitextensions#3286]
Exception:
System.ComponentModel.Win32Exception
The system cannot find the file specified

Target site:
Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

Call stack:
   at GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()
   at GitUI.GitUIExtensions.<>c__DisplayClass12.<InvokeAsync>b__11(Object s)

**Comment by TimLovellSmith** [comment]
Ugh. Looks like this was caused by me reinstalling git for windows with my VS update 3.
Fixed by reinstalling git extensions.
