### ISSUE TITLE
GitEx does not validate hotkeys

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3699]
1. NPE:

 * Assign "Ctrl+R" to some script.
 * Try to press this hotkey in main window - NPE will be raised.

```
System.NullReferenceException

Void compareToBaseToolStripMenuItem_Click(System.Object, System.EventArgs) @ GitUI.RevisionGrid

   at GitUI.RevisionGrid.compareToBaseToolStripMenuItem_Click(Object sender, EventArgs e)
   at GitUI.RevisionGrid.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

2. Does not check uniqueness of hotkeys:

 * Assign "Ctrl+G" to GitBash
 * Assign "Ctrl+G" to GitGui
 * Assign "Ctrl+G" to some script

All hotkeys will be present. No errors, no warnings.

--- GitExtensions2.49.03, Git 2.11.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by RussKie** [comment]
NRE has been fixed in https://github.com/gitextensions/gitextensions/commit/8098a701832c54b1add9b3a30fca02395d2fa010

**Comment by pravic** [comment]
What is the state of the second problem?

**Comment by gerhardol** [comment]
> What is the state of the second problem?

Not changed
