### ISSUE TITLE
[2.50RC1] Crash after saving settings

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3755]
**Do you want to request a *feature* or report a *bug*?**
bug, crash

**What is the current behavior?**
crash 
Exception: System.ArgumentException
Void ThrowArgumentException(System.ExceptionResource) @ System.ThrowHelper

Stack Trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.Hotkey.HotkeySettingsManager.FillDictionaryWithCommands(Dictionary`2 dict, HotkeySettings[] settings)
   at GitUI.Hotkey.HotkeySettingsManager.MergeIntoDefaultSettings(HotkeySettings[] defaultSettings, HotkeySettings[] loadedSettings)
   at GitUI.Hotkey.HotkeySettingsManager.LoadSettings()
   at GitUI.Hotkey.HotkeySettingsManager.LoadHotkeys(String name)
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands aCommands, String filter)
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands aCommands, String filter, String selectCommit)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, String selectedCommit)
   at GitUI.GitUICommands.StartBrowseDialog()
   at GitExtensions.Program.Main()

Also in other dialogs:
Error: Failed to load plugin JenkinsIntegration.dll
Error: Failed to load plugin TfsIntegration.dll

Complaining about missing "Initialize" method.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Make copy of working installation of GitExtensions v2.49.03
2) Start GitExtensions 
3) Go to settings
4) Save Settings
5) Crash

**What is the expected behavior?**
Don't crash :)

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions v2.50RC1
Windows 7 Pro
Worked is last version.

**Comment by jbialobr** [comment]
>Also in other dialogs:
Error: Failed to load plugin JenkinsIntegration.dll
Error: Failed to load plugin TfsIntegration.dll

Do you want to raise a separete issue for that?

**Comment by jbialobr** [comment]
Fixed version is available: https://github.com/gitextensions/gitextensions/releases/tag/v2.50RC2
