### ISSUE TITLE
Exception shown instead of error message for locked file in commit dialog

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#3759]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
Unsupported file: 

System.IO.IOException: The process cannot access the file 'XYXYpath.csv' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at GitUI.Editor.FileViewer.GetFileText(String fileName)
   at GitCommands.AsyncLoader.<>c__DisplayClass21_0`1.<Load>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<>c__DisplayClass22_0`1.<Load>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a csv file and open it in LibreOffice

**What is the expected behavior?**
Show the contents of the file or show meaningful error message

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Latest, Win10

**Comment by palver123** [comment]
Hi!

Just for the sake of clarity (it took me a while to understand what's the problem) the bug is that instead of showing the content of a locked file (which I believe GitExt has no read rights to) a stacktrace is shown, like this:

![image](https://user-images.githubusercontent.com/12460850/27306642-a583be20-5546-11e7-8194-9a679e4164c9.png)
