### ISSUE TITLE
GitExtensions gives continuous System.ArgumentNullException

### ISSUE THREAD

**Issue by janvangurp** [gitextensions/gitextensions#3806]
Hello,

Today my Git Extensions 2.49.03 (Windows 10) told me there’s a new update: 2.50.00. Installing went fine. Although not asked to restart my computer I did so just to be sure. Now there’s a problem: checking out another branch isn’t possible anymore. I get a "System.ArgumentNullException". Update remote branch info and prune branches works fine.

How can I solve this problem?

Thanks,
Jan

**Comment by RussKie** [comment]
Do you have any stack traces?

**Comment by janvangurp** [comment]
No, I removed 2.50.00 and reinstalled 2.49.03.

**Comment by jbialobr** [comment]
Without the stacktrace there is little we can do. Can you install the 2.50 and provide the callstack for this exception?

**Comment by janvangurp** [comment]
Installed 2.50.00 again and the same error occurs when checking out another branch.

Here's the stack trace:
   at System.Windows.Forms.ComboBox.ObjectCollection.AddInternal(Object item)
   at System.Windows.Forms.ComboBox.ObjectCollection.AddRangeInternal(IList items)
   at System.Windows.Forms.ComboBox.ObjectCollection.AddRange(Object[] items)
   at GitUI.CommandsDialogs.FormCheckoutBranch.PopulateBranches()
   at GitUI.CommandsDialogs.FormCheckoutBranch..ctor(GitUICommands aCommands, String branch, Boolean remote, String[] containRevisons)
   at GitUI.GitUICommands.<>c__DisplayClass297_0.<StartCheckoutBranch>b__0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, GitUIEventHandler preEvent, GitUIPostActionEventHandler postEvent, Func`1 action)
   at GitUI.GitUICommands.StartCheckoutBranch(IWin32Window owner, String branch, Boolean remote, String[] containRevisons)
   at GitUI.CommandsDialogs.FormBrowse.<CurrentBranchDropDownOpening>b__218_0(Object hs, EventArgs he)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
![gitextensions 2 50 error 1](https://user-images.githubusercontent.com/29888825/27829933-5c9272cc-60c4-11e7-810e-0be777114db4.JPG)
![gitextensions 2 50 error 2](https://user-images.githubusercontent.com/29888825/27829932-5c8ea4e4-60c4-11e7-9e55-fad01c8912e4.JPG)

**Comment by jbialobr** [comment]
Can you run `git show-ref --dereference | awk -F " " '{print $2}'` and see if in the output there is anything that does not start with `refs/`?

**Comment by tunlige** [comment]
Same problem, where can I find version 2.49.03

**Comment by vbjay** [comment]
Look at the releases on this site.

**Comment by janvangurp** [comment]
Hi jbialobr,
I run that command. A lot of lines appeared, but every one started with "refs/".

Problem persists.

**Comment by jbialobr** [comment]
Can you try this version?
https://ci.appveyor.com/api/buildjobs/oyhvvonuh8vvmc5c/artifacts/GitExtensions-2.50.00.311-Setup.msi

**Comment by janvangurp** [comment]
I've downloaded GetExtensions 2.50.01 and that works fine.
Thanks!
