### ISSUE TITLE
commit message template file not found in root folder of repo

### ISSUE THREAD

**Issue by janverley** [gitextensions/gitextensions#3897]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
I use a commit message template file.
(idea from http://codeinthehole.com/tips/a-useful-template-for-commit-messages/)

Git Extension shows an Exception dialog when I try to commit.
![screenshot-000022](https://user-images.githubusercontent.com/4922422/29205329-68e9173a-7e7c-11e7-8862-f1c3f96f1d12.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have this line in my .git\config file:
```
[commit]
	template = .gitmessage.txt
```
There is a .gitmessage.txt file in the root of my repository.

**What is the expected behavior?**
When I commit from the cmd line, the file is found at the root of my repository, and listed as a starting point for the commit message in the editor that opens.

Git Extensions should not look in 'C:\Program Files (x86)\GitExtensions\'.
But in the root folder of the repository

**Environment you encounter the issue:**

- GitExtensions version: GitExtensions.exe [2.50.01]
- GIT version: git version 2.13.0.windows.1
- OS version: Win 10 Enterprise

**Did this work in previous version of GitExtensions (which)?**
No idea.

**Comment by RussKie** [comment]
Please post the full stack trace

**Comment by janverley** [comment]
Full callstack:

 ```
  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at GitUI.CommandsDialogs.FormCommit.AssignCommitMessageFromTemplate()
   at GitUI.CommandsDialogs.FormCommit..ctor(GitUICommands aCommands, CommitKind commitKind, GitRevision editedCommit)
   at GitUI.GitUICommands.<>c__DisplayClass323_0.<StartCommitDialog>b__0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, GitUIEventHandler preEvent, GitUIPostActionEventHandler postEvent, Func`1 action)
   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, Boolean showOnlyWhenChanges)
   at GitUI.CommandsDialogs.FormBrowse.StatusClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```


![screenshot-000023](https://user-images.githubusercontent.com/4922422/29216223-35160062-7eae-11e7-82aa-ccdee01beea7.png)
