### ISSUE TITLE
GitExtensions crashes on startup - "There is an error in the XML document"

### ISSUE THREAD

**Issue by Doug0855** [gitextensions/gitextensions#3929]
When opening git extensions version 2.50.01

## The Error/Behavior
Whenever I open git extensions it immediately crashes with 

```
Exception Type: System.InvalidOperationException
Message: "There is an error in the XML document (24,29).
Target Site: System.Object Deserialize(System.Xml.XmlReader, System.String, System.Xml.Serialization.XmlDeserializationEvents) @ System.Xml.Serialization.XmlSerializer
Inner Exception: System.Xml.XmlException
Source: System.XML

Stack Trace: 
at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at GitCommands.XmlSerializableDictionary`2.ReadXml(XmlReader reader)
   at GitCommands.Settings.GitExtSettingsCache.ReadSettings(String fileName)
   at GitCommands.Settings.FileSettingsCache.LoadImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass4_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.<>c__DisplayClass4_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.EnsureSettingsAreUpToDate()
   at GitCommands.SettingsCache.<>c__DisplayClass23_0`1.<TryGetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitCommands.AppSettings.get_IconStyle()
   at GitUI.Lemmings.GetPictureBoxImage(DateTime currentDate)
   at GitUI.FormSplash..ctor()
   at GitUI.FormSplash.ShowSplash()
   at GitExtensions.Program.Main()
```

## What I've tried
-Running as an administrator
-Uninstalling and Reinstalling git extensions

**Comment by vbjay** [comment]
Please search issues.

**Comment by RussKie** [comment]
I'm pretty sure I've seen this issue previously reported, but can't find the original.

Try renaming/deleting:
* C:\Users<username>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings
* C:\Users\<username>\AppData\Local\GitExtensions\*\<version>\user.config (there could be few of these)

**Comment by zxxc** [comment]
I closed 4 windows gitextensions at one time (windows 10) and now 
[GitExtensions.zip](https://github.com/gitextensions/gitextensions/files/1805855/GitExtensions.zip)
GitExtensions.settings truncated
maybe we can restore this settings from backup automatically if on startup this file is corrupted

previously i spend a lot of time digging what causes this problem and how to solve it

**Comment by ioanb7** [comment]
Same issue happening here.

Exception reading XML file "C:\Users\me\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings": '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

Git extensions 3.00.rc2

CLR 4.0.30319.42000

`Void ReadSettings(System.String) @ GitCommands.Settings.GitExtSettingsCache`

inner exception trace:
```
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at GitCommands.XmlSerializableDictionary`2.ReadXml(XmlReader reader)
   at GitCommands.Settings.GitExtSettingsCache.ReadSettings(String fileName)
```

**Comment by RussKie** [comment]
@ioanb7 I can't see how you may be getting an exception: https://github.com/gitextensions/gitextensions/blob/v3.00.00-rc2/GitCommands/Settings/GitExtSettingsCache.cs#L60-L70

We need more information.
