### ISSUE TITLE
Bug: Fatal exception in Microsoft.WindowsAPICodePack.Shell.ShellException

### ISSUE THREAD

**Issue by jakebathman** [gitextensions/gitextensions#3952]
**What is the current behavior?**
When opening the program and selecting a repository from "Recent Repositories", the program crashes. It has also occurred when closing a repository using Edit > Close. 

Crashes show the following dialog and stack trace:

![image](https://user-images.githubusercontent.com/43112/29826731-ae8964fa-8c9d-11e7-90b8-dd98e9ebd280.png)
```
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.UpdateThumbnailButton()
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.set_Enabled(Boolean value)
   at GitUI.CommandsDialogs.FormBrowse.CreateOrUpdateTaskBarButtons(Boolean validRepo)
   at GitUI.CommandsDialogs.FormBrowse.UpdateJumplist(Boolean validWorkingDir)
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<>c__DisplayClass18_0.<InvokeAsync>b__0(Object s)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Here's a video of the problem happening after closing a repository: https://youtu.be/suLcspe8z6Q

And a video of the exception after opening a repository from the dashboard: https://youtu.be/BJhOt7_F3XM

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.8.4.windows.1
- OS version: Windows 10.0.15063 Build 15063

**Did this work in previous version of GitExtensions (which)?**
Everything was fine until yesterday, when I added a few new repos and remotes.

**Comment by gerhardol** [comment]
Cannot reproduce. The buttons are always recreated (in CreateOrUpdateTaskBarButtons()) just above where the enable fails.

**Comment by RussKie** [comment]
The code has been re-worked in v3. Please report back if it is still an issue.
