### ISSUE TITLE
OutOfMemoryException on startup after Changing Commit View Layout

### ISSUE THREAD

**Issue by Togusa09** [gitextensions/gitextensions#3959]
*bug*

Experiencing an out of memory exception on startup, and commit history replaced by a red X

Pressed Ctrl+Shift+L a couple of times, which shrunk the size of each line in the commit window, until I got the out of memory exception and the commit history was replaced with a red X

I'm not completely sure what "Change Commit View Layout" is supposed to do, but I'm assuming it shouldn't make the application crash

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.10.2.windows.1
- OS version: Windows 10 15063.540 (also has a 4k screen)

Unsure

**Comment by vbjay** [comment]
Sure it is. :). There are a few layouts for the revision Grid. Some with
the path of commits and other details shown or not. Try this

Press it once and wait 20 seconds. Then press again. Try doing it faster
and faster untill you get a timing where it crashes. I'm guessing it was
updating and you switched stain and again till it layered update calls and
ran out of memory.

**Comment by Togusa09** [comment]
I upgraded my git version to 2.14.1.64 for windows, which has resolved the issue.

**Comment by Togusa09** [comment]
Actually, no it didn't. Can still crash.

**Comment by Togusa09** [comment]
Upgrading to git 2.14.1. temporarily resolved the problem, but I was able to trigger it again by rapidly switching.

**Comment by RussKie** [comment]
Do you have any stack trace to share?
I've seen it failing because of multitude of gravatar requests...

The develop branch should be more stable, since it was upgraded to .NET 4.6.1, gravatar service has been reworked and some calls are made proper async.

**Comment by Togusa09** [comment]
@RussKie 
Stack trace from the error window:

Exception: System.OutOfMemoryException
Message: Out of memory
Target Site: Void CheckErrorStatus(Int32) @ System.Drawing.Graphics
Source: System.Drawing
Stack Trace:
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at GitUI.RevisionGrid.RevisionsCellPainting(Object sender, DataGridViewCellPaintingEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellPainting(DataGridViewCellPaintingEventArgs e)
   at System.Windows.Forms.DataGridViewCell.PaintWork(Graphics graphics, Rectangle clipBounds, Rectangle cellBounds, Int32 rowIndex, DataGridViewElementStates cellState, DataGridViewCellStyle cellStyle, DataGridViewAdvancedBorderStyle advancedBorderStyle, DataGridViewPaintParts paintParts)
   at System.Windows.Forms.DataGridViewRow.PaintCells(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow, DataGridViewPaintParts paintParts)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
HResult: -2147024882

**Comment by vbjay** [comment]
@russkie. Do you know if with async it is using cancellation tokens?

**Comment by vbjay** [comment]
That definitely looks like gravatar drawing.

**Comment by Togusa09** [comment]
@vbjay Is there an existing issue for the gravatar drawing this can be merged into?

**Comment by RussKie** [comment]
I don't expect us fixing this in 2.50, given that it is unlikely to be an issue in 2.51.
You can try the alpha version and see if you still have issues - https://ci.appveyor.com/api/buildjobs/2ejk2vnao7bhkko1/artifacts/GitExtensions-2.50.01.643-Mono.zip

**Comment by Togusa09** [comment]
@RussKie 
Thanks for the link to the 2.51 version, it resolves the issue. I had to add a copy of System.IO.Abstractions.dll and there's some layout issues, but the out of memory exception no longer occurs.

**Comment by RussKie** [comment]
Good to hear.

The layouts will have to be looked at at some point too.
