### ISSUE TITLE
Crash when "Commit (..)" button is clicked

### ISSUE THREAD

**Issue by b3rnhard** [gitextensions/gitextensions#3960]
I am getting this crash on two machines every time this button is clicked, meaning I can't commit changes anymore. The stack trace is:
```
   at GitUI.SpellChecker.EditNetSpell.UpdateOrShowAutoComplete(Boolean calledByUser)
   at GitUI.SpellChecker.EditNetSpell.TextBox_SelectionChanged(Object sender, EventArgs e)
   at System.Windows.Forms.RichTextBox.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.RichTextBox.WmSelectionChange(SELCHANGE selChange)
   at System.Windows.Forms.RichTextBox.WmReflectNotify(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I tried to find out, what was going on and did a small debug session. It turns out the field `_customUnderlines` of EditNetSpell isn't initialized yet and the lines
```
            if (_customUnderlines.IsImeStartingComposition)
            {
                return;
            }
```
cause a `NullReferenceException`.
My version is `2.50.01`

**Comment by RussKie** [comment]
Please search before raising an issue.
Duplicate of #3827 

You can try the alpha version and see if you still have issues - https://ci.appveyor.com/api/buildjobs/2ejk2vnao7bhkko1/artifacts/GitExtensions-2.50.01.643-Mono.zip

**Comment by b3rnhard** [comment]
I searched for "NullReferenceException" and Spell check. "Commit" was not on my mind for unknown reasons. :)

**Comment by RussKie** [comment]
`EditNetSpell` was the keyword :)
