### ISSUE TITLE
NRE when jira plugin not configured

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3962]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
```
System.NullReferenceException
   at Atlassian.Jira.Remote.JiraRestClient..ctor(ServiceLocator services, String url, String username, String password, JiraRestClientSettings settings) in C:\projects\atlassian-net-sdk\Atlassian.Jira\Remote\JiraRestClient.cs:line 19
   at Atlassian.Jira.Jira.CreateRestClient(String url, String username, String password, JiraRestClientSettings settings) in C:\projects\atlassian-net-sdk\Atlassian.Jira\Jira.cs:line 45
   at JiraCommitHintPlugin.JiraCommitHintPlugin.UpdateJiraSettings() in D:\projekty\GitExt\Plugins\JiraCommitHintPlugin\JiraCommitHintPlugin.cs:line 87
   at JiraCommitHintPlugin.JiraCommitHintPlugin.gitUiCommands_PostSettings(Object sender, GitUIPostActionEventArgs e) in D:\projekty\GitExt\Plugins\JiraCommitHintPlugin\JiraCommitHintPlugin.cs:line 98
   at GitUIPluginInterfaces.GitUIPostActionEventHandler.Invoke(Object sender, GitUIPostActionEventArgs e)
   at GitUI.GitUICommands.InvokePostEvent(IWin32Window ownerForm, Boolean actionDone, GitUIPostActionEventHandler gitUIEventHandler) in D:\projekty\GitExt\GitUI\GitUICommands.cs:line 1675
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, GitUIEventHandler preEvent, GitUIPostActionEventHandler postEvent, Func`1 action) in D:\projekty\GitExt\GitUI\GitUICommands.cs:line 447
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage) in D:\projekty\GitExt\GitUI\GitUICommands.cs:line 1257
   at GitUI.CommandsDialogs.FormBrowse.SettingsClick(Object sender, EventArgs e) in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 1681
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in D:\projekty\GitExt\GitUI\UserControls\ToolStripEx.cs:line 35
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Start GitExt
2. Close GitExt.

**Environment you encounter the issue:**

- GitExtensions version: ae84b49936c0e067d8b6f0208737865d925b6bed

**Comment by RussKie** [comment]
@ierof FYI

**Comment by ierof** [comment]
Yes, i'll fix it
