### ISSUE TITLE
Stage All throws an exception when a single item is selected

### ISSUE THREAD

**Issue by bshafer** [gitextensions/gitextensions#3989]
**What is the issue kind?**

- bug report

**What is the current behavior?**

In the Commit window, clicking on the "Stage All" button can crash the application

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In the Commit window, select one of the unstaged items. Then, click on the double-arrow button to move stage all the files. An exception is thrown. This might only be thrown when there is a sub-module update (not sure), but when I click on the submodule, the diff view shows:

```
Unsupported file:

System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.GetSubmoduleFullPath(String localPath)
   at ResourceManager.LocalizationHelpers.ProcessSubmoduleStatus(GitModule module, GitSubmoduleStatus status)
   at GitUI.Editor.FileViewer.<>c__DisplayClass91_0.<ViewCurrentChanges>b__1()
   at GitCommands.AsyncLoader.<>c__DisplayClass21_0`1.<Load>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<>c__DisplayClass22_0`1.<Load>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**What is the expected behavior?**

All the files should be staged.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: Windows 10 Pro 1703 Build 15063.540

**Did this work in previous version of GitExtensions (which)?**

I know it still crashed in 2.50.01.

**Comment by RussKie** [comment]
It is likely be some kind of environmental issue.

* Does it happen for all repos or for a specific repo only? 
* Does it affect al submdules or only specific ones?
* Can you please check that module folder exists. Also run GE in the problematic submodule.

**Comment by RussKie** [comment]
Closing due to lack of follow up
