### ISSUE TITLE
Commit tab: _commitInformationProvider was null.

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4255]
**Do you want to request a *feature* or report a *bug*?**
regression in master

**What is the current behavior?**
Commit tab raises an exception when first started

```
_commitInformationProvider was null.
System.NullReferenceException
  HResult=0x80004003
  Message=Objektreferensen har inte angetts till en instans av ett objekt.
  Source=GitUI
  StackTrace:
   at GitUI.CommitInfo.CommitInfo.ReloadCommitInfo() in F:\dev\gc\gitextensions_wt2\GitUI\CommitInfo\CommitInfo.cs:line 172
   at GitUI.CommitInfo.CommitInfo.SetRevisionWithChildren(GitRevision revision, List`1 children) in F:\dev\gc\gitextensions_wt2\GitUI\CommitInfo\CommitInfo.cs:line 103
   at GitUI.CommandsDialogs.FormBrowse.FillCommitInfo() in F:\dev\gc\gitextensions_wt2\GitUI\CommandsDialogs\FormBrowse.cs:line 1060
   at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e) in F:\dev\gc\gitextensions_wt2\GitUI\CommandsDialogs\FormBrowse.cs:line 1485
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

![image](https://user-images.githubusercontent.com/6248932/34183115-6fd34f3a-e519-11e7-8433-42d24bdf5d04.png)

Seen especially with #4254
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Normal view of the commit

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
yes, this is a regression, introduced in 8de2dc4c33204d37ceb063fb413d1c7051de90ad (earlier today)

**Comment by RussKie** [comment]
It is actually quite bizarre...
![image](https://user-images.githubusercontent.com/4403806/34193319-36c4700a-e5a7-11e7-864c-98efde1ead91.png)
It claims it is null when it isn't...

**Comment by RussKie** [comment]
I've pushed a fix, please have a look
