### ISSUE TITLE
BuildReport: Exception for WebBrowserCtrl.Navigate

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4322]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
WebBrowserCtrl.Navigate raises exception when displaying the build report in some situations.
This occurred with the current implementation of the Jenkins plugin, I have not seen this with the implementation in #4279.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the Jenkins plugin with several projects, 
This occurred frequently for some time, I have not tried so hard to reproduce, but the workaround is simple.

**What is the expected behavior?**
Catch the exception, the build report should not crash GE.
Also if #4279 is merged, this should be handled.

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
Same in all

**Comment by gerhardol** [comment]
The workaround should be to just wrap the Navigate() call in try-catch, this how the examples I see with this issue are handled.

Maybe some custom changes to the reported exception, mostly master about a month ago. (My patches are hard to find now.)

System.Runtime.InteropServices.COMException

   at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.Navigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.Navigate(String urlString)
   at GitUI.CommandsDialogs.BuildReportTabPageExtension.FillBuildReport(GitRevision revision) in F:\dev\gc\gitextensions\GitUI\CommandsDialogs\BuildReportTabPageExtension.cs:line 61
   at GitUI.CommandsDialogs.BuildReportTabPageExtension.RevisionPropertyChanged(Object sender, PropertyChangedEventArgs e) in F:\dev\gc\gitextensions\GitUI\CommandsDialogs\BuildReportTabPageExtension.cs:line 101
   at GitCommands.GitRevision.OnPropertyChanged(String propertyName) in F:\dev\gc\gitextensions\GitCommands\Git\GitRevision.cs:line 140
   at GitCommands.GitRevision.set_BuildStatus(BuildInfo value) in F:\dev\gc\gitextensions\GitCommands\Git\GitRevision.cs:line 55
   at GitUI.BuildServerIntegration.BuildServerWatcher.OnBuildInfoUpdate(BuildInfo buildInfo) in F:\dev\gc\gitextensions\GitUI\BuildServerIntegration\BuildServerWatcher.cs:line 266
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
