### ISSUE TITLE
2.51: App crashes upon pressing "Script" 

### ISSUE THREAD

**Issue by fan-jiang** [gitextensions/gitextensions#4488]
**Do you want to request a *feature* or report a *bug*?**
A *bug*

**What is the current behavior?**
Git Extension crashes when the "setting - script" is chosen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Install the latest version of 2.51
- Go to menu Tools - > Settings -> Scripts
- Git Extension crashes.
- Uninstall Git Extension.
- Reinstall 2.50.2.
- No crash occurs.

**What is the expected behavior?**
No crash happens.

**Environment you encounter the issue:**
- GitExtensions version: 2.51
- GIT version: 2.15.1.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.50.2,

**Comment by gerhardol** [comment]
Cannot reproduce. What is the exception?

**Comment by BUInvent** [comment]
I also could not reproduce.

**Comment by jbialobr** [comment]
I can reproduce:

System.ArgumentNullException
```
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ScriptsSettingsPage.ResizeBitmap(Bitmap b, Int32 nWidth, Int32 nHeight)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ScriptsSettingsPage.RefreshScriptDetails()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ScriptsSettingsPage.ScriptList_SelectionChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   at System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   at System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by jbialobr** [comment]
`scriptInfo.GetIcon()` returns null which is not properly handled in the `ResizeBitmap` method.
In my case `scriptInfo.GetIcon()` returns null because I have a script that has set an Icon that has been removed (https://github.com/gitextensions/gitextensions/commit/c6703a758a648557bc17ff66150f65ef49213f67#diff-e0a1a1d545050b52dbfa71584e404347)
