### ISSUE TITLE
TaskCanceledException for ShowSelectedFileDiff()

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4570]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Since merge of #4541 I have got occasional exceptions. See also 
https://github.com/gitextensions/gitextensions/pull/4555#issuecomment-370243067

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The behavior is sporadic and has occurred a couple of times on my private builds.
This occurrence was for EbenZhang/LeftBranchTreePanel

The exceprion occurs when switching in a certain timing. I have not been able to reproduce reliably

**What is the expected behavior?**
No exception

**Environment you encounter the issue:**

- GitExtensions version: master, maybe release/2.51
- GIT version: 2.16.2
- OS version: Win10

**Did this work in previous version of GitExtensions (which)?**
yes

**Comment by gerhardol** [comment]
@jbialobr 
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=En uppgift har avbrutits.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.CommandsDialogs.RevisionDiff.<ShowSelectedFileDiff>d__32.MoveNext() in F:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\RevisionDiff.cs:line 268
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.CommandsDialogs.RevisionDiff.<DiffFiles_SelectedIndexChanged>d__33.MoveNext() in F:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\RevisionDiff.cs:line 274

![image](https://user-images.githubusercontent.com/6248932/36951304-58cfb192-2002-11e8-9c80-5ccf3252b3f2.png)
![image](https://user-images.githubusercontent.com/6248932/36951310-6dee16b8-2002-11e8-852c-cc0a57434d68.png)

**Comment by gerhardol** [comment]
A try-catch would be a workaround, especially in the release/2.51 branch

**Comment by vbjay** [comment]
https://channel9.msdn.com/Shows/On-NET/Brandon-Minnick-asyncawait-best-practices

**Comment by gerhardol** [comment]
From what I get from the article, the design is as recommended. There USA an example similar to what is used.

**Comment by vbjay** [comment]
If any cancellations are done, the task code needs to be in a try catch.
