### ISSUE TITLE
Crash when searching for string in commit files filtered by name

### ISSUE THREAD

**Issue by Atria1234** [gitextensions/gitextensions#4764]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Git Extension crashes when I search for a string in filtered commit files.
When I have filtered out only 1 file and try search for non existing string in filtered files:

```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'index'.
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at GitUI.FileStatusList.set_SelectedIndex(Int32 value)
   at GitUI.FileStatusList.SetSelectedIndex(Int32 idx, Boolean notify)
   at GitUI.CommandsDialogs.RevisionDiff.GetNextPatchFile(Boolean searchBackward)
   at GitUI.FindAndReplaceForm.FindNext(Boolean viaF3, Boolean searchBackward, String messageIfNotFound)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Select commit
- Filter commit files so that not all are shown
- Search for some string in filtered files
- When git extension searches in filtered files for next match (and there is not any next match) it tries to search for next match in the list after the last one (index out of bounds exception is thrown)

**What is the expected behavior?**
Git extension checks for number of filtered items (instead of number of all files in commit) and doesn't crash.

**Environment you encounter the issue:**
Windows 7 Enterprise (64 bit) SP 1

- GitExtensions version: 2.51
- GIT version: 2.15.2.windows.2
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
Don't know, probably not

**Comment by GintasS** [comment]
I couldn't replicate this, closing this one. If someone else experience this, please reopen.
