### ISSUE TITLE
Invalid patch header: diff --combined GitUI/CommandsDialogs/FormBrowse.cs

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4827]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

```
   at GitCommands.Patches.PatchProcessor.CreatePatchFromString(String[] lines, Encoding filesContentEncoding, Int32& lineIndex) in C:\d\projekty\gitextensions\GitCommands\Patches\PatchProcessor.cs:line 103
   at GitCommands.Patches.PatchProcessor.<CreatePatchesFromString>d__1.MoveNext() in C:\d\projekty\gitextensions\GitCommands\Patches\PatchProcessor.cs:line 52
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitCommands.GitModule.GetCombinedDiffContent(GitRevision revisionOfMergeCommit, String filePath, String extraArgs, Encoding encoding) in C:\d\projekty\gitextensions\GitCommands\Git\GitModule.cs:line 3876
   at GitUI.CommandsDialogs.RevisionDiff.<ShowSelectedFileDiffAsync>d__35.MoveNext() in C:\d\projekty\gitextensions\GitUI\CommandsDialogs\RevisionDiff.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.FindAndReplaceForm.<FindNextAsync>d__27.MoveNext() in C:\d\projekty\gitextensions\GitUI\Editor\FindAndReplaceForm.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitUI.FindAndReplaceForm.<btnFindNext_Click>d__26.MoveNext() in C:\d\projekty\gitextensions\GitUI\Editor\FindAndReplaceForm.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Fetch jbialobr fork.
2. Select ffdfbaccc8710c2a2d4aebdc65313791ac02a08a in revision grid
3. Go to the Diff tab
4. Select FormBrowse file in the CombinedDiff

- GitExtensions version: 08a69150e35861e9cfc363629b57176afc444352

**Did this work in previous version of GitExtensions (which)?**
Yes: 2.50.02

**Comment by jbialobr** [comment]
Also happens when viewing a diff for a new file in the untracked files sub node of a stash node.
![gitext](https://user-images.githubusercontent.com/1003909/38806767-a7a4b36e-417a-11e8-8277-69385964235f.png)
