### ISSUE TITLE
Changing the selected revision does not change related data.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5202]
**Do you want to request a *feature* or report a *bug*?**
:bug:

**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/43148932-9a9a8826-8f66-11e8-9334-38847af140e6.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open GitExt repo
2. Select 1512100a012bb929b82da61b9d99ffe6129efa2c
3. Select b210331fb67b2362cc1c666ad49911d4666d85e0

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 0776ec902ca743811a7e75d92a02e52fb31090a0

**Comment by drewnoakes** [comment]
I haven't ben able to repro this. Do you know how it happened?

**Comment by drewnoakes** [comment]
I worked out a way to repro it, and I understand the bug. This would actually have been present prior to #5087, for what it's worth. It's just much easier now to experience this due to the ease of toggling layouts.

1. Show commit info at bottom
1. Click diff tab
1. Click revision A
1. Click commit info tab
1. Click revision B
1. Show commit info at right
1. Diff tab shows commit A while commit info panel shows commit B

Clicking another revision should get things back in sync.

@jbialobr does that sound like the bug you observed?

**Comment by jbialobr** [comment]
It does require no additional actions in my case. I updated the repro steps. Since it is not reproducible in your build I will debug it.

**Comment by jbialobr** [comment]
There is an exception thrown inside of FillDiff. The exception is swallowed silently here https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormBrowse.cs#L294
I propose to remove this try-catch at all.
```
System.AggregateException
  HResult=0x80131500
  Message=Wystąpił przynajmniej jeden błąd.
  Source=mscorlib
  Ślad stosu:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GitUI.ThreadHelper.CompletedResult[T](Task`1 task) in D:\projekty\GitExt\GitExtUtils\GitUI\ThreadHelper.cs:line 128
   at GitUI.FileStatusList.AppendItemSubmoduleStatus(String text, GitItemStatus item) in D:\projekty\GitExt\GitUI\UserControls\FileStatusList.cs:line 375
   at GitUI.FileStatusList.UpdateFileStatusListView(Boolean updateCausedByFilter) in D:\projekty\GitExt\GitUI\UserControls\FileStatusList.cs:line 887
   at GitUI.FileStatusList.set_GitItemStatusesWithParents(IReadOnlyList`1 value) in D:\projekty\GitExt\GitUI\UserControls\FileStatusList.cs:line 802
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions) in D:\projekty\GitExt\GitUI\UserControls\FileStatusList.cs:line 1224
   at GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab() in D:\projekty\GitExt\GitUI\CommandsDialogs\RevisionDiffControl.cs:line 142
   at GitUI.CommandsDialogs.FormBrowse.FillDiff() in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 1079
   at GitUI.CommandsDialogs.FormBrowse.<.ctor>b__52_1(Object sender, EventArgs e) in D:\projekty\GitExt\GitUI\CommandsDialogs\FormBrowse.cs:line 285
   at GitUI.RevisionGridControl.<.ctor>b__100_0(Object _, EventArgs e) in D:\projekty\GitExt\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 134
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Wewnętrzny wyjątek 1:
ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: oldCommit
```

![gitext](https://user-images.githubusercontent.com/1003909/43153248-0986a33c-8f71-11e8-9691-bf16adbade16.png)

**Comment by jbialobr** [comment]
The `ParseSubmoduleStatus` is invoked with:
```
		text	"diff --git a/Externals/ICSharpCode.TextEditor b/Externals/ICSharpCode.TextEditor\nnew file mode 160000\nindex 000000000..05321769f\n--- /dev/null\n+++ b/Externals/ICSharpCode.TextEditor\n@@ -0,0 +1 @@\n+Subproject commit 05321769f039f39fa7f6748e8f30d5c8f157c7dc\n"	string
```

**Comment by jbialobr** [comment]
It is resolved in #5203

**Comment by jbialobr** [comment]
Duplicate of #5200

**Comment by drewnoakes** [comment]
Confirming: the scenario I observed is also fixed on master now.
