### ISSUE TITLE
RevisionDataGridView ArgumentException

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5236]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**
```
System.ArgumentException
  HResult=0x80070057
  Message=Parametr jest nieprawidłowy.
  Source=System.Drawing
  Ślad stosu:
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<>c.<.ctor>g__OnRowPrePaint|18_5(Object sender, DataGridViewRowPrePaintEventArgs e) in D:\projekty\GitExt\GitUI\UserControls\RevisionGrid\RevisionDataGridView.cs:line 120
   at System.Windows.Forms.DataGridView.OnRowPrePaint(DataGridViewRowPrePaintEventArgs e)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
```
**Environment you encounter the issue:**

- GitExtensions version: b0666e53e584d29146e0ca6c53e9d564e5de6e58

**Comment by drewnoakes** [comment]
Any chance you can find the value of the `rect` argument passed to `FillRectangle` on `RevisionDataGridView.cs:120`?

**Comment by RussKie** [comment]
Would it be ok to close this now?

**Comment by jbialobr** [comment]
I think so, for I was not able to reproduce it and it seems that the fix is correct.
