### ISSUE TITLE
Unable to launch the app

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5244]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Attempting to launch an app built from 927829d9670cabf7f73bbe90ae417082b126408a located outside a git repository fails

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* build from 927829d9670cabf7f73bbe90ae417082b126408a
* copy to a new folder that doesn't have .git repository, e.g. to D:\GitExtensions
* launch the app
* observe the error: 
![image](https://user-images.githubusercontent.com/4403806/43388190-cf65f90e-942b-11e8-86cc-0e171a673f46.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Unable to parse object ID "fatal: not a git repository (or any of the parent directories): .git".
   at GitUIPluginInterfaces.ObjectId.Parse(String s) in D:\Development\gitextensions\gitextensions\Plugins\GitUIPluginInterfaces\ObjectId.cs:line 172
   at GitCommands.GitModule.GetCurrentCheckout() in D:\Development\gitextensions\gitextensions\GitCommands\Git\GitModule.cs:line 1310
   at GitUI.RevisionGridControl.ForceRefreshRevisions() in D:\Development\gitextensions\gitextensions\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 820
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions() in D:\Development\gitextensions\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 491
   at GitUI.CommandsDialogs.FormBrowse.RefreshButtonClick(Object sender, EventArgs e) in D:\Development\gitextensions\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 1346
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in D:\Development\gitextensions\gitextensions\GitUI\UserControls\ToolStripEx.cs:line 27
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

//* rest is trimmed for brevity *//

```

The error is caused by attempting to parse the error response from git process:
![image](https://user-images.githubusercontent.com/4403806/43388128-ae22e630-942b-11e8-89a7-d42b4d8218e9.png)

**What is the expected behavior?**
normal start without errors

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 927829d9670cabf7f73bbe90ae417082b126408a

**Comment by drewnoakes** [comment]
GE shouldn't be attempting to load revisions when there's not a valid work dir. I'll take a look at this.
