### ISSUE TITLE
Process was not started by this object, so requested information cannot be determined.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5362]
**Do you want to request a *feature* or report a *bug*?**
:bug:

**What is the current behavior?**

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Process was not started by this object, so requested information cannot be determined.
  Source=System
Callstack:
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at GitCommands.Executable.ProcessWrapper.OnProcessExit(Object sender, EventArgs eventArgs) in D:\projekty\GitExt\GitCommands\Git\Executable.cs:line 109
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
```

**Environment you encounter the issue:**

- GitExtensions version: 3172d1c318460f5909a597cdea1d705b942a4ed1

**Comment by jbialobr** [comment]
There is a race condition. 
Thread 1 can pass the `if (_disposed == 0)` (line 107) and then Thread 2 can come into play and call Dispose until the line 191. After that Thread 1 gets resumed and works in the disposed state.

**Comment by RussKie** [comment]
Is it easy to replicate?

**Comment by jbialobr** [comment]
I doubt it - it is a race condition. It happened only once for me.

**Comment by RussKie** [comment]
I observed it just now, though now sure what exactly cause it.
There's a SO answer that may possibly help - https://stackoverflow.com/a/47656845/2338036

**Comment by jbialobr** [comment]
Since `ProcessWrapper` provides `WaitForExitAsync` and is responsible for logging the process' start and end events, I would consider to redesign it a little bit:
1. `ProcessWrapper.Dispose` does not dispose anything unless the process already exited.
2. `ProcessWrapper.Dispose` marks this ProcessWrapper as inoperable.
3. `OnProcessExit` disposes all the ProcessWrapper members if this ProcessWrapper is in a disposed state.

**Comment by jbialobr** [comment]
Interesting, but seems to be the case in the current design as well. See https://referencesource.microsoft.com/#system/services/monitoring/system/diagnosticts/Process.cs,1312

Moreover I see there no call that closes or disposes the standard output, perhaps the process owner is responsible for this.

**Comment by drewnoakes** [comment]
There was a previous PR that fixed lingering processes by ensuring the `System.Diagnostics.Process` object was disposed properly in case of partial reads. It may not be the stream objects themselves, but something internal. It seemed related to having redirected output, however. I can imagine the implementation you link to doesn't dispose the streams in case they have buffered data the consumer hasn't read yet. I think the main thing is that the internal handle is closed, which likely allows the OS to unlink the process's in/out stream handles.

**Comment by jbialobr** [comment]
I will try to reproduce the situation you describe to see what happens. 

I don't like your proposal of swallowing the exceptions because the ExitCode is not reliable due to race conditions. For each case the disposal occurs first, the ExitCode is undefined.

**Comment by jbialobr** [comment]
@drewnoakes Here is my proposal: https://github.com/gitextensions/gitextensions/pull/5388
