### ISSUE TITLE
ArgumentException on scrolling revision grid

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5396]
**Do you want to request a *feature* or report a *bug*?**
:bug:

**What is the current behavior?**
```
 System.ArgumentException
  HResult=0x80070057
  Message=Parametr jest nieprawidłowy.
  Source=System.Drawing
  Ślad stosu:
   at System.Drawing.Graphics.get_Transform()
   at System.Drawing.GraphicsContext..ctor(Graphics g)
   at System.Drawing.Graphics.BeginContainer()
   at GitUI.UserControls.RevisionGrid.Columns.AvatarColumnProvider.OnCellPainting(DataGridViewCellPaintingEventArgs e, GitRevision revision, Int32 rowHeight, ValueTuple`4& style) in C:\d\projekty\GitExt\GitUI\UserControls\RevisionGrid\Columns\AvatarColumnProvider.cs:line 82
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.OnCellPainting(Object sender, DataGridViewCellPaintingEventArgs e) in C:\d\projekty\GitExt\GitUI\UserControls\RevisionGrid\RevisionDataGridView.cs:line 314
   at System.Windows.Forms.DataGridView.OnCellPainting(DataGridViewCellPaintingEventArgs e)
   at System.Windows.Forms.DataGridViewCell.PaintWork(Graphics graphics, Rectangle clipBounds, Rectangle cellBounds, Int32 rowIndex, DataGridViewElementStates cellState, DataGridViewCellStyle cellStyle, DataGridViewAdvancedBorderStyle advancedBorderStyle, DataGridViewPaintParts paintParts)
   at System.Windows.Forms.DataGridViewRow.PaintCells(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow, DataGridViewPaintParts paintParts)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just scrolled the revisions grid on a freshly opened repo.

**Environment you encounter the issue:**

- GitExtensions version: 1a5528cece5ceba1a162e6334d8d77c006e2a3fa

**Comment by jbialobr** [comment]
Looks very similar to https://github.com/gitextensions/gitextensions/issues/5276

**Comment by RussKie** [comment]
Wow you're good at finding weird bugs :)

**Comment by vbjay** [comment]
Lol. We knight him Sir BugFinder

**Comment by jbialobr** [comment]
I don't seek for them, it is they finding me :)

**Comment by RussKie** [comment]
Please have a look at #5545. I haven't observed the bug myself, so I can't really test it.

**Comment by mstv** [comment]
The rendering chain has been revised. If you can still reproduce this or a similar bug, report it anew, please.
