### ISSUE TITLE
Open fails when a recent repository doesn't exists anymore

### ISSUE THREAD

**Issue by ecairo** [gitextensions/gitextensions#5515]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Trying to open after installation and fails.

```
   at GitUIPluginInterfaces.ObjectId.Parse(String s) in C:\Development\gitextensions\Plugins\GitUIPluginInterfaces\ObjectId.cs:line 173
   at GitCommands.GitModule.GetCurrentCheckout() in C:\Development\gitextensions\GitCommands\Git\GitModule.cs:line 1145
   at GitUI.RevisionGridControl.ForceRefreshRevisions() in C:\Development\gitextensions\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 821
   at GitUI.RevisionGridControl.Load() in C:\Development\gitextensions\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 485
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e) in C:\Development\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 453
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

![image](https://user-images.githubusercontent.com/4403806/46572546-202a7e80-c9cb-11e8-9a41-38ac6d1be936.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have previously a Git Extensions installed Version 2*. 
- Configure to open the last working dir
- Close GE
- Remove/rename the last working dir
- Try to open it.
- Fails because is trying to get info from a repository path that doesn't exists anymore.

**Environment you encounter the issue:**
- GitExtensions version: 3.00 Beta
- GIT version: 2.19
- OS version: Windows 10
- .NET version: 4+

**Did this work in previous version of GitExtensions (which)?**
All

**Comment by RussKie** [comment]
Errors? Screenshots?

**Comment by ecairo** [comment]
Sorry I couldn't provide any screen shot, but I uninstalled the application and deleted all Windows registry entries and all the folders in AppData related with GitExtensions then installed again and now is working. Again error was related with a repository path that doesn't exists anymore. Dashboard now has the repo with a warning icon.
