### ISSUE TITLE
Exception opening commit window due to bad WindowPositions.xml

### ISSUE THREAD

**Issue by allsorts46** [gitextensions/gitextensions#5627]
GitExtensions suddenly started failing with an exception dialog every time I clicked 'Commit'. Couldn't think of anything I had recently done to cause it, so tried reinstalling, deleting configuration files, etc.

Discovered that removing AppData\Local\GitExtensions\WindowPositions.xml solved the problem.

Exception was:

```
System.ArgumentException
An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at GitUI.GitExtensionsForm.<RestorePosition>g__FindWindowScreen|9_1(Point location)
   at GitUI.GitExtensionsForm.RestorePosition()
   at GitUI.CommandsDialogs.FormCommit..ctor(GitUICommands commands, CommitKind commitKind, GitRevision editedCommit)
   at GitUI.GitUICommands.<>c__DisplayClass82_0.<StartCommitDialog>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, Boolean showOnlyWhenChanges)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Attaching the 'bad' WindowPositions.xml file (appended .txt extension so GitHub accepts it).

GitExtensions version 3.00.00.01-beta1 on Windows 10 x64

[WindowPositions.xml.txt](https://github.com/gitextensions/gitextensions/files/2517025/WindowPositions.xml.txt)

**Comment by allsorts46** [comment]
Just to add because it might be useful, I often use GitExtensions over RDP. I was using it locally when I first saw the error, but had been using it over RDP earlier in the day.

**Comment by vbjay** [comment]
We may want to check the values for invalid(off the screen) or if an
exception, reset to defaults
