### ISSUE TITLE
System.ArgumentException when loading graph

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5703]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When openeing or refreshing a repo, NBug may popup with the following:
System.ArgumentException
An item with the same key has already been added.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Appears for a certain repo, not general

**What is the expected behavior?**
Load the graph normally

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**
Appeared a few times last weeks in custom builds based on master+misc branches

**Comment by gerhardol** [comment]
System.ArgumentException
An item with the same key has already been added.
 at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraphRow.BuildSegmentLanes()
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.<>c.<CalculateGraphColumnWidth>b__22_2(RevisionGraphRow laneRow)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DefaultIfEmptyIterator>d__93`1.MoveNext()
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.CalculateGraphColumnWidth(VisibleRowRange& range, Int32 currentWidth, Int32 minimumWidth)
   at GitUI.UserControls.RevisionGrid.Columns.RevisionGraphColumnProvider.OnVisibleRowsChanged(VisibleRowRange& range)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.NotifyProvidersVisibleRowRangeChanged()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

**Comment by spdr870** [comment]
Is it possible to share that specific repository?

**Comment by gerhardol** [comment]
> Is it possible to share that specific repository?

Not really. I can try to debug though, late tonight.

**Comment by spdr870** [comment]
There are two possible problems.
Option 1: RevisionGraph.cs, method BuildOrderedRowCache, the same segment is added 2 times to the list. This will result in the error you posted later, in the method BuildSegmentLanes. This is what I suspect
Option 2: There is an error in BuildSegmentLanes.

**Comment by RussKie** [comment]
Looking at the stack trace, the error is in `BuildSegmentLanes`.
We need tests to try to simulate and fix the issue.

**Comment by spdr870** [comment]
I looked over the code and I might have spotted the issue. Could you test this? PR #5706

**Comment by gerhardol** [comment]
fixed in #5706

**Comment by spdr870** [comment]
@RussKie I build a really heavy unit test, that runs with multiple threads a worst case scenario (adding revisions in random order). It proves really useful, since this helps me making it stable. Problem is, its all random. To find multi threading issues, I let this test run for a while. How to handle this? I can make a shorter variant, but its less likely to find a problem.

I did find and solved this bug btw! Searching for the best approach now, to minimize the performance impact of the fix.

**Comment by RussKie** [comment]
Awesome news!

If you think a shorter variant would be useful - let's have it. If not,
let's run the test on demand.

**Comment by spdr870** [comment]
> Awesome news! If you think a shorter variant would be useful - let's have it. If not, let's run the test on demand.

There is a short variant included. It takes under a second to run. Without my fixes, this shot test was enough to trigger the argument exception from the issue.
