### ISSUE TITLE
Crash when pressing F5 while hovering item in dashboard.

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5764]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
GitExtensions crashes when pressing F5 while hovering item in dashboard.

Stack Trace:
```
   at System.Windows.Forms.ListView.GetItemRect(Int32 index, ItemBoundsPortion portion)
   at System.Windows.Forms.ListView.GetItemRect(Int32 index)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.set_HoveredItem(ListViewItem value)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open GE
- Hover with mouse over item in recent items
- Press F5
- Boom

**What is the expected behavior?**
- No crash

**Environment you encounter the issue:**
- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3110.0
- DPI X:100,00% Y:100,00%

**Did this work in previous version of GitExtensions (which)?**

Yes

**Comment by RussKie** [comment]
@NikolayXHD would you be able to have a look at it?

**Comment by NikolayXHD** [comment]
Yes, should be as simple as adding a check `ListView.IsHandleCreated`
