### ISSUE TITLE
Double click in empty TextBox raises ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by bluepanter** [gitextensions/gitextensions#5890]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
On double click into the *empty* commit message text box raises an ArgumentOutOfRangeException
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open Repository -> Click "Commit" -> Double click into the Commit message text box

**What is the expected behavior?**
Do nothing

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
I don't know.

![image](https://user-images.githubusercontent.com/4439101/49834832-a97c7980-fd9d-11e8-9d2a-3a06d65d8a9a.png)

![image](https://user-images.githubusercontent.com/4439101/49834959-0c6e1080-fd9e-11e8-8fb5-8846552d085a.png)

**Comment by gerhardol** [comment]
reproduceable

   at System.Windows.Forms.TextBoxBase.Select(Int32 start, Int32 length)
   at GitUI.SpellChecker.EditNetSpell.TextBox_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
