### ISSUE TITLE
Crash when multiple repositories are closed at once

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#6121]
## Current behaviour

Crashes with exception (settings file already used by other process). 

## Expected behaviour
Does not crash. 

## Steps to reproduce
* Open multiple repositories.
* Right click on taskbar
* Close all windows

## Did this work in previous version of GitExtensions
No. 

## Environment

- GitExtensions version: Version 2.51.05
- GIT version: not relevant
- OS version: win 10
- .NET version: not sure

**Comment by tomasfejfar** [comment]
Right click on the group and close all windows. Just as you write.

**Comment by gerhardol** [comment]
I cannot reproduce. 
Stacktrace?

**Comment by tomasfejfar** [comment]
Yes, sorry. Does not happen every time. But it happens quite often. 

Please not that I have Samsung EVO SSD (e.g. quite fast), i7 2640M (also relatively fast) and Bitlocker full drive cpu encryption (that may be the only thing slowing it down).

**Comment by tomasfejfar** [comment]
I just ancountered this and I send the report. (like 30s ago)

**Comment by RussKie** [comment]
Any stack traces available?

**Comment by gerhardol** [comment]
Nbug is not pushing anywhere need to post manually

**Comment by tomasfejfar** [comment]
@RussKie 

```
System.IO.IOException: The process cannot access the file 'C:\Users\tomasfejfar\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings' because it is being used by another process.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at GitCommands.Settings.GitExtSettingsCache.ReadSettings(String fileName)
   at GitCommands.Settings.FileSettingsCache.LoadImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass4_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.<>c__DisplayClass4_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.EnsureSettingsAreUpToDate()
   at GitCommands.SettingsCache.<>c__DisplayClass23_0`1.<TryGetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitCommands.GitCommandHelpers.SetEnvironmentVariable(Boolean reload)
   at GitCommands.GitCommandHelpers.StartProcess(String fileName, String arguments, String workingDirectory, Encoding outputEncoding)
   at GitCommands.GitCommandHelpers.StartProcessAndReadAllBytes(String arguments, String cmd, String workDir, Byte[]& stdOutput, Byte[]& stdError, Byte[] stdInput)
   at GitCommands.GitCommandHelpers.RunCmdByte(String cmd, String arguments, String workingdir, Byte[] stdInput, Byte[]& output, Byte[]& error)
   at GitCommands.GitModule.RunCmdResult(String cmd, String arguments, Encoding encoding, Byte[] stdInput)
   at GitCommands.GitModule.RunGitCmdResult(String arguments, IEnumerable`1 configValues, Encoding encoding, Byte[] stdInput)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule aModule, RepoDistSettings aLowerPriority, Boolean allowCache)
   at GitCommands.GitModule.get_EffectiveSettings()
   at ResourceManager.GitPluginBase.Register(IGitUICommands gitUiCommands)
   at BackgroundFetch.BackgroundFetchPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.OnClosed(EventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Void WinIOError(Int32, System.String) @ System.IO.__Error
mscorlib
HResult: -2147024864
```

**Comment by RussKie** [comment]
Thank you.

How do we want to have it handled?
* Ignore?
* Retry in few ms/sec and ignore?

**Comment by tomasfejfar** [comment]
It may happen, it may even throw and quit. But it **MUST NOT empty the configuration file**. 

Now when this happens, whole configuration is lost. The config file is 0 bytes. When I start again after I get the whole fresh install experience with selecting flags, checking if git is present, etc...

**Comment by RussKie** [comment]
@tomasfejfar I've just noticed you're reporting a bug for v2.51.05 on Windows.
We do not support this version any longer, the code has significantly evolved since then.

Is there a reason you don't update to the latest?

**Comment by tomasfejfar** [comment]
There was a massive performance drop for me in v3. I'm yet to give it second chance.

**Comment by tomasfejfar** [comment]
I've given it a second chance :) So now I'm on v 3.

**Comment by RussKie** [comment]
@tomasfejfar is this issue reproducible in 3.1 or the master?

**Comment by tomasfejfar** [comment]
No, it's not. I'll reopen if it happens.
