### ISSUE TITLE
Exception from revision grid

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#6193]
## Details

I switched to `FormBrowse` and maximised the window. I don't think I hit refresh, but I may have.

NBug popped up an exception with this stack trace:

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.CheckRowCacheIsDirty(IList`1 orderedRowCache, IList`1 orderedNodesCache)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedRowCache(IList`1 orderedNodesCache, Int32 currentRowIndex, Int32 lastToCacheRowIndex)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundThreadEntry>g__UpdateGraph|42_1(Int32 fromIndex, Int32& toIndex)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.BackgroundThreadEntry()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

GE then crashed. I attached a debugger but couldn't tell much. `orderedNodesCache` had zero items. Unfortunately I couldn't determine the index as it had been optimised away.

//cc: @spdr870 

## Steps to reproduce

Not sure, I think it's likely a race condition.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 144dpi (150% scaling)

**Comment by spdr870** [comment]
If orderedRowCache and orderedNodesCache both have zero items, an argument exception will occur. Its not hard to fix, but it is hard to simulate in the app. I can simulate it in a unit test
