### ISSUE TITLE
Exception on creating worktree

### ISSUE THREAD

**Issue by rysavyjan** [gitextensions/gitextensions#6277]
## Current behaviour

In repository with only one branch (master) when choosing Create a new worktree command, the Checkout an existing branch combobox is empty and disabled. When I specify Create a new branch and click the Create the new worktree button, following exception is displayed:

```
GitUI.CommandsDialogs.WorktreeDialog.FormCreateWorktree.CreateWorktree()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

System.NullReferenceException
Object reference not set to an instance of an object.
Void CreateWorktree() @ GitUI.CommandsDialogs.WorktreeDialog.FormCreateWorktree
```

Problem is my empty combobox and following code:
```
            var args = new GitArgumentBuilder("worktree")
            {
                "add",
                WorktreeDirectory.Quote(),
                { radioButtonCreateNewBranch.Checked, $"-b {textBoxNewBranchName.Text}", ((GitRef)comboBoxBranches.SelectedItem).Name }
            };
```
## Screenshots

![gitextproblem](https://user-images.githubusercontent.com/46950152/53037612-f3a76880-347a-11e9-96e3-1691b84a36c9.png)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Confirmed
The workaround is of course to create the branch prior to creating the worktree

@rysavyjan 
Is it possible for you to send a PR?
