### ISSUE TITLE
NRE on script hotkey unless the revision grid has the focus

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6285]
## Current behaviour

A NullReferenceException is thrown when the hotkey of a script is hit while the Revision Grid is not focused.

## Expected behaviour

No exception, no hard exit.

## Steps to reproduce

- assign a hotkey to a script
- focus something else than the Revision Grid, e.g. the Diff files list or the Commit Info
- hit the assigned hotkey

## Screenshots

![script hotkeys](https://user-images.githubusercontent.com/36601201/53130908-b8389700-356b-11e9-9b5d-2020c59a3559.png)

## Did this work in previous version of GitExtensions

Yes, partially: Both 2.51.05 and 3.0.0.4433 show an explanation:
![grafik](https://user-images.githubusercontent.com/36601201/53131024-02ba1380-356c-11e9-80c3-4d92b20c42bb.png)

*Not* caused by the appreciated PR # 6219 crypto-rsa/5834-skip-grid-refresh-after-navigational-script.

## Environment

- Git Extensions 3.1.0
- Build 5e825a186d8ea793be4c3bff9893ab56b158700b
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at GitUI.Script.ScriptOptionsParser.ParseScriptArguments(String argument, String option, IWin32Window owner, RevisionGridControl revisionGrid, IGitModule module, IReadOnlyList`1 allSelectedRevisions, IList`1& selectedTags, IList`1& selectedBranches, IList`1& selectedLocalBranches, IList`1& selectedRemoteBranches, IList`1& selectedRemotes, GitRevision selectedRevision, IList`1& currentTags, IList`1& currentBranches, IList`1& currentLocalBranches, IList`1& currentRemoteBranches, GitRevision currentRevision, String currentRemote) in F:\Build\gitextensions\GitUI\Script\ScriptOptionsParser.cs:line 351
   at GitUI.Script.ScriptOptionsParser.Parse(String argument, IGitModule module, IWin32Window owner, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptOptionsParser.cs:line 118
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, GitModule module, ScriptInfo scriptInfo, IGitUICommands uiCommands, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptRunner.cs:line 83
   at GitUI.Script.ScriptRunner.ExecuteScriptCommand(IWin32Window owner, GitModule module, Int32 command, IGitUICommands uiCommands, RevisionGridControl revisionGrid) in F:\Build\gitextensions\GitUI\Script\ScriptRunner.cs:line 19
   at GitUI.GitModuleForm.ExecuteCommand(Int32 command) in F:\Build\gitextensions\GitUI\GitModuleForm.cs:line 69
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd) in F:\Build\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 2205
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData) in F:\Build\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 52
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData) in F:\Build\gitextensions\ResourceManager\GitExtensionsControl.cs:line 90
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**Comment by crypto-rsa** [comment]
It seems that `ScriptOptionsParser.ParseScriptArguments` doesn't handle situation when `selectedRevision` or `currentRevision` parameter is `null`.

**Comment by RussKie** [comment]
Would a fix be just `selectedRevision?.Xxx`?

**Comment by crypto-rsa** [comment]
> Would a fix be just `selectedRevision?.Xxx`?

Actually, for the other parameters (like `sLocalBranch`) we return an empty string instead of `null` if it is not available.

**Comment by mstv** [comment]
Why do we have the restriction that the Revision Grid must be focused, at all? Its selected revision(s) are valid always when the FormBrowse is active, e.g. also if the Commit Info or the Diff have the focus.

**Comment by RussKie** [comment]
Valid question. 
I don't think we should be restricting, the revision graph is there and we know the current selection.
