### ISSUE TITLE
ArgumentException on startup

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6442]
## Current behaviour

Start GE, opens the last repo (GE) automatically --> AE "duplicate key in dictionary".

## Expected behaviour

no crash

## Screenshots

![exception](https://user-images.githubusercontent.com/36601201/55625266-86406480-57a8-11e9-8596-6626f69babf2.png)

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 3.1.0
- Build 259c501a27db6de9723fbcddbdd40638a9498f24
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>g__ToDictionary|53_0(IReadOnlyList`1 list) in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 218
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__53.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__47_0>d.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\Build\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

**Comment by RussKie** [comment]
It looks like there is a duplicate returned by the following call:
https://github.com/gitextensions/gitextensions/blob/703fae5793bcb73c55be0b34d556deee04399fe8/GitCommands/Git/GitModule.cs#L750-L758

Could you share what you get running the command?

**Comment by mstv** [comment]
Unfortunately, Git does not indicate my broken repo with an non-zero the exit code.
```
$ git for-each-ref --sort=-committerdate --sort=-taggerdate --format="%(refname)" refs/
warning: ignoring broken ref refs/remotes/upstream/HEAD
warning: ignoring broken ref refs/remotes/upstream/master
refs/tags/v3.0.2
refs/tags/v3.0.1
...
```

**Comment by mstv** [comment]
The file `gitextensions\.git\refs\remotes\upstream\master` contained 41 null bytes.
