### ISSUE TITLE
Exception if opening a submodule with incorrect superproject reference

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6512]
Unable to parse object ID "fatal: not a git repository: 

## Current behaviour

If a repo to be opened is a submodule, and the superproject for some reason is corrupted (also if the submodule has been copied), opening the repo gives an exception: 

## Expected behaviour

No exception, showing that the repo has no commits (the normal behavior)

## Steps to reproduce

Get a submodule with incorrect link to the superrepo by modifying the superrepo or just copy the submodule:
$ cp -pr ../gitextensions/Externals/Git.hub/ .
Open the submodule and the error occurs

## Error Details
```
System.FormatException: Unable to parse object ID "fatal: not a git repository: F:/dev/gc/tmp/Git.hub/../../.git/modules/Externals/Git.hub".
   at GitUIPluginInterfaces.ObjectId.Parse(String s) in F:\dev\gc\gitextensions\Plugins\GitUIPluginInterfaces\ObjectId.cs:line 173
   at GitCommands.GitModule.GetCurrentCheckout() in F:\dev\gc\gitextensions\GitCommands\Git\GitModule.cs:line 1170
   at GitUI.RevisionGridControl.ForceRefreshRevisions() in F:\dev\gc\gitextensions\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:line 884
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions() in F:\dev\gc\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:line 602
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext() in F:\dev\gc\gitextensions\GitUI\GitUIExtensions.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\dev\gc\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

## Environment
- Git Extensions 3.1.0
- Build 33675bd986268ccbace666afe9bdbcbd34b012e8
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/pull/6451#pullrequestreview-224113329

If the response to git-rev-parse starts with "fatal:" (really any ":"), do not try to parse but return null.
https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitModule.cs#L1151
