### ISSUE TITLE
[NBug] Unexpected artificial commit in Git command: 22222222222222...

### ISSUE THREAD

**Issue by xinfli** [gitextensions/gitextensions#6533]
## Error Details
```
System.ArgumentException: Unexpected artificial commit in Git command: 2222222222222222222222222222222222222222
   at GitCommands.ArgumentBuilderExtensions.Add(ArgumentBuilder builder, ObjectId objectId)
   at GitCommands.GitModule.GetDescribe(ObjectId commitId)
   at GitCommands.Git.GitDescribeProvider.Get(ObjectId revision)
   at GitUI.CommitInfo.CommitInfo.<ReloadCommitInfo>g__GetDescribeInfoForRevision|56_14(<>c__DisplayClass56_3& )
   at GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>g__LoadDescribeInfoAsync|9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.3761.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please fill in all sections of the template

**Comment by xinfli** [comment]
Filed a new issue with more details (#6535), please delete this one.
