### ISSUE TITLE
Crashes when loading PageAnt for the first time

### ISSUE THREAD

**Issue by zacatkogan** [gitextensions/gitextensions#6538]
## Current behaviour

GitExtensions freezes after any operation that involves starting Pageant (PuTTY auth agent).

## Expected behaviour

GE will load Pageant and continue to remain responsive afterwards

## Steps to reproduce

E.g. If Pageant isn't loaded when committing or fetching
  - GE will open Pageant
  - Pageant will prompt you to enter the password for the SSL key
  - Regardless of whether you completed password entry or just close the window, GE becomes unresponsive. You must end the process and reopen, and as long as Pageant is still loaded, it will work correctly.

If you close Pageant again and repeat the above steps, GE will again become unresponsive.

## Did this work in previous version of GitExtensions

Didn't have this problem before updating to GE 3.0

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.2.windows.1
- Microsoft Windows NT 6.3.9600.0 (Windows Server 2012)
- .NET Framework 4.7.2650.0
- DPI 96dpi (no scaling)

## Diagnostics

![image](https://user-images.githubusercontent.com/7855639/57342274-63c3b180-7181-11e9-99ee-9a422baddc43.png)

Unable to get any more information (e.g. log export) because it all becomes unresponsive.

**Comment by zacatkogan** [comment]
Similar issue to 235

**Comment by zacatkogan** [comment]
Just as a follow up to this, it doesn't hang if I go through Tools => Putty => Start Authentication Agent and start PuTTY/Pageant that way.

**Comment by vbjay** [comment]
Update git. Try again. 

Try our current rc

Install latest putty and point putty exe paths to installed versions. Yuy can use chocolatey to do this with the putty.install package.

**Comment by zacatkogan** [comment]
I've updated Git to 2.21, updated PuTTY to 0.71 (and pointed GitExt to it). Problem is still occurring.

Next step: try the RC.

One more note: I've found that if you close Pageant while GitExt is hanging, GitExt will come back to life (but it will try to load the SSH key, opening Pageant and causing the same problem again...)

**Comment by thorade** [comment]
Also happens to me, with gitExtensions 


## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitUI.CommandsDialogs.FormBrowse.StartAuthenticationAgentToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```


## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by thorade** [comment]
After downloading the latest binaries (zip with all binaries, 64bit version) from 
https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
and placing them in 
C:\Program Files (x86)\GitExtensions\PuTTY
it does not crash anymore

**Comment by zacatkogan** [comment]
@thorade pretty sure that's a different issue - it was opening Pageant just fine (meaning that it could find it just fine), but then it was hanging until I either terminated Git Extensions, or exited Pageant.

**Comment by dueringa** [comment]
Have you tried resetting the paths in the settings? (Tools->Settings, GitExtensions->SSH)
That is, really go there, click "Browse", and browse for the executable.

I don't know why it should've helped, but it helped me.

**Comment by zacatkogan** [comment]
I've tried setting (and re-setting) the paths in settings (mentioned on May 13).
It worked for a little bit, then started causing hangs again.
I've installed the 64-bit version into the 32-bit path, and again it was working fine for a few days, but then it started causing hangs again.

**Comment by RussKie** [comment]
If it was working for a few days and then stopped the could be something else that is causing problems.
Is that on your personal computer or a company-managed?
Can you use SSH instead?

**Comment by zacatkogan** [comment]
This is a company-managed Windows Server 2012 machine, but it's just a dev machine so it's not a huge problem if we need to try several things to get it working correctly.

What do you mean by "can you use SSH instead?"

I've attached Visual Studio to it while it's hung, and here's the stack trace.
[GitExt Hang Stack Trace.txt](https://github.com/gitextensions/gitextensions/files/3440439/GitExt.Hang.Stack.Trace.txt)

It looks like it's waiting for something to come back from when it's starting Pageant.

**Comment by gerhardol** [comment]
> What do you mean by "can you use SSH instead?"

Create a key in OpenSSH format

![image](https://user-images.githubusercontent.com/6248932/62080931-e1173380-b251-11e9-8f87-ddfbe19be8a1.png)

**Comment by zacatkogan** [comment]
I think I've worked out why it's working some times and not others.

It's a shared dev box, there are other users running GitExtensions, and as an extension of that, PageAnt.

When it's working, it's because I'm the only one signed in, and there's no instances of PageAnt running. GitExtensions starts it up, it loads the key, all good no hangs.
When someone else is running PageAnt, it checks to see if there's an instance (there is), then tries to load the key, then it hangs.

I've verified that this is the case with the following:

 - With no other uses running PageAnt, and the current user not running it either, Push/Pull/Fetch whatever, PageAnt loads fine, GitExtensions doesn't hang
 - With another user running PageAnt, current user not running it, Push/Pull/Fetch whatever, PageAnt loads, GitExtensions hangs
 - With the other user exiting from PageAnt, current user not running it, Push/Pull/Fetch whatever, PageAnt loads fine, GitExtensions doesn't hang.

When GitExtensions is checking whether PageAnt is running, it's not checking if it's running for the current user, or whether it's just running *somewhere*.
In [GitModules.cs@1439](https://github.com/gitextensions/gitextensions/blob/49fa6903aee631520e8352137e2e9b795df7d6c9/GitCommands/Git/GitModule.cs#L1439) it says 

>            // ensure pageant is loaded, so we can wait for loading a key in the next command
            // otherwise we'll stuck there waiting until pageant exits

which is consistent with the behavior I'm seeing.

I'm not sure exactly when this behavior changed, whether it was there in later versions of GE V2, or if it's only been introduced in GE V3, but it's something that I've only noticed since we upgraded to V3

**Comment by zacatkogan** [comment]
It might be as simple a fix as:

```
bool IsPageantRunning()
{
    var pageantProcName = Path.GetFileNameWithoutExtension(AppSettings.Pageant);
    // ensure that pageant is running for the current user session
    var sessionId = System.Diagnostics.Process.GetCurrentProcess().SessionId;
    return Process.GetProcessesByName(pageantProcName).Any(p => p.SessionId == sessionId);
}
```

**Comment by zacatkogan** [comment]
Looks like this behavior was added in commit c9b4e25536c8031ba761ba1d8a8c85d8157310bb, which was part of the V3.0 development.

**Comment by RussKie** [comment]
It looks like you're in the best position to work on the fix.
I suggest you make the change and see if it works.

**Comment by gerhardol** [comment]
The workaround should be to start PageAnt manually
The behavior in 2.x and 3.x looks the same to me, but the suggested change make sense

**Comment by RussKie** [comment]
Is this still a problem in v4.1?

**Comment by thorade** [comment]
> After downloading the latest binaries (zip with all binaries, 64bit version) from https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html ftp://ftp.chiark.greenend.org.uk/users/sgtatham/putty-latest/w64/putty.zip and placing them in C:\Program Files (x86)\GitExtensions\PuTTY it does not crash anymore

I have not experienced this anymore since ~4 years, but I am not the original author of the issue
