### ISSUE TITLE
Branch filtering not working in 3.1

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#6555]
#4370 still not fixed in the latest release.

```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3761.0
- DPI 96dpi (no scaling)

**Comment by mast-eu** [comment]
Please use our template for bug reports and provide a description of the exact steps to reproduce the issue.

**Comment by NN---** [comment]
No problems. Meanwhile I cannot reproduce it with 3.1 release.
Closing for now.
