### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Janry** [gitextensions/gitextensions#6579]
## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass10_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please provide all required information

**Comment by sharwell** [comment]
@tombresson may have provided additional details for this in https://github.com/gitextensions/gitextensions/issues/6720#issuecomment-497750308. Either way, if NBug says the crash happened I'm inclined to believe it 😄

**Comment by gerhardol** [comment]
Use of GitModule should be investigated. Suspicious handling if RecreateObservable() already fetches information when module switches.

**Comment by RussKie** [comment]
I'm closing this in favour of #6720 since that one has some information
