### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by cadamlamb** [gitextensions/gitextensions#6584]
## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.Executable.GetOutput(ArgumentString arguments)
   at GitCommands.GitModule.GetSortedRefs()
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__49_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
After removing a submodule (I might have deleted it directly from the project folder first??), it was still listed on the main screen.  When I clicked on the now removed sub module, it crashes.

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
https://gist.github.com/myusuf3/7f645819ded92bda6677#gistcomment-2650640

**Comment by bansan85** [comment]
Confirm. It happend when removing a submodule but forget to remove the lines in ```.gitmodules```.

Crash happens when I double click on this submodule on the tree at the left on the GUI.

**Comment by RussKie** [comment]
Thank you @bansan85, that's very valuable information.

**Comment by bansan85** [comment]
I can't reproduce anymore with version 3.3.
Now, the git project is closing (without a warning :/ )
This issue should be closed.
