### ISSUE TITLE
[NBug] The path is not of a legal form.

### ISSUE THREAD

**Issue by larrydolsen** [gitextensions/gitextensions#6599]
## Current behaviour

When I close the GitHub: Remote repository fork and clone window, Git Extensions crashes with this exception.

## Expected behaviour

The application should not crash.

## Steps to reproduce

1. In the menu, select GitHub>Fork/Clone repository...
2. Click the Close button.
3. Git Extensions crashes.

## Error Details
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitCommands.Submodules.SubmoduleStatusProvider.GetSuperProjectRepositorySubmodulesStructure(GitModule currentModule, SubmoduleInfoResult result, String noBranchText)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass16_0.<<UpdateSubmodulesStructure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by larrydolsen** [comment]
After typing a valid path in the Destination folder textbox, the error no longer occurs.

**Comment by RussKie** [comment]
I'm afraid I can't repro the issue.
![6599-repro](https://user-images.githubusercontent.com/4403806/57979956-9d40ca80-7a67-11e9-8de1-ad7f5081c1b9.gif)

Is there something else required to reproduce?

**Comment by illfated** [comment]
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

Cannot reproduce. All Git Extensions does when I close the "Github: Remote repository fork and clone" window is to refresh the views in the commit list and diff view (maybe some of the other frames too, but the change is too small to notice).

**Comment by Killinika** [comment]
I get the same issue when starting GitExtension.exe without arguments. 
Could remove the problem whit editing the following file: "%appdata%\GitExtensions\GitExtensions\GitExtensions.settings"

Problem was: there was a tab character (\t) in one of the paths in the history.
After removing it the program works fine again.
