### ISSUE TITLE
[NBug] The requested operation requires elevation

### ISSUE THREAD

**Issue by Nik4321** [gitextensions/gitextensions#6666]
## Current behaviour

GitExtensions.exe Error

## Expected behaviour
Open Git bash.

## Steps to reproduce

1. Open Git extensions.
2. Open a repository.
3. Click on the Git bash button.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.GitModule.RunBash(String bashCommand)
   at GitUI.CommandsDialogs.FormBrowse.GitBashClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by illfated** [comment]
Cannot replicate your issue. Git Bash has always worked fine for me.

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

![image](https://user-images.githubusercontent.com/38162891/58369634-66eacb80-7efd-11e9-9c13-028085615471.png)

**Comment by Nik4321** [comment]
Yes, @illfated I just tried the run as administrator and the issue was gone. Not sure why I did not have this issue before.  Maybe an update changed something or it was just something on my end.

Thanks for the feedback.

**Comment by illfated** [comment]
The issue seems to be that your repository does not allow regular user write access.

**Comment by RussKie** [comment]
Is the issue only observed for a specific repo or all repos?
Can you please provide more info

**Comment by Nik4321** [comment]
The issue can be reproduced on all repos.

**Comment by illfated** [comment]
This is a long shot, but have you installed GE for only your user account, or for all accounts? (Just trying to think of anything that could affect user access to files or programs when trying to open Git bash.)

**Comment by Nik4321** [comment]
@illfated 
I installed it for all account.

**Comment by illfated** [comment]
Very well, fair enough. I must admit that I don't know what else to look for, regarding any missing read/write access for the Git bash application, using default settings.

**Comment by Nik4321** [comment]
@illfated 
No, the account is an admin.
Furthermore, today I reinstalled the windows on my machine and I now when I open GE without admin, the Git bash button works as expected. Git bash opens normally. I probably won't be able to reproduce anymore

**Comment by illfated** [comment]
Very well, fair enough. Looks like you solved the issue and that it could have been a random Windows OS issue on your computer. Not sure exactly what happened there, but I am glad you were able to fix it by reinstalling your Windows OS.

**Comment by gerhardol** [comment]
Not much can be done, closing

**Comment by vbjay** [comment]
I'll bet your ntfs permissions got fried.

**Comment by vbjay** [comment]
Look at the permissions of the .git folder of a repo. I'll bet the user
account running bash doesn't have write access.  Just for a lark also check
bash permissions too.
