### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by mettafort** [gitextensions/gitextensions#6681]
## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.6.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please fill in all required information and ping us back to re-open.

**Comment by mettafort** [comment]
I followed the instructions via the app.

**Comment by RussKie** [comment]
The app pre-populates some of the fields, such as the stack trace and the technical info, however we need more info
![image](https://user-images.githubusercontent.com/4403806/58443237-1f9a5000-8134-11e9-8bde-ab56f577be21.png)
