### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: key

### ISSUE THREAD

**Issue by MarkAguirre26** [gitextensions/gitextensions#6704]
## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
   at GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
Please fill in all required information and ping us back to re-open.
