### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by BMarinov** [gitextensions/gitextensions#6706]
## Current behaviour

After updating to 3.1.0.5877 the application started crashing on startup. Reinstalling it did not help.

## Expected behaviour
The application doesnt crash.

## Steps to reproduce

N/A

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|155_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I installed the latest version of GitExtensions (up from 3.0.x) and I started getting this exception on startup, right after clicking OK in the settings checklist prompt.

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.13.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by BMarinov** [comment]
The version of git seems to be outdated. The error message implies a different issue, especially since I had no issues with remotes in the previous version of GitExtensions.

**Comment by RussKie** [comment]
Please refer to #6562 for more details

**Comment by RussKie** [comment]
Please update git or wait for 3.1.1
