### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by coola** [gitextensions/gitextensions#6735]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6675
