### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by veyroter** [gitextensions/gitextensions#6742]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.PathUtil.NormalizePath(String path)
   at GitCommands.GitModule..ctor(String workingDir)
   at GitUI.CommandsDialogs.SubmodulesDialog.FormAddSubmodule.BranchDropDown(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnDropDown(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6701 
Not the same trigger, but both exceptions in PathUtil.NormalizePath that should handle this
