### ISSUE TITLE
[NBug] Shell Exception has occurred, look at inner exception for i...

### ISSUE THREAD

**Issue by devarmada** [gitextensions/gitextensions#6760]
## Error Details
```
Microsoft.WindowsAPICodePack.Shell.ShellException (0x80070008): Shell Exception has occurred, look at inner exception for information.
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.UpdateThumbnailButton()
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.set_Enabled(Boolean value)
   at GitUI.WindowsJumpListManager.DisableThumbnailToolbar()
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
@gitextensions/git-extensions-source 
NBug reports should collect inner exceptions too

**Comment by gerhardol** [comment]
Duplicate of #7783
