### ISSUE TITLE
[NBug] The path is not of a legal form.

### ISSUE THREAD

**Issue by xrulz** [gitextensions/gitextensions#6765]
## Error Details
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitCommands.Submodules.SubmoduleStatusProvider.GetSuperProjectRepositorySubmodulesStructure(GitModule currentModule, SubmoduleInfoResult result, String noBranchText)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass16_0.<<UpdateSubmodulesStructure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Comment by gerhardol** [comment]
Duplicate of #6599
