### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by paulomorgado** [gitextensions/gitextensions#6771]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

Press F4 on the list of staged files on the commit dialog. 

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormCommit.editFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 168dpi (175% scaling)

**Comment by gerhardol** [comment]
Seem to be a new issue.

**Comment by gerhardol** [comment]
I could recreate once when clicking quickly in maybe 30 tries.
But that is likely the only null ref exception

@paulomorgado 
Please test the portable build in the related PR

**Comment by paulomorgado** [comment]
I tried again and it didn't happen. If it happens again, I'll try to debug it.

**Comment by RussKie** [comment]
Can we repro it in master? 
I could repro it consistently in 3.1.1 but not in master...
