### ISSUE TITLE
[NBug] InvalidArgument=Value of '0' is not valid for 'index'.Par...

### ISSUE THREAD

**Issue by lerthe61** [gitextensions/gitextensions#6782]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Put a branch name (issue id - 216369) into "Branches:" text box to filter out branches. And once I press Enter I get OutOfRange

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Duplicate of #6680
