### ISSUE TITLE
[NBug] Could not find a part of the path 'H:\.gitconfig19636.tmp'.

### ISSUE THREAD

**Issue by eohlde** [gitextensions/gitextensions#6783]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'H:\.gitconfig19636.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Fails in the File.Copy()
Most copying the tmp file, at least one when creating the backup (the latter could be ignored).
The exceptions related to "tmp file no longer accessible" could maybe be catched too, but at least a popup should be shown for the user.

https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Settings/FileSettingsCache.cs#L146

```
                if (File.Exists(SettingsFilePath))
                {
                    var backupName = SettingsFilePath + ".backup";
                    try
                    {
                        File.Copy(SettingsFilePath, backupName, true);
                    }
                    catch (IOException)
                    {
                        // Ignore errors for the backup file
                    }
                }

                try
                {
                    File.Copy(tmpFile, SettingsFilePath, true);
                    File.Delete(tmpFile);
                }
                catch (FileNotFoundException)
                {
                    // Ignore
                }
                catch (DirectoryNotFoundException)
                {
                    // Ignore
                }
```
