### ISSUE TITLE
[NBug] The path is not of a legal form.

### ISSUE THREAD

**Issue by wapadam** [gitextensions/gitextensions#6789]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitCommands.Submodules.SubmoduleStatusProvider.GetSuperProjectRepositorySubmodulesStructure(GitModule currentModule, SubmoduleInfoResult result, String noBranchText)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass16_0.<<UpdateSubmodulesStructure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6599

**Comment by gerhardol** [comment]
All set to a duplicate of this seem to get the exception here:
https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Submodules/SubmoduleStatusProvider.cs#L198

So it seems like the submodule path is invalid in some situations.
Something like the following should prevent it:

```
            if (isCurrentTopProject)
            {
                string path = result.Module.WorkingDir;
                if (Directory.Exists(path))
                {
                    string name = Path.GetFileName(Path.GetDirectoryName(path)) + GetBranchNameSuffix(path, noBranchText);
                    result.TopProject = new SubmoduleInfo { Text = name, Path = path, Bold = true };
                }

                return;
            }
```
