### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid github secret gist  

### ISSUE THREAD

**Issue by LexiconCode** [gitextensions/gitextensions#6823]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Expected behaviour
clone a secret gist github

## Steps to reproduce
Create a secret gist aand try to clone it using the URL provided by the webUI.

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.PathUtil.NormalizePath(String path)
   at GitCommands.GitModule..ctor(String workingDir)
   at GitUI.CommandsDialogs.FormInit.InitClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 144dpi (150% scaling)

**Comment by LexiconCode** [comment]
The fields should be satisfied

**Comment by gerhardol** [comment]
Duplicate of #6556
Not exactly the same exception, but same handling.
The exception no longer occurs in 3.2
