### ISSUE TITLE
[NBug] Could not find file 'config6456.tmp'.

### ISSUE THREAD

**Issue by Vyjayanthrobonaut** [gitextensions/gitextensions#6830]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Could not find file 'config6456.tmp'.
File name: 'config6456.tmp'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.SaveAndRescan_Click(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.GitFound_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)

**Comment by gerhardol** [comment]
Duplicate of #6783
