### ISSUE TITLE
[NBug] Error reading the C:\GitRepo\EH-Qfirmwareserver-master\ dir...

### ISSUE THREAD

**Issue by SinghHY** [gitextensions/gitextensions#6852]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Error reading the C:\GitRepo\EH-Qfirmwareserver-master\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6812
Corrected in #6834
