### ISSUE TITLE
Open file history from command line

### ISSUE THREAD

**Issue by apobekiaris** [gitextensions/gitextensions#6873]
## Current behaviour

GitExtensions throws exception

## Expected behaviour
Open file hitory from command line

## Steps to reproduce

I have a script in autohotkey to open filehistory like

"C:\Program Files (x86)\GitExtensions\GitExtensions.exe" filehistory %ClipBoard% 

was working fine but now throws

## Error Details
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at GitUIPluginInterfaces.ObjectId.TryParseAsciiHexBytes(ArraySegment`1 bytes, Int32 index, ObjectId& objectId)
   at GitCommands.RevisionReader.TryParseRevision(GitModule module, ArraySegment`1 chunk, StringPool stringPool, Encoding logOutputEncoding, GitRevision& revision)
   at GitCommands.RevisionReader.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at GitUI.RevisionGridControl.<>c__DisplayClass150_2.<ForceRefreshRevisions>b__9()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
---> (Inner Exception #0) System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at GitUIPluginInterfaces.ObjectId.TryParseAsciiHexBytes(ArraySegment`1 bytes, Int32 index, ObjectId& objectId)
   at GitCommands.RevisionReader.TryParseRevision(GitModule module, ArraySegment`1 chunk, StringPool stringPool, Encoding logOutputEncoding, GitRevision& revision)
   at GitCommands.RevisionReader.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()<---

```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 144dpi (150% scaling)

**Comment by pmiossec** [comment]
Same as #6872
