### ISSUE TITLE
[NBug] The path is not of a legal form.

### ISSUE THREAD

**Issue by princebillyGK** [gitextensions/gitextensions#6896]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitCommands.Submodules.SubmoduleStatusProvider.GetSuperProjectRepositorySubmodulesStructure(GitModule currentModule, SubmoduleInfoResult result, String noBranchText)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass16_0.<<UpdateSubmodulesStructure>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a

**Comment by gerhardol** [comment]
Duplicate of #6599
Corrected in 3.2
