### ISSUE TITLE
[NBug] Cannot access a disposed object.Object name: 'FormQuickGi...

### ISSUE THREAD

**Issue by moshe-shahar** [gitextensions/gitextensions#6901]
## Current behaviour

Application crashs.

## Expected behaviour

Open browser on selected commit url in GitHub.
## Steps to reproduce
RClick -> Open on GitHub:
Script command: {openurl}
Script params: https://github.com/{cDefaultRemotePathFromUrl}/commit/{sHashes}

## Error Details
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FormQuickGitRefSelector'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at GitUI.Script.ScriptOptionsParser.AskToSpecify(IEnumerable`1 options, RevisionGridControl revisionGrid)
   at GitUI.Script.ScriptOptionsParser.Parse(String argument, IGitModule module, IWin32Window owner, RevisionGridControl revisionGrid)
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, GitModule module, ScriptInfo scriptInfo, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   at GitUI.RevisionGridControl.<RefreshOwnScripts>g__RunScript|205_2(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
@moshe-shahar, try the [current development build](https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts), please. We have fixed some bugs recently.

Though I am not sure whether `{cDefaultRemotePathFromUrl}` is expanded correctly.
In my setup with multiple remotes, it gives an empty string.
Which `Remote repositories` do you have configured?

(And I would use rather `{sHash}` than `{sHashes}` because the URL would become invalid if multiple commits are selected.)

There is also a feature named [Revision Links](https://git-extensions-documentation.readthedocs.io/en/master/settings.html#git-extensions-revision-links) which adds clickable links to the `Commit info`.

**Comment by moshe-shahar** [comment]
Thanks for your help.

Not sure which `Remote repositories`. I think only one, `origin`.

**Comment by mstv** [comment]
With a single remote, it should work. The regarding NUnit test cases have passed.

**Comment by pmiossec** [comment]
>There is also a feature named Revision Links which adds clickable links to the Commit info.

And there is also GitHub templates to easily configure it: https://github.com/gitextensions/gitextensions/pull/6785
