### ISSUE TITLE
[NBug] Overflow error.

### ISSUE THREAD

**Issue by CarrolSequal** [gitextensions/gitextensions#6911]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Single x, Single y, Single width, Single height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, RectangleF rect)
   at ICSharpCode.TextEditor.TextView.DrawDocumentWord(Graphics g, String word, Point position, Font font, Color foreColor, Brush backBrush)
   at ICSharpCode.TextEditor.TextView.PaintLinePart(Graphics g, Int32 lineNumber, Int32 startColumn, Int32 endColumn, Rectangle lineRectangle, Int32 physicalXPos)
   at ICSharpCode.TextEditor.TextView.PaintDocumentLine(Graphics g, Int32 lineNumber, Rectangle lineRectangle)
   at ICSharpCode.TextEditor.TextView.Paint(Graphics g, Rectangle rect)
   at ICSharpCode.TextEditor.TextArea.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6633
That issue has some reproduce info too
