### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by ggnkua** [gitextensions/gitextensions#6922]
## Current behaviour
Application crashes when it tries to open a repository with two "url" fields in [remote "origin"] section. This is NOT the same as issue #6562 and family.

## Expected behaviour

Application should handle two "url" fields

## Steps to reproduce

Open a repository's .git/config file and add two "url" fields in [remote "origin"] section. Then open that repository using git extensions.

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
This is NOT the same as issue #6562. To reproduce, open a repository's .git/config file and add two "url" fields in [remote "origin"] section

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
What is in the config?
Output from git remote -v

Any similarities with https://github.com/gitextensions/gitextensions/issues/6093#issuecomment-493892843 or the discussions in the thread?

**Comment by ggnkua** [comment]
> What is in the config?

```
 git config --list
core.symlinks=false
core.autocrlf=false
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
merge.tool=kdiff3
diff.guitool=kdiff3
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
core.autocrlf=false
mergetool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
difftool.kdiff3.path=C:/Program Files/KDiff3/kdiff3.exe
difftool.kdiff3.cmd="C:/Program Files/KDiff3/kdiff3.exe" "$LOCAL" "$REMOTE"
user.name=ggn
user.email=ggn.dbug@gmail.com
pull.rebase=false
fetch.prune=false
rebase.autostash=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ggnkua/half-sprite.git
remote.origin.url=https://ggnkua@bitbucket.org/ggnkua/half-sprite.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

> Output from git remote -v

```git remote -v
origin  https://github.com/ggnkua/half-sprite.git (fetch)
origin  https://github.com/ggnkua/half-sprite.git (push)
origin  https://ggnkua@bitbucket.org/ggnkua/half-sprite.git (push)
```

> 
> Any similarities with [#6093 (comment)](https://github.com/gitextensions/gitextensions/issues/6093#issuecomment-493892843) or the discussions in the thread?

Possibly, but I cannot understand if there's anything I can do?

**Comment by RussKie** [comment]
We do not currently support multiple push remotes.
Please remove the second one.

**Comment by ggnkua** [comment]
> We do not currently support multiple push remotes. Please remove the second one.

With all due respect, I'd rather go back to version 2.x of git extensions where this actually worked.

**Comment by ggnkua** [comment]
Another interesting observation: version 3.0.2.5232 does not crash using the above configuration.

**Comment by RussKie** [comment]
Could you please try this build and see if it is working for you - https://ci.appveyor.com/api/buildjobs/heuf5ppwr6ebtp01/artifacts/Setup%2FGitExtensions-Portable-3.3.0.6720.zip

**Comment by ggnkua** [comment]
I just did and it seems ok. Thanks :)

(nice improvements on the UI btw!)
