### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ZodmanPerth** [gitextensions/gitextensions#6966]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BackgroundFetch.BackgroundFetchPlugin.<>c__DisplayClass10_0.<RecreateObservable>b__1(Int64 i)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ScheduledObserver`1.Dispatch(ICancelable cancel)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

## Additional information
After cloning a repo with submodules, but not retrieving those submodules, I navigated to a submodule.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6720
