### ISSUE TITLE
Crash when clicking "Suggest" button next to merge/diff tool paths, when those paths contain forward slashes

### ISSUE THREAD

**Issue by IanKemp** [gitextensions/gitextensions#7000]
![image](https://user-images.githubusercontent.com/1726434/62776574-d99e2880-baa2-11e9-9677-0babd37d7f0d.png)

The "Path to mergetool" and "Path to difftool" fields support forward slashes as that's what Git supports, but `System.IO.Path.GetFileName` which you're invoking when someone clicks the "Suggest"  button next to those items, does not.

This means that if you click the "Suggest" button and your path has forward slashes, you get this crash.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.DiffToolCmdSuggest_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0 (Windows 10 Home 1903)
- .NET Framework 4.8.3815.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Back and forward slashes are handled correctly.
In your example, you have enclosed the path with quotes (not done by GE), those are not legal characters.

The popup error is correct but could be nicer, but I would consider this a low priority issue.

**Comment by RussKie** [comment]
There should be no `"` for either "path" value:
![image](https://user-images.githubusercontent.com/4403806/62922929-46703600-bdb5-11e9-9b14-2110add58578.png)

**Comment by gerhardol** [comment]
Quotes are added when need to limit from other information. To remove quotes here would be a very special check. I am not convinced that should be done. What more special cleaning should be done?

GE should regardless not crash when the input data is incorrect.
