### ISSUE TITLE
[NBug] Sequence contains no elements

### ISSUE THREAD

**Issue by manuc66** [gitextensions/gitextensions#7011]
## Current behaviour

Git Extension process crash and show a popup window of bug reporting instead of compare to menu

## Expected behaviour

No process crash and ability to compare a commit with a branch

## Steps to reproduce
Click to select a commit row
Ctrl+Click to unselect the commit
Right click on that commit row
Go to Compare sub menu, then click on "Compare To branch..."

## Error Details
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GitUI.RevisionGridControl.CompareToBranchToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information

Looking at the code the exception is on that line and cause because there is no selected commit
https://github.com/gitextensions/gitextensions/blob/ddce80631f19c41662fef4632b6d0aa22a8cddde/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs#L2365

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by manuc66** [comment]
Information completed

**Comment by manuc66** [comment]
Also reproductible when 
- triggering the action with a hot key whout a selection in the grid
- launching other compare actions from context menu when there is no selection in the grid
