### ISSUE TITLE
[NBug] Error reading the C:\dev\pipWare\pip.bi\ directory.

### ISSUE THREAD

**Issue by ThulaniMakoba** [gitextensions/gitextensions#7022]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Error reading the C:\dev\pipWare\pip.bi\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Duplicate of #6812
Corrected in #6834
