### ISSUE TITLE
[NBug] NullReferenceException on unstage

### ISSUE THREAD

**Issue by penev92** [gitextensions/gitextensions#7045]
## Current behaviour

GitExtensions crashed when unstaging multiple lines. Doesn't seem to crash consistently.

## Steps to reproduce

No steps to reproduce reliably available.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormCommit.StageSelectedLinesToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.UnStageSelectedFile()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Additional information
Error occured when I tried unstaging multiple lines from a file that had 1563 deleted and 26 added lines.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Without a repro it is hard to tell what went wrong.

I had a look at the 3.1.1 code and there was a possible for a NRE:
https://github.com/gitextensions/gitextensions/blob/v3.1.1/GitUI/CommandsDialogs/FormCommit.cs#L833

However the code has changed in 3.2, so it could be that the problem is fixed:
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormCommit.cs#L833-L837

**Comment by penev92** [comment]
Sorry, I have no further information to give you and no reliable repro case.
If you feel this might have been fixed already or can't be debugged properly feel free to close the issue.
