### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by sheinv78** [gitextensions/gitextensions#7050]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

Just tried to select a branch when adding a submodule with path like git@github.com:somerepopath.git

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.PathUtil.NormalizePath(String path)
   at GitCommands.GitModule..ctor(String workingDir)
   at GitUI.CommandsDialogs.SubmodulesDialog.FormAddSubmodule.BranchDropDown(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnDropDown(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I tried to select a branch when adding a submodule from path : git@gitlab.com:<some_repo>.git

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6556
The exception no longer occurs in 3.2
