### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by rjshaver** [gitextensions/gitextensions#7054]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass38_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass38_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Just opened a directory which did not contain a git  repository.  Received error about no git repo.  Exception occurred within a minute or two.  This was about the time I moved the directory because it was in the wrong library.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 240dpi (250% scaling)

**Comment by gerhardol** [comment]
Duplicate of #6584
Likely fixed in 3.2

**Comment by gerhardol** [comment]
There will be a release candidate soon, translators have their time.
You can use a portable build from master meanwhile.

**Comment by RussKie** [comment]
The current dev build is available here: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by rjshaver** [comment]
Thanks so much RussKie and gerhardol.  I tried this out yesterday and it worked great.  No crashes at all even trying.  Sorry for not getting back until today, I was on the road.

**Comment by RussKie** [comment]
Glad to hear it
