### ISSUE TITLE
[NBug] Access to the path 'C:\Labs' is denied.

### ISSUE THREAD

**Issue by vardhananand** [gitextensions/gitextensions#7063]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UnauthorizedAccessException: Access to the path 'C:\Labs' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
This seems like an attempt to clone to a directory that already exists and where the user do not have access:
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormClone.cs#L403

A try-catch should be added here.

**Comment by RussKie** [comment]
That method is an abomination and should be refactored....
