### ISSUE TITLE
[NBug] Collection was modified; enumeration operation may not exec...

### ISSUE THREAD

**Issue by CorrieScheepers2** [gitextensions/gitextensions#7067]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.SelectRowsIfReady(Int32 rowCount)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundThreadEntry>g__UpdateRowCount|48_2(Int32 row)
   at GitUI.GitUIExtensions.<InvokeAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6924
