### ISSUE TITLE
[NBug] The specified path, file name, or both are too long. The fu...

### ISSUE THREAD

**Issue by ekachaitose** [gitextensions/gitextensions#7076]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass129_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.7.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6982, that is as Duplicate of #6755
Fixed in #6984 
Include in next release
