### ISSUE TITLE
[NBug] CombinedDiff artificial commit cannot be explicitly compare...

### ISSUE THREAD

**Issue by simontom** [gitextensions/gitextensions#7087]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: CombinedDiff artificial commit cannot be explicitly compared: 3333333333333333333333333333333333333333, a7d7f51ed7a57322d4ebb8805d7bd4a0c9d011de
Parameter name: firstRevision
Actual value was 3333333333333333333333333333333333333333.
   at GitCommands.Git.RevisionDiffProvider.GetInternal(String firstRevision, String secondRevision, String fileName, String oldFileName, Boolean isTracked)
   at GitCommands.GitModule.OpenWithDifftool(String filename, String oldFileName, String firstRevision, String secondRevision, String extraDiffArguments, Boolean isTracked)
   at GitUI.CommandsDialogs.RevisionDiffControl.openWithDifftoolToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at GitUI.CommandsDialogs.RevisionDiffControl.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The context menu is correctly disabling diff with combined diff, but shortcut can make the same diff. So difftool (using F3 etc) must be handled too.

**Comment by simontom** [comment]
Yessss, exactly!
It was in a merge commit, using F3 shortcut.
Sorry, I was just leaving the office & was in kinda hurry.

**Comment by RussKie** [comment]
Can you please share some screenshots, I don't seem to understand the issue.

**Comment by gerhardol** [comment]
> Can you please share some screenshots, I don't seem to understand the issue.

See the PR for reproduce information

The combinedDiff only exists in RevisionDiff what I can realize.
It should be enough to just ignore CombinedDiff also if normal diff are selected (even if menu is disabled if at least one combineddiff is selected).
