### ISSUE TITLE
[NBug] Invalid escape character in .gitmodule leads to crash

### ISSUE THREAD

**Issue by JoostvanPinxten** [gitextensions/gitextensions#7097]
## Current behaviour

GitExtensions crashes with an error message when an invalid escape character is found in .gitmodule

## Expected behaviour

GitExtensions should warn the user, and make the user correct the file, before attempting to reload it again.

## Steps to reproduce

When you manually edit the path entry of a module in .gitmodules, the path may contain invalid escape characters. Upon saving the file, GitExtensions reloads the file, and crasehs.

## Error Details
```
System.Exception: Invalid escape character: f
   at GitCommands.Config.ConfigFile.ConfigFileParser.ReadValue(Char c)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.GitModule.GetSubmoduleConfigFile()
   at GitCommands.GitModule.<GetSubmodulesLocalPaths>g__GetSubmodulePaths|72_1(GitModule module)
   at GitCommands.GitModule.<GetSubmodulesLocalPaths>g__DoGetSubmodulesLocalPaths|72_0(GitModule module, String parentPath, List`1 paths, Boolean recurse)
   at GitCommands.GitModule.GetSubmodulesLocalPaths(Boolean recursive)
   at GitCommands.Submodules.SubmoduleStatusProvider.<UpdateSubmodulesStatusAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass17_0.<<UpdateSubmodulesStatus>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by lhiginbotham** [comment]
@RussKie 
I can take a look at this one.  Is there a convention set in-place in GitExtensions regarding the treatment of run-time exceptions?  For example, should I catch the exception and display a message to the user saying their path is corrupt due to the invalid escape sequence, or should the workflow 'fail silently'?

**Comment by RussKie** [comment]
Sure, thank you 👍 

The main thing is not to crash and burn. In this instance a broken config is something a user has direct control over, so we probably should warn the user and let the user know what is broken. And then ignore the issue and keep on going.
Do you agree?

**Comment by lhiginbotham** [comment]
@RussKie 
Alright, I agree on 1) notifying the user and 2) continuing on with the operation.  I haven't looked into the area of code yet to determine what is going on, but conceptually, I feel like the fix would look like this (in pseudocode):

`for (submoduleInfo in submoduleInfoArr) {`
`....try {`
`........doSubmoduleAction(parseSubmoduleInfo(submoduleInfo)));`
`....} catch (Exception e) {`
`........displayMessage(e); // prettify the exception for the user?`
`....}`
`}`

as opposed to:

`for (submoduleInfo in submoduleInfoArr) {`
`....doSubmoduleAction(parseSubmoduleInfo(submoduleInfo)));`
`}`

**Comment by RussKie** [comment]
👍

**Comment by lhiginbotham** [comment]
@RussKie 
Looking at the ConfigFileParser class, the .gitmodules file is parsed all in one-go rather than submodule by submodule (since we need to parse the file to figure out what submodules are available in the first place!).  I think it might be possible for us to catch all errors in the file and keep parsing the rest of the file, and present an 'error summary' at the end which lists all the errors if there are any.  Though this may be possible, it will add a significant amount of complexity to the parser, which will definitely require a suite of unit tests.  In addition, I am not even sure if Git gives this sort of luxury to the user or if Git stops parsing at the first error it finds.  I think for now, to at least solve the problem of crashing GitExtensions, I will just catch the first error hit, display the message, and cancel the submodules operation.  Any further development/enhancement will require further study of how Git handles parsing this file.

**Comment by RussKie** [comment]
Sounds good 👍

**Comment by gerhardol** [comment]
Explicit parsing of the config file should be avoided, use git config if possible. But just avoiding the exception is ok for me here.
