### ISSUE TITLE
[NBug] Unable to parse object ID "error launching git: The requested operation requires elevation."

### ISSUE THREAD

**Issue by mdsmark** [gitextensions/gitextensions#7102]
## Current behaviour

Flag "Run as administrator" for GitExtension executable

## Expected behaviour

The application should work with full privileges

## Steps to reproduce

1. Start GitExt
2. The dashboard loads without problems
3. After few seconds this exception raise (First exception)
![image](https://user-images.githubusercontent.com/49102769/64336627-bd2bd800-cfdd-11e9-9d31-e7690c337793.png)
4. Click on the X to not quit GitExt
![image](https://user-images.githubusercontent.com/49102769/64336747-00864680-cfde-11e9-8c98-636f40be49fa.png)
5. Opening a repository will throw the second exception

I think all these exceptions are raised because GitExt does not run git as administrator also if it can

## Error Details
1st
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```
2nd
```
System.FormatException: Unable to parse object ID "error launching git: The requested operation requires elevation.".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When running GitExt as administrator this error should not appears, because GitExt has the full privileges to start git as administrator.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git v3.20.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by mdsmark** [comment]
I also tried with latest version of Git 3.23.0 but other errors appears. So I restored the 3.20.1.
Eg.:
Git: The application was unable to start correctly stating with the error code 0xc0000142
Conhost: The memory could not be written

**Comment by mdsmark** [comment]
Replaced with complete informations: https://github.com/gitextensions/gitextensions/issues/7103
