### ISSUE TITLE
[NBug] Unable to parse object ID "error launching git: The requested operation requires elevation."

### ISSUE THREAD

**Issue by mdsmark** [gitextensions/gitextensions#7103]
## Current behaviour

Flag "Run as administrator" for GitExtension 3.1.1 executable. Or install latest version 3.2.0.

## Expected behaviour

The application should work with full privileges

## Steps to reproduce

1. Start GitExt 3.1.1
2. The dashboard loads without problems
3. After few seconds this exception raise (First exception)
![image](https://user-images.githubusercontent.com/49102769/64342148-30d3e200-cfea-11e9-84ad-e679590fe4c6.png)

4. Click on the X to not quit GitExt
![image](https://user-images.githubusercontent.com/49102769/64342164-36c9c300-cfea-11e9-933b-6229dd5d70b3.png)

5. Opening a repository will throw the second exception
I think all these exceptions are raised because GitExt does not run git executable as administrator also if it can

2nd Environment
1. Start Git Ext 3.2.0
2. git executable found with exact version but not valid/usable? (tried also v3.23.0)
![image](https://user-images.githubusercontent.com/49102769/64342055-03873400-cfea-11e9-9bbf-dde69cd3ddd0.png)

## Error Details
1st
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```
2nd
```
System.FormatException: Unable to parse object ID "error launching git: The requested operation requires elevation.".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When running GitExt as administrator this error should not appears, because GitExt has the full privileges to start git as administrator.

## Environment no.1
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git v3.20.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

## Environment no.2
- Git Extensions 3.2.0.6581
- Build 43413466e9874d8e78cafbf1c303947e9eb85a30
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
I cannot reproduce, run as admin works me

Your issue seem to be that you cannot run git.exe as admin and therefore receives garbage output.
So this can be seen as a Git issue.

1-2 is not an exception in 3.2.
Printout 2 is related, I cannot provoke it though. The current value (or null, "") is displayed if version is lower than expected.

**Comment by mdsmark** [comment]
After many tries I resolved by:

1. Unistalling Git and GitExtensions (running uninstaller as admin)
2. Manually removing the registry keys related to the Windows context menu (looking for 'git-bash.exe', 'git-gui.exe' and 'GitExtensions.exe'). This is because even after uninstalling the menu items were not deleted.
3. Reboot
4. Reinstallation of Git Extensions 3.2.0.6581 and Git 2.22.0.windows.1 (32 bit because 64 bit gave me same problems). Unchecking the item: Windows context menu in both installer.
5. Reboot

Maybe this happens because the explorer.exe process wasn't running as admin. Since my workstation is managed by my company.

**Comment by gerhardol** [comment]
In your case, it may be better to use the portable build
