### ISSUE TITLE
Exception when Opening New Repository with No Added Remote

### ISSUE THREAD

**Issue by BruceWyxv** [gitextensions/gitextensions#7133]
This may appear related to the  myriad "System.Exception: Remote URLs should appear in pairs." issues. However, I am running the most recent version of Git for Windows; this issue is _not_ related to an ancient Git version.

## Current behaviour
GE displays an exception when opening a repository that has no remote configured.

## Expected behaviour
No exception

## Steps to reproduce
1. Create an empty folder
1. Right click, select "GitExt Create new repository..."
1. Click on "Create" (either repository type doesn't make a difference)
1. Right click on the same folder and select "GitExt Open repository"
1. Git Extensions GUI appears then generates the exception

### Create a repo, step 1
![image](https://user-images.githubusercontent.com/8092205/64873251-ad804500-d616-11e9-95b0-974cab4d4412.png)
### Create a repo, step 2
![image](https://user-images.githubusercontent.com/8092205/64873075-5bd7ba80-d616-11e9-990e-60f60f0b5ab1.png)
### Open the reop
![image](https://user-images.githubusercontent.com/8092205/64873167-86297800-d616-11e9-885f-c1e34c3b450a.png)
### Displayed exception
![image](https://user-images.githubusercontent.com/8092205/64873384-ee785980-d616-11e9-9a37-2ff14497c7dd.png)

## Did this work in previous version of GitExtensions
Not tested, please let me know if further testing is needed

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

### Stack Trace
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```
### Command Line Queries
```
$ git --version
git version 2.23.0.windows.1
```
```
$ git remote -v
origin
```

## Additional Thoughts
Perhaps [ParseRemotes](https://github.com/gitextensions/gitextensions/blob/aff7b86a29fc400f76e4c027994356b11688eea8/GitCommands/Git/GitModule.cs#L2135) should first check for the default remote "origin" without any URL? It would simply return an empty list of remotes like [this check](https://github.com/gitextensions/gitextensions/blob/aff7b86a29fc400f76e4c027994356b11688eea8/GitCommands/Git/GitModule.cs#L2156). I'm not an expert in Git, but this may be a strong enough indicator that the repo has no remote added/configured.

**Comment by gerhardol** [comment]
This should be duplicate of #6922
Please test update in https://github.com/gitextensions/gitextensions/pull/7214

**Comment by BruceWyxv** [comment]
@gerhardol It doesn't seem to be a direct duplicate of #6922, since the tested repo has 0 url fields instead of 2. However, it does seem that the portable artifact for your branch in #7214 does resolve the issue.
Thanks for the fix!

**Comment by gerhardol** [comment]
> the tested repo has 0 url fields instead of 2

Thanks for confirming, another scenario
The change was to ignore remotes with invalid info (like no url), secondly to make sure there is a one to many relationship between fetchurl and pushurl
