### ISSUE TITLE
[NBug] The given path's format is not supported.

### ISSUE THREAD

**Issue by lentv** [gitextensions/gitextensions#7145]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.PathEqualityComparer.GetHashCode(String path)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at GitUI.CommandsDialogs.FormPull.LoadPuttyKey()
   at GitUI.CommandsDialogs.FormPull.<>c__DisplayClass50_0.<PullChanges>g__CalculateSource|1()
   at GitUI.CommandsDialogs.FormPull.PullChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPull.PullAndShowDialogWhenFailed(IWin32Window owner, String remote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass89_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
New issue, related to PuTTY
How to reproduce?
