### ISSUE TITLE
not able to use submodules that are outside of the parent repo's directory.

### ISSUE THREAD

**Issue by iiaiiappa** [gitextensions/gitextensions#7151]
[NBug] Object reference not set to an instance of an object.

## Current behaviour
I am not able to use submodules that are outside of the parent repo's directory.

## Expected behaviour
I should be able to use submodules that are outside of the parent repo's directory.

## Steps to reproduce
Create a .gitmodules file to have one or more submodules outside of parent repo's directory.

Create a submodule outside of parent repo's directory. Crash on opening the parent repo with Git-Extensions.
Has been a few versions of git like this already.

For example, my .gitmodules:
[submodule "bc-proto"]
	path = ../bc-proto
	url = https://github.com/PGITAb/bc-proto.git

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.CreateSubmoduleNodes(IEnumerable`1 submodules, GitModule threadModule, List`1& nodes)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.FillSubmoduleTree(SubmoduleInfoResult result)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<LoadNodesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<>c__DisplayClass4_0.<<OnStatusUpdated>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Has been a few versions of git like this already.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Any public repos with this setup?
How is standard Git handling this, from what I have seen there are always some tweaks to be done to get this structure working.

**Comment by RussKie** [comment]
Why would you want to do this?
