### ISSUE TITLE
[NBug] The directory is not empty.

### ISSUE THREAD

**Issue by sheinv78** [gitextensions/gitextensions#7170]
## Error Details
```
System.IO.IOException: The directory is not empty.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Just tried to delete non empty worktree.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The exception is slightly misleading:
https://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true

One of the files/directories in the worktree is readonly (or maybe looked by Explorer or Git processes).
GE cannot delete the file
It would be slightly niccer to to show a popup here.
