### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sergeig-stcu** [gitextensions/gitextensions#7174]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Create pull request

## Environment
- Git Extensions 3.2.0.6586
- Build abac1b4564a5166f0453fa3ee459769e8a199b6f
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6757 
Set the github oauth token, please.

There has been corrections here in 3.2. Are all corrections included @pmiossec ?

**Comment by pmiossec** [comment]
>Are all corrections included @pmiossec ?

Yes. And I don't reproduce. It opens the GitHub Authentication popup when no OAUth token has been set.

Maybe a bad token set.

**Comment by sergeig-stcu** [comment]
My token is set and works well.  I probably was trying to create another PR from UI.  I might've not noticed that I have no PR to create or some other edge case.  I don't remember anymore.
