### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by mbostwick** [gitextensions/gitextensions#7197]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Exception 0xC0000005 (Read x014FA000) was occurred (conemu.exe, PID=4900)
ConEmu build 190310 

doing a clone of:
https://github.com/LLK/scratch-blocks

## Environment
- Git Extensions 3.2.0.6586
- Build abac1b4564a5166f0453fa3ee459769e8a199b6f
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4010.0
- DPI 240dpi (250% scaling)

**Comment by gerhardol** [comment]
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem

It may be something with timing, how quickly the popup status is clicked.
There are no known way to reproduce, if you are in a position, please try to describe how to reliably recreate the problem.
