### ISSUE TITLE
[NBug] Index (zero based) must be greater than or equal to zero an...

### ISSUE THREAD

**Issue by footorama** [gitextensions/gitextensions#7203]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at GitUI.CommandsDialogs.FormResolveConflicts.HandleSingleSelect()
   at GitUI.CommandsDialogs.FormResolveConflicts.ConflictedFiles_SelectionChanged(Object sender, EventArgs e)
   at System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.FlushSelectionChanged()
   at System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   at System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean vali

**Comment by gerhardol** [comment]
Possibly a duplicate of #6687, with a correction in 3.2 (that maybe is not complete)

Have you set the diff tool correctly?
