### ISSUE TITLE
[NBug] Unable to parse git command output.

### ISSUE THREAD

**Issue by ericspolidor** [gitextensions/gitextensions#7227]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Exception: Unable to parse git command output.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
installed the latest GIT version 2.23.0, get errors.
Nothing else to say

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1

warning: 'C:\ProgramData/Git/config' has a dubious owner: 'S-1-5-21-1761044819-142934201-924725345-119967'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> Git Extensions 3.1.1.6049

Please update to the latest version 3.2.1 and see whether the problem is fixed.

> warning: 'C:\ProgramData/Git/config' has a dubious owner: 'S-1-5-21-1761044819-142934201-924725345-119967'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.

You probably need to fix this.

**Comment by gerhardol** [comment]
Duplicate of #6922
Multiple push url is not supported in 3.2, #7214 is to add support again. Please trust the portable build.
