### ISSUE TITLE
[NBug] Error reading the C:\dev\keboola\looker-api\build\.git\ dir...

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#7235]
## Error Details
```
System.IO.FileNotFoundException: Error reading the C:\dev\keboola\looker-api\build\.git\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.UserControls.RevisionGrid.IndexWatcher.set_IndexChanged(Boolean value)
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Deleted and recreated the repository directory while app was open

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Please test the updated build
