### ISSUE TITLE
[NBug] The given path's format is not supported.

### ISSUE THREAD

**Issue by n2lose** [gitextensions/gitextensions#7240]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.FileStatusList.FileStatusListView_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4010.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
How did this happen?
