### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: path3

### ISSUE THREAD

**Issue by charles-halifax** [gitextensions/gitextensions#7248]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path3
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindFileInFolders(String fileName, String[] locations)
   at GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindMergeToolFullPath(ConfigFileSettingsSet settings, String mergeToolText, String& exeName)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.MergeToolCmdSuggest_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at System.Windows.Forms.ComboBox.UpdateText()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Messag

**Comment by gerhardol** [comment]
Duplicate of #7169
Corrected in master
(No real workaround, you can use the portable version to set TortoiseMerge as mergetool.)
