### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by nayeemnshaikh** [gitextensions/gitextensions#7269]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|153_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
error

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git fatal: bad config line 1 in file C:/Users/lenovo/.gitconfig (minimum: 2.11.0, please update!)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6922

Please try the proposed correction
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/27912288/artifacts

Duplicate pushurl is not supported, as well as garbage in the remote configuration
