### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by LyubomirIvanov** [gitextensions/gitextensions#7270]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When Push with defaule merge action

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem, or just dismiss the popup

Corrected in master
