### ISSUE TITLE
[NBug] Collection was modified; enumeration operation may not exec...

### ISSUE THREAD

**Issue by Fulgan** [gitextensions/gitextensions#7279]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Started the app and accidentally clicked in the commit list while it was being displayed (not sure exactly where or how)

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6924 

No known way to reproduce
