### ISSUE TITLE
[NBug] One or more errors occurred.

### ISSUE THREAD

**Issue by Lechus** [gitextensions/gitextensions#7282]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamCityIntegration.TeamCityAdapter.GetStreamFromHttpResponseAsync(Task`1 task, String restServicePath, CancellationToken cancellationToken)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at TeamCityIntegration.TeamCityAdapter.<>c.<GetXmlResponseAsync>b__43_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at TeamCityIntegration.TeamCityAdapter.GetBuildType(String buildId)
   at TeamCityIntegration.Settings.TeamCitySettingsUserControl.lnkExtractDataFromBuildUrlCopiedInTheClipboard_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamCityIntegration.TeamCityAdapter.GetStreamFromHttpResponseAsync(Task`1 task, String restServicePath, CancellationToken cancellationToken)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

```

## Additional information
click to copy url from clipboard for TC.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7500 
That issue has more information
