### ISSUE TITLE
[NBug] Array cannot be null.Parameter name: bytes

### ISSUE THREAD

**Issue by cristinanatea** [gitextensions/gitextensions#7295]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Array cannot be null.
Parameter name: bytes
   at System.Text.Encoding.GetChars(Byte[] bytes)
   at GitCommands.Patches.Chunk.FromNewFile(GitModule module, String fileText, Int32 selectionPosition, Int32 selectionLength, Boolean reset, Byte[] filePreamble, Encoding fileContentEncoding)
   at GitCommands.Patches.PatchManager.FromNewFile(GitModule module, String text, Int32 selectionPosition, Int32 selectionLength, Boolean reset, Byte[] filePreamble, Encoding fileContentEncoding)
   at GitCommands.Patches.PatchManager.GetSelectedLinesAsNewPatch(GitModule module, String newFileName, String text, Int32 selectionPosition, Int32 selectionLength, Encoding fileContentEncoding, Boolean reset, Byte[] filePreamble)
   at GitUI.CommandsDialogs.FormCommit.StageSelectedLinesToolStripMenuItemClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.StageSelectedFile()
   at GitUI.Command

**Comment by gerhardol** [comment]
Previously unknown issue.
Pleas provide version and reproduction information
