### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\projects\pr1675\.git\...

### ISSUE THREAD

**Issue by jflheureux** [gitextensions/gitextensions#7316]
## Current behaviour

1. Open Git Extensions.
1. Open a repo.
1. Open the commit window. (I am unsure if pending changes to files are required)
1. On the file system, delete the repository that is opened in Git Extensions.
1. Close the Git Extensions commit window.
1. Git Extensions crashes with this exception.

## Expected behaviour

Git Extensions should not crash. The commit window should close. The opened repository could be closed in Git Extensions and the user could be shown the dashboard to choose a repository to open.

## Error Details

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\projects\pr1675\.git\COMMITMESSAGE'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.Abstractions.FileWrapper.WriteAllText(String path, String contents, Encoding encoding)
   at GitCommands.CommitMessageManager.set_MergeOrCommitMessage(String value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Could you please explain why someone would delete a repo while it is open?

**Comment by jflheureux** [comment]
In my job, I clone repos on specific branches for code review and QA validation. Once this done, I delete the repo (clone) from my drive. When this repo was opened in Git Extensions at the time of the delete, then this issue occurs.

**Comment by RussKie** [comment]
As an alternative you could add a new (temporary) remote, fetch all from the new remote, review, delete the remote.
![image](https://user-images.githubusercontent.com/4403806/67169295-3f3d5800-f3f6-11e9-9a2b-11b5cddfa4d9.png)

**Comment by jflheureux** [comment]
That would be ok to review. I also have to QA validate. This means to build and deploy the code on my local machine. Only a remote would not be enough for that.

**Comment by RussKie** [comment]
I think you may have missed the "fetch" part.
I collaborate this way with dozens of contributors by reviewing, testing
and committing changes back to original branches.

**Comment by jflheureux** [comment]
Maybe I am not understanding git enough. I thought "fetch" was only downloading new commits but not updating the working copy files (checkout).

I do not want to checkout on my main clone as I have pending changes for my own work there. And the deployment of this clone is in sync with an external system I do not want to change.

Whatever the best workflow to code review and QA validate, there is still a crash/bug in Git Extensions. It could be made more robust by checking the files exist before trying to access them.

**Comment by gerhardol** [comment]
A worktree would be a better option than a separate clone but you would still have to dismiss the nbug

**Comment by RussKie** [comment]
> Whatever the best workflow to code review and QA validate, there is still a crash/bug in Git Extensions. It could be made more robust by checking the files exist before trying to access them.

Yes, this is absolutely true.
