### ISSUE TITLE
[NBug] The given path's format is not supported.

### ISSUE THREAD

**Issue by n2lose** [gitextensions/gitextensions#7344]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.<ShowOrDeferAsync>g__GetFileLength|88_0(<>c__DisplayClass88_0& )
   at GitUI.Editor.FileViewer.ViewCurrentChanges(String fileName, String oldFileName, Boolean staged, Boolean isSubmodule, Func`1 getStatusAsync, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewCurrentChanges(GitItemStatus item, Boolean isStaged, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass129_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I got crashed when touch on added files auto when checkout code, seems someones was committed an image that is editting, so they checked-in also the image temp files. 
And when I click or focus on that images temp files, it crashs

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
This is similar to #6755 and probably fixed by #6702 in 3.2
Caused by long paths

Please upgrade to 3.2. There are further corrections in master
