### ISSUE TITLE
[NBug] System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#7366]
## Current behaviour

GE crashes

## Expected behaviour

Selected branch is filtered

## Steps to reproduce

Couldn't reproduce second time. Will try again.

Right click on remote branch which doesn't have local branch in the tree, "Show only this branch"

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at GitUI.BranchTreePanel.RepoObjectsTree.FilterInRevisionGrid(BaseBranchNode branch)
   at GitUI.BranchTreePanel.RepoObjectsTree.Node.OnNode[T](TreeNode treeNode, Action`1 action)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Seem to be a new issue
Cannot reproduce
