### ISSUE TITLE
ArgumentException when `git show-ref` shows duplicates

### ISSUE THREAD

**Issue by rickaas** [gitextensions/gitextensions#7372]
## Current behaviour

When opening GitExtensions on my repository I get an `System.ArgumentException`.
If I interpret the stacktrace correct this is triggered when `CommitInfo.GetSortedRefs()` is called on a background Task to get the all the refs for the repository.

When I continue the "contained in branches" information is not visible for any given commit.

## Error Details

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at GitUI.CommitInfo.CommitInfo.GetSortedRefs()
   at GitUI.CommitInfo.CommitInfo.<LoadSortedRefsAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommitInfo.CommitInfo.<<RefreshSortedRefs>b__48_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

running GitExtensions from source via Visual Studio in Debug mode gives the following stacktrace:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at void System.Collections.Generic.Dictionary<TKey, TValue>.Insert(TKey key, TValue value, bool add)
   at IDictionary<string, int> GitUI.CommitInfo.CommitInfo.GetSortedRefs() in C:/development/tools/gitextensions/GitUI/CommitInfo/CommitInfo.cs:line 228
   at async Task GitUI.CommitInfo.CommitInfo.LoadSortedRefsAsync() in C:/development/tools/gitextensions/GitUI/CommitInfo/CommitInfo.cs:line 243
   at async void GitUI.CommitInfo.CommitInfo.RefreshSortedRefs()+(?) => { } in C:/development/tools/gitextensions/GitUI/CommitInfo/CommitInfo.cs:line 151
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext() in C:/development/tools/gitextensions/GitExtUtils/GitUI/ThreadHelper.cs:line 101
```

## Expected behaviour

GitExtensions should not throw the Exception and should be able to handle duplicate refs. E.g. by ignoring the duplicates. The workaround is to clean up those refs via a purge, but maybe GitExtensions could also support this (malformed/invalid/unexpected) output

## Steps to reproduce

In `.git/packed-refs` I seems to have duplicate entries with different revisions:

```
15a5742e180f6ac78ada5fb424692e4648985a03 refs/remotes/svn-branch/7.0-VI-UX
83b1c5c96c81c0da08f6bdd3606fd9c89d426448 refs/remotes/svn-branch/7.0-trunk
85bd3ed9a30f9d0895094ebf662a4aaec879f678 refs/remotes/svn-branch/7.0-VI-UX
```

The following git commands will also show these duplicates in my repository

```
git for-each-ref --format="%(refname)" refs/
git show-ref
```

Doing a purge of old branches will probably solve the issue. I also use git-svn on this repository, maybe that is related as well.

## Screenshots

No screenshot, the stacktrace should point us in the right direction.

## Did this work in previous version of GitExtensions

GitExtensions 2.x didn't have this problem, or my repo didn't have this problem.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by rickaas** [comment]
A basic pull-request with testcase is on its way :)
