### ISSUE TITLE
protocol error using ssh in gitext only

### ISSUE THREAD

**Issue by ps-simonsparkes** [gitextensions/gitextensions#7378]
## Current behaviour

I have a repository with the following config:

```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = ssh://simon@10.1.0.9/volume1/git/FltkPlus
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

If I do a git pull from the Git Extensions I get the following output:
```
"C:\Program Files\Git\bin\git.exe" pull --progress "origin"
fatal: protocol error: bad line length character: simo
Done

Press Enter or Esc to close console...
```

BUT If I run git pull from the windows command line everything works fine with the following output:

`Already up to date.`

The following is a screenshot of the Remote repositories

![2019-11-04](https://user-images.githubusercontent.com/57355583/68122212-bcda8b00-ff01-11e9-853a-fb4a779ab40d.png)

## Did this work in previous version of GitExtensions

Not sure

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Anything in the GE Git command log?

**Comment by ps-simonsparkes** [comment]
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   pull --progress "origin"
Working dir: D:\3rdParty\SwiftTec\FltkPlus\
Process ID:  unknown
Started at:  2019-11-05T07:13:49.3824361+00:00
UI Thread?:  True
Duration:    1670.825 ms
Exit code:   1
Call stack: 
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitUI.UserControls.ConsoleEmulatorOutputControl.StartProcess(String command, String arguments, String workDir, Dictionary`2 envVariables)
   at GitUI.FormProcess.ProcessStart(FormStatus form)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.ShowWindow(HandleRef hWnd, Int32 nCmdShow)
   at System.Windows.Forms.SafeNativeMethods.ShowWindow(HandleRef hWnd, Int32 nCmdShow)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPull.PullChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPull.PullAndShowDialogWhenFailed(IWin32Window owner, String remote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass89_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.DoPull(PullAction pullAction, Boolean isSilent)
   at System.Windows.Forms.ToolStripSplitButton.OnButtonClick(EventArgs e)
   at System.Windows.Forms.ToolStripSplitButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

**Comment by gerhardol** [comment]
ssh://user@address does not seem to be supported right now. Try PuTTY (I did not get it working either at a quick test though)
Can you use a git:// url instead?

**Comment by ps-simonsparkes** [comment]
Unfortunately the git:// url will not work, but I do have access via network share using local protocol so I can get around it until it is fixed. I can also work with the command line version using ssh as this works ok.

**Comment by RussKie** [comment]
> ssh://user@address does not seem to be supported right now

Do you know which piece of code is responsible for that?

**Comment by mstv** [comment]
It works for me with OpenSSH (and ConEmu active). Though my username is just "m" at the available Linux box. My git config looks almost identical.
Could you try again without the ConEmu, @ps-simonsparkes?
![grafik](https://user-images.githubusercontent.com/36601201/68324402-95351f80-00c7-11ea-860d-10dc50ebd0cb.png)

**Comment by ps-simonsparkes** [comment]
Same result.

![image](https://user-images.githubusercontent.com/57355583/68382614-fd2d4980-014b-11ea-9df6-784e2817f416.png)

If I run the exact same command in a command prompt

![image](https://user-images.githubusercontent.com/57355583/68382763-48475c80-014c-11ea-8d18-9ab9477f47d5.png)

**Comment by ps-simonsparkes** [comment]
On further investigation I realised that I can do an ssh to the server without issue from a command prompt from both putty and the built-in ssh in Windows 10 (which turns out to be OpenSSH). So I changed the settings in GitExt SSH section from PuTTY to OpenSSH and it started to work.

So what I then did was to generate a new key using the key generation tool, added the new private key under the PuTTY settings and pasted the public key into the authorized_keys2 file on the server. It then started to work with PuTTY setting.

So the original message I got about bad protocol was very confusing.

It should be noted that when I cloned the original repository I did so via the command line (as is my normal practice) which is why I did not think to set up the PuTTY key. I just expected GitExt to work with the repository as worked from the command line.

**Comment by mstv** [comment]
Thank you for the investigation! Using PuTTY, I can reproduce it -- also on the command line which I started from Git Extensions.
It sets the environment variable `GIT_SSH=C:\Program Files\GitExtensions\PuTTY\plink.exe`.
I guess it is an unlucky handling of the output from PuTTY by Git.
Report this to the Git team, please.
