### ISSUE TITLE
"Invoke or BeginInvoke cannot be called on a control until the window handle has been created" exception after closing commit dialog opened from Windows Explorer

### ISSUE THREAD

**Issue by loop-evgeny** [gitextensions/gitextensions#7385]
## Current behaviour

After closing the commit dialog opened from Windows explorer a "Git Extensions has stopped working" crash dialog is shown.

## Expected behaviour

No crash.

## Steps to reproduce

From the Windows Explorer context menu of a git-tracked file select File History. Click on the Commit tab. Close the window.

## Did this work in previous version of GitExtensions

Yes. Not sure, but fairly recent (definitely 3.x).

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

## Diagnostics

Exception details (from attaching Visual Studio):

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(SendOrPostCallback d, Object state)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c__DisplayClass5_0.<Connect>b__0()
   at System.Reactive.Disposables.AnonymousDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.ObserveOnObserver`1.Dispose(Boolean disposing)
   at System.Reactive.ObserverBase`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at GitUI.CommitInfo.CommitInfoHeader.DisposeCustomResources()
   at GitUI.GitModuleControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

**Comment by gerhardol** [comment]
The exception occurs when closing down the form.
For some reason the control cannot cancelled.
Should this be called only if disposing in Dispose() is true?
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommitInfo/CommitInfo.cs#L828

**Comment by RussKie** [comment]
I can't replicate it. Looking at the stack trace, I think it is a pure timing thing, while a we are attempting to close the form and dispose the control, something is trying to pump events to the UI thread.
I propose we wrap it in a try..catch

**Comment by RussKie** [comment]
Actually, I could repro the issue locally, the error was written into the eventlog.
After updating Reactive packages from 3.1.1 to 4.2.0 the issue seems to be gone.
