### ISSUE TITLE
Test RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder fails

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7393]
## Current behaviour

Build https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28729159 failed because of test

```
1) Error : GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder
System.AggregateException : One or more errors occurred.
  ----> System.ArgumentException : Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Array+FunctorComparer`1[GitUI.UserControls.RevisionGrid.Graph.RevisionGraphRevision]'.
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder() in C:\projects\gitextensions\UnitTests\GitUITests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 62
--ArgumentException
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedNodesCache(Int32 currentRowIndex) in C:\projects\gitextensions\GitUI\UserControls\RevisionGrid\Graph\RevisionGraph.cs:line 329
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.GetNodeForRow(Int32 row) in C:\projects\gitextensions\GitUI\UserControls\RevisionGrid\Graph\RevisionGraph.cs:line 123
   at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.Render() in C:\projects\gitextensions\UnitTests\GitUITests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 113
   at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.<ShouldReorderInTopoOrder>b__5_2() in C:\projects\gitextensions\UnitTests\GitUITests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 56
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
Run Settings
    DisposeRunners: True
    WorkDirectory: C:\projects\gitextensions
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 2
Test Run Summary
  Overall result: Failed
  Test Count: 1968, Passed: 1965, Failed: 1, Warnings: 0, Inconclusive: 1, Skipped: 1
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
    Skipped Tests - Ignored: 1, Explicit: 0, Other: 0
  Start time: 2019-11-08 23:25:09Z
    End time: 2019-11-08 23:30:57Z
    Duration: 347.672 seconds
```

## Expected behaviour

tests pass, CI build succeeds

## Steps to reproduce

? trigger many AppVeyor builds

## Did this work in previous version of GitExtensions

don't know

## Environment

Merge pull request (#)7343 from meaney/syntax_highlight
Show syntax highlighting also when displaying a diff
3.3.0.7192
2 hours ago by msftbot[bot] (committed by GitHub)
master 764aabaf

**Comment by mstv** [comment]
It seems that the failed test was the very first test executed:
![grafik](https://user-images.githubusercontent.com/36601201/68518262-78e1e000-028b-11ea-94f9-502a4e40a817.png)

**Comment by pmiossec** [comment]
>It seems that the failed test was the very first test executed:

What is the thing that let you think that it's the first test run that fails? 

For me, Appveyor just display the failed tests first to let the user see the result more easily. And the logs seems to confirm that it is not the first test run.

**Comment by mstv** [comment]
> For me, Appveyor just display the failed tests first to let the user see the result more easily.

Good point.

> And the logs seems to confirm that it is not the first test run.

Where did you find them?

> What is the thing that let you think that it's the first test run that fails?

See screenshot.

**Comment by pmiossec** [comment]
> And the logs seems to confirm that it is not the first test run.
>
> Where did you find them?
>
OH, sorry, I was just talking about the console output where we could see
that some tests output before the one failing.


What is the thing that let you think that it's the first test run that
> fails?
>
> See screenshot.
>

Thanks, that was to be sure that there was not another source of
information that I didn't know.

So I'm pretty sure that the test is only displayed first because it failed.

>

**Comment by mstv** [comment]
> So I'm pretty sure that the test is only displayed first because it failed.

Yes, in the meantime, I've seen the failed test being inserted in front of the list (Nikolay's build).

> console output where we could see that some tests output before the one failing.

Failed tests are printed afterwards.

**Comment by RussKie** [comment]
I don't believe the test is failing consistently, so it is more a red herring than a culprit.

**Comment by mstv** [comment]
> I don't believe the test is failing consistently, so it is more a red herring than a culprit.

I cannot agree. `IComparer.Compare()` _must_ return consistent results. It is a multi-threading test, which might fail under rare circumstands only. Everything else worked well.

**Comment by RussKie** [comment]
I suppose it should be easy to test - disable the test and see if we get
any more hangs :)

**Comment by mstv** [comment]
This test did not hang -- it _failed_ with a valid Exception.

**Comment by mstv** [comment]
Failed again: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/44053525
