### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mx-bernhard** [gitextensions/gitextensions#7450]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.Script.ScriptOptionsParser.CalculateSelectedRevision(RevisionGridControl revisionGrid, List`1 selectedRemoteBranches, List`1 selectedRemotes, List`1 selectedLocalBranches, List`1 selectedBranches, List`1 selectedTags)
   at GitUI.Script.ScriptOptionsParser.Parse(String argument, IGitModule module, IWin32Window owner, RevisionGridControl revisionGrid)
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, GitModule module, ScriptInfo scriptInfo, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   at GitUI.RevisionGridControl.<RefreshOwnScripts>g__RunScript|207_2(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Happend when executing my custom merge-branch-back-to-develop-script before the console window was visible.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by mx-bernhard** [comment]
# Current behaviour

It crashes.

# Expected behaviour

It should not crash.

# Steps to reproduce
The crash happend when executing my custom merge-branch-back-to-develop-script before the console window was actually visible. 
I don't know if it is important but here goes anyway:
I did this right after doing a rebase with "selected commit with advanced options.." (using a range similar to this: `feature/topic~1..feature/topic`) i. e. I was rebasing only the top commit of the branch back to develop.
When I restarted GitExtensions I could execute my merge script just fine without any crashes.
