### ISSUE TITLE
[NBug] A generic error occurred in GDI+.

### ISSUE THREAD

**Issue by drakor007** [gitextensions/gitextensions#7461]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass54_0.<.ctor>b__13(Object s, GitWorkingDirectoryStatusEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass39_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass39_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
?

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
First time reported
It could be caused by leaking handles
However, a description on how to reproduce will be needed to investigate
