### ISSUE TITLE
NRE testing CommitAutoCompleteProvider

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7473]
## Current behaviour

```
System.Reflection.Assembly.GetEntryAssembly(...) returned null.

System.NullReferenceException
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=GitUI
  StackTrace:
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.ReadOrInitializeAutoCompleteRegexes() in F:\Build\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 84
   at GitUI.AutoCompletion.CommitAutoCompleteProvider.ParseRegexes() in F:\Build\gitextensions\GitUI\AutoCompletion\CommitAutoCompleteProvider.cs:line 98
   at System.Lazy`1.CreateValue()
```

## Expected behaviour

no NRE

## Steps to reproduce

_Debug_ tests, especially `FormCommitTests`.

## Did this work in previous version of GitExtensions

probably no

## Environment

- Git Extensions 3.3.0
- Build 69763de058580d0dbf84be9a2d725b1719f607c6
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

## Diagnostics

```
	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.ReadOrInitializeAutoCompleteRegexes() Line 84	C#
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.ParseRegexes() Line 98	C#
 	[External Code]	
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.GetRegexForExtension(string extension) Line 72	C#
 	GitUI.dll!GitUI.AutoCompletion.CommitAutoCompleteProvider.GetAutoCompleteWordsAsync(System.Threading.CancellationToken cancellationToken) Line 38	C#
 	[Resuming Async Method]	
 	[External Code]	
 	GitCommands.dll!GitCommands.ExecutableExtensions.GetOutputAsync(GitUIPluginInterfaces.IExecutable executable, GitCommands.ArgumentString arguments, byte[] input, System.Text.Encoding outputEncoding, GitCommands.CommandCache cache, bool stripAnsiEscapeCodes) Line 151	C#
 	[Resuming Async Method]	
 	[External Code]	
 	GitCommands.dll!GitCommands.Executable.ProcessWrapper.OnProcessExit(object sender, System.EventArgs eventArgs) Line 116	C#
 	[External Code]	
 	[Async Call Stack]	
 	[External Code]	
 	[Async] GitUI.dll!GitUI.SpellChecker.EditNetSpell.InitializeAutoCompleteWordsTask.AnonymousMethod__109_0() Line 870	C#
 	[External Code]	
```

**Comment by RussKie** [comment]
A fix to this would be to move AutoCompleteRegexes.txt from GitExtensions project to GitUI project and modify the code to something like:
```cs
Stream s = typeof(CommitAutoCompleteProvider).Assembly.GetManifestResourceStream("GitExtensions.AutoCompleteRegexes.txt");
```

However this failure is happening under a very specific scenario, which isn't expected to occur in a course of general use. So I'm not sure it is worth fixing.
During your debug sessions you can probably put some temp guards around it.
