### ISSUE TITLE
[NBug] Error reading the \\omv\Downloads\Powershell_Scripts\Master...

### ISSUE THREAD

**Issue by Galapagon** [gitextensions/gitextensions#7484]
## Error Details
```
System.IO.FileNotFoundException: Error reading the \\omv\Downloads\Powershell_Scripts\Master User Script\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6812
Corrected in 3.2
