### ISSUE TITLE
[NBug] The file exists.

### ISSUE THREAD

**Issue by lerthe61** [gitextensions/gitextensions#7486]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.SaveAndRescan_Click(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.MergeToolFix_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Open Global Settings, click on MergeTool (it is displayed that my mergetool is KDiff3 but when I trying to merge anything vsmerge opening instead)

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
The exception occurs when trying to get a temp file to store a backup of the settings in.
What is temp, is the directory writable?
(There has been several changes here in 3.2 and upcoming in 3.3. I see none of them affecting this problem. Before 3.2 the tempfile was created in the same directory as the settings file.)
