### ISSUE TITLE
[NBug] No application is associated with the specified file for th...

### ISSUE THREAD

**Issue by 1C-Romania** [gitextensions/gitextensions#7499]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): No application is associated with the specified file for this operation
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c.<diffOpenRevisionFileToolStripMenuItem_Click>b__53_0(String fileName)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c__DisplayClass55_0.<<SaveSelectedItemToTempFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
is it Exception?  8-(

## E

**Comment by RussKie** [comment]
You're trying to execute an action (e.g. open a file) for which Windows
doesn't have association for.
E.g. *.txt file needs to be associated with likes of Notepad, email links
with Outlook, urls with a browser etc.

**Comment by RussKie** [comment]
Duplicate of #7156
