### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: key

### ISSUE THREAD

**Issue by gritcsenko** [gitextensions/gitextensions#7519]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
   at GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Updated Jira settings and pressed apply

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6704

Also no information (as in other duplicates), stack trace looks the same so probably not a new problem
