### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JimmXY** [gitextensions/gitextensions#7522]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at JiraCommitHintPlugin.JiraCommitHintPlugin.<>c__DisplayClass23_0.<GetSettings>b__0(Object s, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
After today's update, when auto opening KDiff3 from the resolve merge conflicts window results in opening KDiff3 WITHOUT ANY FILE selection. Was trying to fix that to no avail.

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The exception is in JiraCommitHint. @pmiossec  cleaned up there, any hints of what the problem is?
Otherwise, some way to reproduce the exception is needed.

The mergetool problem is something separate, should be handled in a separate issue.
The mergetools settings and what type of merge that was attempted is needed.

**Comment by pmiossec** [comment]
>The exception is in JiraCommitHint. @pmiossec cleaned up there, any hints of what the problem is?

Looking at the code, I think I understand. It's seems to be there from the beginning. 

We could remove the use of the event handler subscription and prevent the bug.
PR will follow...
