### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by tkingsbury42** [gitextensions/gitextensions#7533]
## Current behaviour

I press the Push toolbar button to upload my code and I see this exception. This is consistently reproducible. This was working great in my older version before I upgraded to 3.3.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
.

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by tkingsbury42** [comment]
Duplicate of #7521
