### ISSUE TITLE
[NBug] Access to the path 'D:\repos\insurancequoting.esb.racq.com\...

### ISSUE THREAD

**Issue by willemsevenster** [gitextensions/gitextensions#7535]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UnauthorizedAccessException: Access to the path 'D:\repos\insurancequoting.esb.racq.com\.git\COMMITMESSAGE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)

**Comment by gerhardol** [comment]
Duplicate of #6908 

The stack trace is truncated and there are no version information.
This seem to be that the user do not have access to the repo file (like if it is cloned by admin and the user do not have access).
