### ISSUE TITLE
[NBug] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by randomvi** [gitextensions/gitextensions#7553]
## Current behaviour

crashes after updating to the latest version and clicking refresh

## Expected behaviour

refresh git repositories and get latest changes

## Steps to reproduce

update git extension to the latest version, then after it loads, click refresh, then it crashes.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormBrowse.RefreshDashboardToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
update git extension, then after it loads, click refresh, then it crashes

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by randomvi** [comment]
hi, i have edited the issue

**Comment by randomvi** [comment]
> Thank you for the bug report 👍
> 
> Sadly, it appears some important information is still missing, which you may have overlooked while submitting the bug.
> Without this information we may not be able to assist you in resolving the issue.
> 
> Please review your submission, fill the missing information in and post a new comment to ping us back to re-open the issue.
> Thanks again

**Comment by gerhardol** [comment]
Cannot reproduce

Is this 
![image](https://user-images.githubusercontent.com/6248932/71353588-c7b4b200-2579-11ea-84de-72bea8727293.png)

This is the only code where the refresh is called, but the dashboard is already active.

**Comment by randomvi** [comment]
Yes, Pressing that immediately after upgrading Git Extensions.
