### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by en3on** [gitextensions/gitextensions#7574]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour
Upon opening PuTTY Authentication Agent screen, I receive an error.
Additionally, I was receiving errors about PuTTY not being correctly configured

## Expected behaviour
Open PuTTY Authentication Agent screen

## Steps to reproduce
After updating Git Extensions, I navigated to Tools > PuTTY > Start Authentication Agent

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitUI.CommandsDialogs.FormBrowse.StartAuthenticationAgentToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Updated to 3.3.0.7719 this morning

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by en3on** [comment]
Check it bot 👍

**Comment by RussKie** [comment]
I think we need to do the following:
* create a custom exception similar to `FileDeleteException` that contains the information for what process (with what args?) couldn't be executed
* look at all `GitCommands.Executable.Start` callsites and  handle the new exception to display a clear message to a user. I thought I remembered we had a PR that dealt with a  similar problem (for submodules?), but I can't find it, nor remember what exception it was... 😕 

@gitextensions/git-extensions-team thoughts?

**Comment by mstv** [comment]
> look at all GitCommands.Executable.Start callsites and handle the new exception to display a clear message to a user. I thought I remembered we had a PR that dealt with a similar problem (for submodules?), but I can't find it, nor remember what exception it was...

Not exactly: #7739, #7576? But I opened the generic issue #6527 for this.

**Comment by RussKie** [comment]
Thank you, yep, not exactly. I think it was something to do with submodules, but I couldn't find anything...
Thank you for #7795 👍
