### ISSUE TITLE
[NBug] The process cannot access the file 'db.lock' because it is ...

### ISSUE THREAD

**Issue by manuelspezzani** [gitextensions/gitextensions#7579]
## Current behaviour
GitExtensions crashed trying to remove an existing worktree (repository --> worktrees --> manage worktrees) while a file was locked by another application.

## Expected behaviour
An error is presented to the user and the worktree is not deleted.

## Steps to reproduce
- open an existing repository 
- create a new worktree
- lock any file on the new worktree (in my case, 'db.lock')
- go to repository / worktrees / manage worktrees
- delete the new worktree before releasing the lock

## Error Details
```
System.IO.IOException: The process cannot access the file 'db.lock' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at GitUI.CommandsDialogs.WorktreeDialog.FormManageWorktree.Worktrees_CellClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Related to #6630 and #7170 

All these should probably just catch the exception and continue, nothing much can be done about
The workaround is just to dismiss NBug
