### ISSUE TITLE
[NBug] Could not load type 'GitCommands.GitArgumentBuilder' from a...

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#7606]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

I tried to publish to Gerrit

I use an older version of gerrit and replaced the gerrit.dll, by the old one (version 2.13.6)

## Error Details
```
System.TypeLoadException: Could not load type 'GitCommands.GitArgumentBuilder' from assembly 'GitExtUtils, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null'.
   at Gerrit.FormGerritPublish.PushCmd(String remote, String toBranch)
   at Gerrit.FormGerritPublish.PublishChange(IWin32Window owner)
   at Gerrit.FormGerritPublish.PublishClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
publish to older gerrit version not working

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
You probably need to use 3.2.1 with the old Gerrit .dll
