### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DougSchmidt-AI** [gitextensions/gitextensions#7627]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormBrowse.RefreshDashboardToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
First launch after upgrade.
Entire workspace view was blank.
Click on the "Dashboard" menu item to try and refresh the view, and KABOOM

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7553
