### ISSUE TITLE
[NBug] Could not find any resources appropriate for the specified ...

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#7661]
## Current behaviour
Switching to console tab or running any processes fail.

## Expected behaviour
Console works like it did in release/3.3

## Steps to reproduce

1. Checkout release/3.3
1. Clean working directory
1. Run Setup\build.cmd Debug
1. Run the git extensions program that was built.
1. Switch to console tab
1. Note it works
1. Checkout this commit and repeat steps
1. Note you get an app crash

## Error Details
```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "ConEmu.WinForms.Resources.resources" was correctly embedded or linked into assembly "ConEmuWinForms" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at ConEmu.WinForms.Resources.get_ConEmuSettingsTemplate()
   at ConEmu.WinForms.ConEmuStartInfo.get_BaseConfiguration()
   at GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__210_0(Object sender, TabControlCancelEventArgs args)
   at System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Somewhere between release/3.3 and 56b6a09ea7d245809a119f51554a091c4dd324f1 The console is broken

## Environment
- Git Extensions 3.3.0
- Build 56b6a09ea7d245809a119f51554a091c4dd324f1
- Git 2.25.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Updated

**Comment by vbjay** [comment]
updated

**Comment by vbjay** [comment]
I ran a bisect.  Looks like 6212917317b05d9ef75d2bae7036e8c737f5cf39 is the merge that broke it.

**Comment by vbjay** [comment]
No processes run either

![image](https://user-images.githubusercontent.com/3629489/72733908-d5ecf280-3b66-11ea-913e-1890acb19713.png)

**Comment by RussKie** [comment]
I'll have a look

**Comment by vbjay** [comment]
I figured it out.  It looks like switching to sdk style needed some touching by opening the resources designer and switching access modifier to public and back to make it update items.  Then it also lacked a namespace import.  I'll send in a pull request in a few.
