### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#7671]
## Current behaviour

If I click on an not physically existing sub module a crash occurs 

## Expected behaviour

don't crash, handle the error somehow

## Steps to reproduce

setup a submodule
remove the folder
click on this submodule

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.ConfigFileSettings.CreateLocal(GitModule module, ConfigFileSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.GitModule.get_EffectiveConfigFile()
   at GitCommands.GitModule.get_FilesEncoding()
   at GitUI.Editor.FileViewer.encodingToolStripComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I deleted the submodule folder manually and does a double click on it on the left side bar

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Similar as #7231, this has actually some information

**Comment by gerhardol** [comment]
Similar to #9091 (not exactly the same, changes since 3.2)
Forward duplicate, continue discussion there.
Please try 3.5 RC1 where the error is displayed with more details
