### ISSUE TITLE
Test GitModuleTests.GetSuperprojectCurrentCheckout fails

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7681]
## Current behaviour

The test `GitCommandsTests.GitModuleTests.GetSuperprojectCurrentCheckout` fails randomly:
```
  Expected: 32
  But was:  '-'
   at GitCommandsTests.GitModuleTests.<>c__DisplayClass40_0.<<GetSuperprojectCurrentCheckout>b__0>d.MoveNext() in C:\projects\gitextensions\UnitTests\GitCommandsTests\GitModuleTests.cs:line 732
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
```

## Expected behaviour

test passes always

## Environment

- AppVeyor
- Windows 10

**Comment by gerhardol** [comment]
https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-status--cached--recursive--ltpathgt82308203

Sometimes the submodule is init (space==32), sometimes not (-).

**Comment by RussKie** [comment]
@mstv are you observing these failures locally? I haven't seen these failures myself.
Are you able to find more information, e.g. is it failing for the same submodule or not, is there some pattern to failures?

**Comment by mstv** [comment]
The tests run stable locally. Most recent fail: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/30350381.
IIUIC the test `GitCommandsTests.GitModuleTests.GetSuperprojectCurrentCheckout` has only one submodule, which is created in a temporary test repo.
