### ISSUE TITLE
[NBug] Collection was modified; enumeration operation may not exec...

### ISSUE THREAD

**Issue by cphillips25132** [gitextensions/gitextensions#7689]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.SelectRowsIfReady(Int32 rowCount)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundThreadEntry>g__UpdateRowCount|48_2(Int32 row)
   at GitUI.GitUIExtensions.<InvokeAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Had a checkout window open while unity was doing stuff

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7067 

No known way to recreate
