### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by tgouala** [gitextensions/gitextensions#7728]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Git extension crash when I add several push url to the remote origin through the CLI

## Expected behaviour

Git extension should not crash

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|154_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<<UICommands_PostRepositoryChanged>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When using several pushurl in config file, git extension will crash,

[remote "origin"]
	
url = https://***.git
	
fetch = +refs/heads/*:refs/remotes/origin/*
	
pushurl = https://*******	
pushurl = https://*******

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Fixed.
Please update to the last version of GitExtensions.
