### ISSUE TITLE
[NBug] Shell Exception has occurred, look at inner exception for i...

### ISSUE THREAD

**Issue by Teterevkova** [gitextensions/gitextensions#7755]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
Microsoft.WindowsAPICodePack.Shell.ShellException (0x80070008): Shell Exception has occurred, look at inner exception for information.
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.UpdateThumbnailButton()
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.set_Enabled(Boolean value)
   at GitUI.WindowsJumpListManager.DisableThumbnailToolbar()
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I just opened it and it crashed

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4121.0
- DPI 216dpi (225% scaling)

**Comment by gerhardol** [comment]
Duplicate of #7783
