### ISSUE TITLE
Crash on start-up after setting 'dark' theme (development build of master)

### ISSUE THREAD

**Issue by wplpgr** [gitextensions/gitextensions#7763]
## Current behaviour

**Exception Type:** System.NullReferenceException
("Object reference not set to an instance of an object.")

**Target site:** Int32 DrawThemeBackgroundHook(IntPtr, IntPtr, Int32, Int32, RECT ByRef, RECT ByRef) @ GitUI.Theming.Win32ThemeHooks

**Stack trace:**
```
   at GitUI.Theming.Win32ThemeHooks.DrawThemeBackgroundHook(IntPtr htheme, IntPtr hdc, Int32 partid, Int32 stateid, RECT& prect, RECT& pcliprect)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Running under the debugger, it appears that the argument that it is complaining about is `pcliprect`

## Expected behaviour

Not crashing.

## Steps to reproduce

I can't guarantee that this will reproduce the problem, but it is how I got into this state...

- Build master (in my case, 8bb539816ba552ac7fb1a6cff145d56b29a1a9c3).
- Start gitextensions.
- Set the theme to 'dark'.
- Restart gitextensions.

The main dialog appears (with the revision grid, branches, and commit information all populated), and then terminates with the exception above.

## Did this work in previous version of GitExtensions

git bisect'ing identifies that commit 1dfd8e4d73c95e856316df2f20ccd3dd2f92b88a is the commit that introduced this behaviour.

## Environment

- GitExtensions version: 8bb539816ba552ac7fb1a6cff145d56b29a1a9c3
- GIT version: 2.25.0.windows.1
- OS version: Windows 10.0.18363
- .NET version: .NET Framework 4.8.4075.0
- Built with: Visual Studio 2019 (16.4.1)

**Comment by gerhardol** [comment]
This is fixed in the existing #7562
Closing, that should be merged soon
