### ISSUE TITLE
[NBug] Shell Exception has occurred, look at inner exception for i...

### ISSUE THREAD

**Issue by boris-papevis-aurea** [gitextensions/gitextensions#7783]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
Microsoft.WindowsAPICodePack.Shell.ShellException (0x80070008): Shell Exception has occurred, look at inner exception for information.
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.UpdateThumbnailButton()
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.set_Enabled(Boolean value)
   at GitUI.WindowsJumpListManager.DisableThumbnailToolbar()
   at GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Crash on start. This occurred two times, GitExtensions started normally the third time.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by boris-papevis-aurea** [comment]
Updated the issue

**Comment by gerhardol** [comment]
Similar problems have occurred a few times, added duplicates
The core problem may not be the same for these though, the inner exception is not tracked, see #6762
