### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by gregsohl** [gitextensions/gitextensions#7789]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

From the menu, clicked Tools / Putty / Generate or import key.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitUI.CommandsDialogs.FormBrowse.GenerateOrImportKeyToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMou

**Comment by gerhardol** [comment]
The path to PuTTYGen seem to be incorrectly configured

**Comment by gerhardol** [comment]
Duplicate of #7167
