### ISSUE TITLE
System.ArgumentOutOfRangeException ScrollBar.set_Value

### ISSUE THREAD

**Issue by MarekKnapek** [gitextensions/gitextensions#7836]
## Current behaviour

Diff window sometimes displays exception with stack trace when selecting different commit.

## Expected behaviour

Diff window should display a diff, not an error message.

## Steps to reproduce

1. Open Git Extensions.
1. Open some repository.
1. Select some commit.
1. Select Diff tab/card in lower panel.
1. Scroll the diff down a bit.
1. Select different commit.
1. The different commit has the same files changed in it. But possible on different lines.
1. Instead of diff, there is an exception message [1].

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4069.0
- DPI 96dpi (no scaling)

I'm using portable version of Git Extensions and portable version of Git 64bit on Windows 7 64bit.

Best Regars,
Marek Knápek

Attachement [1]
```
Unsupported file: 

System.ArgumentOutOfRangeException: Value of '765' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ScrollBar.set_Value(Int32 value)
   at ICSharpCode.TextEditor.TextArea.set_VirtualTop(Point value)
   at ICSharpCode.TextEditor.TextView.set_FirstVisibleLine(Int32 value)
   at GitUI.Editor.FileViewerInternal.CurrentViewPositionCache.Restore(Boolean isDiff)
   at GitUI.Editor.FileViewerInternal.SetText(String text, Action openWithDifftool, Boolean isDiff)
   at GitUI.Editor.FileViewer.<>c__DisplayClass102_0.<ViewPatch>b__1()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitUI.Editor.FileViewer.ViewPatch(String text, Action openWithDifftool, String filename)
   at GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

**Comment by MarekKnapek** [comment]
Could be reproduced with latest master build 4.0.0.8708 downloaded from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/31177091/artifacts. I needed to change position of the commits/lower pane divider a little bit.

- Git Extensions 4.0.0.8708
- Build 9ed8ab37d7baa2e2f6d85b894ceb058353120440 (Dirty)
- Git 2.17.1.windows.2 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4069.0
- DPI 96dpi (no scaling)

**Comment by MarekKnapek** [comment]
## Error Details
```
System.ArgumentOutOfRangeException: Value of '884' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at void System.Windows.Forms.ScrollBar.set_Value(int value)
   at void ICSharpCode.TextEditor.TextArea.set_VirtualTop(Point value) in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextArea.cs:line 136
   at void ICSharpCode.TextEditor.TextView.set_FirstVisibleLine(int value) in C:/projects/gitextensions/Externals/ICSharpCode.TextEditor/Project/Src/Gui/TextView.cs:line 45
   at void GitUI.Editor.FileViewerInternal.set_FirstVisibleLine(int value)
   at void GitUI.Editor.FileViewerInternal+CurrentViewPositionCache.Restore(bool isDiff)
   at void GitUI.Editor.FileViewerInternal.SetText(string text, Action openWithDifftool, bool isDiff)
   at Task GitUI.Editor.FileViewer.ViewPatchAsync(string fileName, string text, Action openWithDifftool, bool isText)+() => { }
   at Task GitUI.Editor.FileViewer.ShowOrDeferAsync(long contentLength, Func<Task> showFunc)
   at async Task GitUI.Editor.FileViewer.ViewPatchAsync(string fileName, string text, Action openWithDifftool, bool isText)
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync()
   at async void GitUI.CommandsDialogs.RevisionDiffControl.DiffFiles_SelectedIndexChanged(object sender, EventArgs e)+(?) => { }
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```


## Environment
- Git Extensions 4.0.0.8708
- Build 9ed8ab37d7baa2e2f6d85b894ceb058353120440 (Dirty)
- Git 2.17.1.windows.2 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4069.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Since you can recreate and build, do you have a possibility to find what the max/min is set to?
The following change on line 134 should fix the problem, but not scroll correctly

var newVirtualTop = new Point(value.X, Math.Min(virtualTop.Y, Math.Min(MaxVScrollValue, Math.Max(val1: 0, value.Y))));

**Comment by MarekKnapek** [comment]
Eh, I never tried to build/compile the Git Extensions (but I can try), I just downloaded the latest build from AppVeyor and checked if this was already fixed or not. I guess the min and max values are set from previously displayed diff.

**Comment by MarekKnapek** [comment]
I successfully attached a debugger (Visual Studio) the the running Git Extensions version 4.0.0.8708 and set it to break when an exception is thrown. File \Externals\ICSharpCode.TextEditor\Project\Src\Gui\TextArea.cs, line 137, variable MotherTextAreaControl.VScrollBar is Value = 0, Min = 0, Max = 340, variable virtualTop is X = 0, Y = 374.

**Comment by MarekKnapek** [comment]
Another observation: When I select a file, diff should appear on the right. My particular diff is that there is one change in the file beginning and one change much later in the file. I left the "Show entire file" option in default settings (so I'm not bothered with the middle of the file). So in the diff view there is a gap, let's say between line 44 and 350, filled with gray line starting with @@. I can scroll the diff down and up. So far so good, everything works as expected.

Now, I maximize the Git Extensions window and adjust the divider between upper and lower half so that the gray line is half visible on the screen. Then I switch to another commit and back. Now I cannot see any scrollbar - that is a BUG. Now when I switch to another commit, scroll down the diff and switch back - an exception is throw.

**Comment by RussKie** [comment]
Can you share screenshots please?
Blur out the content, if necessary.

**Comment by RussKie** [comment]
I just experienced the same issue... Just clicked around, and it happened.

**Comment by RussKie** [comment]
It is intermittent, but something along the lines of:

* Have few commits that changed the same file, but have different size of changes (e.g. one changed many lines, and another few lines)
* When switching between the commits there is a chance that this exception can be triggered.

I had a repro, but as soon as I changed the size of the app, the issue no longer repros...
