### ISSUE TITLE
A lot of Exception when trying to load `XmlSerializer`

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7854]
## Current behaviour

A lot (at least 9) of silent FileNotFoundException are thrown when trying to load `XmlSerializer` class with a strange behavior where it try to load the class from different and sometimes not existing assemblies.

It need to be investigated but I imagine that some data are not well loaded.

## Expected behaviour

No exception. Or an answer to this strange behaviour.

## Steps to reproduce

- Enable all `Common language Runtime Exceptions` in Exceptions Settings in VisualStudio (except `TaskCanceledException` because that makes the debugging impossible)
- Run the application in debug.

## Did this work in previous version of GitExtensions

I don't know and that's what worries me a little...

## Environment

- GitExtensions version: `master`

## Diagnostics

I really don't know but it seems strange

**Comment by RussKie** [comment]
Stack traces could be useful

**Comment by pmiossec** [comment]
>Stack traces could be useful

The 9 ones (from different places)? 

I'm not sure because you have to see it with your own eyes to really grasp what is at stake... 😮

But I will put one the next time I get it.

**Comment by pmiossec** [comment]
Note that the program try to load the class from different assemblies... 

In `TranslationSerializer.cs`

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'ResourceManager.XmlSerializers, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
```

In `ScriptManager.cs`:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)```

In `WindowPositionList.cs`:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'GitUI.XmlSerializers, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
```

**Comment by RussKie** [comment]
Ah, these can be pre-generated. I don't think these are terribly important to worry about.
https://stackoverflow.com/q/17755559

**Comment by pmiossec** [comment]
I learned something today.
