### ISSUE TITLE
NRE on Ctrl+A

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7898]
## Current behaviour

NRE

## Expected behaviour

behavior as in #7560

## Steps to reproduce

`Ctrl+A` on WIP branch #7899

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/77536476-a9be5c80-6e9c-11ea-8c9b-f7ea7c60177a.png)

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 4.0.0.8859
- Build 3bb59459d39c3fe086da40cf59994eb775562014 (Dirty)
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics

```
   at GitCommands.GitModule.GetDiffFilesWithSubmodulesStatus(ObjectId firstId, ObjectId secondId, ObjectId parentToSecond)
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions, Func`2 getRevision)
   at GitUI.CommandsDialogs.RevisionDiffControl.SetDiffs(IReadOnlyList`1 revisions)
   at GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab()
   at GitUI.CommandsDialogs.FormBrowse.FillDiff()
   at GitUI.CommandsDialogs.FormBrowse.<.ctor>b__49_2(Object sender, EventArgs e)
   at GitUI.RevisionGridControl.<.ctor>b__108_0(Object _, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by gerhardol** [comment]
Changed in master #7560

**Comment by gerhardol** [comment]
The problem occurs if selecting a commit that does not have any parent
(I had already changed this in my private build, adapting for master)
