### ISSUE TITLE
NullReferenceException when Clone Repository from Dashboard

### ISSUE THREAD

**Issue by NoahLerner** [gitextensions/gitextensions#7931]
## Current behaviour

From the Dashboard, clicking on 'Clone Repository' throws a NullReferenceException.

## Expected behaviour

Should not throw an exception.

## Steps to reproduce

Go to the Dashboard -> click on 'Clone Repository'

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.CommandsDialogs.FormClone.CanBeGitURL(String url)
   at GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Regression from #7876  

## Environment
- Git Extensions 4.0.0.8945
- Build a6f3362e7ca4d5e18de85b7284bfec4785ef914a (Dirty)
- Git 2.25.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

**Comment by NoahLerner** [comment]
https://github.com/gitextensions/gitextensions/blob/bc1d6757dca74e4b4c7abc5fae7f3564d6cb6f29/GitUI/CommandsDialogs/FormClone.cs#L186

Should be 
`            if (url.IsNullOrWhiteSpace())
`

Opening a new PR with the fix and will cover this with unit tests
