### ISSUE TITLE
[NBug] Index was out of range. Must be non-negative and less than ...

### ISSUE THREAD

**Issue by MarcusJohnson91** [gitextensions/gitextensions#7937]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewSelectedCellCollection.get_Item(Int32 index)
   at GitUI.CommandsDialogs.FormReflog.<GetShaOfRefLine>g__GetSelectedRow|12_0()
   at GitUI.CommandsDialogs.FormReflog.GetShaOfRefLine()
   at GitUI.CommandsDialogs.FormReflog.copySha1ToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
No idea

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 192dpi (200% scaling)

**Comment by gerhardol** [comment]
First time reported
Cannot reproduce

No selected cell?
```
return gridReflog.SelectedRows.Count > 0
                    ? gridReflog.SelectedRows[0]
                    : gridReflog.Rows[gridReflog.SelectedCells[0].RowIndex];
```

**Comment by RussKie** [comment]
I think I can repro it

* Deselect a row in `FormReflog`, yet it shows a context menu
* Copy sha
* 💣 💥 


![ge-reflog-crash](https://user-images.githubusercontent.com/4403806/78362363-b31a9800-7605-11ea-8d49-353d93adbde0.gif)
