### ISSUE TITLE
Flaky test RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8004]
## Current behaviour

```
1) Error : GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder
  System.AggregateException : One or more errors occurred.
    ----> System.ArgumentException : Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Array+FunctorComparer`1[GitUI.UserControls.RevisionGrid.Graph.RevisionGraphRevision]'.
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
     at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
     at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.ShouldReorderInTopoOrder() in C:\projects\gitextensions\UnitTests\GitUI.Tests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 62
  --ArgumentException
     at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
     at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
     at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
     at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
     at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedNodesCache(Int32 currentRowIndex) in C:\projects\gitextensions\GitUI\UserControls\RevisionGrid\Graph\RevisionGraph.cs:line 329
     at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.GetNodeForRow(Int32 row) in C:\projects\gitextensions\GitUI\UserControls\RevisionGrid\Graph\RevisionGraph.cs:line 123
     at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.Render() in C:\projects\gitextensions\UnitTests\GitUI.Tests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 113
     at GitUITests.UserControls.RevisionGrid.RevisionGraphMultiThreadingTests.<ShouldReorderInTopoOrder>b__5_2() in C:\projects\gitextensions\UnitTests\GitUI.Tests\UserControls\RevisionGrid\Graph\RevisionGraphMultiThreadingTests.cs:line 56
     at System.Threading.Tasks.Task.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
```

## Expected behaviour

test passes

## Steps to reproduce

run test on AppVeyor very, very often

## Did this work in previous version of GitExtensions

I have noticed this for the first time

## Environment

- AppVeyor: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/32253801/tests
- based on GE master e283787912ca8b0af82461f3d1eec50f3f680242
- Windows 10

**Comment by mstv** [comment]
Duplicate of #7393
