### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by LogicDaemon** [gitextensions/gitextensions#8005]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextUpdate(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Entered double-quote (") in Destination of Clone window.
Crashing when an invalid character entered in path, is lame.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in master #7633 (so popup instead)
Please try latest master
