### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: objectId

### ISSUE THREAD

**Issue by alexandre-mckinnon** [gitextensions/gitextensions#8019]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: objectId
   at GitCommands.GitRevision..ctor(ObjectId objectId)
   at GitUI.CommandsDialogs.FormDiff..ctor(GitUICommands commands, Boolean firstParentIsValid, ObjectId baseId, ObjectId headId, String baseCommitDisplayStr, String headCommitDisplayStr)
   at GitUI.GitUICommands.ShowFormDiff(Boolean firstParentIsValid, ObjectId baseCommitSha, ObjectId headCommitSha, String baseCommitDisplayStr, String headCommitDisplayStr)
   at GitUI.RevisionGridControl.CompareToBranchToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Diffing a merge commit from a dev branch to master branch

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Repo where this can reproduced?
Git Command log at least, including the result for the git-rev-parse when the form is opened

**Comment by alexandre-mckinnon** [comment]
I could not reproduce the issue, it happened only once. The repo was not corrupted: after restarting GitExtension with the same repo, I could do the same operation: 
- right click the "Working directory" artificial commit
- click the "Compare -> Compare to branch..." context menu item
- choose the "Local branch" radio button
- type in "master" in the "Select branch" combo box
