### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by Binyaminp** [gitextensions/gitextensions#8021]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Every time I try publishing to Gerrit I get this exception. please fix. Thanks

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4121.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Duplicate of #7521

Updated in master
