### ISSUE TITLE
[NBug] The process cannot access the file 'C:\code\CineNet\.git\CO...

### ISSUE THREAD

**Issue by cubanx** [gitextensions/gitextensions#8024]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.IOException: The process cannot access the file 'C:\code\CineNet\.git\COMMITMESSAGE' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.Abstractions.FileWrapper.WriteAllText(String path, String contents, Encoding encoding)
   at GitCommands.CommitMessageManager.set_MergeOrCommitMessage(String value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
Whenever I have multiple Git Extension commit windows open, when I right click on the task bar and say "close all" I get this error

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Related to #8006 
If all errors to persist the commit message is suppressed, some users will not be informed if it fails
Is a popup with the core reson supressed much better here?
