### ISSUE TITLE
[NBug] Could not load file or assembly 'RestSharp, Version=106.1.0...

### ISSUE THREAD

**Issue by bogdanwilli** [gitextensions/gitextensions#8089]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileLoadException: Could not load file or assembly 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at Atlassian.Jira.Jira.CreateRestClient(String url, String username, String password, JiraRestClientSettings settings)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.UpdateJiraSettings()
   at JiraCommitHintPlugin.JiraCommitHintPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

## Additional information
I've just started GitExtensions via the Explorer context menu "GitExt open repository". I did it on a directory 1-leve into the repository.

## Environment
- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.7.3610.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Is this from a portable version or an msi?

**Comment by pmiossec** [comment]
I wonder if using restsharp for one api call is not overkill and this dependency being removed to prevent this kind of errors and problems of dependency management...

**Comment by haldyr** [comment]
> I wonder if using restsharp for one api call is not overkill and this dependency being removed to prevent this kind of errors and problems of dependency management...

RestSharp is dependency of Atlassian.SDK package so it is not probably going away any time soon.

**Comment by TiTime** [comment]
was about to file issue and discovered this unresolved issue

## Current behaviour
Opening git extension causes this an error report 

## Expected behaviour
No error is thrown, so jira hint integration works as expected

## Steps to reproduce
Enable Jira hint plugin. 

## Error Details
```
System.IO.FileLoadException: Could not load file or assembly 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'RestSharp, Version=106.1.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at Atlassian.Jira.Jira.CreateRestClient(String url, String username, String password, JiraRestClientSettings settings)
   at JiraCommitHintPlugin.JiraCommitHintPlugin.UpdateJiraSettings()
   at JiraCommitHintPlugin.JiraCommitHintPlugin.gitUiCommands_PostSettings(Object sender, GitUIPostActionEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at GitUI.GitUICommands.InvokePostEvent(IWin32Window ownerForm, Boolean actionDone, EventHandler`1 gitUIEventHandler)
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage)
   at GitUI.CommandsDialogs.FormBrowse.PluginSettingsToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

## Environment
- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.27.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
As you probably see it,#8123 is expected to fix it but requires some adjustments before merging it...

**Comment by pmiossec** [comment]
@TiTime you could now test the result of the CI build and reports if it solves your problem.
