### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by PavelA85** [gitextensions/gitextensions#8090]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.<CheckoutConflictedFiles>g__CheckoutPart|81_0(Int32 part, String fileName, String unmerged, <>c__DisplayClass81_0& )
   at GitCommands.GitModule.CheckoutConflictedFiles(ConflictData unmergedData)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
trying to resolve conflicts

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in master #7633 (so popup instead)
Please try 3.4 RC
