### ISSUE TITLE
NBug report isn't working

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8096]
## Current behaviour

If application crashes and NBug form is shown, it is impossible to send a report, it crashes

```
Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.BeginInvoke(System.Delegate, System.Object[])
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Post(System.Threading.SendOrPostCallback, System.Object)
   at System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(System.Threading.SynchronizationContext, System.Action)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[[System.ValueTuple`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]](System.ValueTuple`2<System.__Canon,System.__Canon>, System.Func`3<System.Reactive.Concurrency.IScheduler,System.ValueTuple`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Reactive.Concurrency.IScheduler, System.__Canon, System.Action`1<System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2+Session+<>c[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Connect>b__5_0(System.ValueTuple`3<Session<System.__Canon,System.__Canon>,System.Reactive.Linq.ObservableImpl.EventProducer`2<System.__Canon,System.__Canon>,System.IDisposable>)
   at System.Reactive.Disposables.AnonymousDisposable`1[[System.ValueTuple`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose(Boolean)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   at System.Reactive.TailRecursiveSink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Drain()
   at System.Reactive.TailRecursiveSink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose(Boolean)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose(Boolean)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose(Boolean)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(System.IDisposable ByRef)
   at System.Reactive.Linq.ObservableImpl.Catch`2+_[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose(Boolean)
   at System.Reactive.Sink`1[[GitCommands.DiffListSortType, GitCommands, Version=3.4.0.9378, Culture=neutral, PublicKeyToken=null]].Dispose()
   at GitUI.FileStatusList.DisposeCustomResources()
   at GitUI.GitModuleControl.Dispose(Boolean)
   at GitUI.FileStatusList.Dispose(Boolean)
   at System.ComponentModel.Component.Finalize()
```

## Expected behaviour

NBug report is sent without crashes

## Steps to reproduce

1. Clone https://github.com/RussKie/MSBuildStructuredLog.git
2. Open repo
2. Ensure to have switch to [Diff] tab (from [Commit] tab)
2. Select the following commits in the order:
	* a7ecbe179cdf22028e8c30a24462269d7b04e4cd
	* eda3a98d1523670c02f43b6bbef7c59cc28c06ca
	* 20152f44ec377c73dca7c50ce3dce8c2f2478201
    ![image](https://user-images.githubusercontent.com/4403806/81696424-3782f500-94a7-11ea-885a-f851ec1ff3c0.png)

3. Observe NBug form
4. Click [Send and quit] button and observe no issue sent to a browser

## Did this work in previous version of GitExtensions

v3.3.x

## Environment

- Git Extensions 3.4.0.9378
- Build 85ab13ae47d7f68deae8135694ef2c622e2b498b
- Git 2.16.1.windows.4 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Fix included in 3.4 branch, draft #8103 in master
