### ISSUE TITLE
App crash showing diffs for multi selection

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8097]
## Current behaviour

![image](https://user-images.githubusercontent.com/4403806/81696652-8cbf0680-94a7-11ea-90b4-3ef7daf368d6.png)

## Expected behaviour

Get the diff

## Steps to reproduce

1. Clone https://github.com/RussKie/MSBuildStructuredLog.git
2. Open repo
2. Ensure to have switch to [Diff] tab (from [Commit] tab)
2. Select the following commits in the order:
	* a7ecbe179cdf22028e8c30a24462269d7b04e4cd
	* eda3a98d1523670c02f43b6bbef7c59cc28c06ca
	* 20152f44ec377c73dca7c50ce3dce8c2f2478201
    ![image](https://user-images.githubusercontent.com/4403806/81696424-3782f500-94a7-11ea-885a-f851ec1ff3c0.png)

3. Observe NBug form

## Error Details
```
System.ArgumentOutOfRangeException: capacity was less than the current size.
Parameter name: value
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at GitUI.FileStatusList.SetDiffs(IReadOnlyList`1 revisions, Func`2 getRevision)
   at GitUI.CommandsDialogs.RevisionDiffControl.SetDiffs(IReadOnlyList`1 revisions)
   at GitUI.CommandsDialogs.RevisionDiffControl.DisplayDiffTab()
   at GitUI.CommandsDialogs.FormBrowse.FillDiff()
   at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.0.9378
- Build 85ab13ae47d7f68deae8135694ef2c622e2b498b
- Git 2.16.1.windows.4 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Have you deactivated multi diff?

**Comment by RussKie** [comment]
I was about to post - yes, it is happening when the setting is disabled.

**Comment by mstv** [comment]
`tuples.Count` is `2` here:

```
            if (!AppSettings.ShowDiffForAllParents)
            {
                tuples.Capacity = 1;
            }
```

Did you mean to shrink the list to one element, @gerhardol?

**Comment by mstv** [comment]
One does not need to clone another repo. Just select a merge commit.

**Comment by RussKie** [comment]
> Just select a merge commit.

Aye, I found it later. I was testing in that repo
