### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by MisterAcoustic** [gitextensions/gitextensions#8104]
Automated reporting: May be a duplicate of #7671.

:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

In the commit window, I tried to reset the deletion of a directory. I don't recall, but directory may have been a submodule for some reason. The right-click menu showed 'reset submodule changes' instead of the expected 'reset file or directory changes'. When I chose to reset, the app crashed.

## Expected behaviour

The app should restore the directory/submodule

## Steps to reproduce

I'm not sure how this submodule item was created. It was an empty directory. I deleted it. I tried to reset the change through the commit window. Crash.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<RunCommandAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at GitUI.CommandsDialogs.FormCommit.resetSubmoduleChanges_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Don't know. I had deleted a directory named ZXing.Net.Mobile, and made a change to one file, which showed as two changes in the commit window. I tried to reset the delete (it showed as reset submodule changes), and it crashed.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
You selected the menu option to reset submodule changes within the submodule, not to reset changes. With the Git submodule syntax, you should have Updated the submodule to restore the directory.
Similar, for Stash you get a popup and Commit nothing happens at all.
Open is also not relevant (no crash).
Same problem in RevDiff.

Regardless, Reset, Stash and Commit should not be attempted for removed submodules.
(Open is handled in FileStatusList and may be more difficult to change.)
The menu option should be disabled and/or the action handling that the directory do not exist.
