### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by brandon-upshaw** [gitextensions/gitextensions#8158]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I was attempting to create a pull request

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3610.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
duplicate of #6757

The GitHub token is incorrect
Please try the 3.4 RC, the error message is improved
