### ISSUE TITLE
[NBug] Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by jasonkcarter** [gitextensions/gitextensions#8171]
## Current behaviour

The Git Extensions program crashes immediately upon opening.

## Expected behaviour

The Git Extensions program behaves just the same as it would with a local disk folder.

## Steps to reproduce

1. Clone a Git repository in WSL2 / Ubuntu
2. Open a Windows Explorer window for the cloned repo using `explorer.exe .`
3. Right click on the repo folder in Windows Explorer and select GitExt Open Repository

## Error Details
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at GitCommands.PathUtil.NormalizePath(String path)
   at GitCommands.GitModule..ctor(String workingDir)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

## Additional information
Tried opening a WSL2-cloned repository from Windows Explorer using the \\wsl$\Ubuntu\home\ubuntu\git\ path format.

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

Duplicate of issues #6595 and #6709 which were both closed due to lack of detail and no activity.

**Comment by pmiossec** [comment]
Test the 3.4 RC1 version (containing #8031) and please reports if it solves your issue.

As a side note, upgrading to the last version before reporting is a required step to not waste everyone time.

**Comment by jasonkcarter** [comment]
Thanks.  Sorry, this is just the form I was dumped into by the built-in crash reporter.  There was nothing in the form instructions talking about upgrading, although I should have thought of that.

I upgraded to the latest public release first and tested.  It didn't crash, but it didn't open the repo either.

Now, I just installed 3.4 RC1.  It opened the repo, but it's kind of slow and buggy for me so far.
- Right clicking a branch name and selecting "Checkout branch" takes a very long time (15-60 seconds) to bring up the Checkout branch dialog.
- Trying to reset a deleted file throws "error: unable to create symlink <filename>: Permission denied"
- On a php project that is tracking the composer `vendor/` file (don't ask), switching to some branches throws an error "error: open("vendor/bin/composer"): Invalid argument, error: unable to index file 'vendor/bin/composer'".  Other branches with the same file don't throw the same error.

In general, it seems like using `\\wsl$` to run active git commands against is just asking for a bad time. :(  Oh well.

**Comment by gerhardol** [comment]
Check the Git Command Log (F12) to check the Git execution times. GE cannot do much about slow Git operation...

**Comment by jasonkcarter** [comment]
The command that takes so long when selecting "Checkout branch" is `git	-c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files=all --ignore-submodules=all	\\wsl$\Ubuntu\home\ubuntu\git\MyProject\`

I wonder if I would just have a better time running Git Extensions directly from wsl via mono.  Then everything would run natively in Ubuntu without any translation layer.

Anyways, thanks for looking into it.  Doesn't seem like using `\\wsl$` is something that is going to work well for me, but I'm not sure it's something that shortcut is even really designed for.

**Comment by gerhardol** [comment]
> The command that takes so long when selecting "Checkout branch" 

git-status runs in the background, to see the summary for worktree/index

GE 2.x runs on mono, not the 3.x version

**Comment by jasonkcarter** [comment]
I suppose that's true about mono support.

I wonder what it would take to override the git command path for `\\wsl$\{distro}\{path_with_backslashes}` specifically to run commands via `C:\Windows\System32\wsl.exe -d {distro} -- /usr/bin/git -C '{path_with_forwardslashes}'`?  

For example, the following runs almost instantaneously:
`wsl.exe -d Ubuntu -- /usr/bin/git -C '/home/ubuntu/git/MyProject/' -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files=all --ignore-submodules=all /home/ubuntu/git/MyProject/`

**Comment by pmiossec** [comment]
That's another problem. Could you open a new issue/feature request for that?

If I understand well, you want to override the git exe config with a dynamically build command line based on the distribution and working parg used when the path is a WSL one, right?!?

**Comment by jasonkcarter** [comment]
Sure, I'll open a new issue / feature request.  Yes, @pmiossec, that sounds right.  It would also need to translate any file paths starting with the working parg, as well as replace backslashes with forward slashes, but in all, not an impossible translation task.

**Comment by mstv** [comment]
The approach for Wine might help here, too: https://github.com/gitextensions/gitextensions/issues/6051#issuecomment-618122256.

(Most of the) paths in git arguments should already have forward backslashes (Posix style).
