### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by hhao1** [gitextensions/gitextensions#8185]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
after I try to publish to gritte. it crushed

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.3752.0
- DPI 240dpi (250% scaling)

**Comment by RussKie** [comment]
You need to upgrade the Gerrit plugin.
