### ISSUE TITLE
[NBug] Could not load file or assembly 'ICSharpCode.TextEditor, Ve...

### ISSUE THREAD

**Issue by jellojam** [gitextensions/gitextensions#8187]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileLoadException: Could not load file or assembly 'ICSharpCode.TextEditor, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=4d61825e8dd49f1a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'ICSharpCode.TextEditor, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=4d61825e8dd49f1a'
   at GitUI.Editor.FileViewerInternal..ctor()
   at GitUI.Editor.FileViewer.InitializeComponent()
   at GitUI.Editor.FileViewer..ctor()
   at GitUI.CommandsDialogs.RevisionFileTreeControl.InitializeComponent()
   at GitUI.CommandsDialogs.RevisionFileTreeControl..ctor()
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent()
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, String filter, ObjectId selectCommit)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

## Additional information
launch

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.17.1.windows.2 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3620.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
Try repairing your installation.
