### ISSUE TITLE
[NBug] Access to the path 'C:\Users\kleis500\OneDrive - KPN\Local ...

### ISSUE THREAD

**Issue by katharina318** [gitextensions/gitextensions#8201]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\kleis500\OneDrive - KPN\Local Disk\Documents\VFC\CARE\.git\HEAD' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(Str

**Comment by gerhardol** [comment]
Truncated stacktrace and no version info, but this seem to be a repo with access permissions.

**Comment by pmiossec** [comment]
That could sometimes be because the repo has been open with a software (VisualStudio?) with admin rights and know all rights on some files are fucked up...
