### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by b3rnhard** [gitextensions/gitextensions#8221]
## Current behaviour

GitExtensions crashes.

## Expected behaviour

GitExtensions shows an error message telling the user about a script that cannot be executed.

## Steps to reproduce
Go to Settings -> Scripts and add a new entry that points to a non-existing executable (in my case it was a ConEmu installation that used to be available at _Program Files (x86)_ and it was replaced with a path pointing to somewhere within _Program Files_).
Execute the script via context menu.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, IGitModule module, ScriptInfo scriptInfo, IGitUICommands uiCommands, RevisionGridControl revisionGrid, Action`1 showError)
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, IGitModule module, String scriptKey, IGitUICommands uiCommands, RevisionGridControl revisionGrid, Action`1 showError)
   at GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, IGitModule module, String scriptKey, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   at GitUI.Script.ScriptRunner.ExecuteScriptCommand(IWin32Window owner, GitModule module, Int32 command, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   at GitUI.GitModuleForm.ExecuteCommand(Int32 command)
   at GitUI.CommandsDialogs.FormBrowse.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Additional information

None.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by b3rnhard** [comment]
None of the found duplicate candidates mention "GitUI.Script.ScriptRunner.RunScript", so probably no dupe?

**Comment by mstv** [comment]
I tried various variants of the example script "Example" with the portable build of 3.4.1.
I've always got a meaningful message "file not found" like this:

![grafik](https://user-images.githubusercontent.com/36601201/84701630-a1366900-af55-11ea-83e5-9f37bb025bb6.png)

no matter whether the ConEmu shall be used or not:
![grafik](https://user-images.githubusercontent.com/36601201/84702057-579a4e00-af56-11ea-9d93-d139deead2c9.png)

So I think your issue was caused by moving ConEmu. GE usually comes with its own copy of ConEmu. Though ConEmuInside also tries to find it in the `%PATH%`. The regarding third-party code (from ConEmu) contains a `TODO`.
Hence I recommend (to not try to save 6.5 MB drive space and) let GE have its own copy of the ConEmu binaries in the subfolder `ConEmu` relative to the `GitExtensions.exe`.

**Comment by mstv** [comment]
Now that the Script editor really has stored the changed flags, I could reproduce it with `run in background = true`.

Workaround: You do not need to quit - you can dismiss the error report and let GE ignore the exceptions, which is really safe in case of user scripts:
![grafik](https://user-images.githubusercontent.com/36601201/84704069-8bc33e00-af59-11ea-9dcc-ef780fb0cd30.png)

We should mention also this in the above message.

And I will wrap all calls of external executables with error handling in one of my next PRs finally.

**Comment by b3rnhard** [comment]
Sorry about forgetting the detail "Run in Background" = `True`. 🙄
