### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\VS\out-there-media\ou...

### ISSUE THREAD

**Issue by dsidirop** [gitextensions/gitextensions#8232]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\VS\out-there-media\out-there-media-quizer-demo\quizer\server\.git\GitExtensions.amend'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at System.IO.Abstractions.FileWrapper.Delete(String path)
   at GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
I deleted the .git directory in the subfolder while git commit dialog was already open

## Environment
- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.27.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Duplicate of #7751

Removing from 4.0, more info in #7751
