### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by mehmetcakmaz** [gitextensions/gitextensions#8259]
## Current behaviour

I solve the conflicts that occur after merge operation. Than push the merge commit and git extensions got crash

## Steps to reproduce

Standard merge operation

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.<CheckoutConflictedFiles>g__CheckoutPart|82_0(Int32 part, String fileName, String unmerged, <>c__DisplayClass82_0& )
   at GitCommands.GitModule.CheckoutConflictedFiles(ConflictData unmergedData)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool()
   at GitUI.CommandsDialogs.FormResolveConflicts.merge_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I get this error after merge operation

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #8090
