### ISSUE TITLE
[NBug] The specified path, file name, or both are too long. The fu...

### ISSUE THREAD

**Issue by Dirksche** [gitextensions/gitextensions#8264]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at GitUI.Editor.FileViewer.ViewItemAsync(String fileName, Func`1 getImage, Func`1 getFileText, Func`1 getSubmoduleText, Action openWithDifftool)
   at GitUI.Editor.FileViewer.<>c__DisplayClass92_0.<ViewFileAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.ViewFileAsync(String fileName, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass136_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
We would like to use long file paths.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7670
Some similar issues in the latest releases like #7862 and #7660
Probably the same in 3.4 and master

What files was viewed? Can it be stored in the filesystem or is it viewed only from the repo?
Generally will workarounds to handle Windows limitations for files in Git make minor improvement if the files cannot be checked out anyway

**Comment by RussKie** [comment]
260 chars is a hard limit in Windows. I've read about few workarounds but
I'm yet to see one that works.

Besides we're currently constrained by .NET Framework 4.6.1 implementations
that don't handle long paths. This may work better in .NET Core, but time
will tell.

**Comment by Dirksche** [comment]
The problem was the Git Extension crashed with above error report, without showing a usable error to the user.
After upgrading Git and Git Extension to the latest version, Git Extension reported correctly that the file path was too long.
Therefore, I'm happy to have this bug closed. It was my fault to use older versions of Git and Git Extensions.

@RussKie  By thw way, long file paths can be enabled in Git with
`git config --system core.longpaths true`
or
`git config --global core.longpaths true`
and it seems to be working fine using the latest Git and latest Git Extension.
However, we decided to shorten our file paths and to set `core.longpaths` back to `false`, because I've read that long file paths are officially only supported on Windows 10, one of our Build servers is still running Windows 7 and we didn't want to run into any problems.
Also not all applications can cope with long file paths (prefixed with `"\\?\"`). E.g. the Microsoft XML parser complains that this is not a valid file path.
