### ISSUE TITLE
[NBug] Shell Exception has occurred, look at inner exception for i...

### ISSUE THREAD

**Issue by undisclosed67** [gitextensions/gitextensions#8265]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
Microsoft.WindowsAPICodePack.Shell.ShellException (0x80004005): Shell Exception has occurred, look at inner exception for information.
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolBarButton.UpdateThumbnailButton()
   at GitUI.WindowsJumpListManager.UpdateCommitIcon(Image image)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass43_0.<.ctor>b__14(Object s, GitWorkingDirectoryStatusEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.InvalidateGitWorkingDirectoryStatus()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
undo last commit while a rebase is currently in progress (incomplete for some obscure reason)

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #8234
Fixed in #8240
Included in 3.4.2
