### ISSUE TITLE
[NBug] Cannot access a disposed object.Object name: 'FormCommit'.

### ISSUE THREAD

**Issue by Pacmensch** [gitextensions/gitextensions#8272]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FormCommit'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at System.Windows.Forms.MessageBox.Show(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass141_0.<CheckForStagedAndCommit>g__DoCommit|2()
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass141_0.<CheckForStagedAndCommit>b__0()
   at GitUI.CommandsDialogs.FormCommit.BypassFormActivatedEventHandler(Action action)
   at GitUI.CommandsDialogs.FormCommit.CheckForStagedAndCommit(Boolean amend, Boolean push)
   at GitUI.CommandsDialogs.FormCommit.CommitAndPush_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Error occurred after forcing to close applications during update

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.23.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
How to reproduce?
