### ISSUE TITLE
[NBug] Access to the path 'C:\Users\lollo\.gitconfig' is denied.

### ISSUE THREAD

**Issue by WildCard65** [gitextensions/gitextensions#8347]
## Error Details
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\lollo\.gitconfig' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at GitUI.CommandsDialogs.FormEditor.SaveChanges()
   at GitUI.CommandsDialogs.FormEditor.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Additional information
File "~/.gitconfig" is hidden on my Windows install.

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Likely that the file was readonly (which is strange), or was used by another git process. In either case we shouldn't crash the app.

**Comment by RussKie** [comment]
`SaveChanges` has 3 call sites, but only 2 are wrapped in `try..catch`.
`try..catch` must be moved into `SaveChanges` method.

**Comment by WildCard65** [comment]
@RussKie It's not that the file is read-only, it's that the file was hidden.
PowerShell's Remove-Item also has trouble with hidden files/folders.

**Comment by RussKie** [comment]
Hmm, an interesting observation. One would think it shouldn't matter, but I don't remember ever reading a hidden file.

**Comment by WildCard65** [comment]
Ya, I have "core.hideDotFiles" set to true, so git automatically applies the "Hidden" attribute to any "." prefixed file/folder.

**Comment by WildCard65** [comment]
@RussKie A quick Google search yields a possible solution, but the error is actually more interesting.
According to the .NET Framework Reference Source, File.InternalWriteAllText internally calls StreamWriter with "append" as 'false', this causes StreamWriter to call "Create" for FileStream which fails for hidden files (possibly because the file actually exists)

StackOverFlow: https://stackoverflow.com/a/2247115
