### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\Users\yop\StudioProje...

### ISSUE THREAD

**Issue by forestrf** [gitextensions/gitextensions#8353]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\yop\StudioProjects\qtUVCCamera\.git\GitExtensions.amend'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at System.IO.Abstractions.FileWrapper.Delete(String path)
   at GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
removing the folder where a git project is, that is open by GitExtensions with the commit window open, gives an error when trying to close the commit window
This looks like an edge case error, not important, rare and easy to work around. Still, I reported it just in case

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b18

**Comment by forestrf** [comment]
This may have been my fault as I was probably able to delete the folder by unlocking the folder from the process by using another program.

**Comment by gerhardol** [comment]
Duplicate of #7751
