### ISSUE TITLE
Add Upstream Remote causes CRASH

### ISSUE THREAD

**Issue by 7ranceaddic7** [gitextensions/gitextensions#8361]
Attempting to add an upstream remote.

## Steps to reproduce

Select 'GitHub' menu item
Select 'Add Upstream Remote'
CRASH

## Error Details
```
System.Exception: Not Found
   at Git.hub.Client.DoRequest[T](IRestRequest request, Boolean throwOnError)
   at Git.hub.Client.getRepository(String username, String repositoryName)
   at GitHub3.GitHubHostedRemote.GetHostedRepository()
   at GitHub3.GitHub3Plugin.<AddUpstreamRemoteAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormBrowse.<<_addUpstreamRemoteToolStripMenuItem_Click>b__155_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Make sure you gave your GitHub token set.

**Comment by 7ranceaddic7** [comment]
I think it was becasue I used a GitHub token where I needed an Azure token.
