### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Latency** [gitextensions/gitextensions#8380]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Submodules break when trying to create repo for the first time.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.CreateSubmoduleNodes(IEnumerable`1 submodules, GitModule threadModule, List`1& nodes)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.FillSubmoduleTree(SubmoduleInfoResult result)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<LoadNodesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<>c__DisplayClass4_0.<<OnStatusUpdated>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Submodules break pull

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Can you write a detailed description on how to reproduce?

**Comment by Latency** [comment]
It has to do with submodules being included and the .gitmodules file missing or wrong.
