### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by triplesyntax** [gitextensions/gitextensions#8383]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.PathUtil.FindInFolders(String fileName, IEnumerable`1 folders)
   at GitCommands.DiffMergeTools.DiffMergeToolConfigurationManager.LoadDiffMergeToolConfig(String toolName, String userSuppliedPath)
   at GitCommands.DiffMergeTools.DiffMergeToolConfigurationManager.GetToolCommand(String toolName, DiffMergeToolType toolType)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

## Additional information
upon opening, there's an error message

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
Which configuration is causing the error?

**Comment by triplesyntax** [comment]
Hi,

I mistakenly set the diff merge tool to git extension folder. Please see
attached file.

Regards,
Gene

**Comment by RussKie** [comment]
The attachment doesn't work via an email.
