### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: key

### ISSUE THREAD

**Issue by benbrummer** [gitextensions/gitextensions#8396]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
   at GitUIPluginInterfaces.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value)
   at GitUIPluginInterfaces.CredentialsSetting.SaveValue(ISettingsSource settings, String userName, String password)
   at GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   at GitUIPluginInterfaces.SettingControlBinding`2.SaveSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Setting for Jira Hint plugin can not be saved. Preview button works. Plugin therefore can not be used at all

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by benbrummer** [comment]
Saving the Jira URL field alone works. But the Jira credentials can not be applied.

**Comment by MatthieuFereyre** [comment]
Here is a way to reproduce and a workaround.

The error is arriving if you try to configure the plugin **without** a git repo opened (ie : just the view with your most recent repos).
And it's working if you have a git repo opened in git extension.

I don't know why but I verified that on several machines.

**Comment by pmiossec** [comment]
> The error is arriving if you try to configure the plugin **without** a git repo opened (ie : just the view with your most recent repos).
> And it's working if you have a git repo opened in git extension.
> 
> I don't know why but I verified that on several machines.

Reproduced in this case.

I don't know if this is the original use case (because I find strange to change these settings without a repo opened) but indeed, if you try to modify and save a settings when the "Settings source" is not "Global for all the repositories"

And we have that for all the plugin settings but also for other settings page (Revision links, Build server integration, Detailed):
![image](https://user-images.githubusercontent.com/460196/121196476-ce6bdd80-c870-11eb-8155-6483fd1149a0.png)

The reason is that all the settings source except "Global for all the repositories" try to save the setting in the repository folder.

Note: "Effective " is equivalent to "Local for current repository" when you change and save a setting (for me the purpose of this option is more for display)

So the solution is either hide all the settings page having these "setting source " option if a repo is not open or select "Global for all the repositories" in this case and not allow the user to change it.
