### ISSUE TITLE
GitCommands.Config.GitConfigurationException

### ISSUE THREAD

**Issue by aguinane** [gitextensions/gitextensions#8401]
## Current behaviour

On my work laptop the home folder is stored on a network drive. If you try to open git extensions while not connected to the network, it fails to find the config file stored in this home folder and crashes. Connecting to the VPN resolves the problem.

## Expected behaviour

Would expect program to warn that it can't find the config and prompt to find it or create a new one.
Or have an options in the settings to allow setting a different location for storing the config file.

Running git from the command line seems to work without issues. 
Git itself seems to store the config in "C:\\ProgramData/Git/config" wheares Git Extensions is using "H:\\.gitconfig"

## Steps to reproduce

Try to open Git Extensions on a PC where .gitconfig is stored on a network location that is not accessible.

## Screenshots

Error details included below. 

## Did this work in previous version of GitExtensions
Not sure, only noticed since working from home.

## Error Details
```
System.AggregateException: One or more errors occurred. ---> GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitCommands.Settings.ConfigFileSettingsCache.GetValueImpl(String key)
   at GitCommands.SettingsCache.<>c__DisplayClass18_0.<GetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.GetValue(String name)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitUIPluginInterfaces.ISettingsSource.GetString(String name, String defaultValue)
   at GitCommands.Settings.ConfigFileSettings.GetEncoding(String settingName)
   at GitCommands.GitModule.get_LogOutputEncoding()
   at GitCommands.RevisionReader.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at GitUI.RevisionGridControl.<>c__DisplayClass153_2.<ForceRefreshRevisions>b__9()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
---> (Inner Exception #0) GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitCommands.Settings.ConfigFileSettingsCache.GetValueImpl(String key)
   at GitCommands.SettingsCache.<>c__DisplayClass18_0.<GetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.GetValue(String name)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitUIPluginInterfaces.ISettingsSource.GetString(String name, String defaultValue)
   at GitCommands.Settings.ConfigFileSettings.GetEncoding(String settingName)
   at GitCommands.GitModule.get_LogOutputEncoding()
   at GitCommands.RevisionReader.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()<---

```

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.21.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

## Diagnostics

This may be related to #8324 or #8347? But opening a new issue as it appears to be slightly different.

As a side note, when trying to send the automated bug report from the application, GitHub gave a bad request error:
```
Whoa there!
Your request URL is too long. 
```
You may need to truncate the error log to submit via a URL?

**Comment by gerhardol** [comment]
If the Git config is unavailable, just ignoring the file may have unexpected effects for the user too, when other settings are missing.

> This may be related to #8324 or #8347? But opening a new issue as it appears to be slightly different.

This may have the same solution as #8347, but that may be separate.

> You may need to truncate the error log to submit via a URL?

Seems like it, but then the data is truncated and need to be entered manually anyway...
