### ISSUE TITLE
[NBug] Crash due to file locked by another process (Access to the path 'C:\dev\product\xavo\.git\rebase-merge' ...)

### ISSUE THREAD

**Issue by mklinke** [gitextensions/gitextensions#8406]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour
Git Extensions crashed trying to abort a rebase with a merge conflict. I assume this was due to having VSCode open at the same time that is also accessing the .git files.

## Expected behaviour
Git Extensions doesn't crash when aborting a rebase with a merge conflict while having VSCode (or any other tool for that matter) access the .git files. An error message with a note to close any other Git tools and a retry option would be fine IMHO.

## Steps to reproduce

Create rebase with a conflict situation and abort the rebase while having another Git tool like VSCode opened.

## Error Details
```
System.UnauthorizedAccessException: Access to the path 'C:\dev\product\xavo\.git\rebase-merge' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at GitCommands.GitModule.GetRebasePatchFiles()
   at GitUI.PatchGrid.GetPatches()
   at GitUI.PatchGrid.Initialize()
   at GitUI.CommandsDialogs.FormRebase.AbortClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
As mentioned above, I assume this is due to another tool accessing the .git files in the repository concurrently.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by mklinke** [comment]
Looking through the list of duplicates, it seems to me that this is a separate issue since this not a permanent problem with access rights but rather a temporary one due to concurrent access/file locking by another process. I would at least expect a warning instead of a crash in this case.

Thanks for the great tool by the way! Just trying to contribute here. I don't have the resources to look into this myself but maybe this helps someone else.

**Comment by RussKie** [comment]
Running multiple git clients in the same repo is asking for troubles. But we certainly shouldn't crash the app.

I think the UX will improved with https://github.com/gitextensions/gitextensions/pull/8278 and/or https://github.com/gitextensions/gitextensions/pull/8358.
