### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\Users\Work\AppData\Ro...

### ISSUE THREAD

**Issue by Master-Mind** [gitextensions/gitextensions#8423]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce
I installed gitext on a different user account on this machine, doesn't look like it is set up to work on different users

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Work\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GitCommands.Settings.FileSettingsCache.SaveImpl()
   at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.SettingsContainer`2.Save()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.SettingsDialog.Pages.ChecklistSettingsPage.SaveAndRescan_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Selected a language in the settings checklist

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please update to the latest
