### ISSUE TITLE
[NBug] Context menu > "Save remote" crashes in merge resolution dialog

### ISSUE THREAD

**Issue by namtab00** [gitextensions/gitextensions#8437]
## Current behaviour

Context menu > "Save remote" crashes on merge resolution dialog after switch branch with dirty workdir

## Expected behaviour
UI to save the remote file should work..

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.CommandsDialogs.FormResolveConflicts.SaveAs(String side)
   at GitUI.CommandsDialogs.FormResolveConflicts.ContextSaveRemoteAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> Context menu > "Save remote" crashes on merge resolution dialog after switch branch with dirty workdir

Can you please provide steps to reproduce?

**Comment by circias** [comment]
I also had this trouble today.
I can explain the procedure.
