### ISSUE TITLE
[NBug] Application not found

### ISSUE THREAD

**Issue by DevsAnon** [gitextensions/gitextensions#8455]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c.<diffOpenRevisionFileToolStripMenuItem_Click>b__54_0(String fileName)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c__DisplayClass56_0.<<SaveSelectedItemToTempFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Tried to open a specific revision of a file

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
How to reproduce?

**Comment by pmiossec** [comment]
> How to reproduce?

Looking at the stacktrace, I think that it is the same as #7156 (so doing "Open this revision with... (temp file)" but with the little difference that the application associated with the file has been uninstalled or moved or something like that so that the OS can't find it anymore...

**Comment by DevsAnon** [comment]
> > How to reproduce?
> 
> Looking at the stacktrace, I think that it is the same as #7156 (so doing "Open this revision with... (temp file)" but with the little difference that the application associated with the file has been uninstalled or moved or something like that so that the OS can't find it anymore...

Exactly this

**Comment by gerhardol** [comment]
Duplicate of #7156
