### ISSUE TITLE
[NBug] Error reading the Project directory.

### ISSUE THREAD

**Issue by Baljak** [gitextensions/gitextensions#8530]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

A crash can occurred if a repository folder is deleted on disk while opened in Git Extensions.

## Expected behaviour

Git Extensions should not crash.

## Steps to reproduce

- Clone a repository
- Open it with Git Extensions
- Delete the repository using Windows Explorer.

## Error Details
```
System.IO.FileNotFoundException: Error reading the C:\Users\Baljak\Project\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<.ctor>b__24_0(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by Baljak** [comment]
Seems to have been already reported and fixed.

**Comment by gerhardol** [comment]
The same problem has occurred before and it should be handled in 3.4.3
However, that is the version used here

There is a very small possibility that concurrent changes deletes the directory after the check that the directory exist is done
If this occurs again, a try-catch could be added (hides other errors though - maybe not critical if the status monitor stops working)
