### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by richhock** [gitextensions/gitextensions#8571]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.SetVisibilityDiffContextMenu(Boolean visibleTextFile, String fileName)
   at GitUI.Editor.FileViewer.ResetForText(String fileName)
   at GitUI.Editor.FileViewer.<>c__DisplayClass105_0.<ViewTextAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.<ViewTextAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Created a github wiki page with the title
00-abc-"d"-e-f-g,h-(ij)-k&l-m;-n@o

Fetched updates from github, clicked on the newly-fetched commit, and clicked on the Diff tab in Git Extensions when this failure occurred.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.20.1.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
FullPathResolver.Resolve() should check for legal characters and return null if the path have illegal chars.
(It currently throws if called with whitespace too, should also be null.)
All callers with FileExists(Resolve()) will return false, as expected (like in this case as well as FormCommit, RevDiff etc)

There are some other usages that will get a null pointer instead and will very likely throw a different exception, but in the context of the caller instead.

(An alternative is to to add an option to return null only when option set to do so and change call sites explicitly.)

**Comment by gerhardol** [comment]
Please try #8575 
You will not be able to do much with commits named like this as Git can for instance check out the commits, but GE will not crash at load and you can view files.
