### ISSUE TITLE
[NBug] When returning to dashboard while opening a commit diff with a large file addition, exception: Unable to parse object ID "a".

### ISSUE THREAD

**Issue by dagood** [gitextensions/gitextensions#8583]
## Current behaviour

When I check out a commit or select a commit and press Ctrl-W very quickly afterwards, sometimes I get the exception below.

## Expected behaviour

After Ctrl-W, I'm back at the home screen with no error.

## Steps to reproduce

1. Create a repo with a commit that adds a file with a long horizontal scroll.
   * I think the long *horizontal* area in particular makes it take longer to render the diff, which I think makes it easier to hit the time window necessary to repro. When I originally hit this I did also have somewhat long lines.
   * E.g. powershell `git init;  git commit --allow-empty -m 'Initial'; [string]::new('a', 8000) > file.txt; git add file.txt; git commit -a -m 'Add file'`
1. Open the repo.
1. Select the blank commit. Make sure the "Diff" tab is open.
1. Select the commit adding the slow file and at the same time press Ctrl-W.
1. Get the exception popup.

The 8000-char line seems to be a very consistent repro for me. I think I hit it every time as long as I hit Ctrl-W before the file contents show up in the Diff viewer tab.

## Error Details
```
System.FormatException: Unable to parse object ID "a".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetFileBlobHash(String fileName, ObjectId objectId)
   at GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(GitItemStatus file, ObjectId revision, Action openWithDifftool)
   at GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, String defaultText, Action openWithDiffTool)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I initially hit this when I wanted to quickly do a checkout to reset my repo to a known state before I went to go work on another repo using the home screen. But when I worked on a consistent repro, it turns out just clicking on commits causes it too.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Thank you for the repro.

It is failing here:
![image](https://user-images.githubusercontent.com/4403806/98494724-c4114300-2291-11eb-8525-2636a1be6407.png)

@gerhardol @mstv I think this may be somewhat related to fixes you're currently working on. What's the best way to handle it here?

**Comment by gerhardol** [comment]
The failure is likely here:
https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/FileStatusList.cs#L384

Somehow this injects a bad commit sha in the ObjectId, that cannot be used to resolve the file blob.
The objectId and filename in the git call is the important if someone else debugs.

I have problem reproducing. The file must be some MB big to have a chance at all. A bigger file will delay the display but not simplify a repro.
(File on HD, not so fast PC, Defender Virus).
With this I could repro once in fifty tries, but not with the debugger.

The solution should anyway be to use a TryParse to avoid crashing GE, possibly also checking for exit code and for 'fatal' in the first record (or just add that as a comment). The file will not be shown, but no crash (just try again.) (should be handled already in FileViewer) (parsing should use -z too, also no real difference)

I am working in FileViewer, but this is in WinForms/.NET(?) in FileStatusList and in "Git error handling".

**Comment by gerhardol** [comment]
Got the same problem in a scenario where #8658 (that is likely only in master) normally occurs

## Error Details
```
System.FormatException: Unable to parse object ID "a".
   at ObjectId GitUIPluginInterfaces.ObjectId.Parse(string s)
   at ObjectId GitCommands.GitModule.GetFileBlobHash(string fileName, ObjectId objectId)
   at Task GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(GitItemStatus file, ObjectId revision, Action openWithDifftool)
   at Task GitUI.GitUIExtensions.ViewChangesAsync(FileViewer fileViewer, FileStatusItem item, string defaultText, Action openWithDiffTool)
   at async Task GitUI.CommandsDialogs.RevisionDiffControl.ShowSelectedFileDiffAsync()
   at async void GitUI.CommandsDialogs.RevisionDiffControl.DiffFiles_SelectedIndexChanged(object sender, EventArgs e)+(?) => { }
   at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```

**Comment by RussKie** [comment]
We no longer crash the app, instead we show a popup in the dashboard, which looks a little puzzling:
![image](https://user-images.githubusercontent.com/4403806/163806388-ace4b25e-1ad4-49d5-b839-fee7e21d8b95.png)

The error is caused by a race condition that results in an execution of a git command against an invalid context, i.e., the git process working directory.
Here's the successful execution context:
![image](https://user-images.githubusercontent.com/4403806/163809424-cb242768-5757-4f8c-b0b4-ff3c43c77f31.png)

Here's what we have when we close the repo while executing the command:
![image](https://user-images.githubusercontent.com/4403806/163809507-12edc369-1237-403d-a542-a124f73936f7.png)

**Comment by gerhardol** [comment]
I got the following when exiting early.

- Git Extensions 33.33.33
- Build 28cc0f1f4226bfe0f3addd42ed746f23d781bd90
- Git 2.35.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.4
- DPI 96dpi (no scaling)

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: remote

```
GitExtUtils.ExternalOperationException: fatal: not a git repository (or any of the parent directories): .git
 ---> System.Exception: fatal: not a git repository (or any of the parent directories): .git
   --- End of inner exception stack trace ---
   at async Task<ExecutionResult> GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken)
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at ExecutionResult GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action<StreamWriter> writeInput, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes, bool throwOnErrorExit, CancellationToken cancellationToken)
   at IReadOnlyList<string> GitCommands.GitModule.GetRemoteNames()
   at (string repoProject, string repoName) GitCommands.Remotes.RepoNameExtractor.Get()
   at string GitUI.BuildServerIntegration.BuildServerWatcher.ReplaceVariables(string projectNames)
   at void AppVeyorIntegration.AppVeyorAdapter.Initialize(IBuildServerWatcher buildServerWatcher, ISettingsSource config, Action openSettings, Func<ObjectId, bool> isCommitInRevisionGrid)
   at async Task<IBuildServerAdapter> GitUI.BuildServerIntegration.BuildServerWatcher.GetBuildServerAdapterAsync()
   at async Task GitUI.BuildServerIntegration.BuildServerWatcher.LaunchBuildServerInfoFetchOperationAsync()
   at async void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+(?) => { } [30]
   at async void GitUI.ThreadHelper.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

**Comment by RussKie** [comment]
The root cause is the same:
- we are running commands against a volatile instance of GitModule, and
- we aren't cancelling ongoing background operations when switching repos.

I'm not sure there's an easy fix for either of these.
