### ISSUE TITLE
[NBug] startIndex cannot be larger than length of string.Paramet...

### ISSUE THREAD

**Issue by victorcumpana** [gitextensions/gitextensions#8584]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitCommands.GitCommandHelpers.GetAllChangedFilesFromString_v2(String statusString)
   at GitCommands.GitCommandHelpers.GetStatusChangedFilesFromString(IGitModule module, String statusString)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Not know

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.18.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4220.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
First time reported
The output from Git-status is shorter than in the documentation:
https://git-scm.com/docs/git-status#_porcelain_format_version_2
The code is moved to GitCommands\Git\GetAllChangedFilesOutputParser.cs:213 in master

If this occurs again, GE could just ignore the entry.
There is no filename, so not much to report (could be done in a status item, added in #7902 PRs.)
