### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by Gutza** [gitextensions/gitextensions#8585]
## Current behaviour

The upgrade crashes sometimes.

## Expected behaviour

The upgrade never crashes. :)

## Steps to reproduce

I'm afraid I don't know how to reproduce this. All I know is I had kept a few Git Extensions windows opened for at least 24 hours on multiple workspaces, and during the upgrade it crashed with the exception below. I tried again after it crashed, and I was able to upgrade.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Attempting to upgrade

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Looks like the git executable has disappeared, perhaps due to an update of git, which is independent of Git Extensions but required.

**Comment by gerhardol** [comment]
> Looks like the git executable has disappeared, perhaps due to an update of git, which is independent of Git Extensions but required.
> So please close all GE instances before installing a Git update.

Recent discussion in #6692, Git update while GE is running is not supported - you may get this crash

**Comment by gerhardol** [comment]
Duplicate of #6692 
Upgrading while in use is not supported.
This is still changed in master, #8587 

```
This change is like allowing the user to hot swap the engine while running, as long as they do not touch any controls,
or they have changed specific addons.
```
