### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by nelsonestevaomartins** [gitextensions/gitextensions#8613]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.<CheckoutConflictedFiles>g__CheckoutPart|82_0(Int32 part, String fileName, String unmerged, <>c__DisplayClass82_0& )
   at GitCommands.GitModule.CheckoutConflictedFiles(ConflictData unmergedData)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool()
   at GitUI.CommandsDialogs.FormResolveConflicts.merge_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I used the "Resolve merge conflicts" after the conflicts were solved.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
GE tries to get the contents of the conflicting files with git-checkout-index saving the contents to a temporary file (that should have safe characters), GE reads the filename from the command. What is read is causing the exception. A likely reason is that Git responds with "fatal:", which is illegal in filenames.
(.NET 5 IO changes will somehow help here, no exception when combining, the exception when moving the nonexisting temp file will be catched.)
