### ISSUE TITLE
[NBug] Exception of type 'GitCommands.Config.GitConfigurationExcep...

### ISSUE THREAD

**Issue by DmitriSkvortsov** [gitextensions/gitextensions#8625]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: A device which does not exist was specified.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitCommands.Settings.ConfigFileSettingsCache.<GetConfigSections>b__11_0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.Settings.ConfigFileSettingsCache.GetConfigSections()
   at GitCommands.Settings.ConfigFileSettings.GetConfigSections()
   at GitCommands.Remotes.ConfigFileRemoteSettingsManager.GetDisabledRemotes()
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<<UICommands_PostRepositoryChanged>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Just opening repository from local location

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
The error message suggest you have a configuration that points to either a
removable or network device, that wasn't available.

If you can find what it was and let us know we can probably fix it.
