### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by jornletnes** [gitextensions/gitextensions#8629]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
rename the local folder from outside the Git Extensions GUI, then click reload.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
To remove the directory while running the application is not supported.
The presentation of such error situations will however maybe be improved (#8278, #8358).
