### ISSUE TITLE
Crash on refresh

### ISSUE THREAD

**Issue by MonkAlex** [gitextensions/gitextensions#8674]
## Current behaviour

Run app.
Do some actions (open-close commit window, open history, open diff)
On close modal (maybe any) window, commit tree refreshed.
Sometimes (not stable) git extensions crashed.

In event viewer saved exception like this:
```
Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Failed to schedule time on the UI thread. A continuation would never execute.
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+MainThreadAwaiter.OnCompleted(System.Action, Boolean)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AwaitOnCompleted[[GitUI.ControlThreadingExtensions+ControlMainThreadAwaiter, GitExtUtils, Version=3.0.0.4433, Culture=neutral, PublicKeyToken=null],[GitUI.CommitInfo.CommitInfo+<>c__DisplayClass50_0+<<ReloadCommitInfo>g__LoadAnnotatedTagInfoAsync|10>d, GitUI, Version=3.0.0.4433, Culture=neutral, PublicKeyToken=null]](ControlMainThreadAwaiter ByRef, <<ReloadCommitInfo>g__LoadAnnotatedTagInfoAsync|10>d ByRef)
   at GitUI.CommitInfo.CommitInfo+<>c__DisplayClass50_0+<<ReloadCommitInfo>g__LoadAnnotatedTagInfoAsync|10>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

## Expected behaviour
Not crashed.

## Did this work in previous version of GitExtensions

No idea.

## Environment

- GitExtensions version: 3.4.3.999
- GIT version: 2.29
- OS version: Windows 10
- .NET version: Install all, what can found. 4.5-4.8

**Comment by gerhardol** [comment]
Copt the version info from About please.
Similar problems have occurred with older .NET versions
![image](https://user-images.githubusercontent.com/6248932/102018890-7005ec80-3d70-11eb-9604-849d6e4d4c16.png)

**Comment by MonkAlex** [comment]
In about .Net Framework 4.8.4250.0
Windows 10.0.17763.0

**Comment by vbjay** [comment]
Copy the info from the about screen like asked. It provides all the info
needed.

**Comment by MonkAlex** [comment]
Work PC, cannot copy any info, only read-write it manual =)

**Comment by vbjay** [comment]
I see.

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/issues/5936#issuecomment-468911929
What is in the config fiule?
Also see last comment about contents in the registry

**Comment by RussKie** [comment]
This would very likely be an environment induced issue.

**Comment by MonkAlex** [comment]
> 
> 
> [#5936 (comment)](https://github.com/gitextensions/gitextensions/issues/5936#issuecomment-468911929)
> What is in the config fiule?
> Also see last comment about contents in the registry

Config is correct, nothing about "Switch..." configurations.
Registry empty - not found any "AppContext" values.

**Comment by MonkAlex** [comment]
I update desc of bug.
`Sometimes (not stable) git extensions show system warning "Unknown Hard Error", i can ignore this and work, but when i press "Ok" - app closed.`

**Comment by mstv** [comment]
Is there a callstack (with more information) displayed in GE's dialog (I guess our NBug report form) which you can close or click `OK`?

**Comment by MonkAlex** [comment]
> 
> 
> Is there a callstack (with more information) displayed in GE's dialog (I guess our NBug report form) which you can close or click `OK`?

No. It just Windows message box, like this:
![изображение](https://user-images.githubusercontent.com/6784764/102402621-1ca4d000-3ff6-11eb-81ac-9052cc38076c.png)
In event viewer exception with call stack, i put it on topic.

**Comment by mstv** [comment]
Thank you, so we don't have more info.
@sharwell, do you have a clue regarding "Failed to schedule time on the UI thread. A continuation would never execute."`?

**Comment by sharwell** [comment]
The crash is hitting this code:

https://github.com/microsoft/vs-threading/blob/a2c873656dd7a7967499595a4587cee7b71ff4b4/src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs#L970-L973

We need to see the inner exception to diagnose. Easiest way is configuring Windows to automatically collect a crash dump via the registry.
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by MonkAlex** [comment]
> Enabling the feature requires administrator privileges. 

Sorry, i don't have admin on my work PC.

**Comment by sharwell** [comment]
There are multiple ways to diagnose latent errors like this, but all of them require administrator privileges for at least part of the diagnosis.

I do feel your pain. One of my prior employers had a configuration like this and the resulting productivity impairment was acute. Hopefully you can get an admin to help set up the test to capture this data.

**Comment by MonkAlex** [comment]
Configure all registry to dump and ignore debug.

On crash nothing dumped.

**Comment by sharwell** [comment]
I saw that once before but I'm not sure how/why it happened, and I'm not sure why it started working some time after that. Here's the configuration I use myself:

![image](https://user-images.githubusercontent.com/1408396/102660198-7d83f380-412f-11eb-8ea7-b8b3d719ce46.png)

This configuration will capture _any_ process that crashes, so make sure you have a good bit of disk space on the drive that **DumpFolder** points to. Also make sure that folder exists (I'm not sure if it's automatically created; I always have it there).

**Comment by MonkAlex** [comment]
Retry registry configuration - nothing changed.

So, maybe i write it bad.
When i get "Unknown Hard Error" - its not modal window (process explorer say windows title "GitExtensions.exe - System Warning" has owner in csrss.exe), its always on top (and on top of winlogon for example), and when i not press "Ok" - i can work with GitExtensions.
But when i press "Ok" - GitExtensions closed.

Maybe process not "crashred" and dump not needed?

**Comment by MonkAlex** [comment]
Devenv.exe dumped to folder when crash. 
GitExtensions - not dumped on this exception.

**Comment by MonkAlex** [comment]
Any idea?..
