### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by SteWolk** [gitextensions/gitextensions#8692]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.PathUtil.FindInFolders(String fileName, IEnumerable`1 folders)
   at GitCommands.DiffMergeTools.DiffMergeToolConfigurationManager.LoadDiffMergeToolConfig(String toolName, String userSuppliedPath)
   at GitCommands.DiffMergeTools.DiffMergeToolConfigurationManager.GetToolCommand(String toolName, DiffMergeToolType toolType)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.SettingsToPage()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.LoadSettings()
   at GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

## Additional information
I can´t correct the settings, because the program quits before I can change the wrong part

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
As a workaround to fix the issue, edit the `.gitconfig` file to remove the
path. It works also by using the git command line.

**Comment by RussKie** [comment]
Can you please share the offending settings to investigate?

**Comment by gerhardol** [comment]
There was some invisible character in the kdiff3 path. I can reproduce by adding a | for instance
This is hopefully fixed in .NET 5, when IsPathRooted will no longer throw

The exception could be avoided, but it seems like this was introduced outside GE, so I propose no further is done for now
