### ISSUE TITLE
[NBug] rate limit exceeded

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [gitextensions/gitextensions#8701]
## Current behaviour

Commands under the GitHub tab are not working.

## Expected behaviour

Commands should work

## Steps to reproduce

Run any command under the GitHub top-level menu.

## Error Details
```
System.Exception: rate limit exceeded
   at Git.hub.Client.DoRequest[T](IRestRequest request, Boolean throwOnError)
   at Git.hub.Client.getRepository(String username, String repositoryName)
   at GitHub3.GitHubHostedRemote.GetHostedRepository()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass21_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Commands under the GitHub tab fail.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Did you set the github oauth token?
Because that's seemed to be the reason why you reached the github api
limit.

**Comment by gerhardol** [comment]
The limit is 50 requests/h without a token and 5000 with. The requests seem to be counted per IP address, so they may be shared by other users. (Enterprise repos have higher limits.)

**Comment by Mohit-Chakraborty** [comment]
Thanks. That got it working.
