### ISSUE TITLE
[NBug] GitLab Plugin Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Fabman08** [gitextensions/gitextensions#8704]
## Current behaviour

Raise an error clicking on _Create Merge Request_ button

## Expected behaviour

Create a Merge Request :)

## Steps to reproduce

I've added my APIKEY for GitLab Pluging in its configuration section and then I've clicked on _Create Merge Request_ button.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitExtensions.GitLab.GitLabHostedRemote.get_IsOwnedByMe()
   at GitExtensions.GitLab.Forms.CreateMergeRequestForm.<>c.<CreateMergeRequestForm_Load>b__19_0(IHostedRemote remote)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GitExtensions.GitLab.Forms.CreateMergeRequestForm.CreateMergeRequestForm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
add api key for GitLab plugin in configuration section and then click on Create Merge Request button

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.3
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The GitLab plugin is handled in a separate repo, outside of GitExtensions.
Can you please submit the issue:
https://github.com/ahmeturun/GitExtensions.GitLab/issues

The NBug reporter cannot distinguish between a plugin and the main app.
