### ISSUE TITLE
[NBug] The specified path, file name, or both are too long. The fu...

### ISSUE THREAD

**Issue by Ahsanmumtaz1105** [gitextensions/gitextensions#8749]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at GitUI.Editor.FileViewer.ViewFileAsync(String fileName, Boolean isSubmodule, Action openWithDifftool)
   at GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(GitItemStatus file, ObjectId revision, Action openWithDifftool)
   at GitUI.CommandsDialogs.FormCommit.<SetSelectedDiffAsync>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormCommit.<>c__DisplayClass137_0.<<ShowChanges>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
not sure

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Corrected in #8575 , included in 3.5
