### ISSUE TITLE
Crash after installing GitLab extension

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#8757]
## Current behaviour

* Installed GitExtensions on a new machine
* Copied my previous settings over - note: previous install has no extra plugins installed other than the ones which ship with GE by default
* Installed the GitLab plugin. The Plugin Manager closed GE for the install.
* Reopened GE resulting in a hard crash on start-up.

After manually removing the `Users\Name\AppData\Local\GitExtensions\UserPlugins\GitExtensions.GitLab` folder + removing the package from the `Users\Name\AppData\Local\GitExtensions\UserPlugins\packages.config` file, GE starts up again as normal.

## Expected behaviour

No crash

## Steps to reproduce

See above and I have been able to consistently reproduce it by installing the GitLab plugin again as I forgot to take a screenshot the first time round ;-)

## Screenshots

![image](https://user-images.githubusercontent.com/663378/104817180-e1c5d000-581f-11eb-99c6-9d07781c1eb6.png)

I also allowed the error to be send in/reported, so the error details should be in the received reports from the last hour or so. Let me know if you need any additional info to specifically identify this report.

## Did this work in previous version of GitExtensions

No idea as I never installed the extension before.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   at GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

**Comment by gerhardol** [comment]
GitLab plugin is handled in a separate repo:
https://github.com/ahmeturun/GitExtensions.GitLab

**Comment by jrfnl** [comment]
@gerhardol Thanks for pointing me to the correct place. Issues moved there now: https://github.com/ahmeturun/GitExtensions.GitLab/issues/2

**Comment by maphew** [comment]
Agree the plugin is causing the crash, but the bug for GE is that it is not identifying the source of the problem and handling it gracefully. (e.g. by disabling the plugin and continuing to start up or exiting with message saying a plugin is at fault and to remove _"Users\Name\AppData\Local\GitExtensions\UserPlugins\$NAME + removing the package from the Users\Name\AppData\Local\GitExtensions\UserPlugins\packages.config file"_)

**Comment by RussKie** [comment]
You're welcome to propose a solution
