### ISSUE TITLE
[NBug] Unable to parse object ID "364e13b2b02f71f0e3e9d23cf1274a6b...

### ISSUE THREAD

**Issue by DhananjayK-LLA** [gitextensions/gitextensions#8880]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Unable to parse object ID "364e13b2b02f71f0e3e9d23cf1274a6b9e1dbc04

warning: refname 'HEAD' is ambiguous.".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.29.2.windows.3
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3690.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
This is not an exception in 3.4

You have used the special refname HEAD multiple times though...
