### ISSUE TITLE
GitConfigurationException: Cannot open the application

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8890]
## Current behaviour

(opened for colleague, not having the problem myself)

The default setup at work is to set HOME to H: that is synced to the local PC with DFS.
HOMEDRIVE\HOMEPATH is default like C:\Users\username

In some situation the sync fails and the files on H: cannot be accessed, the user can see that files exist but not access them.
This applies for both .settings, .gitconfig and ssh keys.

When starting up on 3.4 or latest portable version, you get multiple pops about inaccessible settings, eventually you get the NBug with the info below. The user had problems getting into the settings, succeeeded eventually but could not change the settings, it seemed to reset back to H: This was also the case for a fresh portable installation.

The eventual workaround was to edit the .settings file and provide another path with a .gitconfig file.

```xml
  <item>
    <key>
      <string>customhomedir</string>
    </key>
    <value>
      <string>C:\cygwin\home\userid</string>
    </value>
  </item>
```

## Expected behaviour

Limited number of popups and at least a possibility to change the settings.

Many users would not even understand that the .gitconfig setting need to be changed, so some automatic fallback would be appreciated.

## Steps to reproduce

I have not succeeded to get the sync in this state myself other than by inserting an error:
```c#
public ConfigFileParser(ConfigFile configFile)
            {
                _configFile = configFile;
            }

            public void Parse(string? fileContent = null)
            {
                _fileContent = fileContent ?? throw new IOException("xxx");
```

A partial reproduce:

* Copy .gitconfig to another directory
* Change GE Git dir to this directory
* Make the directory inaccessible (set deny or something)

## Error Details

<details>
  <summary>Click to expand!</summary>

```
GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: This file is currently not available for use on this computer.

 at void System.IO.__Error.WinIOError(int errorCode, string maybeFullPath)
at void System.IO.FileStream.Init(string path, FileMode mode, FileAccess access, int rights, bool useRights, FileShare share, int bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)
at new System.IO.FileStream(string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, FileOptions options, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)
at new System.IO.StreamReader(string path, Encoding encoding, bool detectEncodingFromByteOrderMarks, int bufferSize, bool checkHost)
at string System.IO.File.InternalReadAllText(string path, Encoding encoding, bool checkHost)
at string System.IO.File.ReadAllText(string path, Encoding encoding)
at void GitCommands.Config.ConfigFile+ConfigFileParser.Parse(string fileContent)
at new GitCommands.Config.ConfigFile(string fileName, bool local)
--- End of inner exception stack trace ---
at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy`1.get_Value()
at GitCommands.Settings.ConfigFileSettingsCache.GetValueImpl(String key)
at GitCommands.SettingsCache.<>c__DisplayClass18_0.<GetValue>b__0()
at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
at GitCommands.SettingsCache.GetValue(String name)
at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
at GitUIPluginInterfaces.ISettingsSource.GetString(String name, String defaultValue)
at GitUI.CommandsDialogs.FormResolveConflicts.InitMergetool()
at GitUI.CommandsDialogs.FormResolveConflicts.Initialize()
at GitUI.CommandsDialogs.FormResolveConflicts.FormResolveConflicts_Load(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Windows.Forms.Form.OnLoad(EventArgs e)
at GitUI.GitExtensionsForm.OnLoad(EventArgs e)
at System.Windows.Forms.Form.OnCreateControl()
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl()
at System.Windows.Forms.Control.WmShowWindow(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
at System.Windows.Forms.Form.WmShowWindow(Message& m)
at System.Windows.Forms.Form.WndProc(Message& m)
at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
</details>

## Environment
- Git Extensions 3.6.0.11114
- Build f54a727a95393dcacfbbd8603dfd6daf931618c4 (Dirty)
- Git 2.21.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

With 3.4

<details>
  <summary>Click to expand!</summary>
```
System.AggregateException: One or more errors occurred. ---> GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: This file is currently not available for use on this computer.

 

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitCommands.Settings.ConfigFileSettingsCache.GetValueImpl(String key)
   at GitCommands.SettingsCache.<>c__DisplayClass18_0.<GetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.GetValue(String name)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitUIPluginInterfaces.ISettingsSource.GetString(String name, String defaultValue)
   at GitCommands.Settings.ConfigFileSettings.GetEncoding(String settingName)
   at GitCommands.GitModule.get_LogOutputEncoding()
   at GitCommands.RevisionReader.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at GitUI.RevisionGridControl.<>c__DisplayClass153_2.<ForceRefreshRevisions>b__9()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
---> (Inner Exception #0) GitCommands.Config.GitConfigurationException: Exception of type 'GitCommands.Config.GitConfigurationException' was thrown. ---> System.IO.IOException: This file is currently not available for use on this computer.

 

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   --- End of inner exception stack trace ---
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
   at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at GitCommands.Settings.ConfigFileSettingsCache.GetValueImpl(String key)
   at GitCommands.SettingsCache.<>c__DisplayClass18_0.<GetValue>b__0()
   at GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   at GitCommands.SettingsCache.GetValue(String name)
   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   at GitUIPluginInterfaces.ISettingsSource.GetString(String name, String defaultValue)
   at GitCommands.Settings.ConfigFileSettings.GetEncoding(String settingName)
   at GitCommands.GitModule.get_LogOutputEncoding()
   at GitCommands.RevisionReader.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()<---
```
</details>

**Comment by gerhardol** [comment]
Cannot reproduce, removing from 3.5

**Comment by RussKie** [comment]
Is there anything actionable for this issue?

**Comment by vbjay** [comment]
They shouldn't put portable in program files. It's designed to be on a usb
drive or folder in user profile.

**Comment by gerhardol** [comment]
In this case GE and Git is installed normally.

What should be changed is to not raise exception on every single error and abort loading, you cannot correct the actual issue and change the Git home.
But it is not trivial to achieve.
I have not been able to recreate the exact scenario myself.
