### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by PiotrGasiorek** [gitextensions/gitextensions#8921]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.DisplayInformation.get_BitsPerPixel()
   at System.Windows.Forms.DisplayInformation.get_LowResolution()
   at System.Windows.Forms.ToolStripProfessionalRenderer.get_RendererOverride()
   at System.Windows.Forms.ToolStripProfessionalRenderer.OnRenderToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
   at System.Windows.Forms.ToolStripRenderer.DrawToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
   at System.Windows.Forms.ToolStripPanel.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmEraseBkgnd(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
...

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
How did this happen?
