### ISSUE TITLE
[NBug] A generic error occurred in GDI+.

### ISSUE THREAD

**Issue by DevsAnon** [gitextensions/gitextensions#8960]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at GitUI.WindowsJumpListManager.MakeIcon(Image img, Int32 size, Boolean keepAspectRatio)
   at GitUI.WindowsJumpListManager.<>c__DisplayClass15_0.<UpdateCommitIcon>b__0()
   at GitUI.WindowsJumpListManager.SafeInvoke(Action action, String callerName)
   at GitUI.WindowsJumpListManager.UpdateCommitIcon(Image image)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass43_0.<.ctor>b__14(Object s, GitWorkingDirectoryStatusEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.<>c__DisplayClass41_0.<<Update>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Crashed and I cannot even see the error, Empty, full white error Report screen

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This looks something in Windows didn't agree with the app... Is this issue reproducible, or a one off?

**Comment by DevsAnon** [comment]
It was a one off. Seems like graphics related, but I was not sure as everything was white, no visible text. I found the send error report button from memory

**Comment by RussKie** [comment]
Thank you for sending it through (great memory!). Without more data I don't think we can action this.
If you get a repro or more info, please holler back.
