### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by Dobatymo** [gitextensions/gitextensions#9015]
## Current behaviour

Similar bug, but not the same as it's happening in different circumstances. https://github.com/gitextensions/gitextensions/issues/8613

One of the filenames include a ascii backspace character (ascii code 08) which is illegal in a Windows filename. The file was created on Linux. In the UI on Windows it's shown as a empty square. Clicking on the file in the diff tab crashes git extensions. 

## Expected behaviour

Not crash.

## Steps to reproduce

Create a file on Linux with such a character in the filename and check it out on Windows.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at GitCommands.FullPathResolver.Resolve(String path)
   at GitUI.Editor.FileViewer.SetVisibilityDiffContextMenu(Boolean visibleTextFile, String fileName)
   at GitUI.Editor.FileViewer.ResetForDiff(String fileName)
   at GitUI.Editor.FileViewer.<>c__DisplayClass103_0.<ViewPatchAsync>b__0()
   at GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   at GitUI.Editor.FileViewer.<ViewPatchAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.RevisionDiffControl.<<DiffFiles_SelectedIndexChanged>b__36_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
Nasty... ;)

Can you try the latest dev version and see if it works?

**Comment by gerhardol** [comment]
Please try the latest portable build. There has been some changes here.

**Comment by Dobatymo** [comment]
Works great now!
