### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by valeriu33** [gitextensions/gitextensions#9024]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.<CheckoutConflictedFiles>g__CheckoutPart|82_0(Int32 part, String fileName, String unmerged, <>c__DisplayClass82_0& )
   at GitCommands.GitModule.CheckoutConflictedFiles(ConflictData unmergedData)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   at GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool()
   at GitUI.CommandsDialogs.FormResolveConflicts.merge_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I made a cherrypick and solved the conflicts, it crashed when i clicked commit

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4341.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Please try the just released 3.5RC1
There has been changes related to this, a repo where this occurs and detailed instructions are required to confirm that this was corrected or to address any other cases
