### ISSUE TITLE
[NBug] Could not find a part of the path '{ProjectDir}.git\rebase-merge\git-rebase-todo'

### ISSUE THREAD

**Issue by ddimkovikj** [gitextensions/gitextensions#9080]
## Current behaviour

Git Extensions crashes when unable to find rebase file.

## Expected behaviour

When unable to find rebase file Git Extensions should report missing file instead of crashing .

## Steps to reproduce

1. Start one instance of Git Extensions and do an interactive rebase.
2. Modify anything in the commit window.
3. Start another instance of Git Extensions and abort the rebase
4. Click Save in the commit window on the first Git Extensions instance.

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path '{ProjectDir}.git\rebase-merge\git-rebase-todo'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at GitUI.CommandsDialogs.FormEditor.SaveChanges()
   at GitUI.CommandsDialogs.FormEditor.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at ResourceManager.GitExtensionsControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Additional information
I was doing interactive rebase while having another instance of Git Extensions opened.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
You could close the BugReportForm using the cross button in order to ignore the exception.

The presentation will improve with 9a9c8ae7f86e97ca57e87649c87dfdb7a2573230.
I would create a PR for 3.5 after #9063.
