### ISSUE TITLE
[NBug] Unexpected artificial commit in Git command: 11111111111111...

### ISSUE THREAD

**Issue by DennisPitallano** [gitextensions/gitextensions#9084]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Unexpected artificial commit in Git command: 1111111111111111111111111111111111111111
   at GitCommands.ArgumentBuilderExtensions.Add(ArgumentBuilder builder, ObjectId objectId)
   at GitCommands.GitModule.GetRevision(ObjectId objectId, Boolean shortFormat, Boolean loadRefs)
   at GitUI.UserControls.CommitDiff.SetRevision(ObjectId objectId, String fileToSelect)
   at GitUI.HelperDialogs.FormCommitDiff..ctor(GitUICommands commands, ObjectId objectId)
   at GitUI.RevisionGridControl.<>c__DisplayClass169_0.<ViewSelectedRevisions>g__ProvideForm|1()
   at GitUI.GitUICommands.ShowModelessForm(IWin32Window owner, Boolean requiresValidWorkingDir, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 provideForm)
   at GitUI.RevisionGridControl.ViewSelectedRevisions()
   at GitUI.RevisionGridControl.OnGridViewDoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Unexpected artificial commit in Git command: 1111111111111111111111111111111111111111

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
How to recreate:
* Select a normal commit
* Ctrl-click on artificial
* Doubleclick the artificial (you need a little timing...)

In this case the revisions should be compared instead

Just dismiss the popup

Fix: Change in `C:\dev\gc\gitextensions_4\GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:ViewSelectedRevisions()`
```
            if (selectedRevisions.Count > 0 && !selectedRevisions[0].IsArtificial)
```
