### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by yelkarama** [gitextensions/gitextensions#9093]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   at GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__45_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I opened a git directory in WSL

## Environment
- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.21354.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Issue in the GitLab plugin, please open an issue in the plugin repo instead.
https://github.com/ahmeturun/GitExtensions.GitLab
