### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: key

### ISSUE THREAD

**Issue by ArgonAlex** [gitextensions/gitextensions#9098]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Setting User name and Password in the Jira Commit Hint plugin causes NullException.

## Expected behaviour

Setting User name and Password in the Jira Commit Hint plugin should succeed and not cause a NullException.

## Steps to reproduce

Settings > Plugins > Jira Commit Hint

All the settings are the defaults, not changed before.

Set User name and Password, click Apply, this exception happens.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
   at GitUIPluginInterfaces.CredentialsManager.SetCredentials(SettingLevel settingLevel, String name, NetworkCredential value)
   at GitUIPluginInterfaces.CredentialsSetting.SaveValue(ISettingsSource settings, String userName, String password)
   at GitUIPluginInterfaces.CredentialsSetting.CredentialsControlBinding.SaveSetting(ISettingsSource settings, CredentialsControl control)
   at GitUIPluginInterfaces.SettingControlBinding`2.SaveSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
