### ISSUE TITLE
Missing Newtonsoft.Json.dll if installed with no plugins selected / Git Extensions (3.5.0.11713)

### ISSUE THREAD

**Issue by yegor-mialyk** [gitextensions/gitextensions#9110]
After clean installation of Git Extensions (3.5.0.11713) with no plugins selected. trying to open Settings leads to  an exception (see diagnostics).

## Steps to reproduce

- Make clean installation of Git Extensions
- Select no plugins during installation
- Open Git Extensions
- Go to Tools -> Settings

## Did this work in previous version of GitExtensions

I think so

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 240dpi (250% scaling)

## Diagnostics

---------------------------
Error
---------------------------

System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

   at GitCommands.Settings.Setting.SettingOf`1.<>c.<GetValue>b__20_0(String value)

   at GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)

   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)

   at GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)

   at GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)

   at GitCommands.Settings.SettingsPath.GetValue[T](String name, T defaultValue, Func`2 decode)

   at GitCommands.Settings.Setting.SettingOf`1.GetValue(String name)

   at GitCommands.Settings.Setting.SettingOf`1.get_Value()

   at GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.SettingsToPage()

   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()

   at GitUI.CommandsDialogs.FormSettings.LoadSettings()

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by mstv** [comment]
Thank you for pointing out that it depends on whether the plugins are installed or not!
GE crashes when closing the **manually opened** settings dialog.

It suffices to copy the `Newtonsoft.Json.dll` to the existing (non-empty - why?) folder "c:\Program Files (x86)\GitExtensions\Plugins".

Workaround: You could install with plugins and delete everything but the `Newtonsoft.Json.dll` from "c:\Program Files (x86)\GitExtensions\Plugins".

**Comment by yegor-mialyk** [comment]
I did this already, just letting you know.

**Comment by gerhardol** [comment]
What is it used for?

**Comment by mstv** [comment]
Fixed by #9124
