### ISSUE TITLE
[NBug] Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by balmeida-nokia** [gitextensions/gitextensions#9119]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at GitUIPluginInterfaces.NumberSetting`1.ConvertFromString(String value)
   at GitUIPluginInterfaces.NumberSetting`1.TextBoxBinding.SaveSetting(ISettingsSource settings, TextBox control)
   at GitUIPluginInterfaces.SettingControlBinding`2.SaveSetting(ISettingsSource settings)
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   at GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings()
   at GitUI.CommandsDialogs.FormSettings.Save()
   at GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Entered a number too large for Delete obselete branches and no check was made to make sure I was not abusing the entry

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Cannot reproduce in 3.4 or 3.5, when focus changes the max allowed value

**Comment by balmeida-nokia** [comment]
I changed 1 detail. Try now

**Comment by RussKie** [comment]
You're welcome to submit a fix

**Comment by pmiossec** [comment]
> Cannot reproduce in 3.4 or 3.5, when focus changes the max allowed value

The issue description is not very clear but it's when you enter this value in the settings of the plugin.

I think that we can assume that Jesus was not using a version control tool and so set a max length to 5 or 6 for this text input.
