### ISSUE TITLE
[NBug] Not Found

### ISSUE THREAD

**Issue by SvenVMSW** [gitextensions/gitextensions#9147]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Exception: Not Found
   at Git.hub.Client.DoRequest[T](IRestRequest request, Boolean throwOnError)
   at Git.hub.Client.getRepository(String username, String repositoryName)
   at GitHub3.GitHubHostedRemote.GetHostedRepository()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass21_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
trying to access github

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by at-ng** [comment]
I'm having the same issue when I tried adding a personal toke under "OAuth Token" for GitHub settings. If I remove the token I get "GitHub credentials" (not getting the other "GitHub login" box) instead but I can't login (normally or with token), I just get the error "Failed to generate token due to error: Not Found". Pushing to remote works fine but can't view pull requests.

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
@at-ng Not sure that's exactly the same.
Api used to generate toek has been deprecated by GitHub.
So either generate token from GitHUb website and fill the setting or update to v3.5 to have a little more help ( See #9103 )

**Comment by pmiossec** [comment]
Could also be a duplicate of #9117 that has a PR #9133 trying to fix the problem but still not tested. If it's your problem, then you could test it and confirm if it works...

**Comment by at-ng** [comment]
@pmiossec I do have the same issue, the details I mentioned where just meant as additional information.

I tried updating to 3.5 and generating a new token though but still getting a not found error (same error if I delete the token in GitHub):

> System.Exception: Not Found
   at Git.hub.Client.DoRequest[T](IRestRequest request, Boolean throwOnError)
   at Git.hub.Client.getRepository(String username, String repositoryName)
   at GitHub3.GitHubHostedRemote.GetHostedRepository()
   at GitUI.CommandsDialogs.RepoHosting.ViewPullRequestsForm.<ViewPullRequestsForm_Load>b__20_0()
   at GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)  
   at GitCommands.AsyncLoader.<LoadAsync>d__121.MoveNext()

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
