### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by ghostzali** [gitextensions/gitextensions#9175]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   at GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   at GitExtensions.GitLab.GitLabPlugin.CurrentGitUiCommands_PostSettings(Object sender, GitUIPostActionEventArgs e)
   at GitUI.GitUICommands.InvokePostEvent(IWin32Window ownerForm, Boolean actionDone, EventHandler`1 gitUIEventHandler)
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.GitUICommands.StartSettingsDialog(IWin32Window owner, SettingsPageReference initialPage)
   at GitUI.GitUICommands.StartSettingsDialog(IGitPlugin gitPlugin)
   at GitExtensions.GitLab.GitLabPlugin.Execute(GitUIEventArgs gitUIEventArgs)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass63_0.<RegisterPlugins>b__2(Object <p0>, EventArgs <p1>)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
after install gitlab plugin

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please submit the bug to the GitLab plugin repo https://github.com/ahmeturun/GitExtensions.GitLab
