### ISSUE TITLE
Crash with Ctrl+F3 on binary file.

### ISSUE THREAD

**Issue by MarekKnapek** [gitextensions/gitextensions#9214]
Steps to reproduce:
 - Open repository.
 - Focus commit.
 - Switch to Diff tab.
 - Select binary file (Windows DLL).
 - Right mouse click for context menu.
 - Open this revision (temp file) Ctrl+F3.
 - Crash.

Windows 10, x64, 10.0.19042.985, not administrator, English language, non-standard locale.
 - Git Extensions 3.4.3.9999
 - Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
 - Git 2.31.1.windows.1
 - Microsoft Windows NT 10.0.19042.0
 - .NET Framework 4.8.4341.0
 - DPI 96dpi (no scaling)

System.ComponentModel.Win32Exception
No application is associated with the specified file for this operation
Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo) @ System.Diagnostics.Process
Call stack:
```
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c.<diffOpenRevisionFileToolStripMenuItem_Click>b__54_0(String fileName)
   at GitUI.CommandsDialogs.RevisionDiffControl.<>c__DisplayClass56_0.<<SaveSelectedItemToTempFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

**Comment by mstv** [comment]
The open method has changed for 3.5. Then Win10 20H2 displays a warning like "You are attempting to open a system file".
An eventual exception is displayed in a TaskDialog now.

3.5 has some issues. You could test the portable build. 3.5.1 is being prepared.
If it isn't resolved, please holler back to reopen.
