### ISSUE TITLE
[NBug] Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by pplans** [gitextensions/gitextensions#9228]
## Current behaviour

After installing gitlab plugin the whole app crash at each run

## Expected behaviour

That it won't crash and remove or disable this faulting plugin to avoid crashing again or at least propose that

## Steps to reproduce

Just install the gitlab plugin

## Error Details
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   at GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Installed gitlab plugin, then it fucked up everything

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please submit the bug to the GitLab plugin repo ahmeturun/GitExtensions.GitLab
