### ISSUE TITLE
[NBug] startIndex cannot be larger than length of string.Paramet...

### ISSUE THREAD

**Issue by duralf** [gitextensions/gitextensions#9338]
## Current behaviour

I right click on commit 'git-svn' (321a14e6617ede932ecdffb4c9532eda67cc85c1) in repo: https://github.com/duralf/yabe.git and press 'Create new branch here' and get this exception.

## Expected behaviour
A popup shows up and allows for creating a branch.

## Steps to reproduce

See current behaviour. It may possibly be related to git svn.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitCommands.GitRef.get_LocalName()
   at GitUI.CommandsDialogs.FormCreateBranch..ctor(GitUICommands commands, ObjectId objectId, String newBranchNamePrefix)
   at GitUI.RevisionGridControl.<>c__DisplayClass173_0.<CreateNewBranchToolStripMenuItemClick>b__0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent, Func`1 action)
   at GitUI.RevisionGridControl.CreateNewBranchToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I right-clicked a commit and pressed create branch here. Crashes in version 3.5.1 as well

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
> See current behaviour. It may possibly be related to git svn.

Good hint. The remote name might not be part of the full branch name as the code presumes.

**Comment by mstv** [comment]
You could try the dev build based on 3.5.1 https://ci.appveyor.com/api/buildjobs/kduel6anx2s57ten/artifacts/combined.3.5.1.12261-unsigned.zip.
