### ISSUE TITLE
[NBug] An item with the same key has already been added.

### ISSUE THREAD

**Issue by Sinstraliz** [gitextensions/gitextensions#9343]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at GitUI.CommandsDialogs.FormBrowse.<UpdateSubmoduleMenuStatusAsync>d__195.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass193_0.<<SubmoduleStatusProvider_StatusUpdated>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
When I open any git repo I get this error but if I ignore it seems that everything is working fine

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.20.1.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
New in 3.5, 3 occurrences seen

For some reason , the submodule list contains submodules with identical paths. This could be empty/whitespace oaths too, they are ignored anyway.
For 3.5.2 the list should filter empty paths and only accept the first path.
