### ISSUE TITLE
[NBug] Already transitioned to the Completed state.

### ISSUE THREAD

**Issue by ssokratov** [gitextensions/gitextensions#9373]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.InvalidOperationException: Already transitioned to the Completed state.
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.Threading.AsyncQueue`1.Enqueue(T value)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.UpdateVisibleRowRange()
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.Add(GitRevision revision, RevisionNodeFlags types)
   at GitUI.RevisionGridControl.<>c__DisplayClass165_0.<ForceRefreshRevisions>g__OnRevisionRead|0(GitRevision revision)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.ObserveOnObserverLongRunning`1.Drain()
   at System.Reactive.ObserveOnObserverLongRunning`1.<>c.<.cctor>b__17_0(ObserveOnObserverLongRunning`1 self, ICancelable cancelable)
   at System.Reactive.Concurrency.NewThreadScheduler.<>c__DisplayClass7_0`1.<ScheduleLongRunning>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

## Additional information
Just pulled the remote brunch

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.25.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
_backgroundQueue.Enqueue() failed
Same in 3.4

**Comment by mstv** [comment]
Will be resolved by #8809, which replaces the `_backgroundQueue`.
