### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by gdavidkov** [gitextensions/gitextensions#9383]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.ResolveGitInternalPath(String relativePath)
   at GitUI.CommandsDialogs.FormPull..ctor(GitUICommands commands, String defaultRemoteBranch, String defaultRemote, PullAction pullAction)
   at GitUI.GitUICommands.<>c__DisplayClass93_0.<StartPullDialogInternal>g__Action|0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Func`1 action, Boolean requiresValidWorkingDir, Boolean changesRepo, EventHandler`1 preEvent, EventHandler`1 postEvent)
   at GitUI.GitUICommands.StartPullDialogInternal(IWin32Window owner, Boolean pullOnShow, Boolean& pullCompleted, String remoteBranch, String remote, PullAction pullAction)
   at GitUI.CommandsDialogs.FormBrowse.rebaseToolStripMenuItem1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Nothign to add

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.30.0.windows.1

14:19:33.766435 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:19:33.767456 git.c:444               trace: built-in: git version
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 120dpi (125% scaling)

**Comment by mstv** [comment]
> Nothign to add

How do your settings look?
Or did you even update Git while running GE?
It works for me both with backslashes and with forward slashes:

![image](https://user-images.githubusercontent.com/36601201/126562231-36d6fef7-3d9e-4006-95f4-e3ca8d79574a.png)
