### ISSUE TITLE
Git extensions not responding (freezing) from time to time

### ISSUE THREAD

**Issue by roblatprogen** [gitextensions/gitextensions#9409]
## Current behaviour

Git extensions not responding (freezing) from time to time
I am using a repo with a submodule. Sometimes I open two GE windows, one for main repo one for the submodule. I was doing fine before I upgraded to 3.5.1.12196. I cannot be 100% sure what's the previous version I use, may be 3.5.0.11713.

## Expected behaviour
Git extensions should not be freezing

## Steps to reproduce

I am not sure about the minimal reliable RS
Just daily usage, clicking GE window here and there, menus, buttons. Sometimes the freezing just happens.

## Screenshots

<img width="787" alt="GitExtensionsFreeze" src="https://user-images.githubusercontent.com/87788764/126729042-f77aa24f-6e3c-413f-a6d1-5f0e441404fe.png">

## Did this work in previous version of GitExtensions

Maybe 3.5.0.11713 doesn't have this issue

## Environment

- GitExtensions version: 3.5.1.12196
- GIT version: 2.30.1.windows.1
- OS version: Windows 10 Enterprise
- .NET version: .net 5

**Comment by RussKie** [comment]
If you open git commands log (F12) you can see which commands take long
time to execute, which may help understanding what's wrong.

Does it affect repos without submodules?

**Comment by roblatprogen** [comment]
> If you open git commands log (F12) you can see which commands take long time to execute, which may help understanding what's wrong. Does it affect repos without submodules?

The GE window froze,  not responding to F12, I have to force closing it. Not sure about repos without submodules.

**Comment by roblatprogen** [comment]
> If you open git commands log (F12) you can see which commands take long time to execute, which may help understanding what's wrong. Does it affect repos without submodules?

Ok, I caught something from git command log this time, that window also frozen:
![image](https://user-images.githubusercontent.com/87788764/126746966-07ecd6d5-29e9-4795-9a0d-a490b65e7b0b.png)

**Comment by pmiossec** [comment]
If I understand well, the git command log doesn't provide the information we need.
Because you should post the git command log **after** the freeze is finished so that it is updated with the git command that takes a lot of time.

That bring another question: Does the application freeze completely and never come back usable again (even if you click "Wait for the program to respond")? Or the freeze is temporary and after that you could use the application again?

Because in the second case, you will be able to provide the git command log but not in the first case 😟

**Comment by roblatprogen** [comment]
> If I understand well, the git command log doesn't provide the information we need.
> Because you should post the git command log **after** the freeze is finished so that it is updated with the git command that takes a lot of time.
> 
> That bring another question: Does the application freeze completely and never come back usable again (even if you click "Wait for the program to respond")? Or the freeze is temporary and after that you could use the application again?
> 
> Because in the second case, you will be able to provide the git command log but not in the first case 😟

Once it happened, GE never come back. I opened F12 window before the issue happened.

**Comment by RussKie** [comment]
Is this issue only observed in a specific repo? Or all repos?
How long do you wait before killing the process?

**Comment by roblatprogen** [comment]
> Is this issue only observed in a specific repo? Or all repos? How long do you wait before killing the process?
I only worked and reproduced the issue in one repo. I could have waited a few minutes. I don't think it would recover. I feel it's a deadlock or infinite loop happened.

Now I rolled my GE back to:
Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4390.0
- DPI 144dpi (150% scaling)
The issue has gone.

**Comment by RussKie** [comment]
Without more information I don't think we can provide any help... Can you may be do a memory dump when it hangs?

**Comment by OJacot-Descombes** [comment]
I have a log showing once a delay of about 55 seconds and 3 times of 28 seconds.
Version 4.0.2.16100
```
2023-05-05T16:02:48.8225066+02:00	56	11952	UI	1	git	config --get ą	
2023-05-05T16:02:48.8967466+02:00	51	22572	UI	0	git	--version	
2023-05-05T16:02:50.2891778+02:00	52	400	UI	0	git	rev-parse --git-common-dir	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.3453443+02:00	59	38316		0	git	--no-optional-locks for-each-ref --format="%(if)%(authordate)%(then)%(objectname) %(refname)%(else)%(*objectname) %(*refname)%(end)"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.3535740+02:00	59	20080			git	stash list -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%gD%n%B"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.3582215+02:00	68	8604		0	git	-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --author-date-order --max-count=100000 --reflog --	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.3828473+02:00	59	26308	UI	0	git	ls-files -z --unmerged	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.4153032+02:00	56	36236		0	git	for-each-ref --format="%(push:track,nobracket)::%(upstream:track,nobracket)::%(push)::%(upstream)::%(refname:short)" refs/heads/	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.4845385+02:00	64	32092		0	git	remote -v	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.6113709+02:00	59	37592	UI	0	git	ls-files -z --unmerged	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.8072457+02:00	59	17940	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.8829977+02:00	60	31256		0	git	for-each-ref --sort="-taggerdate" --format="%(refname)" refs/tags/	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.8855255+02:00	69	3024		0	git	branch --contains b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.8857786+02:00	73	34244		0	git	tag --contains b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:50.8867655+02:00	81	25576		128	git	describe --tags --first-parent --abbrev=40 b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:02:58.2614238+02:00	55799	30424		0	git	difftool --tool-help	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:06.1671841+02:00	56	34184	UI	0	git	ls-files -z --unmerged	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:09.6674790+02:00	58	36128		0	git	tag --contains 18b42e27fa44bd43085efe6da25b5a5654e4753d	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:09.6675182+02:00	67	26308		0	git	branch --contains 18b42e27fa44bd43085efe6da25b5a5654e4753d	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:09.6675543+02:00	71	7724		128	git	describe --tags --first-parent --abbrev=40 18b42e27fa44bd43085efe6da25b5a5654e4753d	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:09.6684225+02:00	80	13740	UI	0	git	branch --format="%(refname)" -a --merged 18b42e27fa44bd43085efe6da25b5a5654e4753d	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.3215856+02:00	60	23816		0	git	branch --contains 2599e1b081f63b0a963e4c0f3c2df1164d1f58d8	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.3216510+02:00	82	36236	UI	0	git	branch --format="%(refname)" -a --merged 2599e1b081f63b0a963e4c0f3c2df1164d1f58d8	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.3216520+02:00	67	7912		128	git	describe --tags --first-parent --abbrev=40 2599e1b081f63b0a963e4c0f3c2df1164d1f58d8	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.3216639+02:00	72	2808		0	git	tag --contains 2599e1b081f63b0a963e4c0f3c2df1164d1f58d8	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.8399819+02:00	78	36968		0	git	tag --contains 30bc0bd9b9b39c21841dcab0705ac9feb5329ab5	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.8400052+02:00	85	38576		0	git	branch --contains 30bc0bd9b9b39c21841dcab0705ac9feb5329ab5	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.8400152+02:00	111	8880	UI	0	git	branch --format="%(refname)" -a --merged 30bc0bd9b9b39c21841dcab0705ac9feb5329ab5	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:10.8400298+02:00	93	38452		128	git	describe --tags --first-parent --abbrev=40 30bc0bd9b9b39c21841dcab0705ac9feb5329ab5	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:11.4300401+02:00	63	38908		0	git	branch --contains 76592617e90871e739072f58d091a487e2a43000	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:11.4300514+02:00	82	37884	UI	0	git	branch --format="%(refname)" -a --merged 76592617e90871e739072f58d091a487e2a43000	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:11.4300558+02:00	68	32032		0	git	tag --contains 76592617e90871e739072f58d091a487e2a43000	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:11.4300582+02:00	75	38476		128	git	describe --tags --first-parent --abbrev=40 76592617e90871e739072f58d091a487e2a43000	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.2146607+02:00	61	32288		0	git	branch --contains c9dc26d15d61a3ab770309743113cc200c29fcb9	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.2146722+02:00	65	27008		128	git	describe --tags --first-parent --abbrev=40 c9dc26d15d61a3ab770309743113cc200c29fcb9	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.2146848+02:00	82	25104	UI	0	git	branch --format="%(refname)" -a --merged c9dc26d15d61a3ab770309743113cc200c29fcb9	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.2146939+02:00	73	38476		0	git	tag --contains c9dc26d15d61a3ab770309743113cc200c29fcb9	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.7278317+02:00	60	29064		0	git	tag --contains 00fb715a4f8ab0a3f1df0995f456435ff6f1ba9e	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.7278382+02:00	66	25756		128	git	describe --tags --first-parent --abbrev=40 00fb715a4f8ab0a3f1df0995f456435ff6f1ba9e	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.7278408+02:00	76	33988		0	git	branch --contains 00fb715a4f8ab0a3f1df0995f456435ff6f1ba9e	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:12.7278464+02:00	83	7300	UI	0	git	branch --format="%(refname)" -a --merged 00fb715a4f8ab0a3f1df0995f456435ff6f1ba9e	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:13.6822984+02:00	54	37808	UI	0	git	rev-parse --quiet --verify "master~0"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:13.8212757+02:00	54	4252		128	git	describe --tags --first-parent --abbrev=40 b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:13.8212809+02:00	65	27028		0	git	tag --contains b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:13.8212905+02:00	73	38360		0	git	branch --contains b4ea4dc8704705425089b7fcf968bd24ee69f75b	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:22.0075640+02:00	28453	16816		0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:22.1445499+02:00	28320	16604		0	git	--no-optional-locks for-each-ref --format="%(objectname) %(refname)" refs/heads/	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:22.1519881+02:00	28326	38488	UI	1	git	rev-parse --quiet --verify "MERGE_HEAD~0"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:22.1525970+02:00	28324	34128		0	git	-c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.4653143+02:00	61	18756		0	git	remote	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.4656228+02:00	72	18288		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 --cached -- "Helpers/Options.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.5252217+02:00	60	36588	UI	0	git	rev-parse --quiet --verify "HEAD~0"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.5263548+02:00	67	5088		0	git	remote	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.5576096+02:00	63	13992		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 --cached -- "Helpers/Xml.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.6071890+02:00	57	14264	UI	0	git	ls-files -z --unmerged	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.6208570+02:00	58	25852		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 --cached -- "Model/RenderInfo.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.6795701+02:00	58	20376		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 -- "Services/DocCommentParser.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.6816103+02:00	64	33444	UI	0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram --ignore-all-space --unified=3 -- "Services/DocCommentParser.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.7253990+02:00	60	4424	UI	0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram --ignore-all-space --unified=3 -- "Services/DocCommentParser.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.7388279+02:00	59	22716		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 -- "Services/LineTransformSource.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.8014602+02:00	58	38680		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 -- "Services/Renderer.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:50.8596122+02:00	55	24816		0	git	-c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --histogram -U1000000 -- "Services/ShapeParser.cs"	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:52.5699236+02:00	54	38016	UI	0	git	ls-files -z --unmerged	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
2023-05-05T16:03:52.9110330+02:00	58	20816	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
```

**Comment by mstv** [comment]
(The 55 seconds is the runtime of a background task, used for providing additional diff tools. This does not delay the UI.)

As the first and the last call of `git status ...` finished in 59 / 58 ms, you did not have many uncommitted changes.
Perhaps there is a conflict between `git --no-optional-locks status ...` started before `git status ...` (both run in the background) and `git rev-parse ...` run by the UI thread.

What's your version of git?
Which plugins have you activated? In order to answer whether a plugin triggers the "git status" commands, you could activate "Capture call stacks" in the Git Command Log.

**Comment by OJacot-Descombes** [comment]
The log was made with git version 2.38.1.windows.1

I did install v2.40.1 now and will see if it makes a difference.
The Plugin Manager lists only itself. Most of the pre-installed plugins are disabled or not configured.

**Comment by mstv** [comment]
> Which plugins have you activated? In order to answer whether a plugin triggers the "git status" commands, you could activate "Capture call stacks" in the Git Command Log.

The callstacks of the involved commands would help to analyze (regardless of plugins). Could you share them, please?

![image](https://github.com/gitextensions/gitextensions/assets/36601201/fcc2de90-3b99-4e1e-be40-105d89c66404)

**Comment by OJacot-Descombes** [comment]
Okay, I caught one such event while I was browsing a repo:
```
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   ls-files -z --unmerged
Working dir: C:\Users\Oli\source\repos\PrettyDocComments\PrettyDocComments\
Process ID:  56336
Started at:  2023-05-23T14:33:22.9871222+02:00
UI Thread?:  True
Duration:    29136.899 ms
Exit code:   0
Call stack:  
   at GitCommands.Logging.CommandLog.LogProcessStart(String fileName, String arguments, String workDir)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitCommands.ExecutableExtensions.ExecuteAsync(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.ExecutableExtensions.<>c__DisplayClass8_0.<Execute>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.InTheMiddleOfConflictedMerge(Boolean throwOnErrorExit)
   at GitUI.UserControls.InteractiveGitActionControl.RefreshGitAction(Boolean checkForConflicts)
   at GitUI.CommandsDialogs.FormBrowse.OnActivate()
   at GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at GitUI.CommandsDialogs.FormBrowse.OnActivated(EventArgs e)
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolbarProxyWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DestroyWindow(IHandle hWnd)
   at System.Windows.Forms.NativeWindow.DestroyHandle()
   at System.Windows.Forms.Control.DestroyHandle()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at GitUI.CommandsDialogs.BrowseDialog.FormGitCommandLog.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.CallWindowProcW(IntPtr wndProc, IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam)
   at Interop.User32.CallWindowProcW(IntPtr wndProc, IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Form.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmSysCommand(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.CallWindowProcW(IntPtr wndProc, IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam)
   at Interop.User32.CallWindowProcW(IntPtr wndProc, IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Form.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmNcButtonDown(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

**Comment by RussKie** [comment]
> Okay, I caught one such event while I was browsing a repo:

Thank you!

That's a curious chain of events:

```
   ...
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes, Boolean throwOnErrorExit, CancellationToken cancellationToken)
   at GitCommands.GitModule.InTheMiddleOfConflictedMerge(Boolean throwOnErrorExit)
   at GitUI.UserControls.InteractiveGitActionControl.RefreshGitAction(Boolean checkForConflicts)
   at GitUI.CommandsDialogs.FormBrowse.OnActivate()
   at GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at GitUI.CommandsDialogs.FormBrowse.OnActivated(EventArgs e)
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at GitUI.CommandsDialogs.FormBrowse.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at Microsoft.WindowsAPICodePack.Taskbar.ThumbnailToolbarProxyWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DestroyWindow(IHandle hWnd)
   at System.Windows.Forms.NativeWindow.DestroyHandle()
   at System.Windows.Forms.Control.DestroyHandle()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at GitUI.CommandsDialogs.BrowseDialog.FormGitCommandLog.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   ...
```

We're in a middle of dispose flow and we're checking whether we're in a middle of conflict...

**Comment by gerhardol** [comment]
With 4.1 `git ls-files -z --unmerged` (the only Git call I know about that is started async when the application is minimized) is not started, could make a difference.
Was Log window closed while Browse was minimized here?

**Comment by gerhardol** [comment]
RepoObjectsTree runs GetMergedBranchesAsync() on Main thread. Opened PR for this.

Note that also ls-branches runs on the main thread. This command is executed every time the UI is activated.
This should not be the situation here.
Some more restructuring is required to run Git and related IO (file system, so much faster) calls on the default thread.
May be a separate PR.

Similar for GitStatusMonitor Update() and RevDiff -> GitUIExtensions.ViewChangesAsync()
But this is maybe not needed

**Comment by mstv** [comment]
Do such hangs still occur with the current version?
If yes, might it be caused by displaying large diffs in the `Diff` tab?

**Comment by OJacot-Descombes** [comment]
I haven't experienced such hangups for a long time.

**Comment by mstv** [comment]
> I haven't experienced such hangups for a long time.

Thank you for the feedback. This was the right answer. :)
