### ISSUE TITLE
[NBug] Method not found: 'GitUIPluginInterfaces.IProcess GitUIPlug.. when opening a Solution from Git Extensions

### ISSUE THREAD

**Issue by DLN-India** [gitextensions/gitextensions#9417]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.MissingMethodException: Method not found: 'GitUIPluginInterfaces.IProcess GitUIPluginInterfaces.IExecutable.Start(GitCommands.ArgumentString, Boolean, Boolean, Boolean, System.Text.Encoding)'.
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.<GetListAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at GitExtensions.SolutionRunner.Services.GitSolutionFileProvider.GetListAsync(Boolean isTopLevelSearchOnly, Boolean includeWorkspaces)
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.<>c__DisplayClass4_0.<<CreateBundleItemsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.<CreateBundleItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitExtensions.SolutionRunner.UI.SolutionListMenuItem.<OnDropDownOpening>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

## Additional information
daf

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 192dpi (200% scaling)

**Comment by pmiossec** [comment]
Maybe update the plugin if you don't have the last version.

**Comment by sanghel-payoff** [comment]
Had the same issue, uninstalled v4.1 and installed v5 via Plugin Manager, all is fine

**Comment by pmiossec** [comment]
IMHO it's better to open an issue in the plugin repo: https://github.com/maraf/GitExtensions.SolutionRunner
and tag @maraf if he can't update the plugin to support GE v4.2

**Comment by MTimoshinin** [comment]
> @RussKie  Please contact GitExtensions.SolutionRunner plugin developers.
I guess there is no support of new version in [GitExtensions.Extensibility](https://github.com/gitextensions/gitextensions.extensibility)

**Comment by MISTikus** [comment]
Fixed GitExtensions.SolutionRunner v.7 is available to download now
