### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80...

### ISSUE THREAD

**Issue by luweeewu** [gitextensions/gitextensions#9429]
## Current behaviour

Program crashed sometime during the night.

## Expected behaviour

Shouldn't crash.

## Steps to reproduce

Leave the program running overnight.

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 8007007E ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Additional information
Left the program running overnight.

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Was a Windows update being installed or a reboot pending?

**Comment by luweeewu** [comment]
Not to my knowledge. This problem is happening on a regular basis. If I leave Git Extensions running overnight or over the weekend, the error happens, and it crashes. It works properly when I start it again, but it’s so annoying to have this happen all the time.

**Comment by mstv** [comment]
@luweeewu, @Kableado, @dallf44,

could you enable the exception log files (refer to https://github.com/gitextensions/gitextensions/issues/9166#issuecomment-846364668) and share them after the next crash, please?

**Comment by dallf44** [comment]
It did not happen again, but I'll try.

**Comment by luweeewu** [comment]
Git Extensions crashed again last night. Here are the log files as you requested.

One detail to note: When I have my view set to Show all branches, I can leave Git Extensions open for days, and it won’t crash. The crashes seem to happen if I have the view set to Show current branch only.

**Comment by mstv** [comment]
> Here are the log files as you requested.

GH removes mail attachments. Could you paste them here?

**Comment by luweeewu** [comment]
> GH removes mail attachments. Could you paste them here?

[GitExtensions.3.5.1.12196.20210806.034820042.log](https://github.com/gitextensions/gitextensions/files/6947949/GitExtensions.3.5.1.12196.20210806.034820042.log)
[GitExtensions.3.5.1.12196.20210806.034820344.log](https://github.com/gitextensions/gitextensions/files/6947950/GitExtensions.3.5.1.12196.20210806.034820344.log)

**Comment by mstv** [comment]
> One detail to note: When I have my view set to Show all branches, I can leave Git Extensions open for days, and it won’t crash. The crashes seem to happen if I have the view set to Show current branch only.

Thank you. This will help to track down the issue.
In a short test, I did not notice a leak of GDI objects. But according to the exception, the GDI pool might be exhausted (usually 10000 or 20000).
Does the number of GDI objects used by GE increase significantly over the time? (TaskManager | Details | Add column "GDI objects") 

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.DrawImage(Image image, Rectangle rect)
   at System.Windows.Forms.ToolStripProfessionalRenderer.OnRenderItemImage(ToolStripItemImageRenderEventArgs e)
   at System.Windows.Forms.ToolStripRenderer.DrawItemImage(ToolStripItemImageRenderEventArgs e)
   at System.Windows.Forms.ToolStripButton.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandlePaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by luweeewu** [comment]
I’ve been seeing the GDI objects climb over the last 2 hours or so. It was in the high 2000s when I first looked at it, and it’s now sitting at around 3193. I see it go up and down slightly, but the general trend is up.

**Comment by RussKie** [comment]
Are you running the dark theme?

**Comment by mstv** [comment]
The number of GDI objects increases on refresh in dark theme also with `Show all branches` and without Left Panel, Build Server Integration, Avatars, Toolbars.

**Comment by luweeewu** [comment]
Yes.

**Comment by luweeewu** [comment]
While I don’t have the avatars visible, I do have the left panel and all toolbars visible.

**Comment by mstv** [comment]
> The number of GDI objects increases on refresh in dark theme also with Show all branches and without Left Panel, Build Server Integration, Avatars, Toolbars.

@NikolayXHD, it seems to be caused by a core functionality. Could you have a look?

**Comment by NikolayXHD** [comment]
> @NikolayXHD, it seems to be caused by a core functionality. Could you have a look?

ok, the coming weekend

**Comment by luweeewu** [comment]
I noticed that the number of GDI objects increases when showing all branches in dark mode, but nowhere near as catastrophically as when showing only the current branch. After a couple of days, the number of GDI objects is sitting at just over a couple hundred when showing all branches vs several thousand after a day when showing only the current branch.

**Comment by luweeewu** [comment]
I just had a look at the GDI object count now, and it was up over 59k. This was with leaving it set to show all branches for the entire time since I left a comment yesterday morning.

**Comment by pmiossec** [comment]
I did a quick investigation using [GDIVew](https://www.nirsoft.net/utils/gdi_handles.html) on the **portable version of v3.5.3**

With default theme:

| Total GDIs objects | Font | Brush | bitmap | Palette | Region | DC | Action|
|-----|-----|-----|-----|-----|-----|-----|-----|
| 149 | 35 | 10 | 18 | 1 | 6 | 21 | Startup & open repo|
| 156 | 43 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 151 | 38 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 156 | 43 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 152 | 40 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 155 | 43 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 156 | 44 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 155 | 43 | 10 | 18 | 1 | 6 | 21 | After refresh |
| 151 | 39 | 10 | 18 | 1 | 6 | 21 | After scrolling |
| 156 | 44 | 10 | 18 | 1 | 6 | 21 | After 10 refresh |
| 151 | 39 | 10 | 18 | 1 | 6 | 21 | After 10 refresh |
| 161 | 41 | 10 | 18 | 1 | 6 | 21 | After switch repositories |


With dark theme:
| Total GDIs objects | Font | Brush | bitmap | Palette | Region | DC | Action|
|-----|-----|-----|-----|-----|-----|-----|-----|
| 153 | 25 | 24 | 16 | 1 | 4 | 19 | Startup |
| 194 | 33 | 42 | 18 | 1 | 7 | 21 | Open repo |
| 216 | 42 | 56 | 18 | 1 | 7 | 21 | after refresh |
| 231 | 42 | 71 | 18 | 1 | 7 | 21 | after refresh |
| 236 | 36 | 82 | 18 | 1 | 7 | 21 | after refresh |
| 355 | 42 | 195 | 18 | 1 | 7 | 21 | After 10 refresh |

**From these numbers, we could clearly see that dark them is leaking brushes...**

/cc @NikolayXHD

**Comment by pmiossec** [comment]
We could have the 'Handle ref' and the 'kernel address' but I don't know if it could help debugging in VS:

![image](https://user-images.githubusercontent.com/460196/131399286-20ff9615-fba4-406e-a398-c1e494833ad5.png)

**Comment by pmiossec** [comment]
Spotted maybe another GDI leak:

The brushes count increase regularly when scrolling (by 8 or 10  at each page scrolled approximately)
When hiding the revision graph column, the number nearly stopped to increase (but still a small increase of 1 or 2 some time to time after a big scroll) .

Hiding the revision graph when doing a refresh doesn't reduce a lot the the brushes increase so it's possible that we have to main leaks...

**Comment by pmiossec** [comment]
After a little last test, hypothesis that should be verified:

Even if hidden, the revision graph is calculated for the commits actually displayed when doing a refresh and so is the same reason why there is a brush leak when doing a refresh.

**Comment by pmiossec** [comment]
Another one I think:
With only the revision grid visible (left panel, commit info and diff panel hidden, revision graph hidden), when you change the selected revision you leak every time some brushes: 1 or 3 most of the time (in rare cases it could be 5)

Not a clear pattern but it seems to be most of the times 1 brush is leaked when you select a commit from the same author and 3 when from another author (but not always because in rare cases you leak also 3 for the same author). I struggle to know if the option "highlight commits from same author has an impact"...

**I spent also some time trying to debug the application but without success**. If someone has an idea and could have a look now that we know that we leak only brushes with none 'default' theme...

**Comment by RussKie** [comment]
Were you able to narrow what method result in leaks?

One way of trying to find these is by commenting out code.

**Comment by RussKie** [comment]
Thank you for doing the investigation btw.

**Comment by pmiossec** [comment]
> Were you able to narrow what method result in leaks?
>

No. I spent most of the time trying to find a pattern that could give me a clue on the piece of code to investigate. 


> One way of trying to find these is by commenting out code.

Yes it is a good idea but l didn't want to comment half of GE code 😅

I only spent 30min trying to debug the application (especially revision graph code) but without success.

And I don't know when I will be able to give it another try....

**Comment by RussKie** [comment]
Haha, you'd be surprised how fast the app can run when you comment code out
;)

**Comment by NikolayXHD** [comment]
So, I can see the hard work is done - undoubtedly gdi objects are leaking.

When rendering code needs a brush, the one it gets may be a system brush, or a customized newly created brush adjusted for theme settings.

Because of that, the code which uses such brushes is not allowed to dispose them - system brushes are not supposed to be disposed.

What I plan to do, is return a Disposable brush wrapper, which knows whether the underlying actual brush should be disposed or not. All the brush consuming code will unconditionally call Dispose() on the wrapper.

Fill free to object :)

**Comment by gerhardol** [comment]
Please test the portable build in #9566 (currently latest build is https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40747903/artifacts, there may be updates though).
This fixes an issue seen with themes as seen here, if you also could check the GDI object count it would be great.
