### ISSUE TITLE
[NBug] Value cannot be null.Parameter name: value

### ISSUE THREAD

**Issue by AndreiSingeorzan** [gitextensions/gitextensions#9466]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at ConEmu.WinForms.ConEmuStartInfo.set_ConsoleProcessCommandLine(String value)
   at GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__201_0(Object sender, TabControlCancelEventArgs args)
   at System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
nohting special, just try to use the console

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Duplicate of #9471
