### ISSUE TITLE
[NBug] An unexpected internal error occurred in the Win32 call: 80...

### ISSUE THREAD

**Issue by Fulgan** [gitextensions/gitextensions#9514]
## Current behaviour

App crashed

## Expected behaviour

App doesn't crash

## Steps to reproduce

No idea... 

## Error Details
```
System.ComponentModel.Win32Exception: An unexpected internal error occurred in the Win32 call: 8007007E ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   --- End of inner exception stack trace ---
   at Microsoft.WindowsAPICodePack.Dialogs.NativeTaskDialog.NativeShow()
   at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog.ShowCore()
   at GitUI.NBugReports.BugReportInvoker.Report(Exception exception, Boolean isTerminating)
   at GitExtensions.Program.<>c.<Main>b__1_3(Object s, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

## Additional information
found this dialog when loging into windows this morning

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #9429

**Comment by gerhardol** [comment]
Please test the portable build in #9566 (currently latest build is https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40747903/artifacts, there may be updates though).
This fixes an issue seen with themes as seen here, if you also could check the GDI object count it would be great.
