### ISSUE TITLE
[NBug] The system cannot find the file specified

### ISSUE THREAD

**Issue by arnonax-tr** [gitextensions/gitextensions#9596]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
GitCommands.ExternalOperationException: The system cannot find the file specified ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   --- End of inner exception stack trace ---
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule module, RepoDistSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.Settings.RepoDistSettings.CreateEffective(GitModule module)
   at GitCommands.GitModule.get_EffectiveSettings()
   at GitCommands.GitModule.GetEffectiveSettings()
   at GitUI.CommandsDialogs.BuildReportTabPageExtension.IsBuildResultPageEnabled()
   at GitUI.CommandsDialogs.BuildReportTabPageExtension.FillBuildReport(GitRevision revision)
   at GitUI.CommandsDialogs.FormBrowse.FillBuildReport(GitRevision revision)
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, String filter, ObjectId selectedId, ObjectId firstId)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, ObjectId selectedId, ObjectId firstId)
   at GitUI.GitUICommands.RunOpenRepoCommand(IReadOnlyList`1 args)
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments)
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

```

## Additional information
I downloaded and installed Git 2.33.0 (becuase I had a warning about the git version whenever I open GitExtensions) and then after I restarted GitExtensions I received this exception

## Environment
- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git - (minimum: 2.19.0, recommended: 2.30.0)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The Git executable cannot be found, set the correct path in settings.
Maybe you had a 32 bit version before and installed a 64 bit now in a different path.
