### ISSUE TITLE
[NBug] Out of memory.

### ISSUE THREAD

**Issue by ozalifs** [gitextensions/gitextensions#9633]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
First time run, then popup showed that my workstation is out of memory. while I've check  my windows task manager, that I'm still 500MB left

## Environment
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The images for languages seem to be corrupt. The actual images are about 5KB.

**Comment by RussKie** [comment]
Was this a once off or is this happening consistently? Is it happening in a specific repo or across different repos? Are you using theming?
