### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by ivo-martisek-swi** [gitextensions/gitextensions#9674]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

### Issue description

Issue happens all the time on my system, while switching branches and probably any other activity.

## Error Details
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1..ctor(Int32 capacity)
   at GitUI.UserControls.RevisionGrid.Graph.RevisionGraph.BuildOrderedRowCache(IList`1 orderedNodesCache, Int32 currentRowIndex, Int32 lastToCacheRowIndex)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundUpdateAsync>g__UpdateGraph|50_0(Int32 fromIndex, Int32 toIndex)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.BackgroundUpdateAsync(CancellationToken cancellationToken)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.<RunBackgroundAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at GitUI.UserControls.RevisionGrid.RevisionDataGridView.Clear()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.RefreshRevisions()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```
OS:  Win 11 22000.558, issue was happening also on latest Win 10

### Steps to reproduce

Issue happens when switching branches or just listing trough commits

### Diagnostics

count: 122
size: 30.41 KiB
in-pack: 5483334
packs: 44
size-pack: 1.74 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes

**Comment by RussKie** [comment]
Was this a once off or is this happening consistently? Is it happening in a specific repo or across different repos? Are you using theming?

**Comment by gerhardol** [comment]
The background updating of the revision grid has been rewritten in master, please try a development build to verify if this still occurs.
