### ISSUE TITLE
[NBug] fatal: ambiguous argument 'HEAD': unknown revision or path ...

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9913]
### Environment

- Git Extensions 33.33.33
- Build df51d5061d8c22f6ccaf4295ac4a603be743c4ff
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

FormCommit trying to get commit messages while a new orphan branch is checked out (see also #9910)

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z -n 6 HEAD --pretty=format:%B

```
GitExtUtils.ExternalOperationException: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 ---> System.Exception: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in D:\Build\gitextensions3\GitCommands\Git\ExecutableExtensions.cs:line 152
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes) in D:\Build\gitextensions3\GitCommands\Git\ExecutableExtensions.cs:line 48
   at GitCommands.GitModule.GetPreviousCommitMessages(Int32 count, String revision, String authorPattern) in D:\Build\gitextensions3\GitCommands\Git\GitModule.cs:line 3621
   at GitUI.CommandsDialogs.FormCommit.CommitMessageToolStripMenuItemDropDownOpening(Object sender, EventArgs e) in D:\Build\gitextensions3\GitUI\CommandsDialogs\FormCommit.cs:line 2327
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownShow(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownButton.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m) in D:\Build\gitextensions3\GitUI\UserControls\ToolStripEx.cs:line 60
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

- create a new orphan branch
- in FormCommit open the `Commit messages` dropdown

**Comment by gerhardol** [comment]
A classic situation where error should be allowed...
Untested
```
            ExecutionResult result = _gitExecutable.Execute(args, outputEncoding: LosslessEncoding, throwOnErrorExit: false);
            if (!result.ExitedSuccessfully)
            {
                return new[] { string.Empty };
            }

            string[] messages = result.StandardOutput.Split(Delimiters.Null, StringSplitOptions.RemoveEmptyEntries);
            return messages.Length == 0
                ? new[] { string.Empty }
                : messages.Select(ReEncodeCommitMessage);
```
