### ISSUE TITLE
[NBug] Could not load file or assembly 'Microsoft.VisualStudio.Int...

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9922]
### Environment

- Git Extensions 4.0.0.13624
- Build c3903e122d7d97fcceb82bb66a85f2756a48558c (Dirty)
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

### Issue description

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GitUI.VisualStudioIntegration.get_IsVisualStudioRunning()
   at GitUI.FileStatusList.FileStatusListView_ContextMenu_Opening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.NativeListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Opps

### Steps to reproduce

Using the latest build [ci.appveyor.com/project/gitextensions/gitextensions/builds/43040750/artifacts](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/43040750/artifacts)

In the FormCommit right click on a staged or unstaged file.

**Comment by mstv** [comment]
.NET 6 only! Works without using .NET 5.

**Comment by RussKie** [comment]
Ah, interesting! Thank you. I'll apply the fix to .NET 6 branch.
